<div class="gutter20WithBorder">
	<div class="showOnly_duringCampaign">
	<!-- 製品キャンペーン中のみ表示 -->
		<div class="product__campaign">
			<div class="clm1">
				<a href="/directplus_ent/campaign/">
					<img src="/directplus_ent/images/banners/bnr_400_txt01.png" width="200" class="m0auto" alt="キャンペーン価格で即時お見積">
					<img src="/directplus_ent/images/banners/bnr_400x90_dx_campaign.jpg" width="200" class="m0auto" alt="HPE サーバー&amp;ストレージ DX応援キャンペーン">
				</a>
			</div>
			<div class="clm2">
				<p class="lhMid">
					キャンペーンモデルのHPE ProLiant Gen10サーバー本体および内蔵オプション、UPS、StoreEasy、MSAストレージが<span class="bold f20">30%OFF</span><br>
					メモリ、HDD/SSDが<span class="bold f20">50%OFF</span><!--<br>
					さらにHPEプロアクティブケアも<span class="bold f20">15%OFF</span>--><br>
					<span class="f14 bold">2021年10月29日（金）お申し込み分まで</span><br>
					<span class="f12">※本サイトでは「キャンペーンモデル」にて、キャンペーン価格で即時お見積・ご注文いただけます。</span>
				</p>
				<div class="lhMid mt15">
					<a href="/directplus_ent/campaign/" class="linkWithArrow">
						「HPE サーバー&amp;ストレージ DX応援キャンペーン」の詳細はこちら
						<span class="arrow">→</span>
					</a>
				</div>
			</div>
		</div>
	<!-- 製品キャンペーン中のみ表示ここまで -->
	</div>

	<!--<div class="product__campaign">
		<div class="clm1">
			<a href="/directplus_ent/promotion/amazongift/">
				<img src="/directplus_ent/images/banners/bnr_img_800x350_amazongift.jpg" width="200" class="m0auto" alt="お見積でもらえる、ギフト券がもらえる">
			</a>
		</div>
		<div class="clm2">
			<p>
				<span class="f16 bold">お見積でもらえる、ギフト券がもらえる</span><br>
				HPE DirectPlusでお見積、抽選で100名様に1,000円分のAmazonギフト券プレゼント<br>
				キャンペーン期間　2021年10月29日（金）17：00お申込み分まで
			</p>
			<div class="lhMid mt15">
				<a href="/directplus_ent/promotion/amazongift/" class="linkWithArrow">
					詳細はこちら
					<span class="arrow">→</span>
				</a>
			</div>
		</div>
	</div>-->
</div>
