<div class="js-section has-js-toc mb20" id="Compare">
	
	<h3 class="f24 bold mb5">
		1Uサーバーであらゆるワークロードに対応する性能を追及したい場合は・・・
	</h3>
	<div class="mb10">
		<p class="mb10">
			2プロセッサー/最大56コアを1Uで実現するHPE ProLiant DL360 Gen10をおすすめいたします。最大7年の長期保守にも対応。<br>
			またコストパフォーマンスと1Pでの拡張性に優れるAMD EPYC<sup>&trade;</sup> プロセッサー搭載サーバー、<a href="/directplus_ent/server/dl325gen10/" class="tertiary-link">HPE ProLiant DL325 Gen10</a>や<a href="/directplus_ent/server/dl325gen10plus/" class="tertiary-link">HPE ProLiant DL325 Gen10 Plus</a>もございます。<br>
			<!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" -->へお電話いただければ、ご希望の用途や環境に合わせた構成で比較のお見積をさせていただきます。</p>
		<div class="alignRgt lhMid"> <a href="#ContactUs" class="linkWithArrow"><!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" --><span class="arrow">→</span></a> </div>
	</div>
	<div class="optokuTable">
		<table>
			<tr>
				<th width="20%"></th>
				<th width="40%">DL160 Gen10</th>
				<th width="40%">DL360 Gen10</th>
			</tr>
			<tr class="whiteCell">
				<th>モデル</th>
				<td class="alignCtr">
					<a href="#CustomizeOrder">
						<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl160_gen10.gif" class="m0auto" alt="">
						<!--<img src="/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl160_gen10_campaign.gif" class="m0auto" alt="">-->
					</a>
					<a href="#CustomizeOrder" role="button" class="btn btn-secondary">モデルを選択する</a>
				</td>
				<td class="alignCtr">
					<a href="/directplus_ent/server/dl360gen10/">
						<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl360_gen10.gif" class="m0auto" alt="">
						<!--<img src="/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl360_gen10_campaign.gif" class="m0auto" alt="">-->
					</a>
					<a href="/directplus_ent/server/dl360gen10/" role="button" class="btn btn-secondary">モデルを選択する</a>
				</td>
			</tr>
			<tr class="gryCell">
				<th>最小構成価格(税抜)</th>
				<td class="alignCtr">
					通常モデル　354,000円～
					<!--通常モデル　<span class="lineThrough">354,000円～</span><br>
					<span class="bold f18">期間限定　235,000円～</span>-->
				</td>
				<td class="alignCtr">
					通常モデル　494,000円～
					<!--通常モデル　<span class="lineThrough">548,000円～</span><br>
					<span class="bold f18">期間限定　385,000円～</span>-->
				</td>
			</tr>
				<tr class="whiteCell">
				<th>フルカスタマイズCTO対応<br><a class="tertiary-link alpha" href="/directplus_ent/promotion/merit/"><span class="white">メリットはこちら</span></a></th>
				<td class="alignCtr">○</td>
				<td class="alignCtr">○</td>
				</tr>
			<tr class="gryCell">
				<th>おすすめ用途</th>
				<td class="alignCtr">
					・中小規模業務アプリケーションサーバー<br>
					・サービスプロバイダ用途<br>
					・Webサーバー
				</td>
				<td class="alignCtr">
					・大中規模業務アプリケーションサーバー<br>
					・Webサーバー<br>
					・メールサーバー<br>
					・仮想化&amp;VDI<br>
					・中規模DB<br>
					・ファイルサーバー
				</td>
			</tr>
			<tr class="whiteCell">
				<th>プロセッサー</th>
				<td class="alignCtr">最大2基/52コア<br>
					インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー</td>
				<td class="alignCtr">最大2基/56コア<br>
					インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー</td>
			</tr>
			<tr class="gryCell">
				<th>メモリ</th>
				<td class="alignCtr">16DIMMスロット DDR4 RDIMM</td>
				<td class="alignCtr">24DIMMスロット DDR4 RDIMM</td>
			</tr>
			<tr class="whiteCell">
				<th>ドライブ</th>
				<td class="alignCtr">4(3.5型ホットプラグSAS/SATA/SSD)<br>
					8(2.5型ホットプラグSAS/SATA/SSD)</td>
				<td class="alignCtr">標準8、最大10(2.5型ホットプラグSAS/SATA/SSD)</td>
			</tr>
			<tr class="gryCell">
				<th>拡張スロット</th>
				<td class="alignCtr">3 (メディアモジュールアダプター用×1、フルハイト/ハーフレングス PCI Express Gen3 x16×1、ロープロファイル/ハーフレングス PCI Express Gen3 x8×1)</td>
				<td class="alignCtr">3 (FlexibleLOMアダプター用スロット×1、FH/HL PCI Express Gen3 x16×1、LP/HL PCI Express Gen3 x8×1)<br>
					<span class="f12">※オプションにより最大4</span></td>
			</tr>
		</table>
	</div>
</div><!-- /#Compare -->
