<div>
	<p>
		HPE ProLiant DL160 Gen10は中小のワークロードに最適なサーバーです。アプリサーバー、管理サーバー、中・小規模仮想化などのワークロードで、よりコストパフォーマンスの良いサーバーを必要とする場合に最適です。
	</p>
	<p>
		ローエンドでありながら柔軟な拡張性を提供。最新のインテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリーを搭載し、最大16個のDIMMスロット、最大8台の2.5型ドライブ(3.5型ドライブ構成時は最大4台)を搭載可能と、上位モデルHPE ProLiant DL360 Gen10並みの拡張性を提供します。
	</p>
	<p>
		iLO 5を搭載し、特長であるSilicon root of trust(シリコンレベルの信頼性)によるセキュリティ機能もサポート。HPE独自の電子認証によるファームウェアの更新や不正書き換えの検知と回復機能を備えています。お客様の業務を守る“世界標準の安心サーバー”の進化版です。
	</p>
	<p class="mt15">
		<a href="/directplus_ent/server/infosight_for_servers.html" class="linkWithArrow" target="_blank">HPE InfoSight for Servers 対応サーバー　詳しくはこちら<span class="arrow">→</span></a>
	</p>
</div>
