<div class="specTable2Area fixedTable">
	
	<div class="specTable2 title2lines relative">
		<!--<div class="specTableTitle">
			<table width="1000">
				<tr>
					<th width="100"></th>
					<th width="450" class="f14" colspan="2">
						信頼性とコストパフォーマンス
					</th>
					<th width="450" class="f14" colspan="2">
						性能・信頼性重視
					</th>
				</tr>
				<tr>
					<th width="100"></th>
					<th width="225" class="f20">
						4LFF SATA
					</th>
					<th width="225" class="f20">
						4LFF SAS
					</th>
					<th width="225" class="f20">
						8SFF SATA
					</th>
					<th width="225" class="f20">
						8SFF SAS
					</th>
				</tr>
			</table>
		</div>-->
		<table width="1000">
			<tr>
				<th width="100"></th>
				<th width="450" class="f14" colspan="2">
					信頼性とコストパフォーマンス
				</th>
				<th width="450" class="f14" colspan="2">
					性能・信頼性重視
				</th>
			</tr>
			<tr>
				<th width="100"></th>
				<th width="225" class="f20">
					4LFF SATA
				</th>
				<th width="225" class="f20">
					4LFF SAS
				</th>
				<th width="225" class="f20">
					8SFF SATA
				</th>
				<th width="225" class="f20">
					8SFF SAS
				</th>
			</tr>
			<tr>
				<th></th>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl160_gen10.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl160_gen10.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl160_gen10.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl160_gen10.gif" alt="" class="m0auto">
				</td>
			</tr>
			<tr class="campaign">
				<th>適用可能な<br>キャンペーン</th>
				<td>
						<a href="/directplus_ent/promotion/amazongift/">
							<img src="/directplus_ent/images/banners/bnr_400x90_amazongift_campaign.jpg" alt="お見積でもらえる、ギフト券がもらえる">
						</a>
						<a href="/directplus_ent/campaign/">
							<img src="/directplus_ent/images/banners/bnr_400_txt01.png" alt="キャンペーン価格で即時お見積">
							<img src="/directplus_ent/images/banners/bnr_400x90_dx_campaign.jpg" alt="HPE サーバー&amp;ストレージ DX応援キャンペーン">
						</a>
				</td>
				<td>
						<a href="/directplus_ent/promotion/amazongift/">
							<img src="/directplus_ent/images/banners/bnr_400x90_amazongift_campaign.jpg" alt="お見積でもらえる、ギフト券がもらえる">
						</a>
						<a href="/directplus_ent/campaign/">
							<img src="/directplus_ent/images/banners/bnr_400_txt01.png" alt="キャンペーン価格で即時お見積">
							<img src="/directplus_ent/images/banners/bnr_400x90_dx_campaign.jpg" alt="HPE サーバー&amp;ストレージ DX応援キャンペーン">
						</a>
				</td>
				<td>
						<a href="/directplus_ent/promotion/amazongift/">
							<img src="/directplus_ent/images/banners/bnr_400x90_amazongift_campaign.jpg" alt="お見積でもらえる、ギフト券がもらえる">
						</a>
						<a href="/directplus_ent/campaign/">
							<img src="/directplus_ent/images/banners/bnr_400_txt01.png" alt="キャンペーン価格で即時お見積">
							<img src="/directplus_ent/images/banners/bnr_400x90_dx_campaign.jpg" alt="HPE サーバー&amp;ストレージ DX応援キャンペーン">
						</a>
				</td>
				<td>
						<a href="/directplus_ent/promotion/amazongift/">
							<img src="/directplus_ent/images/banners/bnr_400x90_amazongift_campaign.jpg" alt="お見積でもらえる、ギフト券がもらえる">
						</a>
						<a href="/directplus_ent/campaign/">
							<img src="/directplus_ent/images/banners/bnr_400_txt01.png" alt="キャンペーン価格で即時お見積">
							<img src="/directplus_ent/images/banners/bnr_400x90_dx_campaign.jpg" alt="HPE サーバー&amp;ストレージ DX応援キャンペーン">
						</a>
				</td>
			</tr>
			<tr>
				<th>ドライブ</th>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 3.5型</span> 最大4<br>
					SATA HDD、SATA SSD選択可
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 3.5型</span> 最大4<br>
					SAS HDD、SAS SSD選択可
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 2.5型</span> 最大8<br>
					SATA HDD、SATA SSD選択可
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 2.5型</span> 最大8<br>
					SAS HDD、SAS SSD選択可
				</td>
			</tr>
			<tr>
				<th>プロセッサー</th>
				<td colspan="4">
					<span class="cutomizable2">カスタマイズ可能</span>最大2基　インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー
				</td>
			</tr>
			<tr>
				<th>メモリ</th>
				<td colspan="4">
					<span class="cutomizable2">カスタマイズ可能</span>16DIMMスロット DDR4 RDIMM
				</td>
			</tr>
			<tr>
				<th>パワーサプライ</th>
				<td colspan="4">
					<span class="cutomizable2">カスタマイズ可能</span>標準1　オプションで冗長化対応、ホットプラグ対応
				</td>
			</tr>
			<tr>
				<th>
					最小構成価格<sup>※</sup><br>（税抜）
					<p class="f12 indent-1 mt10" style="font-weight: normal; text-align: left;">
						※ライザーオプション搭載時
					</p>
				</th>
				<td class="pt10 pb10">
					<div class="mb25">
						<span class="bold f16">キャンペーンモデル</span><br>
						<span class="f13">期間限定</span>
						<span class="bold f18">235,000円～</span><br>
						<span class="f12">119,000円引き～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4378&ProductSKU=BASE:16017" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
					<div>
						<span class="bold f16">通常モデル</span>
						<span class="f16">354,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4378&ProductSKU=BASE:15949" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
				<td class="pt10 pb10">
					<div class="mb25">
						<span class="bold f16">キャンペーンモデル</span><br>
						<span class="f13">期間限定</span>
						<span class="bold f18">270,000円～</span><br>
						<span class="f12">133,000円引き～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4378&ProductSKU=BASE:16018" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
					<div>
						<span class="bold f16">通常モデル</span>
						<span class="f16">403,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4378&ProductSKU=BASE:15950" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
				<td class="pt10 pb10">
					<div class="mb25">
						<span class="bold f16">キャンペーンモデル</span><br>
						<span class="f13">期間限定</span>
						<span class="bold f18">246,000円～</span><br>
						<span class="f12">124,000円引き～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4378&ProductSKU=BASE:16015" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
					<div>
						<span class="bold f16">通常モデル</span>
						<span class="f16">370,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4378&ProductSKU=BASE:15947" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
				<td class="pt10 pb10">
					<div class="mb25">
						<span class="bold f16">キャンペーンモデル</span><br>
						<span class="f13">期間限定</span>
						<span class="bold f18">280,000円～</span><br>
						<span class="f12">138,000円引き～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4378&ProductSKU=BASE:16016" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
					<div>
						<span class="bold f16">通常モデル</span>
						<span class="f16">418,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4378&ProductSKU=BASE:15948" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
			</tr>
			<tr>
				<th></th>
				<td colspan="4" class="pt10 pb15">
					<a href="pdfs/spec_cto.pdf" target="_blank" class="linkWithArrow">
						仕様一覧はこちら（PDF）
						<span class="arrow">→</span>
					</a>
				</td>
			</tr>
		</table>
	</div><!-- /.specTable2 -->
	
</div><!-- /.specTable2Area -->
