			<table border="0" cellpadding="0" cellspacing="0" width="170" background="/comm/legacy/img/s.gif">
				<tr class="colorDCDCDCbg">
					<td align="left"><img src="/comm/legacy/img/s.gif" width="10" height="1" alt=""></td>
					<td align="left" valign="top" width="10" nowrap><span class="linkarrowbold">≫</span></td>
					<td align="left" valign="middle">
						<h2><a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Partner-Site/ja_JP/-/JPY/StorefrontForPartner-Start" class="bold" target="_blank"><!--#include virtual="/comm/include/directpartner_name.inc" --></a>
						</h2>
					</td>
				</tr>
			</table>
<table border="0" cellpadding="0" cellspacing="0" width="170" background="/comm/legacy/img/s.gif">
	<tr>
		<td align="left" valign="top"><img src="/comm/legacy/img/s.gif" width="10" height="1" alt=""></td>
		<td align="left" valign="top">
			<table border="0" cellpadding="0" cellspacing="0" width="150" background="/comm/legacy/img/s.gif">
				<tr class="decoration">
					<td align="left" width="10"><img src="/comm/legacy/img/s.gif" width="10" height="10" alt=""></td>
					<td align="left" width="10"><img src="/comm/legacy/img/s.gif" width="10" height="10" alt=""></td>
					<td align="left" width="10"><img src="/comm/legacy/img/s.gif" width="10" height="10" alt=""></td>
					<td align="left" width="10"><img src="/comm/legacy/img/s.gif" width="120" height="10" alt=""></td>
				</tr>
				<tr>
					<td align="left"></td>
					<td align="left" valign="top" class="linkarrow">≫</td>
					<td align="left" colspan="2"><a href="/directplus_ent/directpartner/howto/">トップページのご案内</a></td>
				</tr>
				<tr>
					<td align="left"></td>
					<td align="left" valign="top" class="linkarrow">≫</td>
					<td align="left" colspan="2"><a href="/directplus_ent/directpartner/howto/delivery_flow.html">ご納品までの流れ</a></td>
				</tr>
				<tr>
					<td align="left"></td>
					<td align="left" valign="top" class="linkarrow">≫</td>
					<td align="left" colspan="2"><a href="/directplus_ent/directpartner/howto/delivery_charge.html">配送料について</a></td>
				</tr>
				<tr class="decoration">
						<td align="left" colspan="4" width="150"><img src="/comm/legacy/img/s.gif" width="150" height="10" alt=""></td>
				</tr>
				<tr class="decoration">
					<td align="left"width="10"><img src="/comm/legacy/img/s.gif" width="10" height="1" alt=""></td>
					<td align="left" valign="top" class="colorCCCCCCbg" colspan="3" width="140"><img src="/comm/legacy/img/s.gif" width="140" height="1" alt=""></td>
				</tr>
				<tr class="decoration">
					<td align="left" colspan="4" width="150"><img src="/comm/legacy/img/s.gif" width="150" height="10" alt=""></td>
				</tr>
				<tr>
					<td align="left"></td>
					<td align="left" valign="top" class="linkarrow">≫</td>
					<td align="left" colspan="2"><a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Partner-Site/ja_JP/-/JPY/StorefrontForPartner-Start" target="_blank"><!--#include virtual="/comm/include/directpartner_name.inc" --><br>サイトマップ</a></td>
				</tr>
				<tr>
					<td align="left"></td>
					<td align="left" valign="top" class="linkarrow">≫</td>
					<td align="left" colspan="2"><a href="https://www.hpe.com/jp/ja/sitemap.html" target="_blank"><!--#include virtual="/comm/include/company_name_body.inc" --> サイトマップ</a></td>
				</tr>
				<tr class="decoration">
					<td align="left" colspan="4"><img src="/comm/legacy/img/s.gif" width="150" height="10" alt=""></td>
				</tr>
			</table>
		</td>
		<td align="left" valign="top" width="10"><img src="/comm/legacy/img/s.gif" width="10" height="1" alt=""></td>
	</tr>
	<tr class="decoration">
		<td colspan="3" class="colorCCCCCCbg"><img src="/comm/legacy/img/s.gif" width="1" height="2" alt="" border="0"></td>
	</tr>
</table>
