			<table width="560" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td width="280"><a href="https://www.hpe.com/jp" target="_blank"><img src="/directplus_ent/directpartner/images/local_navigation_hphome.gif" alt="HPホーム" width="280" height="19" border="0"></a></td>
					<td width="1"><img src="/comm/legacy/img/s.gif" alt="" width="1" height="1" class="decoration"></td>
					<td width="279"><a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Partner-Site/ja_JP/-/JPY/StorefrontForPartner-Start"><img src="/directplus_ent/directpartner/images/local_navigation_directpartner.gif" alt="<!--#include virtual="/comm/include/directpartner_name.inc" -->ホーム" width="279" height="19" border="0"></a></td>
				</tr>
				<tr class="decoration">
					<td colspan="3"><img src="/comm/legacy/img/s.gif" alt="" width="1" height="20"></td>
				</tr>
			</table>
