<div class="aboutModels" id="AboutModel">
	<div class="gryBdr4px paddBlock15">
		<div class="aboutModel">
			<div class="aboutModelLabel">
				キャンペーンモデル<sup>※1</sup>とは
			</div>
			<div class="aboutModelDetail">
				<p>
					お好みのスペックにフルカスタマイズ<sup>※2</sup>可能なモデルです。キャンペーン実施時にキャンペーン価格を適用したモデル
				</p>
			</div>
		</div>
		<div class="aboutModel">
			<div class="aboutModelLabel">
				オプ得モデル<sup>※1</sup>とは
			</div>
			<div class="aboutModelDetail">
				<p>
					お好みのスペックにフルカスタマイズ<sup>※2</sup>可能なモデルです。さらにプロセッサー、メモリ、ディスクドライブその他のカスタマイズオプションを通常価格の30%OFF相当でご提供いたします。<a href="/directplus_ent/optoku/" class="tertiary-link">詳細はこちら</a>
				</p>
			</div>
		</div>
		<div class="aboutModel">
			<div class="aboutModelLabel">
				通常モデルとは
			</div>
			<div class="aboutModelDetail">
				<p>
					お好みのスペックにフルカスタマイズ<sup>※2</sup>可能なモデルです。
				</p>
			</div>
		</div>
		<div class="f12 indent-2">
			※1: キャンペーンモデル、オプ得モデルは製品によって取り扱いの無い場合がございます。
		</div>
		<div class="f12 indent-2">
			※2: 一部対象外の製品がございます。<a href="/directplus_ent/server/" class="tertiary-link">こちらのページ</a>の仕様表の「フルカスタマイズCTO対応」をご覧ください。
		</div>
	</div>
</div>