<!--<style>
.amazonCampaignBnr {
	border: 1px solid #CCC;
	background-image: url('/directplus_ent/promotion/amazongift/images/main.jpg');
	background-position: right top;
	background-repeat: no-repeat;
	position: relative;
	color: #FFF;
}
@media only screen and (max-width:999px){
	.amazonCampaignBnr {
		background-size:cover
	}
}
.amazonCampaignBnrInr {
	width: 100%;
	height: 100%;
	padding: 20px;
	box-sizing: border-box;
	background: linear-gradient(90deg, rgba(0,0,0,1) 0%, rgba(0,0,0,1) 20%, rgba(0,0,0,0) 60%);
}
@media only screen and (max-width:999px){
	.amazonCampaignBnrInr {
		padding: 15px;
		background: linear-gradient(180deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.2) 100%);
	}
}
.amazonCampaignBnrTtl {
	font-weight: bold;
	font-size: 34px;
	line-height: 1;
	margin-bottom: 10px;
}
@media only screen and (max-width:999px){
	.amazonCampaignBnrTtl {
		font-size: 28px;
		line-height: 1.2;
	}
}
.amazonCampaignBnrTxt {
	line-height:1.4;
	font-size:18px;
	font-weight:bold;
}
@media only screen and (max-width:999px){
	.amazonCampaignBnrTxt {
		font-size:16px;
	}
}
.amazonCampaignBnrBtn {
	position: absolute;
	bottom: 20px;
	right: 30px;
}
@media only screen and (max-width:999px){
	.amazonCampaignBnrBtn {
		position: relative;
		bottom: auto;
		right: auto;
		text-align:center;
	}
}
</style>
<div class="contentBox">
	<div class="amazonCampaignBnr mb30">
		<div class="amazonCampaignBnrInr">
			<p class="amazonCampaignBnrTtl">お見積でもらえる、ギフト券がもらえる</p>
			<div class="amazonCampaignBnrTxt">
				HPE DirectPlusでお見積、抽選で100名様に1,000円分のAmazonギフト券プレゼント<br>
				2021年6月30日（水）17：00お申込み分まで
			</div>
			<div class="amazonCampaignBnrBtn">
				<a href="/directplus_ent/promotion/amazongift/" role="button" class="btn btn-secondary alpha">詳細・応募フォームはこちら</a>
			</div>
		</div>
	</div>
</div>-->