<!-- コールセンターへお問い合わせください -->

<!--<div class="gryBdr2px paddBlock10 mb20">

	<div class="column33-33-33 cfx">

		<div class="clm1 alignCtr pt20">
			<p class="bold f20 lhMid">適用可能なキャンペーン</p>
		</div>

		<div class="clm2">
			<a href="/directplus_ent/campaign/mitsumori/">
				<img src="/directplus_ent/images/banners/bnr_400_txt_mitumori.png" width="200" class="m0auto" alt="見積したらLINEポイント">
				<img src="/directplus_ent/images/banners/bnr_400x90_mitsumori.gif" width="200" class="m0auto" alt="見積したらLINEポイント　まず参加登録！">
			</a>
		</div>

		<div class="clm3">
			<a href="https://www.hpe.com/jp/ja/servers/tokutoku-campaign.html">
				<img src="/directplus_ent/images/banners/bnr_400_txt02.png" width="200" class="m0auto" alt="コールセンターへお問い合わせください">
				<img src="/directplus_ent/images/banners/bnr_400x90_tokutoku.jpg" width="200" class="m0auto" alt="サーバー&amp;ストレージとくとくキャンペーン">
			</a>
		</div>

	</div>

	<p class="f12 indent-1 mt10 alignRgt">
		※キャンペーン価格については<a href="#ContactUs" class="tertiary-link">HPE DirectPlusコールセンター</a>にお問い合わせください。
	</p>

</div>-->
