<!--<div class="product__campaignWrapper">
							<div class="product__campaign">
								<div class="clm1">
									<a href="/directplus_ent/promotion/amazongift/">
										<img src="/directplus_ent/images/banners/bnr_img_800x350_amazongift.jpg" width="200" class="m0auto" alt="お見積でもらえる、ギフト券がもらえる">
									</a>
								</div>
								<div class="clm2">
									<p>
										<span class="f16 bold">お見積でもらえる、ギフト券がもらえる</span><br>
										HPE DirectPlusでお見積、抽選で100名様に1,000円分のAmazonギフト券プレゼント<br>
										キャンペーン期間　2021年10月29日（金）17：00お申込み分まで
									</p>
									<div class="product__campaign__detailLink">
										<a href="/directplus_ent/promotion/amazongift/">
											<span class="cta-link">
												<em class="icon-arrow-circle-right"></em>詳細はこちら
											</span>
										</a>
									</div>
								</div>
							</div>
						</div>-->