<!-- コールセンターへお問い合わせください -->

<!--<div class="mb40">
    <p class="mb10 bold f20">適用可能なキャンペーン</p>

    <div class="column25-75 cfx mb20">
        <div class="clm1">
            <a href="https://www.hpe.com/jp/ja/servers/tokutoku-campaign.html">
                <img src="/directplus_ent/images/banners/bnr_400_txt02.png" width="200" class="m0auto" alt="コールセンターへお問い合わせください">
                <img src="/directplus_ent/images/banners/bnr_400x90_tokutoku.jpg" width="200" class="m0auto" alt="サーバー&amp;ストレージとくとくキャンペーン">
            </a>
        </div>
        <div class="clm2">
            <p class="lhMid mb5">
                HPE ProLiant Gen10サーバー本体および内蔵オプション、StoreEasyが<span class="bold f16">30％OFF</span><br>
                <span class="f12 mt5">※MicroServer Gen10は10%OFF</span><br>
                さらにHPEプロアクティブケアも<span class="bold f16">15%OFF</span><br>
                <span class="f14 bold">2020年3月31日(火)お申し込み分まで</span><br>
                <a href="https://www.hpe.com/jp/ja/servers/tokutoku-campaign.html" class="tertiary-link">キャンペーン詳細はこちら</a>
            </p>
            <p class="f12 mt10 indent-1">※キャンペーン価格については<a href="#ContactUs" class="tertiary-link">HPE DirectPlusコールセンター</a>にお問い合わせください。</p>
        </div>
    </div>

    <div class="column25-75 cfx">
        <div class="clm1">
            <p class="alignCtr bold">ご好評につき第2弾！</p>
            <a href="/directplus_ent/campaign/mitsumori/">
                <img src="/directplus_ent/images/banners/bnr_400_txt_mitumori.png" width="200" class="m0auto" alt="見積したらLINEポイント">
                <img src="/directplus_ent/images/banners/bnr_400x90_mitsumori.gif" width="200" class="m0auto" alt="見積したらLINEポイント　まず参加登録！">
            </a>
        </div>
        <div class="clm2">
            <p class="lhMid">
                ご好評につき、今回は見積すべてが対象です。お見積いただいた方に<span class="bold f16">LINEポイント</span>コードをご送付。<br>
                <span class="f14 bold">なくなり次第終了</span><br>
                <a href="/directplus_ent/campaign/mitsumori/" class="tertiary-link">参加登録はこちら</a>
            </p>
        </div>
    </div>

</div>-->
