<style>
.informations {
	font-size: 12px;
}
.information {
	display: flex;
	align-items: baseline;
}
.information-label {
	flex: 0 0 11em;
	text-align: center;
	color: #fff;
	margin-right: 10px;
}
.information:not(:last-child) {
	margin-bottom: 10px;
}
</style>
<div class="informations mb30">
	<div class="f18 bold mb20">
		関連情報
	</div>
	<div class="information">
		<div class="information-label bgPurple">
			解説記事
		</div>
		<div class="information-text">
			導入事例と選定にかかわる全てのITプロフェッショナルの皆様に　<a href="/directplus_ent/server/advice.html" class="tertiary-link">サーバー「導入前のアドバイス」</a>
		</div>
	</div>
	<div class="information">
		<div class="information-label bgPurple">
			おすすめ構成
		</div>
		<div class="information-text">
			用途に合わせたHPEおすすめの構成例をご紹介　<a href="/directplus_ent/server/purpose/file.html" class="tertiary-link">サーバーを用途で選ぶ</a>
		</div>
	</div>
</div>
