<div class="lineuplist tower mb20">
	<div class="lineuplist__header">
		<div class="f22 bold">
			HPE ProLiant タワー型サーバー ラインアップ
		</div>
		<div class="f14 indent-1">
			※コア数は1P(プロセッサー)あたりの数
		</div>
	</div>
	<div class="lineuplist__bodyWrapper">
		<div class="lineuplist__body">
			<div class="lineuplist__body__y">
				高性能
			</div>
			<div class="lineuplist__body__x">
				拡張性
			</div>
			<div class="lineuplist__main">
				<div class="lineuplist__item__groups">
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<a class="lineuplist__item" href="/directplus_ent/server/microservergen10plus/">
									<div class="lineuplist__item__proceccor">1P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_microserver_gen10_plus.jpg" alt="" width="88" height="42">
									</div>
									<div class="lineuplist__item__name">
										MicroServer<br>
										Gen10 Plus
									</div>
								</a>
							</div>
							<div class="lineuplist__item__group__label">
								<div>2～4コア</div>
							</div>
						</div>
					</div>
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<!--<a class="lineuplist__item" href="/directplus_ent/server/ml30gen10/">
									<div class="lineuplist__item__proceccor">1P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_ml30_gen10.jpg" alt="" width="76" height="107">
									</div>
									<div class="lineuplist__item__name">
										ML30 Gen10
									</div>
								</a>-->
								<a class="lineuplist__item" href="/directplus_ent/server/ml30gen10plus/">
									<div class="lineuplist__item__proceccor">1P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_ml30_gen10_plus.jpg" alt="" width="76" height="107">
									</div>
									<div class="lineuplist__item__name">
										ML30 Gen10 Plus
									</div>
								</a>
							</div>
							<div class="lineuplist__item__group__label">
								<!--<div>2～6コア</div>-->
								<div>2～8コア</div>
							</div>
						</div>
					</div>
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<a class="lineuplist__item" href="/directplus_ent/optoku/ml110gen10/">
									<div class="lineuplist__item__proceccor">1P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_ml110_gen10.jpg" alt="" width="78" height="116.5">
									</div>
									<div class="lineuplist__item__name">
										ML110 Gen10
									</div>
								</a>
							</div>
							<div class="lineuplist__item__group__label">
								<div>4～16コア</div>
							</div>
						</div>
					</div>
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<a class="lineuplist__item" href="/directplus_ent/server/ml350gen10/">
									<div class="lineuplist__item__proceccor">2P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_ml350_gen10.jpg" alt="" width="123" height="157">
									</div>
									<div class="lineuplist__item__name">
										ML350 Gen10
									</div>
								</a>
							</div>
							<div class="lineuplist__item__group__label">
								<div>6～28コア</div>
							</div>
						</div>
					</div>
				</div>
				<div class="lineuplist__main__x">
					<div>小規模</div>
					<div class="arrow"><span></span></div>
					<div>大規模</div>
				</div>
			</div>
		</div>
	</div>
</div>
