<div class="lineuplist rack intel mb20">
	<div class="lineuplist__header">
		<div class="f22 bold">
			HPE ProLiant ラックマウント型サーバー ラインアップ
		</div>
		<div class="f14 indent-1">
			※コア数は1P(プロセッサー)あたりの数
		</div>
	</div>
	<div class="lineuplist__bodyWrapper">
		<div class="lineuplist__body">
			<div class="lineuplist__body__y">
				高性能
			</div>
			<div class="lineuplist__body__x">
				拡張性
			</div>
			<div class="lineuplist__main">
				<div class="lineuplist__main__title">
					インテル プロセッサー搭載サーバー
				</div>
				<div class="lineuplist__item__groups">
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<a class="lineuplist__item" href="/directplus_ent/server/dl160gen10/">
									<div class="lineuplist__item__proceccor">2P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_dl160_gen10.jpg" alt="" width="112" height="20.5">
									</div>
									<div class="lineuplist__item__name">
										DL160 Gen10
									</div>
								</a>
								<a class="lineuplist__item" href="/directplus_ent/server/dl180gen10/">
									<div class="lineuplist__item__proceccor">2P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_dl180_gen10.jpg" alt="" width="111.5" height="30.5">
									</div>
									<div class="lineuplist__item__name">
										DL180 Gen10
									</div>
								</a>
							</div>
							<div class="lineuplist__item__group__label">
								<div>4～24コア</div>
								<div>4～26コア</div>
							</div>
						</div>
					</div>
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<a class="lineuplist__item" href="/directplus_ent/server/dl360gen10/">
									<div class="lineuplist__item__proceccor">2P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_dl360_gen10.jpg" alt="" width="119.5" height="27.5">
									</div>
									<div class="lineuplist__item__name">
										DL360 Gen10
									</div>
								</a>
								<a class="lineuplist__item" href="/directplus_ent/server/dl380gen10/">
									<div class="lineuplist__item__proceccor">2P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_dl380_gen10.jpg" alt="" width="115" height="33">
									</div>
									<div class="lineuplist__item__name">
										DL380 Gen10
									</div>
								</a>
							</div>
							<div class="lineuplist__item__group__label">
								<div>4～28コア</div>
							</div>
						</div>
					</div>
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<a class="lineuplist__item" href="/directplus_ent/server/dl360gen10plus/">
									<div class="lineuplist__item__proceccor">2P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_dl360_gen10_plus.jpg" alt="" width="115.5" height="20.5">
									</div>
									<div class="lineuplist__item__name">
										DL360<br>
										Gen10 Plus
									</div>
								</a>
								<a class="lineuplist__item" href="/directplus_ent/server/dl380gen10plus/">
									<div class="lineuplist__item__proceccor">2P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_dl380_gen10_plus.jpg" alt="" width="115.5" height="31">
									</div>
									<div class="lineuplist__item__name">
										DL380<br>
										Gen10 Plus
									</div>
								</a>
							</div>
							<div class="lineuplist__item__group__label">
								<div>16～40コア</div>
							</div>
						</div>
					</div>
				</div>
				<div class="lineuplist__main__x">
					<div>小規模</div>
					<div class="arrow"><span></span></div>
					<div>大規模</div>
				</div>
			</div>
		</div>
	</div>
</div>


<div class="lineuplist rack amd mb20">
	<div class="lineuplist__bodyWrapper">
		<div class="lineuplist__body">
			<div class="lineuplist__body__y">
				高性能
			</div>
			<div class="lineuplist__body__x">
				拡張性
			</div>
			<div class="lineuplist__main">
				<div class="lineuplist__main__title">
					AMD プロセッサー搭載サーバー
				</div>
				<div class="lineuplist__item__groups">
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<a class="lineuplist__item" href="/directplus_ent/server/dl325gen10/">
									<div class="lineuplist__item__proceccor">1P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_dl325_gen10.jpg" alt="" width="126" height="28.5">
									</div>
									<div class="lineuplist__item__name">
										DL325 Gen10
									</div>
								</a>
							</div>
							<div class="lineuplist__item__group__label">
								<div>8～64コア</div>
							</div>
						</div>
					</div>
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<a class="lineuplist__item" href="/directplus_ent/server/dl325gen10plus/">
									<div class="lineuplist__item__proceccor">1P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_dl325_gen10_plus.jpg" alt="" width="126" height="28.5">
									</div>
									<div class="lineuplist__item__name">
										DL325<br>
										Gen10 Plus
									</div>
								</a>
								<a class="lineuplist__item" href="/directplus_ent/server/dl385gen10plus/">
									<div class="lineuplist__item__proceccor">2P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_dl385_gen10_plus.jpg" alt="" width="110.5" height="28.5">
									</div>
									<div class="lineuplist__item__name">
										DL385<br>
										Gen10 Plus
									</div>
								</a>
							</div>
							<div class="lineuplist__item__group__label">
								<div>8～64コア</div>
							</div>
						</div>
					</div>
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<a class="lineuplist__item" href="/directplus_ent/server/dl325gen10plusv2/">
									<div class="lineuplist__item__proceccor">1P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_dl325_gen10_plus_v2.jpg" alt="" width="112.5" height="19">
									</div>
									<div class="lineuplist__item__name">
										DL325<br>
										Gen10 Plus v2
									</div>
								</a>
								<a class="lineuplist__item" href="/directplus_ent/server/dl345gen10plus/">
									<div class="lineuplist__item__proceccor">1P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_dl345_gen10_plus.jpg" alt="" width="110.5" height="30">
									</div>
									<div class="lineuplist__item__name">
										DL345<br>
										Gen10 Plus
									</div>
								</a>
								<a class="lineuplist__item" href="/directplus_ent/server/dl365gen10plus/">
									<div class="lineuplist__item__proceccor">2P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_dl365_gen10_plus.jpg" alt="" width="112" height="29.5">
									</div>
									<div class="lineuplist__item__name">
										DL365<br>
										Gen10 Plus
									</div>
								</a>
								<a class="lineuplist__item" href="/directplus_ent/server/dl385gen10plusv2/">
									<div class="lineuplist__item__proceccor">2P</div>
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/server/images/lineup_dl385_gen10_plus_v2.jpg" alt="" width="112" height="30.5">
									</div>
									<div class="lineuplist__item__name">
										DL385<br>
										Gen10 Plus v2
									</div>
								</a>
							</div>
							<div class="lineuplist__item__group__label">
								<div>8～64コア</div>
							</div>
						</div>
					</div>
				</div>
				<div class="lineuplist__main__x">
					<div>小規模</div>
					<div class="arrow"><span></span></div>
					<div>大規模</div>
				</div>
			</div>
		</div>
	</div>
</div>
