<div class="msSetupGuideWrapper mb20WithBorder">
	<div class="msSetupGuide">
		<div class="msSetupGuide_row">
			<div class="msSetupGuide_item">
				<div class="clm1">
					<a href="/directplus_ent/server/pdfs/microserver_setupguide.pdf" target="_blank"><img src="/directplus_ent/server/images/microserver_setupguide.jpg" alt="" class="w100per gryBdr1px clmImg"></a>
				</div>
				<div class="clm2">
					<div class="f16 bold mb5">HPE ProLiant MicroServer Gen10 Plus セットアップ・インストールガイド</div>
					<div class="mb5">筐体の開け方からメモリ、ディスク、PCIeカード等のオプション取り付け方法まで、こちらをご覧いただければ簡単にセットアップが可能です。またBIOS/UEFIの初期セットアップや、OSインストール方法も解説しています。</div>
					<div class="detailLinkTxt alignRgt">
						<a href="/directplus_ent/server/pdfs/microserver_setupguide.pdf" target="_blank" class="linkWithArrow">詳しくはこちら<span class="arrow">→</span></a>
					</div>
				</div>
			</div>
		</div>
		<div class="msSetupGuide_row columnFixWidth">
			<div class="clm1">
				<div class="msSetupGuide_item">
					<div class="clm1">
						<a href="https://ascii.jp/featuredarticles/3000665/" target="_blank"><img src="/directplus_ent/server/images/bnr_msgen10_plus.jpg" alt="" class="w100per clmImg"></a>
					</div>
					<div class="clm2">
						<div class="f16 bold mb5">ASCII.jp 特集記事</div>
						<div class="mb5">最新の超小型サーバー「HPE ProLiant <br class="spHide">MicroServer Gen10 Plus」を知る！</div>
						<div class="detailLinkTxt">
							<a href="https://ascii.jp/featuredarticles/3000665/" target="_blank" class="linkWithArrow">詳しくはこちら<span class="arrow">→</span></a>
						</div>
					</div>
				</div>
			</div>
			<div class="clm2">
				<div class="msSetupGuide_item">
					<div class="clm1">
						<a href="/directplus_ent/server/microservergen10plus/pdfs/gigaschool.pdf" target="_blank"><img src="/directplus_ent/network/academic/images/gigaschool.jpg" alt="" class="w100per clmImg"></a>
					</div>
					<div class="clm2">
						<div class="f16 bold mb5">学校内にも設置しやすい最小安心サーバー</div>
						<div class="mb5">GIGAスクール構想を成功に導く校内サーバー活用。<br>その活用例をご紹介</div>
						<div class="detailLinkTxt">
							<a href="/directplus_ent/server/microservergen10plus/pdfs/gigaschool.pdf" target="_blank" class="linkWithArrow">詳しくはこちら<span class="arrow">→</span></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
