<!--<style>
.nikkeiBp > .clm1 {
	padding-right: 1%;
	border-right: 1px solid #CCC;
	margin-right: 0;
}
.nikkeiBp > .clm2 {
	margin-left: 1%;
	
}
@media only screen and (max-width:999px){
	.nikkeiBp > .clm1 {padding-right: 0;border-right: none;}
	.nikkeiBp > .clm2 {margin-left: 0;}
}
.nikkeiBpLogo {width: 130px;}
.nikkeiBpLogoIt {width: 162px;}
@media only screen and (max-width: 768px) {
	.nikkeiBpLogo {width: 130px;}
	.nikkeiBpLogoIt {width: 155px;}
}
</style>
					<div class="mb40WithBorder">
						<div class="cfx column50-50 nikkeiBp">
							<div class="clm1">
								<div class="column35-65 cfx">
									<div class="clm1">
										<img src="/directplus_ent/images/nikkeibp_logo_2020-2021-4c.png" alt="" class="m0auto nikkeiBpLogo">
									</div>
									<div class="clm2">
										<h4 class="bold f16 mb5 lhMid">PCサーバー部門、ストレージ部門で1位を獲得！</h4>
										<p class="mb10 f13 lhMid">日経コンピュータ 2020年9月3日号 顧客満足度調査 2020-2021 PCサーバー部門、ストレージ部門において、日本ヒューレット・パッカード株式会社が1位を獲得しました。</p>
										<p class="f11 mb10 lhMid">[調査概要]<br>顧客満足度調査 2020-2021は、企業向けIT関連製品やサービス 全24部門における ITベンダーに関する満足度を、CIO（最高情報責任者）や情報システム部長といった製品・サービス導入の責任者が評価するものです（日経 BP「日経コンピュータ」が企画・実施）。</p>
										<p><a href="https://www.hpe.com/jp/ja/japan/newsroom/press-release/2020/082701.html"><span class="cta-link"><em class="icon-arrow-circle-right"></em>プレスリリースはこちら</span></a></p>
									</div>
								</div>
							</div>
							<div class="clm2">
								<div class="column40-60 cfx">
									<div class="clm1">
										<img src="/directplus_ent/images/nikkeibp_logo_it.png" alt="" class="m0auto nikkeiBpLogo nikkeiBpLogoIt">
									</div>
									<div class="clm2">
										<h4 class="bold f16 mb5 lhMid">PCサーバー部門で1位を獲得！</h4>
										<p class="mb10 f13 lhMid">日経BPガバメントテクノロジー 2020年秋号 自治体ITシステム満足度調査 2020-2021 PCサーバー部門において、日本ヒューレット・パッカード株式会社が1位を獲得しました。</p>
										<p class="f11 mb10 lhMid">[調査概要]<br>
										「日経BPガバメントテクノロジー自治体ITシステム満足度調査」は、日経コンピュータ誌が企画・実施した「顧客満足度調査」（対象は民間企業を含む1万2356社・団体の情報システム部門）のうち、官公庁・自治体の計202団体からの回答を集計したもの（調査票発送数は1630団体）。</p>
									</div>
								</div>
							</div>
						</div>
					</div>-->
<!--<style>
.nikkeiBpLogo {width: 160px;}
</style>
					<div class="mb40WithBorder">
						<div class="column33-66 cfx">
							<div class="clm1">
								<img src="/directplus_ent/images/nikkeibp_logo_it.png" alt="" class="m0auto nikkeiBpLogo">
							</div>
							<div class="clm2">
								<h4 class="bold f16 mb5 lhMid">PCサーバー部門で1位を獲得！</h4>
								<p class="mb10 f13 lhMid">日経BPガバメントテクノロジー 2020年秋号 自治体ITシステム満足度調査 2020-2021 PCサーバー部門において、日本ヒューレット・パッカード株式会社が1位を獲得しました。</p>
								<p class="f11 mb10 lhMid">[調査概要]<br>「日経BPガバメントテクノロジー自治体ITシステム満足度調査」は、日経コンピュータ誌が企画・実施した「顧客満足度調査」（対象は民間企業を含む1万2356社・団体の情報システム部門）のうち、官公庁・自治体の計202団体からの回答を集計したもの（調査票発送数は1630団体）。</p>
							</div>
						</div>
					</div>-->