<style>
.cardTitle {
	font-size: 14px;
	font-weight: bold;
	height: 65px;
}
@media only screen and (max-width: 767px) {
	.cardTitle {
		height: auto;
	}
}
</style>


<div class="mb10">
	<a href="/directplus_ent/server/delivery.html"><img src="/directplus_ent/images/banners/bnr_1000x180_stock.jpg" alt="最短5営業日で納品｜売れ筋製品を中心に、在庫大増量中！お早めにご注文ください！" class="w100per"></a>
</div>

<div class="cardsWrapper mb20">
	<div class="cards">
		
		<a class="card" href="/directplus_ent/server/dl160gen10/">
			<div class="spTrimHeight cardImage">
				<div class="cardImageTag">製品情報</div>
				<img src="/directplus_ent/images/banners/bnr_800x350_dl160.jpg" alt="">
			</div>
			<div class="cardText">
				<div class="cardTitle">
					コスト×性能で選ぶなら
				</div>
				<div class="cardLink">
					中小規模システムに最適なラックサーバー
					<span class="cardLinkArrow">→</span>
				</div>
			</div>
		</a>
		
		<a class="card" href="/directplus_ent/server/microservergen10.html">
			<div class="spTrimHeight cardImage">
				<div class="cardImageTag">GIGAスクール構想</div>
				<img src="/directplus_ent/images/banners/bnr_800x350_microservergen10plus.jpg" alt="">
			</div>
			<div class="cardText">
				<div class="cardTitle">
					GIGAスクール構想を成功に導く<br class="br768">校内サーバー活用
				</div>
				<div class="cardLink">
					校内に設置しやすい<br class="spHide">12cmの最小安心サーバー
					<span class="cardLinkArrow">→</span>
				</div>
			</div>
		</a>
		
		<a class="card" href="/directplus_ent/server/advice.html">
			<div class="spTrimHeight cardImage">
				<div class="cardImageTag">解説記事</div>
				<img src="/directplus_ent/images/banners/bnr_800x350_advice.jpg" alt="">
			</div>
			<div class="cardText">
				<div class="cardTitle">
					導入検討と選定に関わる<br class="br768">全てのITプロフェッショナルの皆様に
				</div>
				<div class="cardLink">
					サーバー「導入前のアドバイス」
					<span class="cardLinkArrow">→</span>
				</div>
			</div>
		</a>
		
		<!--<a class="card" href="/directplus_ent/promotion/amazongift/">
			<div class="cardImage">
				<div class="cardImageTag">キャンペーン</div>
				<img src="/directplus_ent/images/banners/bnr_img_800x350_amazongift.jpg" alt="">
			</div>
			<div class="cardText">
				<div class="cardTitle">
					お見積すると、抽選で100名様に1,000円分のAmazonギフト券プレゼント
				</div>
				<div class="cardLink">
					期間限定 6月30日まで
					<span class="cardLinkArrow">→</span>
				</div>
			</div>
		</a>-->
		
		<!--<a class="card" href="/directplus_ent/server/purpose/file.html">
			<div class="cardImage">
				<div class="cardImageTag" style="border-right: 1px solid #fff; border-bottom: 1px solid #fff;">おすすめ構成</div>
				<img src="/directplus_ent/images/banners/bnr_800x350_purpose.jpg" alt="">
			</div>
			<div class="cardText">
				<div class="cardTitle">
					用途に合わせたHPEオススメの構成例をご紹介
				</div>
				<div class="cardLink">
					サーバーを用途で選ぶ
					<span class="cardLinkArrow">→</span>
				</div>
			</div>
		</a>-->
		
		<!--<a class="card" href="/directplus_ent/server/dl160gen10/">
			<div class="spTrimHeight cardImage">
				<div class="cardImageTag">製品情報</div>
				<img src="/directplus_ent/images/banners/bnr_800x350_dl160.jpg" alt="">
			</div>
			<div class="cardText">
				<div class="cardTitle">
					コスト×性能で選ぶなら
				</div>
				<div class="cardLink">
					中小規模システムに最適なラックサーバー
					<span class="cardLinkArrow">→</span>
				</div>
			</div>
		</a>-->
		
		<!--<a class="card" href="/directplus_ent/server/features.html">
			<div class="spTrimHeight cardImage">
				<div class="cardImageTag">解説記事</div>
				<img src="/directplus_ent/images/banners/bnr_800x350_server.jpg" alt="">
			</div>
			<div class="cardText">
				<div class="cardTitle">
					最新テクノロジーを徹底解剖
				</div>
				<div class="cardLink">
					テクノロジー解説記事はこちら
					<span class="cardLinkArrow">→</span>
				</div>
			</div>
		</a>-->

		<!--<a class="card" href="/directplus_ent/server/microservergen10.html">
			<div class="spTrimHeight cardImage">
				<div class="cardImageTag">製品情報</div>
				<img src="/directplus_ent/images/banners/bnr_800x350_microservergen10plus.jpg" alt="">
			</div>
			<div class="cardText">
				<div class="cardTitle">
					わずか12㎝の極小安心サーバー
				</div>
				<div class="cardLink">
					コンパクト性、性能、管理性を大幅に強化
					<span class="cardLinkArrow">→</span>
				</div>
			</div>
		</a>
		
		<a class="card" href="/events/seminars/info/leaving_hpe.html?id=1&url=https%3A%2F%2Fhpe.zoom.us%2Fwebinar%2Fregister%2F6115982814773%2FWN_uFRNWxHHRH-UJMs_KVzn3Q" target="_blank">
			<div class="spTrimHeight cardImage">
				<div class="cardImageTag">オンラインセミナー</div>
				<img src="/directplus_ent/images/banners/bnr_800x350_onlineseminar_20200902.jpg" alt="">
			</div>
			<div class="cardText">
				<div class="cardTitle">
					30分でわかる！上司に「うちのIT、セキュリティ大丈夫？」と言われた時の返し方
					<div class="cardSubTitle">
						[参加無料] 2020年10月7日（水）11:00～
					</div>
				</div>
				<div class="cardLink">
					お申込みはこちら
					<span class="cardLinkArrow">→</span>
				</div>
			</div>
		</a>
		
		<a class="card" href="/directplus_ent/recipe/">
			<div class="spTrimHeight cardImage">
				<img src="/directplus_ent/images/banners/bnr_800x350_recipe.jpg" alt="">
			</div>
			<div class="cardText">
				<div class="cardTitle">
					サーバー導入・更新に役立つ情報やオススメ構成をご紹介
				</div>
				<div class="cardLink">
					HPEのスペシャリストによるサーバーレシピ
					<span class="cardLinkArrow">→</span>
				</div>
			</div>
		</a>-->
		
	</div>
</div><!--End Pannel banners -->