					<!--<div class="mb30">-->
					<div>
						<div class="column50-50HasMovie textTop alignItemsCtr">
							<div class="clm1 movie" style="flex-basis: 65%;">
								<div class="brightCoveWrapper">
									<div class="brightCove gryBdr1px">
										<video
											id="bc_video1"
											data-account="4119874060001"
											data-player="321f0ea8-4a70-4101-8de4-b22992f451f5"
											data-embed="default"
											data-video-id="ref:c5f56219-32ce-4094-a458-df1b89505ccd"
											class="video-js"
											controls
										></video>
									</div>
								</div>
							</div>
							<div class="clm2 f15">
								<h3 class="f20 bold mb10 lessTabletAlignCtr">実機で解説<br>HPE ProLiantサーバー<br class="br375">ユーザーガイド<br>～外部コンポーネント編～</h3>
								<p class="mb20">HPE ProLiant DL380 Gen10 サーバーユーザーガイドの内容に沿って、実機を触りながら解説します。</p>
								<p class="indent-1">※<a href="JavaScript:MM_openBrWindow('/directplus_ent/server/popup/correction_202104.html','DetailWin','screenX=10,screenY=10,left=10,top=10,width=700,height=500,scrollbars=yes,resizable=yes');" class="tertiary-link">動画内容の訂正のお知らせ</a></p>
							</div>
						</div>
					</div>
