<div class="specTableArea specTableAreaSp" style="margin-top: -15px;">
	<div class="specTableAreaBg">
		<div class="specTableAreaBgInr">
		<!--div class="specTableAreaDivider"></div-->
			<div class="hpe-accordion">
				<div class="accordion-panel" style="border-bottom: none;">
					<div class="accordion-panel-header">
						<a href="javascript:void(0);" class="accordion-toggle icon-toggle-circle-open open">ラックマウント型サーバー 1U</a>
					</div>
					<div class="accordion-panel-body" style="display: block;">
						<div class="specTableItemsArea">
							<div class="specTableItems">

								<!--DL160 Gen10 -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="/directplus_ent/server/dl160gen10/">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl160_gen10.gif" class="productImg">
											HPE ProLiant<br>DL160 Gen10
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)<sup>※1</sup>
										<a href="/directplus_ent/server/dl160gen10/" class="btn btn-secondary" role="button"><span>354,000円～</span></a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">6,240円<sup>※</sup>〜</span><br>
									</div>
									<div class="specTableItemDetail">
										ローエンドでありながら柔軟な拡張性を提供
										<div class="indent-1">※1:ライザーオプション搭載時</div>
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">インテル</div>
										<div class="specTableItemType">CTO対応</div>
									</div>
								</div>
								<!--DL325 Gen10 -->
								<!--<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="/directplus_ent/server/dl325gen10/">
											<img src="#include virtual="/directplus_ent/include/intershop_domain.inc" /is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl325_gen10.gif" class="productImg">
											HPE ProLiant<br>DL325 Gen10
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)
										<a href="/directplus_ent/server/dl325gen10/" class="btn btn-secondary" role="button"><span>467,000円～</span></a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">8,240円<sup>※</sup>〜</span><br>
									</div>
									<div class="specTableItemDetail">
										2Pサーバーのコストパフォーマンスを凌駕する1Pラックサーバー
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">AMD</div>
										<div class="specTableItemType">CTO対応</div>
									</div>
								</div>-->

								<!--DL325 Gen10 Plus -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="/directplus_ent/server/dl325gen10plus/">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl325_gen10_plus_campaign.gif" class="productImg">
											HPE ProLiant<br>DL325 Gen10 Plus
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)
										<a href="/directplus_ent/server/dl325gen10plus/" class="btn btn-secondary" role="button"><span>372,000円～</span></a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">6,560円<sup>※</sup>〜</span><br>
									</div>
									<div class="specTableItemDetail">
										設計を一新し、常識を変えるストレージ拡張性を実現
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">AMD</div>
										<div class="specTableItemType">CTO対応</div>
									</div>
								</div>

								<!--DL325 Gen10 Plus v2 -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="/directplus_ent/server/dl325gen10plusv2/">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl325_gen10_plus_v2.gif" class="productImg">
											HPE ProLiant<br>DL325 Gen10 Plus v2
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)
										<a href="/directplus_ent/server/dl325gen10plusv2/" class="btn btn-secondary" role="button"><span>707,000円～</span></a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">12,470円<sup>※</sup>〜</span><br>
									</div>
									<div class="specTableItemDetail">
										2プロセッサーに匹敵する性能で高コストパフォーマンスを発揮する1ソケットサーバー
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">AMD</div>
										<div class="specTableItemType">CTO対応</div>
									</div>
								</div>

								<!--DL360 Gen10 -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="/directplus_ent/server/dl360gen10/">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl360_gen10_campaign.gif" class="productImg">
											HPE ProLiant<br>DL360 Gen10
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)
										<a href="/directplus_ent/server/dl360gen10/" class="btn btn-secondary" role="button"><span>385,000円～</span></a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">6,790円<sup>※</sup>〜</span><br>
									</div>
									<div class="specTableItemDetail">
										あらゆるワークロードに対応する 1U2Pのセキュアなプラットフォーム
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">インテル</div>
										<div class="specTableItemType">CTO対応</div>
									</div>
								</div>

								<!--DL360 Gen10 Plus -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="/directplus_ent/server/dl360gen10plus/">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl360_gen10_plus.gif" class="productImg">
											HPE ProLiant<br>DL360 Gen10 Plus
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)
										<a href="/directplus_ent/server/dl360gen10plus/" class="btn btn-secondary" role="button"><span>700,000円～</span></a>
									</div>
									<div class="mt10 mb10">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">12,350円<sup>※</sup>〜</span><br>
									</div>
									<div class="specTableItemDetail">
										高い性能を要求されるワークロードに最適
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">インテル</div>
										<div class="specTableItemType">CTO対応</div>
									</div>
								</div>

								<!--DL365 Gen10 Plus -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="/directplus_ent/server/dl365gen10plus/">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl365_gen10_plus.gif" class="productImg">
											HPE ProLiant<br>DL365 Gen10 Plus
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)
										<a href="/directplus_ent/server/dl365gen10plus/" class="btn btn-secondary" role="button"><span>695,000円～</span></a>
									</div>
									<div class="mt10 mb10">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">12,260円<sup>※</sup>〜</span><br>
									</div>
									<div class="specTableItemDetail">
										高性能と高集約性を併せ持つ1U2ソケットサーバーの新たなラインアップ
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">AMD</div>
										<div class="specTableItemType">CTO対応</div>
									</div>
								</div>

							</div>
							<span class="f12">※サブスク月額料は残価設定型の場合</span>
						</div>
					</div>
				</div>
			</div>
			<div class="hpe-accordion">
				<div class="accordion-panel">
					<div class="accordion-panel-header">
						<a href="javascript:void(0);" class="accordion-toggle icon-toggle-circle-open open">ラックマウント型サーバー 2U</a>
					</div>
					<div class="accordion-panel-body" style="display: block;">
						<div class="specTableItemsArea">
							<div class="specTableItems">

								<!--DL180 Gen10 -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="/directplus_ent/server/dl180gen10/">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl180_gen10.gif" class="productImg">
											HPE ProLiant<br>DL180 Gen10
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)
										<a href="/directplus_ent/server/dl180gen10/" class="btn btn-secondary" role="button"><span>376,000円～</span></a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">6,630円<sup>※</sup>〜</span><br>
									</div>
									<div class="specTableItemDetail">
										ローエンドでありながら柔軟な拡張性を提供
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">インテル</div>
										<div class="specTableItemType">CTO対応</div>
									</div>
								</div>

								<!--DL345 Gen10 Plus -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="/directplus_ent/server/dl345gen10plus/">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl345_gen10_plus.gif" class="productImg">
											HPE ProLiant<br>DL345 Gen10 Plus
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)
										<a href="/directplus_ent/server/dl385gen10/" class="btn btn-secondary" role="button"><span>574,000円～</span></a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">10,130円<sup>※</sup>〜</span><br>
									</div>
									<div class="specTableItemDetail">
										データを多用するワークロードに対応可能な2Uラックのストレージ容量を備えた1ソケットサーバー
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">AMD</div>
										<div class="specTableItemType">CTO対応</div>
									</div>
								</div>

								<!--DL380 Gen10 -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="/directplus_ent/server/dl380gen10/">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl380_gen10.gif" class="productImg">
											HPE ProLiant<br>DL380 Gen10
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)
										<a href="/directplus_ent/server/dl380gen10/" class="btn btn-secondary" role="button"><span>607,000円～</span></a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">10,710円<sup>※</sup>〜</span><br>
									</div>
									<div class="specTableItemDetail">
										データベース、ERP、データ分析など高負荷ワークロードに最適
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">インテル</div>
										<div class="specTableItemType">CTO対応</div>
									</div>
								</div>

								<!--DL380 Gen10 Plus -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="/directplus_ent/server/dl380gen10plus/">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl380_gen10_plus.gif" class="productImg">
											HPE ProLiant<br>DL380 Gen10 Plus
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)
										<a href="/directplus_ent/server/dl380gen10plus/" class="btn btn-secondary" role="button"><span>849,000円～</span></a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">14,980円<sup>※</sup>〜</span><br>
									</div>
									<div class="specTableItemDetail">
										高い性能と拡張性の増強、安心機能を備えたハイエンド2U機
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">インテル</div>
										<div class="specTableItemType">CTO対応</div>
									</div>
								</div>

								<!--DL385 Gen10 Plus -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="/directplus_ent/server/dl385gen10plus/">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl385_gen10_plus.gif" class="productImg">
											HPE ProLiant<br>DL385 Gen10 Plus
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)
										<a href="/directplus_ent/server/dl385gen10plus/" class="btn btn-secondary" role="button"><span>651,000円～</span></a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">11,480円<sup>※</sup>〜</span><br>
									</div>
									<div class="specTableItemDetail">
										設計を一新し適用用途をさらに拡大
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">AMD</div>
										<div class="specTableItemType">CTO対応</div>
									</div>
								</div>

								<!--DL385 Gen10 Plus v2 -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="/directplus_ent/server/dl385gen10plusv2/">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl385_gen10_plus_v2.gif" class="productImg">
											HPE ProLiant<br>DL385 Gen10 Plus v2
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)
										<a href="/directplus_ent/server/dl385gen10plusv2/" class="btn btn-secondary" role="button"><span>839,000円～</span></a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">14,800円<sup>※</sup>〜</span><br>
									</div>
									<div class="specTableItemDetail">
										すべての領域で高い性能を発揮する新世代のフラッグシップ・サーバー
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">AMD</div>
										<div class="specTableItemType">CTO対応</div>
									</div>
								</div>
							</div>
						</div>
						<span class="f12">※サブスク月額料は残価設定型の場合</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div><!-- ./specTableAreaSp -->
