<div class="specTableArea specTableAreaPc">
	<div class="cfx mb15">
		<div class="floatLft"><h4 class="f22 bold">
			ラックマウント型サーバー スペック一覧
		</h4></div>
		<div class="floatRgt"><a href="#AboutModel" class="cta-link lhMid"><em class="icon-arrow-circle-right"></em>「オプ得モデル」「通常モデル」についてはこちら</a></div>
	</div>
	<div class="mb10">
		<ul class="serverSpecList cfx">
			<li><span class="bold f16 icon25Rack">1U</span></li>
			<li><a href="#SpecDL160Gen10" class="tertiary-link">HPE ProLiant<br>DL160 Gen10</a></li>
			<li><a href="#SpecDL325Gen10" class="tertiary-link">HPE ProLiant<br>DL325 Gen10</a></li>
			<li><a href="#SpecDL325Gen10Plus" class="tertiary-link">HPE ProLiant<br>DL325 Gen10 Plus</a></li>
			<li><a href="#SpecDL325Gen10PlusV2" class="tertiary-link">HPE ProLiant<br>DL325 Gen10 Plus v2</a></li>
			<li><a href="#SpecDL360Gen10" class="tertiary-link">HPE ProLiant<br>DL360 Gen10</a></li>
			<li><a href="#SpecDL360Gen10Plus" class="tertiary-link">HPE ProLiant<br>DL360 Gen10 Plus</a></li>
			<li><a href="#SpecDL365Gen10Plus" class="tertiary-link">HPE ProLiant<br>DL365 Gen10 Plus</a></li>
		</ul>
		<ul class="serverSpecList cfx">
			<li><span class="bold f16 icon25Rack">2U</span></li>
			<li><a href="#SpecDL180Gen10" class="tertiary-link">HPE ProLiant<br>DL180 Gen10</a></li>
			<li><a href="#SpecDL345Gen10Plus" class="tertiary-link">HPE ProLiant<br>DL345 Gen10 Plus</a></li>
			<li><a href="#SpecDL380Gen10" class="tertiary-link">HPE ProLiant<br>DL380 Gen10</a></li>
			<li><a href="#SpecDL380Gen10Plus" class="tertiary-link">HPE ProLiant<br>DL380 Gen10 Plus</a></li>
			<li><a href="#SpecDL385Gen10Plus" class="tertiary-link">HPE ProLiant<br>DL385 Gen10 Plus</a></li>
			<li><a href="#SpecDL385Gen10PlusV2" class="tertiary-link">HPE ProLiant<br>DL385 Gen10 Plus v2</a></li>
		</ul>
	</div>
	<h5 class="f18 mb10 bold">1U</h5>
	<table width="100%" cellpadding="0" cellspacing="0" class="specTable">
		<tr>
			<th width="12.5%">&nbsp;</th>
			<th width="12.5%" class="spTable" id="SpecDL160Gen10">
				<span class="productTitle"><a href="/directplus_ent/server/dl160gen10/">HPE ProLiant<br>DL160 Gen10</a></span>
				<div class="spProductDetail"></div>
			</th>
			<th width="12.5%" class="spTable" id="SpecDL325Gen10">
				<span class="productTitle"><a href="/directplus_ent/server/dl325gen10/">HPE ProLiant<br>DL325 Gen10</a></span>
				<div class="spProductDetail"></div>
			</th>
			<th width="12.5%" class="spTable" id="SpecDL325Gen10Plus">
				<span class="productTitle"><a href="/directplus_ent/server/dl325gen10plus/">HPE ProLiant<br>DL325 Gen10 Plus</a></span>
				<div class="spProductDetail"></div>
			</th>
			<th width="12.5%" class="spTable" id="SpecDL325Gen10PlusV2">
				<span class="productTitle"><a href="/directplus_ent/server/dl325gen10plusv2/">HPE ProLiant<br>DL325 Gen10 Plus v2</a></span>
				<div class="spProductDetail"></div>
			</th>
			<th width="12.5%" class="spTable" id="SpecDL360Gen10">
				<span class="productTitle"><a href="/directplus_ent/server/dl360gen10/">HPE ProLiant<br>DL360 Gen10</a></span>
				<div class="spProductDetail"></div>
			</th>
			<th width="12.5%" class="spTable" id="SpecDL360Gen10Plus">
				<span class="productTitle"><a href="/directplus_ent/server/dl360gen10plus/">HPE ProLiant<br>DL360 Gen10 Plus</a></span>
				<div class="spProductDetail"></div>
			</th>
			<th width="12.5%" class="spTable" id="SpecDL365Gen10Plus">
				<span class="productTitle"><a href="/directplus_ent/server/dl365gen10plus/">HPE ProLiant<br>DL365 Gen10 Plus</a></span>
				<div class="spProductDetail"></div>
			</th>
		</tr>
		<tr class="specs">
			<th>
				商品<br>
				<span class="f11">※画像は構成によって実際の製品と異なる場合があります</span>
			</th>
			<!--DL160 Gen10--><td>
				<a href="/directplus_ent/server/dl160gen10/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl160_gen10.gif" class="productImg">
				</a>
			</td>
			<!--DL325 Gen10--><td>
				<a href="/directplus_ent/server/dl325gen10/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl325_gen10.gif" class="productImg">
				</a>
			</td>
			<!--DL325 Gen10 Plus--><td>
				<a href="/directplus_ent/server/dl325gen10plus/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl325_gen10_plus.gif" class="productImg">
				</a>
			</td>
			<!--DL325 Gen10 Plus v2--><td>
				<a href="/directplus_ent/server/dl325gen10plusv2/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl325_gen10_plus_v2.gif" class="productImg">
				</a>
			</td>
			<!--DL360 Gen10--><td>
				<a href="/directplus_ent/server/dl360gen10/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl360_gen10.gif" class="productImg">
				</a>
			</td>
			<!--DL360 Gen10 Plus--><td>
				<a href="/directplus_ent/server/dl360gen10plus/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl360_gen10_plus.gif" class="productImg">
				</a>
			</td>
			<!--DL365 Gen10 Plus--><td>
				<a href="/directplus_ent/server/dl365gen10plus/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl365_gen10_plus.gif" class="productImg">
				</a>
			</td>
		</tr>
		<tr class="specs">
			<th>最小構成価格(税抜)</th>
			<!--DL160 Gen10--><td>
				<div class="alignCtr">
					<span class="price">
						<a href="/directplus_ent/server/dl160gen10/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
						<span class="bold f18 lhMin">354,000円～</span>
					</span>
					<div class="mt20">
						※ライザーオプション搭載時
					</div>
				</div>
			</td>
			<!--DL325 Gen10--><td>
				<div class="alignCtr">
					<span class="price">
						<a href="/directplus_ent/server/dl325gen10/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
						<span class="bold f18">443,000円～</span>
					</span>
				</div>
			</td>
			<!--DL325 Gen10 Plus--><td>
				<div class="alignCtr">
					<span class="price">
						<a href="/directplus_ent/server/dl325gen10plus/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
						<span class="bold f18">530,000円～</span>
					</span>
				</div>
			</td>
			<!--DL325 Gen10 Plus v2--><td>
				<div class="alignCtr">
					<span class="price">
						<a href="/directplus_ent/server/dl325gen10plusv2/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
						<span class="bold f18">707,000円～</span>
					</span>
				</div>
			</td>
			<!--DL360 Gen10--><td>
				<div class="alignCtr">
					<span class="price">
						<a href="/directplus_ent/server/dl360gen10/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
						<span class="bold f18">494,000円～</span>
					</span>
				</div>
			</td>
			<!--DL360 Gen10 Plus--><td>
				<div class="alignCtr">
					<span class="specTableLinkS"><a href="/directplus_ent/server/dl360gen10plus/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br><span class="bold f18">700,000円～</span></span>
				</div>
			</td>
			<!--DL365 Gen10 Plus--><td>
				<div class="alignCtr">
					<span class="specTableLinkS"><a href="/directplus_ent/server/dl365gen10plus/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br><span class="bold f18">1,839,000円～</span></span>
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th>ラック搭載時</th>
			<!--DL160 Gen10	 --><td class="vMiddle"><div class="alignCtr">1U</div></td>
			<!--DL325 Gen10	 --><td class="vMiddle"><div class="alignCtr">1U</div></td>
			<!--DL325 Gen10 Plus--><td class="vMiddle"><div class="alignCtr">1U</div></td>
			<!--DL325 Gen10 Plus v2--><td class="vMiddle"><div class="alignCtr">1U</div></td>
			<!--DL360 Gen10	 --><td class="vMiddle"><div class="alignCtr">1U</div></td>
			<!--DL360 Gen10 Plus--><td class="vMiddle"><div class="alignCtr">1U</div></td>
			<!--DL365 Gen10 Plus--><td class="vMiddle"><div class="alignCtr">1U</div></td>
		</tr>
		<tr class="specs">
			<th>おすすめ用途</th>
			<!--DL160 Gen10	 --><td>・中小規模業務アプリケーションサーバー<br>・サービスプロバイダ用途<br>・Webサーバー</td>
			<!--DL325 Gen10	 --><td>・中規模業務アプリケーションサーバー<br>・Webサーバー<br>・メールサーバー<br>・仮想化<br>・中規模DB<br>・ファイルサーバー</td>
			<!--DL325 Gen10 Plus--><td>・中規模業務アプリケーションサーバー<br>・Webサーバー<br>・メールサーバー<br>・仮想化<br>・中規模DB<br>・中規模ファイルサーバー</td>
			<!--DL325 Gen10 Plus v2--><td>・中規模業務アプリケーションサーバー<br>・Webサーバー<br>・メールサーバー<br>・仮想化&amp;VDI<br>・中規模DB<br>・ファイルサーバー</td>
			<!--DL360 Gen10	 --><td>・大中規模業務アプリケーションサーバー<br>・Webサーバー<br>・メールサーバー<br>・仮想化&amp;VDI<br>・中規模DB<br>・ファイルサーバー</td>
			<!--DL360 Gen10 Plus--><td>・大中規模業務アプリケーションサーバー<br>・性能を重視する用途<br>・科学技術演算用サーバー<br>・メールサーバー<br>・仮想化&amp;VDI<br>・中規模DB<br>・ファイルサーバー</td>
			<!--DL365 Gen10 Plus--><td>・大中規模業務アプリケーションサーバー<br>・性能を重視する用途<br>・科学技術演算用サーバー<br>・メールサーバー<br>・仮想化&amp;VDI<br>・中規模DB<br>・ファイルサーバー</td>
		</tr>
		<tr class="specs">
			<th>フルカスタマイズCTO対応</th>
			<!--DL160 Gen10	 --><td class="vMiddle"><div class="alignCtr f16">○</div></td>
			<!--DL325 Gen10	 --><td class="vMiddle"><div class="alignCtr f16">○</div></td>
			<!--DL325 Gen10 Plus--><td class="vMiddle"><div class="alignCtr f16">○</div></td>
			<!--DL325 Gen10 Plus v2--><td class="vMiddle"><div class="alignCtr f16">○</div></td>
			<!--DL360 Gen10	 --><td class="vMiddle"><div class="alignCtr f16">○</div></td>
			<!--DL360 Gen10 Plus--><td class="vMiddle"><div class="alignCtr f16">○</div></td>
			<!--DL365 Gen10 Plus--><td class="vMiddle"><div class="alignCtr f16">○</div></td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconProsessor">プロセッサー</th>
			<!--DL160 Gen10	 --><td>最大2基：インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー</td>
			<!--DL325 Gen10	 --><td>最大1基：AMD EPYC&trade; プロセッサー</td>
			<!--DL325 Gen10 Plus--><td>最大1基：AMD EPYC&trade; プロセッサー</td>
			<!--DL325 Gen10 Plus v2--><td>最大1基：AMD EPYC&trade; プロセッサー</td>
			<!--DL360 Gen10	 --><td>最大2基：インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー</td>
			<!--DL360 Gen10 Plus--><td>最大2基：インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー</td>
			<!--DL365 Gen10 Plus--><td>最大2基：AMD EPYC&trade; プロセッサー</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconMemory">メモリ</th>
			<!--DL160 Gen10	 --><td>16DIMMスロット<br>DDR4 RDIMM</td>
			<!--DL325 Gen10	 --><td>16DIMMスロット<br>DDR4 RDIMM</td>
			<!--DL325 Gen10 Plus--><td>16DIMMスロット<br>DDR4 RDIMM</td>
			<!--DL325 Gen10 Plus v2--><td>16DIMMスロット<br>DDR4 RDIMM</td>
			<!--DL360 Gen10	 --><td>24DIMMスロット<br>DDR4 RDIMM</td>
			<!--DL360 Gen10 Plus--><td>24DIMMスロット<br>DDR4 RDIMM</td>
			<!--DL365 Gen10 Plus--><td>30DIMMスロット<br>DDR4 RDIMM</td>
		</tr>
		<tr class="specs">
			<th>チップセット</th>
			<!--DL160 Gen10	 --><td>インテル<sup>&reg;</sup> C622</td>
			<!--DL325 Gen10	 --><td>SoC(System on Chip)</td>
			<!--DL325 Gen10 Plus--><td>SoC(System on Chip)</td>
			<!--DL325 Gen10 Plus v2--><td>SoC(System on Chip)</td>
			<!--DL360 Gen10	 --><td>インテル<sup>&reg;</sup> C621</td>
			<!--DL360 Gen10 Plus--><td>インテル<sup>&reg;</sup> C621A</td>
			<!--DL365 Gen10 Plus--><td>SoC(System on Chip)</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconDrive">ドライブ</th>
			<!--DL160 Gen10	 --><td>4(3.5型ホットプラグSAS/SATA/SSD)<br>8(2.5型ホットプラグSAS/SATA/SSD)</td>
			<!--DL325 Gen10	 --><td>4(3.5型ホットプラグSAS/SATA)<br>標準8、最大10(2.5型ホットプラグSAS/SATA/SSD)</td>
			<!--DL325 Gen10 Plus--><td>標準4、最大8(3.5型ホットプラグSAS/SATA/SSD)<br>標準8、最大16(2.5型ホットプラグSAS/SATA/SSD)</td>
			<!--DL325 Gen10 Plus v2--><td>4(LFF ホットプラグSAS/SATA/SSD)<br>標準8、最大10(SFF ホットプラグSAS/SATA/SSD)</td>
			<!--DL360 Gen10	 --><td>標準8、最大10(2.5型ホットプラグSAS/SATA/SSD)</td>
			<!--DL360 Gen10 Plus--><td>4(LFF ホットプラグ SAS/SATA/SSD)<br>標準8、最大10(SFF ホットプラグ SAS/SATA/SSD)</td>
			<!--DL365 Gen10 Plus--><td>標準8、最大10(SFF ホットプラグSAS/SATA/SSD)</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconDiscController">ディスク<br>コントローラー</th>
			<!--DL160 Gen10	 --><td>Smart アレイ S100i標準搭載<br><span class="f11">※モデルによりアップグレード可</span></td>
			<!--DL325 Gen10	 --><td>Smartアレイ E208i-a標準搭載<br><span class="f11">※モデルによりアップグレード可</span></td>
			<!--DL325 Gen10 Plus--><td>SmartアレイP408i-a、SmartアレイP816i-a、またはSmartアレイE208i-a標準搭載<br><span class="f11">※モデルによりアップグレード可</span></td>
			<!--DL325 Gen10 Plus v2--><td>SmartアレイE208i-a、標準搭載<br><span class="f11">※モデルによりアップグレード可</span></td>
			<!--DL360 Gen10	 --><td>Smartアレイ S100iまたはSmartアレイ E208i-a標準搭載<br><span class="f11">※モデルによりアップグレード可</span></td>
			<!--DL360 Gen10 Plus--><td>Smartアレイ SR100iまたはSmartアレイ E208i-a標準搭載<br><span class="f11">※モデルによりアップグレード可</span></td>
			<!--DL365 Gen10 Plus--><td>SmartアレイE208i-a標準搭載<br><span class="f11">※モデルによりアップグレード可</span></td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconNetwork">ネットワーク</th>
			<!--DL160 Gen10	 --><td>Ethernet 1Gb 2ポート ネットワーク アダプター</td>
			<!--DL325 Gen10	 --><td>オンボードNIC非搭載/各種NIC選択可</td>
			<!--DL325 Gen10 Plus--><td>Ethernet 1Gb 4ポート OCP3 NIC（各種NICに変更可/オンボードNIC非搭載）</td>
			<!--DL325 Gen10 Plus v2--><td>Ethernet 1Gb 4ポート OCP3 NIC（各種NICに変更可/オンボードNIC非搭載）</td>
			<!--DL360 Gen10	 --><td>Ethernet 1Gb 4ポート ネットワークアダプター（第2世代モデルはオンボードNIC非搭載/各種NIC選択可）</td>
			<!--DL360 Gen10 Plus--><td>Ethernet 1Gb 4ポート ネットワークアダプター（オンボードNIC非搭載/各種NIC選択可）</td>
			<!--DL365 Gen10 Plus--><td>Ethernet 1Gb 4ポート OCP3 NIC（各種NICに変更可/オンボードNIC非搭載）</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconNetwork">拡張スロット</th>
			<!--DL160 Gen10	 --><td>3 (メディアモジュールアダプター用×1、フルハイト/ハーフレングス PCI Express Gen3 x16×1、ロープロファイル/ハーフレングス PCI Express Gen3 x8×1)</td>
			<!--DL325 Gen10	 --><td>2(フルハイト/フルレングス PCI Express Gen3 x16×1、ロープロファイルPCI Express Gen3 x8×1)</td>
			<!--DL325 Gen10 Plus--><td>3 (OCP 3.0 スロット×1、フルハイト/フルレングスPCI Express Gen4 x16 ×1、ロープロファイル/ハーフレングスPCI Express Gen4 x16×1)<br><span class="f11">※オプションにより最大4</span></td>
			<!--DL325 Gen10 Plus v2--><td>3 (OCP 3.0 スロット×1、フルハイト/フルレングスPCI Express Gen4 x16 ×1、ロープロファイル/ハーフレングスPCI Express Gen4 x16×1)<br><span class="f11">※オプションにより最大4</span></td>
			<!--DL360 Gen10	 --><td>3(FlexibleLOMアダプター用スロット×1、FH/HL PCI Express Gen3 x16×1、LP/HL PCI Express Gen3 x8×1)<br><span class="f11">※オプションにより最大4</span></td>
			<!--DL360 Gen10 Plus--><td>2(FH/HL PCI Express Gen4 x16×1、LP/HL PCI Express Gen4 x8×1)<br><span class="f11">※オプションにより最大3</span></td>
			<!--DL365 Gen10 Plus--><td>3 (OCP 3.0 スロット×1、フルハイト/ハーフレングスPCI Express Gen4 x16(x16 コネクター) ×1、ロープロファイル/フルレングスPCI Express Gen4 x16(x16 コネクター)×1)<br><span class="f11">※オプションにより最大4</span></td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconPower">パワーサプライ</th>
			<!--DL160 Gen10	 --><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL325 Gen10	 --><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL325 Gen10 Plus--><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL325 Gen10 Plus v2--><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL360 Gen10	 --><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL360 Gen10 Plus--><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL365 Gen10 Plus--><td>リダンダント対応<br>ホットプラグ対応</td>
		</tr>
		<tr class="specs">
			<th>冷却ファン</th>
			<!--DL160 Gen10	 --><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL325 Gen10	 --><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL325 Gen10 Plus--><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL325 Gen10 Plus v2--><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL360 Gen10	 --><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL360 Gen10 Plus--><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL365 Gen10 Plus--><td>リダンダント対応<br>ホットプラグ対応</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconRemote">リモート管理</th>
			<!--DL160 Gen10	 --><td>iLO Management Engine(iLO 5)</td>
			<!--DL325 Gen10	 --><td>iLO Management Engine(iLO 5)</td>
			<!--DL325 Gen10 Plus--><td>iLO Management Engine(iLO 5)</td>
			<!--DL325 Gen10 Plus v2--><td>iLO Management Engine(iLO 5)</td>
			<!--DL360 Gen10	 --><td>iLO Management Engine(iLO 5)</td>
			<!--DL360 Gen10 Plus--><td>iLO Management Engine(iLO 5)</td>
			<!--DL365 Gen10 Plus--><td>iLO Management Engine(iLO 5)</td>
		</tr>
		<tr class="specs">
			<th>サイズ(W×D×H)</th>
			<!--DL160 Gen10	 --><td>435×615×43mm</td>
			<!--DL325 Gen10	 --><td>435×615×43mm</td>
			<!--DL325 Gen10 Plus--><td>434×826×42mm</td>
			<!--DL325 Gen10 Plus v2--><td>434×644×43mm</td>
			<!--DL360 Gen10	 --><td>435×707×43mm</td>
			<!--DL360 Gen10 Plus--><td>SFF: 435×742×43mm<br>LFF: 435×773×43mm</td>
			<!--DL365 Gen10 Plus--><td>482 x 806 x 43mm<br>(ラックイヤー、突起含む)</td>
		</tr>
		<tr class="specs">
			<th>フォーム<br class="spHide">ファクター</th>
			<!--DL160 Gen10	 --><td>1U ラックマウント型</td>
			<!--DL325 Gen10	 --><td>1U ラックマウント型</td>
			<!--DL325 Gen10 Plus--><td>1U ラックマウント型</td>
			<!--DL325 Gen10 Plus v2--><td>1U ラックマウント型</td>
			<!--DL360 Gen10	 --><td>1U ラックマウント型</td>
			<!--DL360 Gen10 Plus--><td>1U ラックマウント型</td>
			<!--DL365 Gen10 Plus--><td>1U ラックマウント型</td>
		</tr>
		<tr class="specs">
			<th>OS</th>
			<!--DL160 Gen10	 --><td><div class="mb5">Windows Server</div><div>RedHat Enterprise Linux</div></td>
			<!--DL325 Gen10	 --><td><div class="mb5">Windows Server</div><div>RedHat Enterprise Linux</div></td>
			<!--DL325 Gen10 Plus--><td><div class="mb5">Windows Server</div><div>RedHat Enterprise Linux</div></td>
			<!--DL325 Gen10 Plus v2--><td><div class="mb5">Windows Server</div><div>RedHat Enterprise Linux</div></td>
			<!--DL360 Gen10	 --><td><div class="mb5">Windows Server</div><div>RedHat Enterprise Linux</div></td>
			<!--DL360 Gen10 Plus--><td><div class="mb5">Windows Server</div><div>RedHat Enterprise Linux</div></td>
			<!--DL365 Gen10 Plus--><td><div class="mb5">Windows Server</div><div>RedHat Enterprise Linux</div></td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconSupport">標準保証</th>
			<!--DL160 Gen10	 --><td>3年間パーツ保証、3年間翌営業日オンサイトサービス</td>
			<!--DL325 Gen10	 --><td>3年間パーツ保証、3年間翌営業日オンサイトサービス</td>
			<!--DL325 Gen10 Plus--><td>3年間パーツ保証、3年間翌営業日オンサイトサービス</td>
			<!--DL325 Gen10 Plus v2--><td>3年間パーツ保証、3年間翌営業日オンサイトサービス</td>
			<!--DL360 Gen10	 --><td>3年間パーツ保証、3年間翌営業日オンサイトサービス</td>
			<!--DL360 Gen10 Plus--><td>3年間パーツ保証、3年間翌営業日オンサイトサービス</td>
			<!--DL365 Gen10 Plus--><td>3年間パーツ保証、3年間翌営業日オンサイトサービス</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconMaintenance">サポート<br class="spHide">サービス</th>
			<!--DL160 Gen10	 --><td>
				<div class="mb10">
					<span class="bold">HPE Tech Care Essential</span><br>
					3,4,5年－HD返却不要
				</div>
				<div>
					<span class="bold">HPE Tech Care Basic 4H</span><br>
					3,4,5年－HD返却不要
				</div>
			</td>
			<!--DL325 Gen10	 --><td>
				<div class="mb10">
					<span class="bold">HPE Tech Care Essential</span><br>
					3,4,5年－HD返却不要
				</div>
				<div>
					<span class="bold">HPE Tech Care Basic 4H</span><br>
					3,4,5年－HD返却不要
				</div>
			</td>
			<!--DL325 Gen10 Plus--><td>
				<div class="mb10">
					<span class="bold">HPE Tech Care Essential</span><br>
					3,4,5年－HD返却不要
				</div>
				<div>
					<span class="bold">HPE Tech Care Basic 4H</span><br>
					3,4,5年－HD返却不要
				</div>
			</td>
			<!--DL325 Gen10 Plus v2--><td>
				<div class="mb10">
					<span class="bold">HPE Tech Care Essential</span><br>
					3,4,5年－HD返却不要
				</div>
				<div>
					<span class="bold">HPE Tech Care Basic 4H</span><br>
					3,4,5年－HD返却不要
				</div>
			</td>
			<!--DL360 Gen10	 -->
			<td>
				<div class="mb10">
					<span class="bold">HPE Tech Care Essential</span><br>
					3,4,5,6,7年－HD返却不要
				</div>
				<div>
					<span class="bold">HPE Tech Care Basic 4H</span><br>
					3,4,5,6,7年－HD返却不要
				</div>
			</td>
			<!--DL360 Gen10 Plus--><td><div class="mb10"><span class="bold">HPE Tech Care Essential</span><br>3,4,5,6,7年－HD返却不要</div><div><span class="bold">HPE Tech Care Basic 4H</span><br>3,4,5,6,7年－HD返却不要</div></td>
			<!--DL365 Gen10 Plus--><td><div class="mb10"><span class="bold">HPE Tech Care Essential</span><br>3,4,5,6,7年－HD返却不要</div><div><span class="bold">HPE Tech Care Basic 4H</span><br>3,4,5,6,7年－HD返却不要</div></td>
		</tr>
		<tr>
			<th>&nbsp;</th>
			<th><a href="/directplus_ent/server/dl160gen10/">HPE ProLiant<br>DL160 Gen10</a></th>
			<th><a href="/directplus_ent/server/dl325gen10/">HPE ProLiant<br>DL325 Gen10</a></th>
			<th><a href="/directplus_ent/server/dl325gen10plus/">HPE ProLiant<br>DL325 Gen10 Plus</a></th>
			<th><a href="/directplus_ent/server/dl325gen10plusv2/">HPE ProLiant<br>DL325 Gen10 Plus v2</a></th>
			<th><a href="/directplus_ent/server/dl360gen10/">HPE ProLiant<br>DL360 Gen10</a></th>
			<th><a href="/directplus_ent/server/dl360gen10plus/">HPE ProLiant<br>DL360 Gen10 Plus</a></th>
			<th><a href="/directplus_ent/server/dl365gen10plus/">HPE ProLiant<br>DL365 Gen10 Plus</a></th>
		</tr>
	</table>
	<h5 class="f18 mb10 bold">2U</h5>
	<table width="100%" cellpadding="0" cellspacing="0" class="specTable">
		<tr>
			<th width="10%">&nbsp;</th>
			<th width="15%" class="spTable" id="SpecDL180Gen10">
				<span class="productTitle"><a href="/directplus_ent/server/dl180gen10/">HPE ProLiant<br>DL180 Gen10</a></span>
				<div class="spProductDetail"></div>
			</th>
			<th width="15%" class="spTable" id="SpecDL345Gen10Plus">
				<span class="productTitle"><a href="/directplus_ent/server/dl345gen10plus/">HPE ProLiant<br>DL345 Gen10 Plus</a></span>
				<div class="spProductDetail"></div>
			</th>
			<th width="15%" class="spTable" id="SpecDL380Gen10">
				<span class="productTitle"><a href="/directplus_ent/server/dl380gen10/">HPE ProLiant<br>DL380 Gen10</a></span>
				<div class="spProductDetail"></div>
			</th>
			<th width="15%" class="spTable" id="SpecDL380Gen10Plus">
				<span class="productTitle"><a href="/directplus_ent/server/dl380gen10plus/">HPE ProLiant<br>DL380 Gen10 Plus</a></span>
				<div class="spProductDetail"></div>
			</th>
			<th width="15%" class="spTable" id="SpecDL385Gen10Plus">
				<span class="productTitle"><a href="/directplus_ent/server/dl385gen10plus/">HPE ProLiant<br>DL385 Gen10 Plus</a></span>
				<div class="spProductDetail"></div>
			</th>
			<th width="15%" class="spTable" id="SpecDL385Gen10PlusV2">
				<span class="productTitle"><a href="/directplus_ent/server/dl385gen10plusv2/">HPE ProLiant<br>DL385 Gen10 Plus v2</a></span>
				<div class="spProductDetail"></div>
			</th>
		</tr>
		<tr class="specs">
			<th>
				商品<br>
				<span class="f11">※画像は構成によって実際の製品と異なる場合があります</span>
			</th>
			<!--DL180 Gen10--><td>
				<a href="/directplus_ent/server/dl180gen10/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl180_gen10.gif" class="productImg">
				</a>
			</td>
			<!--DL345 Gen10 Plus--><td>
				<a href="/directplus_ent/server/dl345gen10plus/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl345_gen10_plus.gif" class="productImg">
				</a>
			</td>
			<!--DL380 Gen10--><td>
				<a href="/directplus_ent/server/dl380gen10/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl380_gen10.gif" class="productImg">
				</a>
			</td>
			<!--DL380 Gen10 Plus--><td>
				<a href="/directplus_ent/server/dl380gen10plus/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl380_gen10_plus.gif" class="productImg">
				</a>
			</td>
			<!--DL385 Gen10 Plus--><td>
				<a href="/directplus_ent/server/dl385gen10plus/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl385_gen10_plus.gif" class="productImg">
				</a>
			</td>
			<!--DL385 Gen10 Plus v2--><td>
				<a href="/directplus_ent/server/dl385gen10plusv2/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl385_gen10_plus_v2.gif" class="productImg">
				</a>
			</td>
		</tr>
		<tr class="specs">
			<th>最小構成価格(税抜)</th>
			<!--DL180 Gen10--><td>
				<div class="alignCtr">
					<span class="price">
						<a href="/directplus_ent/server/dl180gen10/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
						<span class="bold f18">376,000円～</span>
					</span>
				</div>
			</td>
			<!--DL345 Gen10 Plus--><td>
				<div class="alignCtr">
					<span class="price">
						<a href="/directplus_ent/server/dl345gen10plus/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
						<span class="bold f18">574,000円～</span>
					</span>
				</div>
			</td>
			<!--DL380 Gen10--><td>
				<div class="alignCtr">
					<span class="price">
						<a href="/directplus_ent/server/dl380gen10/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
						<span class="bold f18">607,000円～</span>
					</span>
				</div>
			</td>
			<!--DL380 Gen10 Plus--><td>
				<div class="alignCtr">
					<span class="price">
						<a href="/directplus_ent/server/dl380gen10plus/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
						<span class="bold f18">849,000円～</span>
					</span>
				</div>
			</td>
			<!--DL385 Gen10 Plus--><td>
				<div class="alignCtr">
					<span class="price">
						<a href="/directplus_ent/server/dl385gen10plus/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
						<span class="bold f18">651,000円～</span>
					</span>
				</div>
			</td>
			<!--DL385 Gen10 Plus v2--><td>
				<div class="alignCtr">
					<span class="price">
						<a href="/directplus_ent/server/dl385gen10plusv2/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
						<span class="bold f18">839,000円～</span>
					</span>
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th>ラック搭載時</th>
			<!--DL180 Gen10	 --><td class="vMiddle"><div class="alignCtr">2U</div></td>
			<!--DL345 Gen10 Plus--><td class="vMiddle"><div class="alignCtr">2U</div></td>
			<!--DL380 Gen10	 --><td class="vMiddle"><div class="alignCtr">2U</div></td>
			<!--DL380 Gen10 Plus--><td class="vMiddle"><div class="alignCtr">2U</div></td>
			<!--DL385 Gen10 Plus--><td class="vMiddle"><div class="alignCtr">2U</div></td>
			<!--DL385 Gen10 Plus v2--><td class="vMiddle"><div class="alignCtr">2U</div></td>
		</tr>
		<tr class="specs">
			<th>おすすめ用途</th>
			<!--DL180 Gen10	 --><td>・中規模業務アプリケーションサーバー<br>・Non SQL DBサーバー<br>・Hadoop<br>・ストリーミングサーバー</td>
			<!--DL345 Gen10 Plus--><td>・中規模業務アプリケーションサーバー<br>・ディスク容量を重視する用途<br>・メールサーバー<br>・仮想化&amp;VDI<br>・中規模DB<br>・中規模ファイルサーバー</td>
			<!--DL380 Gen10	 --><td>・大中規模ファイル/メールサーバー<br>・仮想化&amp;VDI<br>・ディスク容量を重視する用途<br>・中規模DB<br>・画像配信用ストリーミング<br>・Hadoop<br>・人工知能/HPCなどのニーズ</td>
			<!--DL380 Gen10 Plus--><td>・大中規模ファイル/メールサーバー<br>・仮想化&amp;VDI<br>・性能を重視する用途<br>・ディスク容量を重視する用途<br>・中規模DB<br>・画像配信用ストリーミング<br>・人工知能/HPCなどのニーズ</td>
			<!--DL385 Gen10 Plus--><td>・大中規模ファイル/メールサーバー<br>・仮想化&amp;VDI<br>・ディスク容量を重視する用途<br>・中規模DB<br>・画像配信用ストリーミング<br>・人工知能/HPCなどのニーズ</td>
			<!--DL385 Gen10 Plus v2--><td>・大中規模ファイル/メールサーバー<br>・仮想化&amp;VDI<br>・性能を重視する用途<br>・ディスク容量を重視する用途<br>・中規模DB<br>・画像配信用ストリーミング<br>・人工知能/HPCなどのニーズ</td>
		</tr>
		<tr class="specs">
			<th>フルカスタマイズCTO対応</th>
			<!--DL180 Gen10	 --><td class="vMiddle"><div class="alignCtr f16">○</div></td>
			<!--DL345 Gen10 Plus--><td class="vMiddle"><div class="alignCtr f16">○</div></td>
			<!--DL380 Gen10	 --><td class="vMiddle"><div class="alignCtr f16">○</div></td>
			<!--DL380 Gen10 Plus--><td class="vMiddle"><div class="alignCtr f16">○</div></td>
			<!--DL385 Gen10 Plus--><td class="vMiddle"><div class="alignCtr f16">○</div></td>
			<!--DL385 Gen10 Plus v2--><td class="vMiddle"><div class="alignCtr f16">○</div></td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconProsessor">プロセッサー</th>
			<!--DL180 Gen10	 --><td>最大2基：インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー</td>
			<!--DL345 Gen10 Plus--><td>最大1基：AMD EPYC&trade; プロセッサー</td>
			<!--DL380 Gen10	 --><td>最大2基：インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー</td>
			<!--DL380 Gen10 Plus--><td>最大2基：インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー</td>
			<!--DL385 Gen10 Plus--><td>最大2基：AMD EPYC&trade; プロセッサー</td>
			<!--DL385 Gen10 Plus v2--><td>最大2基：AMD EPYC&trade; プロセッサー</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconMemory">メモリ</th>
			<!--DL180 Gen10	 --><td>16DIMMスロット<br>DDR4 RDIMM</td>
			<!--DL345 Gen10 Plus--><td>16DIMMスロット<br>DDR4 RDIMM</td>
			<!--DL380 Gen10	 --><td>24DIMMスロット<br>DDR4 RDIMM</td>
			<!--DL380 Gen10 Plus--><td>32DIMMスロット<br>DDR4 RDIMM</td>
			<!--DL385 Gen10 Plus--><td>32DIMMスロット<br>DDR4 RDIMM</td>
			<!--DL385 Gen10 Plus v2--><td>30DIMMスロット<br>DDR4 RDIMM</td>
		</tr>
		<tr class="specs">
			<th>チップセット</th>
			<!--DL180 Gen10	 --><td>インテル<sup>&reg;</sup> C622</td>
			<!--DL345 Gen10 Plus--><td>SoC(System on Chip)</td>
			<!--DL380 Gen10	 --><td>インテル<sup>&reg;</sup> C621</td>
			<!--DL380 Gen10 Plus--><td>インテル<sup>&reg;</sup> C620A</td>
			<!--DL385 Gen10 Plus--><td>SoC(System on Chip)</td>
			<!--DL385 Gen10 Plus v2--><td>SoC(System on Chip)</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconDrive">ドライブ</th>
			<!--DL180 Gen10	 --><td>8(3.5型ホットプラグ SAS/SATA/SSD)<br>8(2.5型ホットプラグ SAS/SATA/SSD)<br>12(3.5型ホットプラグ SAS/SATA/SSD)</td>
			<!--DL345 Gen10 Plus--><td>8(LFF ホットプラグ SAS/SATA/SSD)<br>標準8、最大16(SFF ホットプラグ SAS/SATA/SSD)</td>
			<!--DL380 Gen10	 --><td>標準8、最大16(2.5型ホットプラグSAS/SATA/SSD)<br>標準12、最大16(3.5型ホットプラグSAS/SATA/SSD)</td>
			<!--DL380 Gen10 Plus--><td>標準8、最大16(SFF ホットプラグ SAS/SATA/SSD)<br>標準12、最大16(LFF ホットプラグ SAS/SATA/SSD)</td>
			<!--DL385 Gen10 Plus--><td>標準8、最大16(2.5型ホットプラグSAS/SATA/SSD)<br>標準12、最大16(3.5型ホットプラグSAS/SATA/SSD)</td>
			<!--DL385 Gen10 Plus v2--><td>標準8、最大16(SFF ホットプラグSAS/SATA/SSD)<br>標準12、最大16(LFF ホットプラグSAS/SATA/SSD)</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconDiscController">ディスク<br>コントローラー</th>
			<!--DL180 Gen10	 --><td>Smart アレイ S100i、Smart アレイ E208i-aまたはSmartアレイ P816i-a 標準搭載<br><span class="f11">※モデルによりアップグレード可</span></td>
			<!--DL345 Gen10 Plus--><td>SmartアレイE208i-a標準搭載<br><span class="f11">※モデルによりアップグレード可</span></td>
			<!--DL380 Gen10	 --><td>Smartアレイ E208i-aまたはSmartアレイ P816i-a標準搭載<br><span class="f11">※モデルによりアップグレード可</span></td>
			<!--DL380 Gen10 Plus--><td>Smartアレイ E208i-aまたはSmartアレイ P816i-a標準搭載<br><span class="f11">※モデルによりアップグレード可</span></td>
			<!--DL385 Gen10 Plus--><td>Smartアレイ P408i-a、SmartアレイP816i-a、またはSmartアレイE208i-a標準搭載<br><span class="f11">※モデルによりアップグレード可</span></td>
			<!--DL385 Gen10 Plus v2--><td>SmartアレイE208i-aまたはSmartアレイ P816i-a標準搭載<br><span class="f11">※モデルによりアップグレード可</span></td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconNetwork">ネットワーク</th>
			<!--DL180 Gen10	 --><td>Ethernet 1Gb 2ポート ネットワークアダプター</td>
			<!--DL345 Gen10 Plus--><td>Ethernet 1Gb 4ポート OCP3 NIC（各種NICに変更可/オンボードNIC非搭載）</td>
			<!--DL380 Gen10	 --><td>Ethernet 1Gb 4ポート ネットワークアダプター（第2世代モデルはオンボードNIC非搭載/各種NIC選択可）</td>
			<!--DL380 Gen10 Plus--><td>Ethernet 1Gb 4ポート ネットワークアダプター（オンボードNIC非搭載/各種NIC選択可）</td>
			<!--DL385 Gen10 Plus--><td>Ethernet 1Gb 4ポート OCP3 NIC（各種NICに変更可/オンボードNIC非搭載）</td>
			<!--DL385 Gen10 Plus v2--><td>Ethernet 1Gb 4ポート OCP3 NIC（各種NICに変更可/オンボードNIC非搭載）</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconNetwork">拡張スロット</th>
			<!--DL180 Gen10	 --><td>4(メディアモジュールアダプター専用×1、フルハイト/フルレングス PCI Express Gen3 x8×1、フルハイト/ハーフレングス PCI Express Gen3 x8×2)</span></td>
			<!--DL345 Gen10 Plus--><td>3 (OCP 3.0 スロット×1、フルハイト/フルレングスPCI Express Gen4 x16(x16 コネクター) ×2)<br><span class="f11">※オプションにより最大5</span></td>
			<!--DL380 Gen10	 --><td>4(FlexibleLOMアダプター用スロット×1、FH/HL PCI Express Gen3 x16×2、FH/HL PCI Express Gen3 x8)<br><span class="f11">※オプションにより最大6</span></td>
			<!--DL380 Gen10 Plus--><td>3(FH/HL PCI Express Gen4 x16×2、FH/HL PCI Express Gen4 x8)<br><span class="f11">※オプションにより最大6</span></td>
			<!--DL385 Gen10 Plus--><td>4 (OCP 3.0 スロット×1、フルハイト/フルレングスPCI Express Gen4 x8 ×1、フルハイト/フルレングスPCI Express Gen4 x16 ×1、フルハイト/ハーフレングスPCI Express Gen4 x8 ×1)<br><span class="f11">※オプションにより最大6</span></td>
			<!--DL385 Gen10 Plus v2--><td>4 (OCP 3.0 スロット×1、フルハイト/フルレングスPCI Express Gen4 x8 ×1、フルハイト/フルレングスPCI Express Gen4 x16 ×1、フルハイト/ハーフレングスPCI Express Gen4 x8 ×1)<br><span class="f11">※オプションにより最大6</span></td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconPower">パワーサプライ</th>
			<!--DL180 Gen10	 --><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL345 Gen10 Plus--><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL380 Gen10	 --><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL380 Gen10 Plus--><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL385 Gen10 Plus--><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL385 Gen10 Plus v2--><td>リダンダント対応<br>ホットプラグ対応</td>
		</tr>
		<tr class="specs">
			<th>冷却ファン</th>
			<!--DL180 Gen10	 --><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL345 Gen10 Plus--><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL380 Gen10	 --><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL380 Gen10 Plus--><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL385 Gen10 Plus--><td>リダンダント対応<br>ホットプラグ対応</td>
			<!--DL385 Gen10 Plus v2--><td>リダンダント対応<br>ホットプラグ対応</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconRemote">リモート管理</th>
			<!--DL180 Gen10	 --><td>iLO Management Engine(iLO 5)</td>
			<!--DL345 Gen10 Plus--><td>iLO Management Engine(iLO 5)</td>
			<!--DL380 Gen10	 --><td>iLO Management Engine(iLO 5)</td>
			<!--DL380 Gen10 Plus--><td>iLO Management Engine(iLO 5)</td>
			<!--DL385 Gen10 Plus--><td>iLO Management Engine(iLO 5)</td>
			<!--DL385 Gen10 Plus v2--><td>iLO Management Engine(iLO 5)</td>
		</tr>
		<tr class="specs">
			<th>サイズ(W×D×H)</th>
			<!--DL180 Gen10	 --><td>446×635×88mm</td>
			<!--DL345 Gen10 Plus--><td>482 x 761 x 87mm</td>
			<!--DL380 Gen10	 --><td>8SFF：446×680×88mm<br>12LFF：446×731×88mm</td>
			<!--DL380 Gen10 Plus--><td>8SFF：445×679×87mm<br>12LFF：445×730×87mm</td>
			<!--DL385 Gen10 Plus--><td>8SFF：445×711×87mm<br>12LFF：445×749×87mm</td>
			<!--DL385 Gen10 Plus v2--><td>445×749×87mm</td>
		</tr>
		<tr class="specs">
			<th>フォーム<br class="spHide">ファクター</th>
			<!--DL180 Gen10	 --><td>2U ラックマウント型</td>
			<!--DL345 Gen10 Plus--><td>2U ラックマウント型</td>
			<!--DL380 Gen10	 --><td>2U ラックマウント型</td>
			<!--DL380 Gen10 Plus--><td>2U ラックマウント型</td>
			<!--DL385 Gen10 Plus--><td>2U ラックマウント型</td>
			<!--DL385 Gen10 Plus v2--><td>2U ラックマウント型</td>
		</tr>
		<tr class="specs">
			<th>OS</th>
			<!--DL180 Gen10	 --><td><div class="mb5">Windows Server</div><div>RedHat Enterprise Linux</div></td>
			<!--DL345 Gen10 Plus--><td><div class="mb5">Windows Server</div><div>RedHat Enterprise Linux</div></td>
			<!--DL380 Gen10	 --><td><div class="mb5">Windows Server</div><div>RedHat Enterprise Linux</div></td>
			<!--DL380 Gen10 Plus--><td><div class="mb5">Windows Server</div><div>RedHat Enterprise Linux</div></td>
			<!--DL385 Gen10 Plus--><td><div class="mb5">Windows Server</div><div>RedHat Enterprise Linux</div></td>
			<!--DL385 Gen10 Plus v2--><td><div class="mb5">Windows Server</div><div>RedHat Enterprise Linux</div></td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconSupport">標準保証</th>
			<!--DL180 Gen10	 --><td>3年間パーツ保証、3年間翌営業日オンサイトサービス</td>
			<!--DL345 Gen10 Plus--><td>3年間パーツ保証、3年間翌営業日オンサイトサービス</td>
			<!--DL380 Gen10	 --><td>3年間パーツ保証、3年間翌営業日オンサイトサービス</td>
			<!--DL380 Gen10 Plus--><td>3年間パーツ保証、3年間翌営業日オンサイトサービス</td>
			<!--DL385 Gen10 Plus--><td>3年間パーツ保証、3年間翌営業日オンサイトサービス</td>
			<!--DL385 Gen10 Plus v2--><td>3年間パーツ保証、3年間翌営業日オンサイトサービス</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconMaintenance">サポート<br class="spHide">サービス</th>
			<!--DL180 Gen10	 --><td>
				<div class="mb10">
					<span class="bold">HPE Tech Care Essential</span><br>
					3,4,5年－HD返却不要
				</div>
				<div>
					<span class="bold">HPE Tech Care Basic 4H</span><br>
					3,4,5年－HD返却不要
				</div>
			</td>
			<!--DL345 Gen10 Plus-->
			<td>
				<div class="mb10">
					<span class="bold">HPE Tech Care Essential</span><br>
					3,4,5年－HD返却不要
				</div>
				<div class="mb30">
					<span class="bold">HPE Tech Care Basic 4H</span><br>
					3,4,5年－HD返却不要
				</div>
			</td>
			<!--DL380 Gen10	 -->
			<td>
				<div class="mb10">
					<span class="bold">HPE Tech Care Essential</span><br>
					3,4,5,6,7年－HD返却不要
				</div>
				<div>
					<span class="bold">HPE Tech Care Basic 4H</span><br>
					3,4,5,6,7年－HD返却不要
				</div>
			</td>
			<!--DL380 Gen10 Plus--><td><div class="mb10"><span class="bold">HPE Tech Care Essential</span><br>3,4,5,6,7年－HD返却不要</div><div><span class="bold">HPE Tech Care Basic 4H</span><br>3,4,5,6,7年－HD返却不要</div></td>
			<!--DL385 Gen10 Plus-->
			<td>
				<div class="mb10">
					<span class="bold">HPE Tech Care Essential</span><br>
					3,4,5年－HD返却不要
				</div>
				<div>
					<span class="bold">HPE Tech Care Basic 4H</span><br>
					3,4,5年－HD返却不要
				</div>
			</td>
			<!--DL385 Gen10 Plus v2-->
			<td>
				<div class="mb10">
					<span class="bold">HPE Tech Care Essential</span><br>
					3,4,5年－HD返却不要
				</div>
				<div class="mb30">
					<span class="bold">HPE Tech Care Basic 4H</span><br>
					3,4,5年－HD返却不要
				</div>
			</td>
		</tr>
		<tr>
			<th>&nbsp;</th>
			<th><a href="/directplus_ent/server/dl180gen10/">HPE ProLiant<br>DL180 Gen10</a></th>
			<th><a href="/directplus_ent/server/dl345gen10plus/">HPE ProLiant<br>DL345 Gen10 Plus</a></th>
			<th><a href="/directplus_ent/server/dl380gen10/">HPE ProLiant<br>DL380 Gen10</a></th>
			<th><a href="/directplus_ent/server/dl380gen10plus/">HPE ProLiant<br>DL380 Gen10 Plus</a></th>
			<th><a href="/directplus_ent/server/dl385gen10plus/">HPE ProLiant<br>DL385 Gen10 Plus</a></th>
			<th><a href="/directplus_ent/server/dl385gen10plusv2/">HPE ProLiant<br>DL385 Gen10 Plus v2</a></th>
		</tr>
	</table>
	<p class="alignRgt mb10">
		<a href="javascript:void(0);" class="cta-link specSwitch ssTower"><em class="icon-arrow-circle-right"></em>タワー型サーバーのラインアップを見る</a>
	</p>
</div><!-- ./specTableAreaPc -->