<div class="specTableArea specTableAreaPc">
	<div class="cfx mb15">
		<div class="floatLft"><h4 class="f22 bold">
			タワー型サーバー スペック一覧
		</h4></div>
		<div class="floatRgt"><a href="#AboutModel" class="cta-link lhMid"><em class="icon-arrow-circle-right"></em>「キャンペーンモデル」「オプ得モデル」「通常モデル」についてはこちら</a></div>
	</div>
	<table width="100%" cellpadding="0" cellspacing="0" class="specTable pcOnly">
		<tr>
			<th width="10%">&nbsp;</th>
			<th width="18%" class="spTable" id="SpecMicroServerGen10Plus">
				<span class="productTitle"><a href="/directplus_ent/server/microservergen10plus/">HPE ProLiant<br>MicroServer Gen10 Plus</a></span>
				<div class="spProductDetail"></div>
			</th>
			<th width="18%" class="spTable" id="Specml30gen10">
				<span class="productTitle"><a href="/directplus_ent/server/ml30gen10/">HPE ProLiant<br>ML30 Gen10</a></span>
				<div class="spProductDetail"></div>
			</th>
			<th width="18%" class="spTable" id="Specml30gen10plus">
				<span class="productTitle"><a href="/directplus_ent/server/ml30gen10plus/">HPE ProLiant<br>ML30 Gen10 Plus</a></span>
				<div class="spProductDetail"></div>
			</th>
			<th width="18%" class="spTable" id="SpecML110Gen10">
				<span class="productTitle"><a href="/directplus_ent/optoku/ml110gen10/">HPE ProLiant<br>ML110 Gen10</a></span>
				<div class="spProductDetail"></div>
			</th>
			<th width="18%" class="spTable" id="SpecML350Gen10">
				<span class="productTitle"><a href="/directplus_ent/server/ml350gen10/">HPE ProLiant<br>ML350 Gen10</a></span>
				<div class="spProductDetail"></div>
			</th>
		</tr>
		<tr class="specs">
			<th>
				商品<br>
				<span class="f11">※画像は構成によって実際の製品と異なる場合があります</span>
			</th>
			<!--MS Gen10 Plus --><td>
				<a href="/directplus_ent/server/microservergen10plus/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_microserver_gen10_plus_optoku.gif" class="productImg">
				</a>
			</td>
			<!--ML30 Gen10 --><td>
				<a href="/directplus_ent/server/ml30gen10/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml30_gen10_optoku.gif" class="productImg">
				</a>
			</td>
			<!--ML30 Gen10 Plus --><td>
				<a href="/directplus_ent/server/ml30gen10plus/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml30_gen10_plus.gif" class="productImg">
				</a>
			</td>
			<!--ML110 Gen10--><td>
				<a href="/directplus_ent/optoku/ml110gen10/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml110_gen10_campaign.gif" class="productImg">
				</a>
			</td>
			<!--ML350 Gen10--><td>
				<a href="/directplus_ent/server/ml350gen10/">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml350_gen10.gif" class="productImg">
				</a>
			</td>
		</tr>
		<tr class="alignCtr bold lhMin specs">
			<th>適用可能な<br class="spHide">キャンペーン</th>
			<!--MS Gen10 Plus -->
			<!--<td class="vMiddle">-->
			<td>
				&nbsp;
			</td>
			<!--ML30 Gen10-->
			<!--<td class="vMiddle">-->
			<td>
				&nbsp;
			</td>
			<!--ML30 Gen10 Plus-->
			<!--<td class="vMiddle">-->
			<td>
				&nbsp;
			</td>
			<!--ML110 Gen10-->
			<!--<td class="vMiddle">-->
			<td>
				<div class="specTableCpmBnr">
					<!--<a href="/directplus_ent/promotion/amazongift/" class="mb10">
						<img src="/directplus_ent/images/banners/bnr_400x90_amazongift_campaign.jpg" alt="お見積でもらえる、ギフト券がもらえる">
					</a>-->
					<a href="/directplus_ent/campaign/">
						<img src="/directplus_ent/images/banners/bnr_400_txt01.png" alt="キャンペーン価格で即時お見積">
						<!--<p>12/下旬（予定）より<br>キャンペーンモデル開始</p>-->
						<img src="/directplus_ent/images/banners/bnr_400x90_it_asap_campaign.jpg" alt="HPE サーバー&amp;ストレージ “ITの準備はお早めに”キャンペーン">
					</a>
				</div>
			</td>
			<!--ML350 Gen10-->
			<!--<td class="vMiddle">-->
			<td>
				&nbsp;
			</td>
		</tr>
		<tr class="specs">
			<th>最小構成価格<br class="spHide">(税抜)<br>※サブスク月額料は残価設定型の場合</th>
			<!--MS Gen10 Plus --><td>
				<div class="alignCtr">
					<span class="price">
						<a href="/directplus_ent/server/microservergen10plus/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>オプ得モデル</a><br>
						<span class="bold f18 lhMin">110,000円～</span>
					</span>
					<div class="mb20">
						<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
							月額（5年）<span class="bold f14">1,940円<sup>※</sup>〜</span><br>
					</div>
					<span class="specTableLinkS">
						<a href="/directplus_ent/server/microservergen10plus/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
						<span class="f12">110,000円～</span>
					</span>

				</div>

			</td>
			<!--ML30 Gen10 --><td>
				<div class="alignCtr">
					<span class="price">
						<a href="/directplus_ent/server/ml30gen10/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>オプ得モデル</a><br>
						<span class="bold f18 lhMin">135,000円～</span>
					</span>
					<div class="mb20">
						<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
						月額（5年）<span class="bold f14">2,380円<sup>※</sup>〜</span><br>
					</div>
					<span class="price">
						<a href="/directplus_ent/server/ml30gen10/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
						<span class="f12">168,000円～</span>
					</span>
				</div>
			</td>
			<!--ML30 Gen10 Plus --><td>
				<div class="alignCtr">
					<span class="price">
						<a href="/directplus_ent/server/ml30gen10plus/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
						<span class="bold f18 lhMin">247,000円～</span>
					</span>
					<div class="mb20">
						<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
						月額（5年）<span class="bold f14">4,360円<sup>※</sup>〜</span><br>
					</div>
					<!--<span class="price">
						<a href="/directplus_ent/server/ml30gen10plus/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
						<span class="f12">168,000円～</span>
					</span>-->
				</div>
			</td>
			<!--ML110 Gen10--><td>
				<div class="alignCtr">
					<span class="price">
						<a href="/directplus_ent/optoku/ml110gen10/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>キャンペーンモデル</a><br>
						<span class="bold f18 lhMin">期間限定 <br class="spHide">176,000円～</span>
					</span>
					<div class="mb20">
						<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
						月額（5年）<span class="bold f14">3,100円<sup>※</sup>〜</span><br>
					</div>
					<span class="price">
						<a href="/directplus_ent/optoku/ml110gen10/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>オプ得モデル</a><br>
						<span class="bold f18 lhMin">207,000円～</span>
					</span>
					<div class="mb20">
						<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
						月額（5年）<span class="bold f14">3,650円<sup>※</sup>〜</span><br>

					</div>
					<span class="specTableLinkS">
						<a href="/directplus_ent/optoku/ml110gen10/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
						<span class="f12">252,000円～</span>
					</span>
				</div>
			</td>
			<!--ML350 Gen10--><td>
				<div class="alignCtr">
					<span class="price">
						<a href="/directplus_ent/server/ml350gen10/?hash=Normal" class="cta-link f12"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
						<span class="bold f18 lhMin">403,000円～</span>
					</span>
					<div class="mb20">
						<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
						月額（5年）<span class="bold f14">7,110円<sup>※</sup>〜</span><br>

					</div>
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th>おすすめ用途</th>
			<!--MS Gen10 Plus --><td>・SOHO/中小規模向け(～10人)<br>・各拠点や部門、小規模店舗用APサーバー<br>・中小規模ファイルサーバー</td>
			<!--ML30 Gen10 --><td>・SOHO/中小規模向け(～100人)<br>・店舗APサーバー<br>・中小規模ファイルサーバー</td>
			<!--ML30 Gen10 Plus --><td>・SOHO/中小規模向け(～100人)<br>・店舗APサーバー<br>・中小規模ファイルサーバー</td>
			<!--ML110 Gen10--><td>・中規模向け(～250人)<br>・Web・APサーバー<br>・中規模ファイルサーバー</td>
			<!--ML350 Gen10--><td>・大規模向け(251人～)<br>・高負荷のAPサーバー<br>・仮想化プラットフォーム<br>・大規模ファイルサーバー</td>
		</tr>
		<tr class="specs">
			<th>フルカスタマイズCTO対応</th>
			<!--MS Gen10 Plus --><td class="vMiddle"><div class="alignCtr f16">×</div><span class="f11">(オプションはお客様にて取付け作業が必要になります)</span></td>
			<!--ML30 Gen10 --><td class="vMiddle"><div class="alignCtr f16">○</div></td>
			<!--ML30 Gen10 Plus --><td class="vMiddle"><div class="alignCtr f16">○</div></td>
			<!--ML110 Gen10--><td class="vMiddle"><div class="alignCtr f16">○</div></td>
			<!--ML350 Gen10--><td class="vMiddle"><div class="alignCtr f16">○</div></td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconProsessor">プロセッサー</th>
			<!--MS Gen10 Plus --><td>最大1基：インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> E2224 /  Pentium<sup>&reg;</sup> Gold G5420 プロセッサー</td>
			<!--ML30 Gen10 --><td>最大1基：インテル<sup>&reg;</sup> Pentium<sup>&reg;</sup> G5400 / Core&trade; i3 / Xeon<sup>&reg;</sup> E-2100 シリーズ</td>
			<!--ML30 Gen10 Plus --><td>最大1基：インテル<sup>&reg;</sup> Pentium<sup>&reg;</sup> G6400 / Xeon<sup>&reg;</sup> E-2300 シリーズ</td>
			<!--ML110 Gen10--><td>最大1基：インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー</td>
			<!--ML350 Gen10--><td>最大2基：インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconMemory">メモリ</th>
			<!--MS Gen10 Plus --><td>2DIMMスロット DDR4 UDIMM</td>
			<!--ML30 Gen10 --><td>4DIMMスロット DDR4 UDIMM</td>
			<!--ML30 Gen10 Plus --><td>4DIMMスロット DDR4 UDIMM</td>
			<!--ML110 Gen10--><td>6DIMMスロット DDR4 RDIMM</td>
			<!--ML350 Gen10--><td>24DIMMスロット DDR4 RDIMM</td>
		</tr>
		<tr class="specs">
			<th>チップセット</th>
			<!--MS Gen10 Plus --><td>インテルC242</td>
			<!--ML30 Gen10 --><td>インテル<sup>&reg;</sup> C246</td>
			<!--ML30 Gen10 Plus --><td>インテル<sup>&reg;</sup> C256</td>
			<!--ML110 Gen10--><td>インテル<sup>&reg;</sup> C621</td>
			<!--ML350 Gen10--><td>インテル<sup>&reg;</sup> C622</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconDrive">ドライブ</th>
			<!--MS Gen10 Plus --><td>4(3.5型ノンホットプラグSATA/SSD)</td>
			<!--ML30 Gen10 --><td>8(2.5型ホットプラグSAS/SATA/SSD)<br>4(3.5型ホットプラグSAS/SATA/SSD)<br>4(3.5型ノンホットプラグSATA)</td>
			<!--ML30 Gen10 Plus --><td>4(3.5型ノンホットプラグSATA)<br>4(3.5型ホットプラグSAS/SATA/SSD)<br>8(2.5型ホットプラグSAS/SATA/SSD)</td>
			<!--ML110 Gen10--><td>標準8、最大16 (2.5型 ホットプラグSAS/SATA/SSD)<br>標準4、最大8 (3.5型 ホットプラグSAS/SATA/SSD)<br>標準4、最大8 (3.5型 ノンホットプラグSATA)</td>
			<!--ML350 Gen10--><td>標準8、最大24 (2.5型 ホットプラグSAS/SATA/SSD)<br>標準4、最大12 (3.5型 ホットプラグSAS/SATA/SSD)</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconDiscController">ディスク<br>コントローラー</th>
			<!--MS Gen10 Plus --><td>Smartアレイ S100iまたはSmartアレイ E208i標準搭載</td>
			<!--ML30 Gen10 --><td>Smartアレイ S100iまたはSmartアレイ E208i-a標準搭載<br><span class="f11">※モデルによりアップグレード可</span></td>
			<!--ML30 Gen10 Plus --><td>インテル<sup>&reg;</sup> VROC SATA Software RAID(オンボード)<br>またはSmartアレイ E208i-p標準搭載<br><span class="f11">※モデルによりアップグレード可</span></td>
			<!--ML110 Gen10--><td>Smartアレイ S100iまたはSmartアレイ E208i-a標準搭載<br><span class="f11">※モデルによりアップグレード可</span></td>
			<!--ML350 Gen10--><td>Smartアレイ S100iまたはSmartアレイ E208i-a標準搭載<br><span class="f11">※モデルによりアップグレード可</span></td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconNetwork">ネットワーク</th>
			<!--MS Gen10 Plus --><td>Ethernet 1Gb 4ポート Intel i350オンボードネットワーク アダプター</td>
			<!--ML30 Gen10 --><td>Ethernet 1Gb 2ポート 332i ネットワークアダプター</td>
			<!--ML30 Gen10 Plus --><td>Ethernet 1Gb 2ポート ネットワークアダプター</td>
			<!--ML110 Gen10--><td>HPE Ethernet 1Gb 2ポート 332i ネットワークアダプター</td>
			<!--ML350 Gen10--><td>HPE Ethernet 1Gb 4ポート 369i  ネットワークアダプター</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconNetwork">拡張スロット</th>
			<!--MS Gen10 Plus --><td>1 (ロープロファイル/ハーフレングスPCI Express Gen3 x16×1)</td>
			<!--ML30 Gen10 --><td>4 (フルハイト/フルハイトPCI Express Gen3 x16×1、フルハイト/ハーフレングスPCI Express Gen3 x4×2、フルハイト/フルハイトPCI Express Gen3 x4×1)</td>
			<!--ML30 Gen10 Plus --><td>4(フルハイト/フルレングスPCI Express Gen4 x16(x16コネクター)×1、フルハイト/フルレングスPCI Express Gen3 x4(x16コネクター)×1、フルハイト/ハーフレングスPCI Express Gen3 x4(x8コネクター)×2)</td>
			<!--ML110 Gen10--><td>5(FH/ 3/4 L PCI Express Gen3 x16、FH/HL PCI Express Gen3 x8、FH/HL PCI Express Gen3 x16、FH/HL PCI Express Gen3 x4 x2)</td>
			<!--ML350 Gen10--><td>4(FH/FL PCI Express Gen3 x16 x2、FH/FL PCI Express Gen3 x8、FH/FL PCI Express Gen3 x4) <br><span class="f11">※オプションにより最大8</span></td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconPower">パワーサプライ</th>
			<!--MS Gen10 Plus --><td>冗長化非対応<br>ホットプラグ非対応</td>
			<!--ML30 Gen10 --><td>冗長化対応<br>ホットプラグ対応</td>
			<!--ML30 Gen10 Plus --><td>冗長化対応<br>ホットプラグ対応</td>
			<!--ML110 Gen10--><td>冗長化対応<br>ホットプラグ対応<br><span class="f11">※ノンホットモデルはリダンダント非対応</span></td>
			<!--ML350 Gen10--><td>冗長化対応<br>ホットプラグ対応</td>
		</tr>
		<tr class="specs">
			<th>冷却ファン</th>
			<!--MS Gen10 Plus --><td>冗長化非対応<br>ホットプラグ非対応</td>
			<!--ML30 Gen10 --><td>冗長化非対応<br>ホットプラグ非対応</td>
			<!--ML30 Gen10 Plus --><td>冗長化非対応<br>ホットプラグ非対応</td>
			<!--ML110 Gen10--><td>冗長化対応<br>ホットプラグ対応</td>
			<!--ML350 Gen10--><td>冗長化対応<br>ホットプラグ対応</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconRemote">リモート管理</th>
			<!--MS Gen10 Plus --><td>iLO Management Engine(iLO 5)<br><span class="f11">※オプション</span></td>
			<!--ML30 Gen10 --><td>iLO Management Engine(iLO 5)</td>
			<!--ML30 Gen10 Plus --><td>iLO Management Engine(iLO 5)</td>
			<!--ML110 Gen10--><td>iLO Management Engine(iLO 5)</td>
			<!--ML350 Gen10--><td>iLO Management Engine(iLO 5)</td>
		</tr>
		<tr class="specs">
			<th>サイズ(W×D×H)</th>
			<!--MS Gen10 Plus --><td>245×245×119mm</td>
			<!--ML30 Gen10 --><td>175×475×368 mm</td>
			<!--ML30 Gen10 Plus --><td>175×490×370mm</td>
			<!--ML110 Gen10--><td>195×480×440mm</td>
			<!--ML350 Gen10--><td>174×648×462mm</td>
		</tr>
		<tr class="specs">
			<th>フォーム<br class="spHide">ファクター</th>
			<!--MS Gen10 Plus --><td>Ultra Micro タワー型</td>
			<!--ML30 Gen10 --><td>4U タワー型</td>
			<!--ML30 Gen10 Plus --><td>4U タワー型</td>
			<!--ML110 Gen10--><td>4.5U タワー型<br><span class="f11">※ラック搭載キットによりラックマウント可能</span></td>
			<!--ML350 Gen10--><td>4U タワー型<br><span class="f11">※ラック搭載キットによりラックマウント可能。ラック搭載時は5U。</span></td>
		</tr>
		<tr class="specs">
			<th>音響ノイズ</th>
			<!--MS Gen10 Plus --><td>21dBA</td>
			<!--ML30 Gen10 --><td>23～28dBA</td>
			<!--ML30 Gen10 Plus --><td>26～29dBA</td>
			<!--ML110 Gen10--><td>24～25dBA</td>
			<!--ML350 Gen10--><td>28～32dBA</td>
		</tr>
		<tr class="specs">
			<th>OS</th>
			<!--MS Gen10 Plus --><td>カスタマイズメニューからはお選びいただけません<br>・Windows OS購入につきましては、MicroServerと共に販売店へお問い合わせください<br>・RedHat Enterprise Linuxは<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=9EcQpABQII4AAAEPN.uIlXpV&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3" class="tertiary-link">こちら</a>からお選びください</td>
			<!--ML30 Gen10 --><td><div class="mb5">Windows Server</div><div>RedHat Enterprise Linux</div></td>
			<!--ML30 Gen10 Plus --><td><div class="mb5">Windows Server</div><div>RedHat Enterprise Linux</div></td>
			<!--ML110 Gen10--><td><div class="mb5">Windows Server</div><div>RedHat Enterprise Linux</div></td>
			<!--ML350 Gen10--><td><div class="mb5">Windows Server</div><div>RedHat Enterprise Linux</div></td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconSupport">標準保証</th>
			<!--MS Gen10 Plus --><td>1年間パーツ保証、1年間翌営業日オンサイトサービス</td>
			<!--ML30 Gen10 --><td>3年間パーツ保証、3年間翌営業日オンサイトサービス</td>
			<!--ML30 Gen10 Plus --><td>3年間パーツ保証、3年間翌営業日オンサイトサービス</td>
			<!--ML110 Gen10--><td>3年間パーツ保証、3年間翌営業日オンサイトサービス</td>
			<!--ML350 Gen10--><td>3年間パーツ保証、3年間翌営業日オンサイトサービス</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconMaintenance">サポート<br class="spHide">サービス</th>
			<!--MS Gen10 Plus --><td>カスタマイズメニューからはお選びいただけません<br><a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBService_e" class="tertiary-link">こちら</a>からお選びください</td>
			<!--ML30 Gen10 --><td>
				<div class="mb10">
					<span class="bold">HPE Tech Care Essential</span><br>
					3,4,5年－HD返却不要
				</div>
				<div>
					<span class="bold">HPE Tech Care Basic 4H</span><br>
					3,4,5年－HD返却不要
				</div>
			</td>
			<!--ML30 Gen10 Plus --><td>
				<div class="mb10">
					<span class="bold">HPE Tech Care Essential</span><br>
					3,4,5年－HD返却不要
				</div>
				<div>
					<span class="bold">HPE Tech Care Basic 4H</span><br>
					3,4,5年－HD返却不要
				</div>
			</td>
			<!--ML110 Gen10--><td>
				<div class="mb10">
					<span class="bold">HPE Tech Care Essential</span><br>
					3,4,5年－HD返却不要
				</div>
				<div>
					<span class="bold">HPE Tech Care Basic 4H</span><br>
					3,4,5年－HD返却不要
				</div>
			</td>
			<!--ML350 Gen10--><td>
				<div class="mb10">
					<span class="bold">HPE Tech Care Essential</span><br>
					3,4,5,6,7年－HD返却不要
				</div>
				<div>
					<span class="bold">HPE Tech Care Basic 4H</span><br>
					3,4,5,6,7年－HD返却不要
				</div>
			</td>
		</tr>
		<tr>
			<th>&nbsp;</th>
			<th><a href="/directplus_ent/server/microservergen10plus/">HPE ProLiant<br>MicroServer Gen10 Plus</a></th>
			<th><a href="/directplus_ent/server/ml30gen10/">HPE ProLiant<br>ML30 Gen10</a></th>
			<th><a href="/directplus_ent/server/ml30gen10plus/">HPE ProLiant<br>ML30 Gen10 Plus</a></th>
			<th><a href="/directplus_ent/optoku/ml110gen10/">HPE ProLiant<br>ML110 Gen10</a></th>
			<th><a href="/directplus_ent/server/ml350gen10/">HPE ProLiant<br>ML350 Gen10</a></th>
		</tr>
	</table>
	<p class="alignRgt mb10">
		<a href="javascript:void(0);" class="cta-link specSwitch ssRack"><em class="icon-arrow-circle-right"></em>ラックマウント型サーバーのラインアップを見る</a>
	</p>
</div><!-- ./specTableAreaPc -->
