<div class="specTableArea specTableAreaSp">
	<div class="specTableAreaBg pt20">
		<div class="specTableAreaBgInr">
			<p class="mb20">各製品の仕様については価格をクリックして製品ページにてご確認ください。</p>
			<p class="mb20 f12 indent-1">※画像は構成によって実際の製品と異なる場合があります</p>
			<!--div class="specTableAreaDivider" style="margin: 10px 0 15px;"></div-->
			<div class="hpe-accordion">
				<div class="accordion-panel">
					<div class="accordion-panel-header">
						<a href="javascript:void(0);" class="accordion-toggle icon-toggle-circle-open open">タワー型サーバー</a>
					</div>
					<div class="accordion-panel-body" style="display: block;">
						<div class="specTableItemsArea">
							<div class="specTableItems">

								<!--MS Gen10 Plus -->
								<div class="specTableItem">
									<div class="specTableItemImg l2">
										<a href="/directplus_ent/server/microservergen10plus/">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_microserver_gen10_plus_optoku.gif" class="productImg">
											HPE ProLiant<br>MicroServer Gen10 Plus
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)
										<a href="/directplus_ent/server/microservergen10plus/" class="btn btn-secondary" role="button"><span>110,000円～</span></a>
									</div>
									<div class="specTableItemDetail">
										従来機Gen10と比べてコンパクト性、性能、管理性を大幅に強化
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">インテル</div>
										<div class="specTableItemType disabled">CTO非対応</div>
									</div>
								</div>

								<!--ML30 Gen10 -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="/directplus_ent/server/ml30gen10/">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml30_gen10_optoku.gif" class="productImg">
											HPE ProLiant<br>ML30 Gen10
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)
										<a href="/directplus_ent/server/ml30gen10/" class="btn btn-secondary" role="button"><span>110,000円～</span></a>
									</div>
									<div class="specTableItemDetail">
										エンタープライズクラスの機能を備え、オフィスに最適
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">インテル</div>
										<div class="specTableItemType">CTO対応</div>
									</div>
								</div>

								<!--ML110 Gen10 -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="/directplus_ent/optoku/ml110gen10/">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml110_gen10_optoku.gif" class="productImg">
											HPE ProLiant<br>ML110 Gen10
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)
										<a href="/directplus_ent/optoku/ml110gen10/" class="btn btn-secondary" role="button"><span>192,000円～</span></a>
									</div>
									<div class="specTableItemDetail">
										中小規模システムに最適な高性能、優れた拡張性
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">インテル</div>
										<div class="specTableItemType">CTO対応</div>
									</div>
								</div>

								<!--ML350 Gen10 -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="/directplus_ent/server/ml350gen10/">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml350_gen10.gif" class="productImg">
											HPE ProLiant<br>ML350 Gen10
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)
										<a href="/directplus_ent/server/ml350gen10/" class="btn btn-secondary" role="button"><span>403,000円～</span></a>
									</div>
									<div class="specTableItemDetail">
										中小規模システムに最適な高性能、優れた拡張性
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">インテル</div>
										<div class="specTableItemType">CTO対応</div>
									</div>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div><!-- ./specTableAreaSp -->