<div class="specTableArea specTableAreaSp" style="margin-top: -15px;">
	<div class="specTableAreaBg pb20">
		<!--div class="specTableAreaDivider"></div-->
		<div class="specTableAreaBgInr">
			<div class="hpe-accordion">
				<div class="accordion-panel">
					<div class="accordion-panel-header">
						<a href="javascript:void(0);" class="accordion-toggle icon-toggle-circle-open open">NAS製品（HPE StoreEasy）</a>
					</div>
					<div class="accordion-panel-body" style="display: block;">
						<div class="specTableItemsArea">
							<div class="specTableItems">

								<!--HPE StoreEasy -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="/directplus_ent/storage/?hash=StoreEasy">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_storeeasy1560_campaign.gif" alt="" class="productImg">
											<!--<img src="images/icon_servers-storeeasy.jpg" alt="" class="productImg">-->
											HPE StoreEasy
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)
										<a href="/directplus_ent/storage/?hash=StoreEasy" class="btn btn-secondary" role="button"><span>441,000円～</span></a>
									</div>
									<div class="specTableItemDetail">
										ファイルサーバーに特化したNAS (Network Attached Storage)。<br>
										容易かつトータルコストを抑えた導入が可能。無制限のWindows CALがつき、ユーザー数が増えても安心
									</div>
									<div class="specTableItemTypes">
										<div class="specTableItemType">インテル</div>
										<div class="specTableItemType disabled">CTO非対応</div>
									</div>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--div class="specTableAreaDivider" style="margin: 15px 15px 0;"></div-->
	</div>
</div><!-- ./specTableAreaSp -->