<div class="specTableArea specTableAreaPc mb30WithBorder">
	<div class="column20-80 cfx">
		<div class="clm1 mb0"> <img src="images/icon_servers-storeeasy.jpg" alt="" class="nasProductImg"> </div>
		<div class="clm2 paddBlock15">
			<p class="bold f22 mb5 lhMin">NAS製品 (HPE StoreEasy) </p>
			<p>ファイルサーバーに特化したNAS (Network Attached Storage) を利用することで、容易かつトータルコストを抑えた導入が可能です。無制限のWindows CALがつき、ユーザー数が増えても追加コストがかからず安心です。</p>
			<p class="mt10">
				<a href="/directplus_ent/storage/?hash=StoreEasy" class="cta-link"><em class="icon-arrow-circle-right"></em>HPE StoreEasyの詳細はこちら</a>
			</p>
		</div>
	</div>
</div>