<div class="js-section has-js-toc mb40" id="Compare">
	
	<h3 class="f24 bold mb5">
		2Uサーバーであらゆるワークロードに対応する性能を追及したい場合は・・・
	</h3>
	<div class="mb10">
		<p class="mb10">
			最大56コア/112スレッドのインテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> プロセッサーを搭載するHPE ProLiant DL380 Gen10をおすすめいたします。データベース、ERP、データ分析など高負荷ワークロードに最適で、最大7年の長期保守にも対応。<br>
			またAMD EPYC<sup>&trade;</sup> プロセッサーを2基搭載可能な、<a href="/directplus_ent/server/dl385gen10/" class="tertiary-link">HPE ProLiant DL385</a>や<a href="/directplus_ent/server/dl385gen10plus/" class="tertiary-link">HPE ProLiant DL385 Gen10 Plus</a>もございます。<br>
			<!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" -->へお電話いただければ、ご希望の用途や環境に合わせた構成で比較のお見積をさせていただきます。
		</p>
		<div class="alignRgt lhMid"> <a href="#ContactUs" class="linkWithArrow"><!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" --><span class="arrow">→</span></a> </div>
	</div>
	<div class="optokuTable">
		<table>
			<tr>
				<th width="20%"></th>
				<th width="40%">DL180 Gen10</th>
				<th width="40%">DL380 Gen10</th>
			</tr>
			<tr class="whiteCell">
				<th>モデル</th>
				<td class="alignCtr">
					<!-- DL180 Gen10 -->
					<a href="#CustomizeOrder">
						<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl180_gen10.gif" alt="" class="m0auto">
					</a>
					<a href="#CustomizeOrder" role="button" class="btn btn-secondary">モデルを選択する</a>
				</td>
				<td class="alignCtr">
					<!-- DL380 Gen10 -->
					<a href="/directplus_ent/server/dl380gen10/">
						<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl380_gen10.gif" alt="" class="m0auto">
					</a>
					<a href="#CustomizeOrder" role="button" class="btn btn-secondary">モデルを選択する</a>
				</td>
			</tr>
			<tr class="gryCell">
				<th>最小構成価格(税抜)</th>
				<td class="alignCtr">
					通常モデル　376,000円～
				</td>
				<td class="alignCtr">
					通常モデル　607,000円～
				</td>
			</tr>
				<tr class="whiteCell">
				<th>フルカスタマイズCTO対応<br><a class="tertiary-link alpha" href="/directplus_ent/promotion/merit/"><span class="white">メリットはこちら</span></a></th>
				<td class="alignCtr">○</td>
				<td class="alignCtr">○</td>
				</tr>
			<tr class="gryCell">
				<th>おすすめ用途</th>
				<td class="alignCtr">
					・中規模業務アプリケーションサーバー<br>
					・Non SQL DBサーバー<br>
					・Hadoop<br>
					・ストリーミングサーバー
				</td>
				<td class="alignCtr">
					・大中規模ファイル/メールサーバー<br>
					・仮想化&amp;VDI<br>
					・ディスク容量を重視する用途<br>
					・中規模DB<br>
					・画像配信用ストリーミング<br>
					・Hadoop<br>
					・人工知能/HPCなどのニーズ
				</td>
			</tr>
			<tr class="whiteCell">
				<th>プロセッサー</th>
				<td class="alignCtr">
					最大2基/52コア<br>
					インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー
				</td>
				<td class="alignCtr">
					最大2基/56コア<br>
					インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー
				</td>
			</tr>
			<tr class="gryCell">
				<th>メモリ</th>
				<td class="alignCtr">16DIMMスロット DDR4 RDIMM</td>
				<td class="alignCtr">24DIMMスロット DDR4 RDIMM</td>
			</tr>
			<tr class="whiteCell">
				<th>ドライブ</th>
				<td class="alignCtr">
					8(3.5型ホットプラグSAS/SATA/SSD)<br>
					8(2.5型ホットプラグSAS/SATA/SSD)<br>
					12(3.5型ホットプラグ SAS/SATA/SSD)
				</td>
				<td class="alignCtr">
					標準8、最大16(2.5型ホットプラグSAS/SATA/SSD)<br>
					標準12、最大16(3.5型ホットプラグSAS/SATA/SSD)
				</td>
			</tr>
			<tr class="gryCell">
				<th>拡張スロット</th>
				<td class="alignCtr">
					4(メディアモジュールアダプター専用×1、フルハイト/フルレングス PCI Express Gen3 x8×1、フルハイト/ハーフレングス PCI Express Gen3 x8×2)
				</td>
				<td class="alignCtr">
					4(FlexibleLOMアダプター用スロット×1、FH/HL PCI Express Gen3 x16×2、FH/HL PCI Express Gen3 x8)<br>
					<span class="f12">※オプションにより最大6</span>
				</td>
			</tr>
		</table>
	</div>
</div><!-- /#Compare -->