<div class="specTable2Area fixedTable">
	<div class="specTable2 title2lines relative">
		<!--<div class="specTableTitle">
			<table width="1000">
				<tr>
					<th width="100"></th>
					<th width="360" class="f14" colspan="2">信頼性とコストパフォーマンス</th>
					<th width="540" class="f14" colspan="3">性能・信頼性重視</th>
				</tr>
				<tr>
					<th width="100"></th>
					<th width="180" class="f20">8LFF SATA</th>
					<th width="180" class="f20">8LFF SAS</th>
					<th width="180" class="f20">8SFF SATA</th>
					<th width="180" class="f20">8SFF SAS</th>
					<th width="180" class="f20">12LFF</th>
				</tr>
			</table>
		</div>-->
		<table width="1000">
			<tr>
				<th width="100"></th>
				<th width="360" class="f14" colspan="2">信頼性とコストパフォーマンス</th>
				<th width="540" class="f14" colspan="3">性能・信頼性重視</th>
			</tr>
			<tr>
				<th width="100"></th>
				<th width="180" class="f20">8LFF SATA</th>
				<th width="180" class="f20">8LFF SAS</th>
				<th width="180" class="f20">8SFF SATA</th>
				<th width="180" class="f20">8SFF SAS</th>
				<th width="180" class="f20">12LFF</th>
			</tr>
			<tr>
				<th></th>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl180_gen10.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl180_gen10.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl180_gen10.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl180_gen10.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl180_gen10.gif" alt="" class="m0auto">
				</td>
			</tr>
			<tr>
				<th>ドライブ</th>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 3.5型</span> 最大8<br>
					SATA HDD、SATA SSD選択可
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 3.5型</span> 最大8<br>
					SAS HDD、SAS SSD選択可
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 2.5型</span> 最大8<br>
					SATA HDD、SATA SSD選択可
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 2.5型</span> 最大8<br>
					SAS HDD、SAS SSD選択可
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 3.5型</span> 最大12<br>
					SATA HDD、SATA SSD、SAS HDD、SAS SSD選択可
				</td>
			</tr>
			<tr>
				<th>プロセッサー</th>
				<td colspan="5"><span class="cutomizable2">カスタマイズ可能</span>最大2基　インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー</td>
			</tr>
			<tr>
				<th>メモリ</th>
				<td colspan="5"><span class="cutomizable2">カスタマイズ可能</span>16DIMMスロット DDR4 RDIMM</td>
			</tr>
			<tr>
				<th>パワーサプライ</th>
				<td colspan="5"><span class="cutomizable2">カスタマイズ可能</span>標準1　オプションで冗長化対応、ホットプラグ対応</td>
			</tr>
			<tr>
				<th>最小構成価格<br>（税抜）</th>
				<td class="pt10 pb10">
					<div>
						<span class="bold f14">通常モデル</span>
						<span class="f14">376,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4381&ProductSKU=BASE:15953" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14"><span class="disp_ib">カスタマイズして</span><span class="disp_ib">見積・購入</span></span></a>
					</div>
				</td>
				<td class="pt10 pb10">
					<div>
						<span class="bold f14">通常モデル</span>
						<span class="f14">423,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4381&ProductSKU=BASE:15954" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14"><span class="disp_ib">カスタマイズして</span><span class="disp_ib">見積・購入</span></span></a>
					</div>
				</td>
				<td class="pt10 pb10">
					<div>
						<span class="bold f14">通常モデル</span>
						<span class="f14">397,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4381&ProductSKU=BASE:15951" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14"><span class="disp_ib">カスタマイズして</span><span class="disp_ib">見積・購入</span></span></a>
					</div>
				</td>
				<td class="pt10 pb10">
					<div>
						<span class="bold f14">通常モデル</span>
						<span class="f14">444,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4381&ProductSKU=BASE:15952" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14"><span class="disp_ib">カスタマイズして</span><span class="disp_ib">見積・購入</span></span></a>
					</div>
				</td>
				<td class="pt10 pb10">
					<div>
						<span class="bold f14">通常モデル</span>
						<span class="f14">575,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4381&ProductSKU=BASE:15980" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14"><span class="disp_ib">カスタマイズして</span><span class="disp_ib">見積・購入</span></span></a>
					</div>
				</td>
			</tr>
			<tr>
				<th></th>
				<td colspan="5" class="pt10 pb15">
					<a href="pdfs/spec_cto.pdf" target="_blank" class="linkWithArrow">
						仕様一覧はこちら（PDF）
						<span class="arrow">→</span>
					</a>
				</td>
			</tr>
		</table>
	</div><!-- /.specTable2 -->
	
</div><!-- /.specTable2Area -->