<style>
.linkOnCampaign {
	display: none;
}
.page.campaign .linkOnCampaign {
	display: block;
}
.page.campaign .linkToCampaign {
	display: none;
}
</style>
<h3 class="f24 bold mb20" id="IT_asap">
	HPEサーバー&amp;ストレージ “ITの準備はお早めに”キャンペーン
</h3>
<div class="column35-65 cfx">
	<div class="clm1">
		<a href="/directplus_ent/server/?hash=Campaign">
			<img src="/directplus_ent/images/banners/bnr_800x350_it_asap_campaign.jpg" alt="" class="w100per">
		</a>
		<div class="alignCtr">
			<!--<a href="/directplus_ent/server/" role="button" class="btn btn-secondary mt30">キャンペーン価格でのお見積はこちら</a>-->
			<div class="mt10 linkOnCampaign">
				<a href="https://www.hpe.com/jp/ja/servers/servers-campaign.html" target="_blank"><span class="cta-link"><em class="icon-arrow-circle-right"></em>キャンペーン詳細はこちら</span></a>
			</div>
			<div class="mt10 linkToCampaign">
				<a href="/directplus_ent/campaign/"><span class="cta-link"><em class="icon-arrow-circle-right"></em>キャンペーン詳細はこちら</span></a>
			</div>
		</div>
	</div>
	<div class="clm2">
		<h4 class="f18 bold mb5">キャンペーンモデルのサーバーとストレージが30%OFF<sup>※</sup></h4>
		<p class="mb20">
			キャンペーンモデルのHPE PoLiant Gen10サーバー本体および内蔵オプション、UPS、HPE StoreEasy、MSAストレージを希望小売価格の30%引きの特別価格でご提供します。
		</p>
		<div class="campaignColumn mb10 cfx">
			<div class="clm1">
				対象製品
			</div>
			<div class="clm2">
				<a href="/directplus_ent/optoku/ml110gen10/" class="tertiary-link">ML110 Gen10</a>、<a href="/directplus_ent/server/dl325gen10plus/" class="tertiary-link">DL325 Gen10 Plus</a>、<a href="/directplus_ent/server/dl360gen10/" class="tertiary-link">DL360 Gen10</a>、<a href="/directplus_ent/storage/?hash=StoreEasy" class="tertiary-link">StoreEasy 1460</a>、<a href="/directplus_ent/storage/?hash=StoreEasy" class="tertiary-link">StoreEasy 1560</a>、<a href="/directplus_ent/storage/?hash=MSA" class="tertiary-link">MSAストレージ</a>
			</div>
		</div>
		<div class="campaignColumn mb10 cfx">
			<div class="clm1">
				キャンペーン期間
			</div>
			<div class="clm2">
				2022年3月31日（木）お申し込み分まで
			</div>
		</div>
		<p class="f16 lhMid bold indent-1">
			※本サイトでは「キャンペーンモデル」にて、キャンペーン価格で即時お見積・ご注文いただけます。
		</p>
	</div>
</div>
