<!--<h4 class="f18 bold">
	キャンペーン活用してこんなにお得に
</h4>
<p class="f14 mb30">
	サーバー本体だけでなくメモリやディスク、UPSなどのオプションもキャンペーンだけの特別価格でご提供しますので、オプションを追加いただくほど割引額が大きくなります。
</p>

<p class="f18 bold">
	【サーバー構成価格の一例】
</p>
<div class="column50-50WithBdr cfx mb20">
	<div class="clm1 alignCtr paddBlock10" style="box-sizing: border-box">
		<p class="f18 bold alignCtr mb20">
			HPE ProLiant ML110 Gen10
		</p>
		<div class="columnPriceExample">
			<div class="clm1">
				<div class="columnPriceImgWrapper">
					<img src="/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp3_ml110_gen10.jpg" alt="" class="columnPriceImg w100per">
				</div>
				<div class="columnPriceBtn alignCtr mb5">
					<a href="/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CampaignCode=GOTO17" role="button" class="btn btn-secondary">
						詳しい構成はこちら
					</a>
					<div class="f14 mb10">
						カスタマイズも可能
					</div>
					<div class="f14">
						<a href="/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/ViewBasketForBusiness-DirectCartAdd?CampaignCode=GOTO17"><span class="cta-link"><em class="icon-arrow-circle-right"></em>カートに入れる</span></a>
					</div>
				</div>
			</div>
			<div class="clm2">
				<img src="/directplus_ent/campaign/images/example_ml110_gen10.png" alt="" class="w100per">
			</div>
		</div>
	</div>
	<div class="clm2 alignCtr paddBlock10" style="box-sizing: border-box">
		<p class="f18 bold alignCtr mb20">
			HPE ProLiant DL20 Gen10
		</p>
		<div class="columnPriceExample">
			<div class="clm1">
				<div class="columnPriceImgWrapper">
					<img src="/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp3_dl20_gen10.jpg" alt="" class="columnPriceImg w100per">
				</div>
				<div class="columnPriceBtn alignCtr mb5">
					<a href="/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CampaignCode=GOTO18" role="button" class="btn btn-secondary">
						詳しい構成はこちら
					</a>
					<div class="f14 mb10">
						カスタマイズも可能
					</div>
					<div class="f14">
						<a href="/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/ViewBasketForBusiness-DirectCartAdd?CampaignCode=GOTO18"><span class="cta-link"><em class="icon-arrow-circle-right"></em>カートに入れる</span></a>
					</div>
				</div>
			</div>
			<div class="clm2">
				<img src="/directplus_ent/campaign/images/example_dl20_gen10.png" alt="" class="w100per">
			</div>
		</div>
	</div>
</div>
<div class="f12 alignRgt sphoneAlignLft indent-1">
	※価格はすべて税抜金額です
</div>
<div class="f12 alignRgt sphoneAlignLft indent-1">
	※画像は構成によって実際の製品と異なる場合があります
</div>-->
