<!--<h3 class="f24 bold mb20" id="dx">
	HPE サーバー&amp;ストレージ DX応援キャンペーン
</h3>
<div class="column35-65 cfx mb20">
	<div class="clm1">
		<a href="/directplus_ent/server/?hash=Campaign">
			<img src="/directplus_ent/images/banners/bnr_800x350_dx_campaign.jpg" alt="" class="w100per">
		</a>
		<div class="alignCtr">
			<a href="/directplus_ent/server/" role="button" class="btn btn-secondary mt30">キャンペーン価格でのお見積はこちら</a>
			<div class="mt10">
				<a href="/directplus_ent/campaign/"><span class="cta-link"><em class="icon-arrow-circle-right"></em>キャンペーン詳細はこちら</span></a>
			</div>
		</div>
	</div>
	<div class="clm2">
		<h4 class="f18 bold mb5">キャンペーンモデルのサーバーとストレージが30%OFF<sup>※</sup>!--　保守も15%OFF--</h4>
		<p class="mb20">
			キャンペーンモデルのHPE PoLiant Gen10サーバー本体および内蔵オプション、UPS、HPE StoreEasy、MSAストレージを希望小売価格の30%引き。メモリ、HDD/SSDを50%引きの特別価格でご提供します。!--<br>
			また、障害予防のサポートを提供するHPEプロアクティブケアを希望小売価格の15%引きでご提供します。--
		</p>
		<div class="campaignColumn mb10 cfx">
			<div class="clm1">
				対象製品
			</div>
			<div class="clm2">
				<a href="/directplus_ent/server/microservergen10plus/" class="tertiary-link">MicroServer Gen10 Plus</a>、<a href="/directplus_ent/server/ml30gen10/" class="tertiary-link">ML30 Gen10</a>、<a href="/directplus_ent/optoku/ml110gen10/" class="tertiary-link">ML110 Gen10</a>、<a href="/directplus_ent/server/dl20gen10/" class="tertiary-link">DL20 Gen10</a>、<a href="/directplus_ent/server/dl160gen10/" class="tertiary-link">DL160 Gen10</a>、<a href="/directplus_ent/server/dl325gen10/" class="tertiary-link">DL325 Gen10</a>、<a href="/directplus_ent/storage/?hash=StoreEasy1460" class="tertiary-link">StoreEasy 1460</a>、<a href="/directplus_ent/storage/?hash=StoreEasy1560" class="tertiary-link">StoreEasy 1560</a>、<a href="/directplus_ent/storage/?hash=StoreEasy1660" class="tertiary-link">StoreEasy 1660</a>、<a href="/directplus_ent/storage/?hash=MSA" class="tertiary-link">MSAストレージ</a>
			</div>
		</div>
		<div class="campaignColumn mb10 cfx">
			<div class="clm1">
				キャンペーン期間
			</div>
			<div class="clm2">
				2021年10月29日（金）お申し込み分まで
			</div>
		</div>
		<p class="f12 indent-1">
		※本サイトでは「キャンペーンモデル」にて、キャンペーン価格で即時お見積・ご注文いただけます。
		</p>
	</div>
</div>-->
