<h3 class="f24 bold mb20" id="amazongift">
	お見積でもらえる、ギフト券がもらえる
</h3>
<div class="column35-65 cfx mb40">
	<div class="clm1">
		<a href="/directplus_ent/promotion/amazongift/">
			<img src="/directplus_ent/images/banners/bnr_img_800x350_amazongift.jpg" alt="" class="w100per">
		</a>
		<div class="alignCtr">
			<a href="/directplus_ent/promotion/amazongift/" role="button" class="btn btn-secondary mt30">キャンペーン詳細はこちら</a>
		</div>
	</div>
	<div class="clm2">
		<h4 class="f18 bold mb5">HPE DirectPlusでお見積、抽選で100名様に1,000円分のAmazonギフト券プレゼント</h4>
		<div class="campaignColumn mb10 cfx">
			<div class="clm1">
				キャンペーン期間
			</div>
			<div class="clm2">
				2021年10月29日（金）17：00お申し込み分まで
			</div>
		</div>
	</div>
</div>
