<div class="description mb50">
	<h3 class="f24 bold dashed-text">サブスクとは？</h3>
	<p>
		サブスクとはお客様が必要とする設備をお客様に代って日本HPファイナンシャルサービスが購入し、比較的長期にわたって一定のサブスク料でお客様に賃貸するお取引です。<br>
		契約期間中のサブスク料には、製品の取得価格、期間中の支払金利、固定資産税や動産保険料などが含まれており、購入とは異なったメリットをご提供致します。
	</p>
	<div>
		<img src="./images/subscription_pc_img.svg" class="spNonDisplay">
		<img src="./images/subscription_sp_img.svg" class="pcNonDisplay" style="margin:0 auto;">
	</div>
</div>
