<div class="example">
	<h3 class="f24 bold dashed-text">サブスク価格例</h3>
	<div class="example-group">
		<div class="column33-33-33Flex fixUpperTablet alignCtr">
			<div class="clm1 flexGutter30">
				<div class="example-name mb15">
					HPE ProLiant MicroServer Gen10 Plusの場合
				</div>
				<div class="mb25">
					<img src="/directplus_ent/subscription/images/microservergen10plus-1.jpg" alt="" width="550" height="500" class="example-image">
				</div>
				<div class="example-label">
					サブスクご利用で
				</div>
				<div class="example-price">
					<span class="disp_ib">月額（5年）</span><span class="disp_ib"><span class="example-price-value">1,940</span>円（税抜）～</span>
					<div class="f14">購入時価格　¥110,000（税抜）～</div>
					<a href="/directplus_ent/server/microservergen10plus/" role="button" class="btn btn-secondary">この製品をお見積する</a>
				</div>
			</div>
			<div class="clm2 flexGutter30">
				<div class="example-name mb15">
					HPE ProLiant ML110 Gen10の場合<br class="spHide"><br class="spHide">
				</div>
				<div class="mb25">
					<img src="/directplus_ent/subscription/images/ml110gen10.jpg" alt="" width="550" height="500" class="example-image">
				</div>
				<div class="example-label">
					サブスクご利用で
				</div>
				<div class="example-price">
					<span class="disp_ib">月額（5年）</span><span class="disp_ib"><span class="example-price-value">3,390</span>円（税抜）～</span>
					<div class="f14">購入時価格　¥192,000（税抜）～</div>
					<a href="/directplus_ent/optoku/ml110gen10/" role="button" class="btn btn-secondary">この製品をお見積する</a>
				</div>
			</div>
			<div class="clm3">
				<div class="example-name mb15">
					HPE ProLiant DL360 Gen10の場合<br class="spHide"><br class="spHide">
				</div>
				<div class="mb25">
					<img src="/directplus_ent/subscription/images/dl360gen10.jpg" alt="" width="550" height="500" class="example-image">
				</div>
				<div class="example-label">
					サブスクご利用で
				</div>
				<div class="example-price">
					<span class="disp_ib">月額（5年）</span><span class="disp_ib"><span class="example-price-value">8,720</span>円（税抜）～</span>
					<div class="f14">購入時価格　¥494,000（税抜）～</div>
					<a href="/directplus_ent/server/dl360gen10/" role="button" class="btn btn-secondary">この製品をお見積する</a>
				</div>
			</div>
		</div>
	</div>
	<div class="alignRgt mb20">
		<a href="/directplus_ent/server/" class="linkWithArrow">このほかのサーバー製品も見てみる<span class="arrow">→</span></a>
	</div>
	<div class="f12 indent-1">
		※残価設定型の場合の月額です。
	</div>
	<div class="f12 indent-1">
		※製品が特別価格キャンペーンを実施中の場合は、さらにお得な月額料でご利用いただけます。
	</div>
	<div class="f12 indent-1">
		※サブスクご契約時の返済プログラムによって、月額料が変更することがございます。
	</div>
</div>
