<div class="flow">
						<h3 class="f24 bold dashed-text">サブスク契約の流れ</h3>
						<div>
							<img src="./images/subscription_flow_img1.svg">
						</div>
						<!--<div class="flow-steps mb30">
							<div class="flow-steps-group column50-50Flex fixUpperTablet">
								<div class="clm1 flexGutter40">
									<div class="column50-50Flex fixUpperTablet">
										<div class="flow-step clm1 flexGutter40">
											<div class="flow-step-title">1.製品お見積</div>
											<div class="flow-step-labels gutter5">
												<div class="flow-step-label customer">お客様</div>
												<div class="flow-step-label dplus">HPE DirectPlus</div>
											</div>
											<div class="flow-step-text">
												お客様とHPE DirectPlusコールセンターで製品の仕様・価格など打合せのうえ、販売見積書作成。<br>
												サブスクを希望される旨、HPE DirectPlusコールセンターにお知らせください。
											</div>
										</div>
										<div class="flow-step clm2">
											<div class="flow-step-title">2.ご説明・お申込み</div>
											<div class="flow-step-labels gutter5">
												<div class="flow-step-label customer">お客様</div>
												<div class="flow-step-label financial">ファイナンシャルサービス</div>
											</div>
											<div class="flow-step-text">
												サブスク期間、プログラムのご希望をヒアリングさせて頂きます。<br>
												お申込みの際は、お客様情報をご提出頂きます。
											</div>
										</div>
									</div>
								</div>
								<div class="clm2">
									<div class="column50-50Flex fixUpperTablet">
										<div class="flow-step clm1 flexGutter40">
											<div class="flow-step-title">3.審査</div>
											<div class="flow-step-labels gutter5">
												<div class="flow-step-label customer">お客様</div>
												<div class="flow-step-label financial">ファイナンシャルサービス</div>
											</div>
											<div class="flow-step-text">
												審査結果をお客様へご連絡させて頂きます。
											</div>
										</div>
										<div class="flow-step clm2">
											<div class="flow-step-title">4.ご契約締結</div>
											<div class="flow-step-labels gutter5">
												<div class="flow-step-label customer">お客様</div>
												<div class="flow-step-label financial">ファイナンシャルサービス</div>
											</div>
											<div class="flow-step-text">
												日本HPファイナンシャルサービスとお客様の間で契約を締結致します。
											</div>
										</div>
									</div>
								</div>
							</div>
							
							<div class="flow-steps-group column50-50Flex fixUpperTablet">
								<div class="clm1 flexGutter40">
									<div class="column50-50Flex fixUpperTablet">
										<div class="flow-step clm1 flexGutter40">
											<div class="flow-step-title">5.製品発注</div>
											<div class="flow-step-labels gutter5">
												<div class="flow-step-label dplus">HPE DirectPlus</div>
												<div class="flow-step-label financial">ファイナンシャルサービス</div>
											</div>
											<div class="flow-step-text">
												お客様から頂戴した販売見積書の内容で、日本HPファイナンシャルサービスよりHPE DirectPlusへ発注させて頂きます。
											</div>
										</div>
										<div class="flow-step clm2">
											<div class="flow-step-title">6.製品納品</div>
											<div class="flow-step-labels gutter5">
												<div class="flow-step-label customer">お客様</div>
												<div class="flow-step-label dplus">HPE DirectPlus</div>
											</div>
											<div class="flow-step-text">
												HPE DirectPlusからお客様ご指定場所に製品が納品されます。
											</div>
										</div>
									</div>
								</div>
								<div class="clm2">
									<div class="column50-50Flex fixUpperTablet">
										<div class="flow-step clm1 flexGutter40">
											<div class="flow-step-title">7.サブスク開始</div>
											<div class="flow-step-labels gutter5">
												<div class="flow-step-label customer">お客様</div>
												<div class="flow-step-label financial">ファイナンシャルサービス</div>
											</div>
											<div class="flow-step-text">
												納品された製品をご検収頂き、日本HPファイナンシャルサービスへ物件受領書を交付して頂きます。
											</div>
										</div>
										<div class="flow-step clm2">
											<div class="flow-step-title">8.サブスク終了</div>
											<div class="flow-step-labels gutter5">
												<div class="flow-step-label customer">お客様</div>
												<div class="flow-step-label financial">ファイナンシャルサービス</div>
											</div>
											<div class="flow-step-text">
												日本HPファイナンシャルサービスより終了のご連絡をさせて頂きます。延長または、終了の手続きをお取り願います。
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>-->
					</div>
