<div class="merit">
						<h3 class="f24 bold dashed-text">サブスクのメリット</h3>
						<div class="mb20">
							<img src="./images/subscription_merit_img1_1.svg">
						</div>
						<div class="column33-66">
							<div class="clm1">
								<p class="f12 ml10">Powered by 日本HPファイナンシャルサービス株式会社</p>
								<img src="./images/subscription_merit_img1_2.svg">
							</div>
							<div class="clm2">
								<H3 class="f24 bold mb20">「所有する」だけじゃない、「利用する」という選択肢</H3>
								<div class="f16 lhMid">
									<p class="mb10">クラウドにするか、それともオンプレミスにするか、それとも ──</p>
									<p class="mb10">サーバーの導入をご検討される際の調達の選択肢に、クラウドやオンプレミスに加え、もうひとつの選択肢として、「サブスク」はいかがでしょうか。</p>
									<p class="mb10">「サブスク」とは、お客様が必要とする設備をお客様に代って日本HPファイナンシャルサービスが購入し、比較的長期にわたって一定のサブスク料でお客様に賃貸するお取引です。日本ヒューレット・パッカード(HPE）が運営する公式オンラインストア「HPE DirectPlus」からご利用いただくことで、クラウド、オンプレミス、オンラインストアぞれぞれの“いいところ取り”が可能です。</p>
									<p class="mb10">契約期間中のサブスク料には、製品の取得価格、期間中の支払金利、固定資産税や動産保険料などが含まれており、購入とは異なったメリットをご提供いたします。</p>
								</div>
							</div>
						</div>
						<div class="mt30">
							<img src="./images/subscription_merit_img2.svg">
							<div class="f12 indent-2 mt20 ml20 lhMid">
								<p>※1 一部対象外の製品がございます。ホームページ内の仕様表の「フルカスタマイズCTO対応」をご覧ください。</p>
								<p>※2 一部地域は6営業日でのお届けとなります。また離島についてもご納品までに日数を頂戴しております。詳細はホームページをご覧ください。また、正式受注時の在庫状況、お客様が選択した構成、配送その他諸事情により、お届けまでにお時間をいただく場合がございます。1件のご注文に5営業日納品可能でない製品を含む場合は、5営業日での納品は致しかねます。</p>
								<p>※3 別梱包となるオプションもございます。Windows OSのプリインストールをご希望される場合は、カスタマイズ画面で「Windows OSプリインストール」を選択ください。</p>
								<p>※4 一部の機能については、HPE iLO Advancedのライセンスが必要になります。</p>
								<p>※5 機能を有効にするためには、HPE iLO Amplifier Packの設定が必要になります。</p>
							</div>
						</div>
						<!--<div class="f20 bold mb10">
							こんなことはありませんか？
						</div>
						
						<div class="like-this column25-75Flex fixAll">
							<div class="clm1 flexGutter20">
								<div class="icon-wrapper">
									<div class="icon-user flexGutter20">
										<img src="/directplus_ent/callcenter/images/icon-user.png" width="79" height="93" alt="">
									</div>
									<div class="icon-baloon">
										<img src="/directplus_ent/callcenter/images/icon-baloon.png" width="38" height="43" alt="">
									</div>
								</div>
							</div>
							<div class="clm2 pb20">
								「初期投資を抑えたい」「コストを見直したい、月額化したい」「廃棄にかかる費用を無くしたい」・・・
							</div>
						</div>
						
						<div class="mb20">
							<img src="/directplus_ent/callcenter/images/icon-drop_caret.png" width="76" height="54" alt="" class="m0auto drop_caret">
						</div>
						
						<div class="gutter20">
							<div class="column50-50Flex fixUpperTablet">
								<div class="clm1 flexGutter20">
									<div class="f20 bold lhMid mb10">
										製品導入時に、まとまった資金が必要ありません
									</div>
									<p>
										月額でのお支払い。初期投資を抑えて、経営資金を有効に活用できます。
									</p>
								</div>
								<div class="clm2">
									<div class="f20 bold lhMid mb10">
										老朽化リスクをヘッジできます
									</div>
									<p>
										使用予定期間に応じたサブスク期間の設定により、常に最新鋭の機器を使用可能で、老朽化リスクに柔軟に対応できます。
									</p>
								</div>
							</div>
							
							<div class="column50-50Flex fixUpperTablet">
								<div class="clm1 flexGutter20">
									<div class="f20 bold lhMid mb10">
										廃棄コストが不要です
									</div>
									<p>
										サブスク終了後は返却するだけ。日本HPファイナンシャルサービスが法令に従って適正に処理します。
									</p>
								</div>
								<div class="clm2">
									<div class="f20 bold lhMid mb10">
										事務管理を大幅に省力化できます
									</div>
									<p>
										製品所有に伴う事務手続きや、固定資産税の申告・納付・減価償却計算のような煩雑な事務処理を軽減できます。
									</p>
								</div>
							</div>
							
							<div class="column50-50Flex fixUpperTablet">
								<div class="clm1 flexGutter20">
									<div class="f20 bold lhMid mb10">
										不慮の事故にも対応
									</div>
									<p>
										サブスク製品には動産総合保険が付いています。万が一でも安心！
									</p>
								</div>
								<div class="clm2">
									<div class="f20 bold lhMid mb10">
										コスト把握が容易
									</div>
									<p>
										毎月定額のサブスク料のため、コスト把握が容易になります。
									</p>
								</div>
							</div>
						</div>-->
					</div>
