<div class="microsoft">
	<div class="contact gryBdr4px paddBlock25">
		<div class="mb10">
			<h3 class="f20 bold mb20">Windows Server プリインストールモデルもご選択いただけます</h3>
			<p class="lhMid mb10">HPE DirectPlusではWindows Server OSのプリインストールをご選択可能。届いてすぐにセットアップをはじめることができます。HPE ProLiantサーバーと親和性の高いWindows Serverをセットでどうぞ。</p>
			<div class="alignRgt">
				<a href="/directplus_ent/os_software/#WindowsServer" class="linkWithArrow">
					Windows Serverの詳細はこちら <span class="arrow">→</span></a>
			</div>
		</div>
		<!--<div class="contact-column column50-50Flex fixUpperTablet">
			<div class="clm1 flexGutter20 mb20 mt20">
				<img src="/directplus_ent/images/common/microsoft_600x200.png" width="350" alt="Microsoft" class="m0auto">
			</div>
			<div class="clm2">
				<div class="spHide" style="height: 65px;"></div>
				<p class="f16">
					<span class="bold">Windows Server 2022:</span>Be cloud ready with hybrid.
				</p>
			</div>
		</div>-->
	</div>
</div>
