			<table width="560" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td width="83"><a href="https://www.hpe.com/jp" target="_blank"><img src="/directplus_ent/jeprime/images/local_navigation_hpehome.gif" alt="HPEホーム" width="83" height="19" border="0"></a></td>
					<td width="1"><img src="/comm/legacy/img/s.gif" alt="" width="1" height="1" class="decoration"></td>
					<td width="128"><a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Advantage-Site/ja_JP/-/JPY/StorefrontForAdvantage-Start"><img src="/directplus_ent/jeprime/images/local_navigation_hpeadv.gif" alt="<!--#include virtual="/comm/include/advantageplus_name.inc" -->ホーム" width="128" height="19" border="0"></a></td>
					<td width="1"><img src="/comm/legacy/img/s.gif" alt="" width="1" height="1" class="decoration"></td>
					<td width="90"><a href="/directplus_ent/jeprime/howto/" target="_blank"><img src="/directplus_ent/jeprime/images/local_navigation_howto_hpeadv.gif" alt="ご利用方法" width="90" height="19" border="0"></a></td>
					<td width="1"><img src="/comm/legacy/img/s.gif" alt="" width="1" height="1" class="decoration"></td>
					<td width="104"><a href="/directplus_ent/jeprime/faq/" target="_blank"><img src="/directplus_ent/jeprime/images/local_navigation_faq_hpeadv.gif" alt="よくあるご質問" width="104" height="19" border="0"></a></td>
					<td width="1"><img src="/comm/legacy/img/s.gif" alt="" width="1" height="1" class="decoration"></td>
					<td width="151"><a href="javascript: void(0);" onMouseUp="MM_openBrWindow('/directplus_ent/jeprime/comments/comment1.html','Comments','scrollbars=yes,resizable=yes,width=450,height=250')"><img src="/directplus_ent/jeprime/images/local_navigation_mail_hpeadv.gif" alt="メールでのお問い合わせ" width="151" height="19" border="0"></a></td>
				</tr>
				<tr class="decoration">
					<td colspan="9"><img src="/comm/legacy/img/s.gif" alt="" width="1" height="10"></td>
				</tr>
			</table>