		
		<table width="370" border="0" cellspacing="0" cellpadding="0">
			<tr>
				<td><a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Advantage-Site/ja_JP/-/JPY/StorefrontForAdvantage-Start"><img src="/directplus_ent/jeprime/images/page_title.gif" alt="HP J-ePrime" width="132" height="32" border="0"></a></td>
			</tr>
			<tr>
				<td>
					<table width="370" border="0" cellspacing="0" cellpadding="0">
					<tr>
					<td width="170"><img src="/directplus_ent/jeprime/images/jeprime_callcenter_top.gif" alt="HP J-ePrimeƒR[ƒ‹ƒZƒ“ƒ^[:" width="170" height="17" border="0"></td>
					<td width="200"><font color="#0066FF" class="bold">03-5495-8112<!-- isprint value="#BuyerPhoneCC#" --></font></td>
					</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td><img src="/directplus_ent/jeprime/images/jeprime_callcenter_bottom.gif" alt="ŒŽ—j`‹à—j“ú 9:00`" width="295" height="12" border="0"></td>
			</tr>
		</table>
