<div>						
	<p class="bold f18">こちらもどうぞ</p>
	<div class="column50-50 cfx">
		<div class="clm1">
			<a href="/directplus_ent/server/purpose/file.html" class="linkWithArrow">用途で選ぶ – サーバー選定ガイド ファイルサーバー<span class="arrow">→</span></a>
		</div>
		<div class="clm2">
			<a href="/directplus_ent/server/purpose/utm.html" class="linkWithArrow">用途で選ぶ – サーバー選定ガイド 統合脅威管理（UTM）サーバー<span class="arrow">→</span></a>
		</div>
	</div>
</div>
