<div class="js-section has-js-toc mb20" id="Compare">
	
	<h3 class="f24 bold mb5">
		サーバーとしての可用性も必要、または自由にスペックを選択したい場合は・・・
	</h3>
	
	<div class="mb10">
		<p class="mb10">
			ホットプラグや冗長化電源に対応し、標準保証が3年のHPE ProLiant ML30 Gen10 Plusをおすすめいたします。<br>
			Windows Serverをはじめ、より多くの項目をカスタマイズ可能で、工場組込出荷にも対応するため届いてすぐにお使いいただけます。<br>
			<!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" -->へお電話いただければ、ご希望の用途や環境に合わせた構成で比較のお見積をさせていただきます。
		</p>
		<div class="alignRgt lhMid"> <a href="#ContactUs" class="linkWithArrow"><!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" --><span class="arrow">→</span></a> </div>
	</div>
	<div class="optokuTable">
		<table>
			<tr>
				<th width="20%"></th>
				<th width="40%">MicroServer Gen10 Plus</th>
				<th width="40%">ML30 Gen10 Plus</th>
			</tr>
			<tr class="whiteCell">
				<th>モデル</th>
				<td class="alignCtr">
					<a href="#CustomizeOrder">
						<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_microserver_gen10_plus_optoku.gif" class="m0auto" alt="">
						<!--<img src="/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_microserver_gen10_plus_campaign.gif" class="m0auto" alt="">-->
					</a>
					<a href="#CustomizeOrder" role="button" class="btn btn-secondary">モデルを選択する</a>
					<p class="bold mt10">こちらもどうぞ</p>
					<a href="/directplus_ent/server/purpose/file.html" class="linkWithArrow">用途で選ぶ – サーバー選定ガイド<span class="arrow">→</span></a>
				</td>
				<td class="alignCtr">
					<a href="/directplus_ent/server/ml30gen10plus/">
						<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml30_gen10_plus_optoku.gif" class="m0auto" alt="">
						<!--<img src="/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml30_gen10_plus_campaign.gif" class="m0auto" alt="">-->
					</a>
					<a href="/directplus_ent/server/ml30gen10plus/" role="button" class="btn btn-secondary">モデルを選択する</a>
				</td>
			</tr>
			<tr class="gryCell">
				<th>最小構成価格(税抜)</th>
				<td class="alignCtr">
					オプ得モデル　110,000円～
					<!--オプ得モデル　<span class="lineThrough">110,000円～</span><br>
					<span class="bold f18">期間限定　77,000円～</span>-->
				</td>
				<td class="alignCtr">
					オプ得モデル　216,000円～
					<!--オプ得モデル　<span class="lineThrough">110,000円～</span><br>
					<span class="bold f18">期間限定　85,000円～</span>-->
				</td>
			</tr>
			<tr class="whiteCell">
				<th>フルカスタマイズCTO対応<br><a class="tertiary-link alpha" href="/directplus_ent/promotion/merit/"><span class="white">メリットはこちら</span></a></th>
				<td class="alignCtr">非対応<br>オプション組み込み ×<br>OSインストール納品 ×</td>
				<td class="alignCtr">○</td>
			</tr>
			<tr class="gryCell">
				<th>おすすめ用途</th>
				<td class="alignCtr">・SOHO/中小規模向け(～20人)<br>・各拠点や部門、小規模店舗用APサーバー<br>・中小規模ファイルサーバー</td>
				<td class="alignCtr">・SOHO/中小規模向け(～100人)<br>・店舗APサーバー<br>・中小規模ファイルサーバー</td>
			</tr>
			<tr class="whiteCell">
				<th>プロセッサー</th>
				<td class="alignCtr">最大1基：インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> E2224 /<br>Pentium<sup>&reg;</sup> Gold G5420 プロセッサー</td>
				<td class="alignCtr">最大1基/8コア：インテル<sup>&reg;</sup> Pentium<sup>&reg;</sup> G6400 /<br>Xeon<sup>&reg;</sup> E-2300 シリーズ</td>
			</tr>
			<tr class="gryCell">
				<th>メモリ</th>
				<td class="alignCtr">2DIMMスロット DDR4 UDIMM</td>
				<td class="alignCtr">4DIMMスロット DDR4 UDIMM</td>
			</tr>
			<tr class="whiteCell">
				<th>ドライブ</th>
				<td class="alignCtr">4(3.5型ノンホットプラグSATA/SSD)</td>
				<td class="alignCtr">4(3.5型ノンホットプラグSATA)<br>4(3.5型ホットプラグSATA/SAS/SSD)<br>4(2.5型ホットプラグSATA/SSD)<br>8(2.5型ホットプラグSATA/SAS/SSD)</td>
			</tr>
			<tr class="gryCell">
				<th>拡張スロット</th>
				<td class="alignCtr">1(ロープロファイル/ハーフレングスPCI Express Gen3 x16×1)</td>
				<td class="alignCtr">4(フルハイト/フルレングスPCI Express Gen4 x16(x16コネクター)×1、フルハイト/フルレングスPCI Express Gen3 x4(x16コネクター)×1、フルハイト/ハーフレングスPCI Express Gen3 x4(x8コネクター)×2)</td>
			</tr>
			<tr class="whiteCell">
				<th>電源冗長化</th>
				<td class="alignCtr">✕</td>
				<td class="alignCtr">〇<br>オプション。「2nd パワーサプライ<br>(リダンダント用)」選択時</td>
			</tr>
			<tr class="gryCell">
				<th>音響ノイズ</th>
				<td class="alignCtr">21dBA</td>
				<td class="alignCtr">26～29dBA</td>
			</tr>
		</table>
	</div>
	
</div><!-- /#Compare -->
