<div>
	<p>
		HPE ProLiant MicroServer Gen10 Plus は、従来のMicroServer Gen10と比較して半分の筐体サイズ、2倍の性能、管理性に優れたiLO5オプションに対応、と大幅な刷新を図りながら、お求めやすい価格を実現したタワー型サーバーです。<br>
		特に筐体サイズは従来の半分のサイズ(幅11.9cm) を実現しており、オフィス環境に最適なスリムデザインで広範囲な用途に適用可能です。
	</p>
	<p class="mt15">
		<a href="/directplus_ent/server/infosight_for_servers.html" class="linkWithArrow" target="_blank">HPE InfoSight for Servers 対応サーバー　詳しくはこちら<span class="arrow">→</span></a>
	</p>
</div>
