<div class="paddBlock20 broBdr4px">

	<h4 class="f24 bold mb10">オプションが通常価格の30%OFF。「オプ得」でお得にシステム増強</h4>
	
	<div class="product__optoku">
		
		<div class="clm1">
			<p>
				「オプ得」とはプロセッサー、メモリ、ディスクドライブその他のカスタマイズオプションを通常価格の30%OFF相当でお求めいただける、<!--#include virtual="/comm/include/directplus_name.inc" -->ならではの特典です。
			</p>
			<!--<a href="/directplus_ent/optoku/?hash=ProductsOption" target="_blank" role="button" class="alpha btn btn-tertiary">30%OFFになるオプションはこちら</a>-->
			<a href="/directplus_ent/optoku/?hash=ProductsOption" target="_blank" role="button" class="btn btn-secondary">30%OFFになるオプションはこちら</a>
		</div>
		
		<div class="clm2">
			<a href="/directplus_ent/optoku/">
				<img src="/directplus_ent/optoku/images/bnr_optoku_680x280.png" alt="オプ得" class="w100per">
			</a>
		</div>
		
	</div>
</div>