<div class="product__price">
	<div class="clm1 layout__show1000px">
		<!-- 1000px以上でのみ表示 -->
		<div class="clmInr mb20 mt20">
			<div class="gsPriceArea">
				<p class="f18 mb10">通常モデル最小構成価格</p>
				<p><span>110,000</span><span class="f18">円(税抜)～</span></p>
			</div>
			<div class="gsPriceArea mt30 showOnly_duringCampaign">
				<p class="f18 mb10">オプ得モデル最小構成価格</p>
				<p class="f12 mb10 lhMid">メモリ、ディスクといったカスタマイズオプションが通常価格の30%OFFになります。</p>
				<p class=""><span>110,000</span><span class="f18">円(税抜)～</span></p>
				<!--<p class="f18 mt5 mb5">0円引き～</p>-->
			</div>
			<div class="alignCtr mb20">
				<a href="#CustomizeOrder" role="button" class="btn btn-secondary">お見積</a>
			</div>
		</div>
	</div>
	<div class="clm2">
		<div class="clmInr mb20 mt20">
			<div class="gsPriceArea showOnly_duringCampaign">
				<p class="bold f18 mb10 spHide">キャンペーンモデル最小構成価格</p>
				<p class="f18 strikethrough spHide">110,000円(税抜)～</p>
				<p class="bold">期間限定 <span>77,000</span><span class="f18">円(税抜)～</span></p>
				<p class="f18 mt5 mb5 spHide">33,000円引き～</p>
			</div>
			<div class="gsPriceArea hide_duringCampaign">
				<p class="bold f18 mb10">オプ得モデル最小構成価格</p>
				<p class="f12 mb10 lhMid">メモリ、ディスクといったカスタマイズオプションが通常価格の30%OFFになります。</p>
				<p class="bold"><span>110,000</span><span class="f18">円(税抜)～</span></p>
				<!--<p class="f18 mt5 mb5">0円引き～</p>-->
			</div>
			<div class="alignCtr">
				<a href="#CustomizeOrder" role="button" class="btn btn-secondary">お見積</a>
			</div>
		</div>
	</div>
</div>