<div class="specTable2Area fixedTable">
	
	<div class="specTable2">
		<!--<div class="specTableTitle">
		<table width="1000">
			<tr>
				<th width="146"></th>
				<th width="427" class="f16">Pentium G5420 ディスクレス<br>オプ得モデル</th>
				<th width="427" class="f16">Xeon E-2224 ディスクレス<br>オプ得モデル</th>
			</tr>
		</table>
		</div>-->
		<table width="1000">
			<tr>
				<th width="146"></th>
				<th width="427" class="f16">Pentium G5420 ディスクレス<br>オプ得モデル</th>
				<th width="427" class="f16">Xeon E-2224 ディスクレス<br>オプ得モデル</th>
			</tr>
			<tr>
				<th></th>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_microserver_gen10_plus.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_microserver_gen10_plus.gif" alt="" class="m0auto">
				</td>
			</tr>
			<tr>
				<th>ドライブ</th>
				<td colspan="2"><span class="cutomizable">同時購入可能</span><span class="bold">ディスクレス　ノンホットプラグ 3.5型</span> 最大4<br>SATA HDD、SATA SSD選択可</td>
			</tr>
			<tr>
				<th>プロセッサー</th>
				<td>最大1基　インテル<sup>&reg;</sup> Pentium<sup>&reg;</sup> Gold G5420 プロセッサー</td>
				<td>最大1基　インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> E2224 プロセッサー</td>
			</tr>
			<tr>
				<th>メモリ</th>
				<td colspan="2"><span class="cutomizable2">同時購入可能</span>2DIMMスロット DDR4 UDIMM</td>
			</tr>
			<!--<tr>
				<th>パワーサプライ</th>
				<td colspan="3"><span class="cutomizable2">同時購入可能</span>標準1、最大2  オプションで冗長化対応、ホットプラグ対応</td>
			</tr>-->
			<tr>
				<th>最小構成価格<br>（税抜）</th>
				<td class="pt10 pb10">
					<div class="mb25">
						<span class="bold f16">オプ得モデル</span><br>
						<span class="bold f18">110,000円～</span><br>
						<!--<span class="f12">0円引き～</span>-->
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4356&ProductSKU=BASE:15836" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
					<div>
						<span class="bold f16">通常モデル</span>
						<span class="f16">110,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4359&ProductSKU=BASE:15834" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
				<td class="pt10 pb10">
					<div class="mb25">
						<span class="bold f16">オプ得モデル</span><br>
						<span class="bold f18">160,000円～</span><br>
						<!--<span class="f12">0円引き～</span>-->
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4356&ProductSKU=BASE:15837" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
					<div>
						<span class="bold f16">通常モデル</span>
						<span class="f16">160,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4359&ProductSKU=BASE:15835" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
			</tr>
			<tr>
				<th></th>
				<td colspan="4" class="pt10 pb15">
					<a href="pdfs/spec.pdf" target="_blank" class="linkWithArrow">
						仕様一覧はこちら（PDF）
						<span class="arrow">→</span>
					</a>
				</td>
			</tr>
		</table>
	</div><!-- /.specTable2 -->
	
</div><!-- /.specTable2Area -->