<div class="specTable2Area fixedTable">
	
	<div class="specTable2">
		<div class="specTableTitle">
		<table width="1000">
			<tr>
				<th width="146"></th>
				<th width="427" class="f16">Pentium G5420 ディスクレス<br>オプ得モデル</th>
				<th width="427" class="f16">Xeon E-2224 ディスクレス<br>オプ得モデル</th>
			</tr>
		</table>
		</div>
		<table width="1000">
			<tr>
				<th width="146"></th>
				<th width="427" class="f16">Pentium G5420 ディスクレス<br>オプ得モデル</th>
				<th width="427" class="f16">Xeon E-2224 ディスクレス<br>オプ得モデル</th>
			</tr>
			<tr>
				<th>ドライブ</th>
				<td colspan="2"><span class="cutomizable">同時購入可能</span><span class="bold">ディスクレス　ノンホットプラグ 3.5型</span> 最大4<br>SATA HDD、SATA SSD選択可</td>
			</tr>
			<tr>
				<th>プロセッサー</th>
				<td>最大1基　インテル<sup>&reg;</sup> Pentium<sup>&reg;</sup> Gold G5420 プロセッサー</td>
				<td>最大1基　インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> E2224 プロセッサー</td>
			</tr>
			<tr>
				<th>メモリ</th>
				<td colspan="2"><span class="cutomizable2">同時購入可能</span>2DIMMスロット DDR4 UDIMM</td>
			</tr>
			<!--<tr>
				<th>パワーサプライ</th>
				<td colspan="3"><span class="cutomizable2">同時購入可能</span>標準1、最大2  オプションで冗長化対応、ホットプラグ対応</td>
			</tr>-->
			<tr>
				<th>最小構成価格<br>（税抜）</th>
				<td class="pt10 pb10">
				<div class="mb10">
					<span class="bold f14">キャンペーンモデル<br>期間限定</span><br>
					<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4356&ProductSKU=BASE:16002" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f19">77,000円～</span></a><br>
					<span class="f14">33,000円引き～</span>
				</div>
					<div class="mb10">
						<span class="f14">
							<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4356&ProductSKU=BASE:15836" class="cta-link"><em class="icon-arrow-circle-right"></em>オプ得モデル</a><br>
							110,000円～
						</span>
					</div>
					<div>
						<span class="f14">
							<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4359&ProductSKU=BASE:15834" class="cta-link"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
							110,000円～
						</span>
					</div>
				</td>
				<td class="pt10 pb10">
				<div class="mb10">
					<span class="bold f14">キャンペーンモデル<br>期間限定</span><br>
					<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4356&ProductSKU=BASE:16003" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f19">112,000円～</span></a><br>
					<span class="f14">48,000円引き～</span>
				</div>
					<div class="mb10">
						<span class="f14">
							<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4356&ProductSKU=BASE:15837" class="cta-link"><em class="icon-arrow-circle-right"></em>オプ得モデル</a><br>
							160,000円～
						</span>
					</div>
					<div>
						<span class="f14">
							<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4359&ProductSKU=BASE:15835" class="cta-link"><em class="icon-arrow-circle-right"></em>通常モデル</a><br>
							160,000円～
						</span>
					</div>
				</td>
			</tr>
			<tr>
				<th></th>
				<td colspan="4" class="pt10 pb15 bgG"><a href="pdfs/spec.pdf" target="_blank" class="tertiary-link">スペックの詳細はこちら</a></td>
			</tr>
		</table>
	</div><!-- /.specTable2 -->
	
</div><!-- /.specTable2Area -->