<div class="js-section has-js-toc mb40" id="Compare">

	<h3 class="f24 bold mb5">
		将来のユーザー増加に備えて、さらなる拡張性がほしい場合は・・・
	</h3>
	<div class="mb10">
		<p class="mb10">
			お求めやすい価格でより優れた拡張性を備えるHPE ProLiant ML110 Gen10をおすすめいたします。<br>
			<!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" -->へお電話いただければ、ご希望の用途や環境に合わせた構成で比較のお見積をさせていただきます。
		</p>
		<div class="alignRgt lhMid"> <a href="#ContactUs" class="linkWithArrow"><!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" --><span class="arrow">→</span></a> </div>
	</div>
	<div class="optokuTable">
		<table>
			<tr>
				<th width="20%"></th>
				<th width="40%">ML30 Gen10 Plus</th>
				<th width="40%">ML110 Gen10</th>
			</tr>
			<tr class="whiteCell">
				<th>モデル</th>
				<td class="alignCtr">
					<!-- ML30 Gen10 Plus -->
					<!--<span class="bold">お得なキャンペーン実施中！</span><br>-->
					<a href="#CustomizeOrder">
						<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml30_gen10_plus_optoku.gif" alt="" class="m0auto">
						<!--<img src="/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml30_gen10_campaign.gif" alt="" class="m0auto">-->
					</a>
					<a href="#CustomizeOrder" role="button" class="btn btn-secondary">モデルを選択する</a>
				</td>
				<td class="alignCtr">
					<!-- ML110 Gen10 -->
					<!--<span class="bold">お得なキャンペーン実施中！</span><br>-->
					<a href="/directplus_ent/optoku/ml110gen10/">
						<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml110_gen10_optoku.gif" alt="" class="m0auto">
						<!--<img src="/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml110_gen10_campaign.gif" alt="" class="m0auto">-->
					</a>
					<a href="/directplus_ent/optoku/ml110gen10/" role="button" class="btn btn-secondary">モデルを選択する</a>
				</td>
			</tr>
			<tr class="gryCell">
				<th>最小構成価格(税抜)</th>
				<td class="alignCtr">
					<!-- ML30 Gen10 Plus -->
					オプ得モデル　216,000円～
					<!--通常モデル　247,000円～<br>-->
					<!--通常モデル　<span class="lineThrough">232,000円～</span><br>-->
					<!--オプ得モデル　<span class="lineThrough">110,000円～</span><br>
					<span class="bold f18">期間限定　85,000円～</span>-->
				</td>
				<td class="alignCtr">
					<!-- ML110 Gen10 -->
					オプ得モデル　192,000円～
					<!--通常モデル　<span class="lineThrough">252,000円～</span><br>
					<span class="bold f18">期間限定　176,000円～</span>-->
				</td>
			</tr>
			<!--<tr class="whiteCell">
				<th>フルカスタマイズCTO対応<br><a class="tertiary-link alpha" href="/directplus_ent/promotion/merit/"><span class="white">メリットはこちら</span></a></th>
				<td class="alignCtr">○</td>
				<td class="alignCtr">○</td>
			</tr>-->
			<tr class="whiteCell">
				<th>おすすめ用途</th>
				<td class="alignCtr">
					<!-- ML30 Gen10 Plus -->
					・SOHO/中小規模向け(～100人)<br>
					・店舗APサーバー<br>
					・中小規模ファイルサーバー
				</td>
				<td class="alignCtr">
					<!-- ML110 Gen10 -->
					・中規模向け(～250人)<br>
					・Web・APサーバー<br>
					・中規模ファイルサーバー
				</td>
			</tr>
			<tr class="gryCell">
				<th>プロセッサー</th>
				<td class="alignCtr">
					<!-- ML30 Gen10 Plus -->
					最大1基/8コア<br>
					インテル<sup>&reg;</sup> Pentium<sup>&reg;</sup> G6400 /<br>
					Xeon<sup>&reg;</sup> E-2300 シリーズ
				</td>
				<td class="alignCtr">
					<!-- ML110 Gen10 -->
					最大1基/14コア<br>
					インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー
				</td>
			</tr>
			<tr class="whiteCell">
				<th>メモリ</th>
				<td class="alignCtr">
					<!-- ML30 Gen10 Plus -->
					4DIMMスロット DDR4 UDIMM
				</td>
				<td class="alignCtr">
					<!-- ML110 Gen10 -->
					6DIMMスロット DDR4 RDIMM
				</td>
			</tr>
			<tr class="gryCell">
				<th>ドライブ</th>
				<td class="alignCtr">
					<!-- ML30 Gen10 Plus -->
					4(3.5型ノンホットプラグSATA)<br>
					4(3.5型ホットプラグSATA/SAS/SSD)<br>
					4(2.5型ホットプラグSATA/SSD)<br>
					8(2.5型ホットプラグSATA/SAS/SSD)
				</td>
				<td class="alignCtr">
					<!-- ML110 Gen10 -->
					標準8、最大16 (2.5型 ホットプラグSAS/SATA/SSD)<br>
					標準4、最大8 (3.5型 ホットプラグSAS/SATA/SSD)<br>
					標準4、最大8 (3.5型 ノンホットプラグSATA)
				</td>
			</tr>
			<tr class="whiteCell">
				<th>拡張スロット</th>
				<td class="alignCtr">
					<!-- ML30 Gen10 Plus -->
					4(フルハイト/フルレングスPCI Express Gen4 x16(x16コネクター)×1、フルハイト/フルレングスPCI Express Gen3 x4(x16コネクター)×1、フルハイト/ハーフレングスPCI Express Gen3 x4(x8コネクター)×2)
				</td>
				<td class="alignCtr">
					<!-- ML110 Gen10 -->
					5(FH/ 3/4 L PCI Express Gen3 x16、FH/HL PCI Express Gen3 x8、FH/HL PCI Express Gen3 x16、FH/HL PCI Express Gen3 x4 x2)
				</td>
			</tr>
			<tr class="gryCell">
				<th>音響ノイズ</th>
				<td class="alignCtr">
					<!-- ML30 Gen10 Plus -->
					26～29dBA
				</td>
				<td class="alignCtr">
					<!-- ML110 Gen10 -->
					24～25dBA
				</td>
			</tr>
		</table>

		<!--<p class="bold mt10 f18">
			ML30 Gen10 Plus、ML110 Gen10 以外のモデルも--><!--キャンペーン価格にて--><!--オプ得価格にてお見積・ご注文いただけます。
		</p>-->

		<!--<a href="/directplus_ent/campaign/">-->
		<!--<a href="/directplus_ent/optoku/">
			<span class="cta-link"><em class="icon-arrow-circle-right"></em>詳しくはこちら</span>
		</a>-->

	</div>

</div><!-- /#Compare -->
