<style>
.column66-33 .clm2 img{
	max-width: 120px;
	height:auto;
	margin: 0px auto 20px;
}

</style>
<div class="column66-33 cfx">
	<div class="clm1">
		<p>
			HPE ProLiant ML30 Gen10 Plusは、管理性、静音性、冗長性を兼ね備えた中小規模システム向け1ソケットエントリータワー型サーバーです。<br>
		最新のインテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> E-2300プロセッサー、インテル<sup>&reg;</sup> Pentium<sup>&reg;</sup>プロセッサーを採用し、高性能・低消費電力のDDR4-3200 MT/sメモリを採用しています。<br>
		またHPE独自の管理チップ iLO5の提供する“シリコンレベルの信頼性”を基盤に、HPE独自の電子認証によるファームウェアの更新や不正書き換えの早期認識と回復機能を備えています。さらにセキュリティ強化としてTPM2.0も標準搭載となります。<br>
		静音性(26 -29dBA)にも優れ、病院、図書館、オフィス環境に最適です。さらに電源の冗長化にも対応しており、各拠点向けビジネスサーバーや店舗用サーバー等の中小規模システムに期待される機能・性能を備えています。
		</p>
		<p class="mt15">
			<a href="/directplus_ent/server/infosight_for_servers.html" class="linkWithArrow" target="_blank">HPE InfoSight for Servers 対応サーバー　詳しくはこちら<span class="arrow">→</span></a>
		</p>
	</div>
	<div class="clm2">
		<a href="../pdfs/dl20gen10plus_ml30gen10plus.pdf" target="_blank">
			<img src="../images/dl20gen10plus_ml30gen10plus_thumb.jpg">
		</a>
		<div class="alignCtr lhMid">
			<a href="../pdfs/dl20gen10plus_ml30gen10plus.pdf" class="linkWithArrow" target="_blank">
				HPE ProLiant<br>ML30 Gen10 Plus チラシ<span class="arrow">→</span>
			</a>
		</div>
	</div>
</div>
