<div class="specTable2Area fixedTable">

	<div class="specTable2">
		<!--<div class="specTableTitle">
			<table width="775">
				<tr>
					<th width="100"></th>
					<th width="225" class="f14">
						コストパフォーマンス重視<br><span class="f20">NHP 4LFF</span>
					</th>
					<th width="225" class="f14">
						信頼性とコストパフォーマンス<br><span class="f20">4LFF</span>
					</th>
					<th width="225" class="f14">
						性能・信頼性重視<br><span class="f20">8SFF</span>
					</th>
				</tr>
			</table>
		</div>-->
		<table width="100%">
			<tr>
				<th width="12%"></th>
				<th width="22%" class="f14">
					コストパフォーマンス重視<br><span class="f20">NHP 4LFF</span>
				</th>
				<th width="22%" class="f14">
					信頼性とコストパフォーマンス<br><span class="f20">4LFF</span>
				</th>
				<th width="22%" class="f14">
					信頼性とコストパフォーマンス<br><span class="f20">4SFF</span>
				</th>
				<th width="22%" class="f14">
					性能・信頼性重視<br><span class="f20">8SFF</span>
				</th>
			</tr>
			<tr>
				<th></th>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml30_gen10_plus_optoku.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml30_gen10_plus_optoku.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml30_gen10_plus_optoku.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml30_gen10_plus.gif" alt="" class="m0auto">
				</td>
			</tr>
			<tr>
				<th>ドライブ</th>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ノンホットプラグ LFF</span> 最大4<br>SATA HDD選択可<br><br>
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ LFF</span> 最大4<br>SATA HDD、SATA SSD、<br>SAS HDD選択可
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ SFF</span> 最大4<br>SATA HDD、SATA SSD選択可<br><br>
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ SFF</span> 最大8<br>SATA HDD、SATA SSD、SAS HDD、<br>SAS SSD選択可
				</td>
			</tr>
			<tr>
				<th>プロセッサー</th>
				<td colspan="4">
					<span class="cutomizable2">カスタマイズ可能</span>最大1基 インテル<sup>&reg;</sup> Pentium<sup>&reg;</sup> G6400 / Xeon<sup>&reg;</sup> E-2300 シリーズ
				</td>
			</tr>
			<tr>
				<th>メモリ</th>
				<td colspan="4">
					<span class="cutomizable2">カスタマイズ可能</span>4DIMMスロット DDR4 UDIMM
				</td>
			</tr>
			<tr>
				<th>パワーサプライ</th>
				<td colspan="4">
					<span class="cutomizable2">カスタマイズ可能</span>標準1、最大2 オプションで冗長化対応、ホットプラグ対応
				</td>
			</tr>
			<tr>
				<th>最小構成価格<br>（税抜）</th>
				<td class="pt10 pb10">
					<div class="mb25">
						<span class="bold f16">オプ得モデル</span><br>
						<span class="bold f18">216,000円～</span><br>
						<span class="f12">31,000円引き～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4421&ProductSKU=BASE:16109" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
					<div>
						<span class="bold f16">通常モデル</span>
						<span class="f16">247,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4415&ProductSKU=BASE:16102" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
				<td class="pt10 pb10">
					<div class="mb25">
						<span class="bold f16">オプ得モデル</span><br>
						<span class="bold f18">252,000円～</span><br>
						<span class="f12">34,000円引き～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4421&ProductSKU=BASE:16110" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
					<div>
						<span class="bold f16">通常モデル</span>
						<span class="f16">286,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4415&ProductSKU=BASE:16103" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
				<td class="pt10 pb10">
					<div class="mb25">
						<span class="bold f16">オプ得モデル</span><br>
						<span class="bold f18">287,000円～</span><br>
						<span class="f12">34,000円引き～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4421&ProductSKU=BASE:16111" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
					<div>
						<span class="bold f16">通常モデル</span>
						<span class="f16">321,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4415&ProductSKU=BASE:16108" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
				<td class="pt10 pb10">
					<div style="height: 138px;"></div>
					<div>
						<span class="bold f16">通常モデル</span>
						<span class="f16">382,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4415&ProductSKU=BASE:16104" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
			</tr>
			<tr>
				<th></th>
				<td colspan="4" class="pt10 pb15">
					<a href="pdfs/spec.pdf" target="_blank" class="linkWithArrow">
						仕様一覧はこちら（PDF）
						<span class="arrow">→</span>
					</a>
				</td>
			</tr>
		</table>
	</div><!-- /.specTable2 -->

</div><!-- /.specTable2Area -->
