<div class="js-nav-wrapper floating-nav-wrapper">
	<ul class="js-toc-list toc-items">
		<li class="toc-item">
			<a class="js-toc toc" href="#Overview">
				<span class="toc-text">
					特長
				</span>
			</a>
		</li>
		<!--<li class="toc-item">
			<a class="js-toc toc" href="#Names">
				<span class="toc-text">
					各部名称
				</span>
			</a>
		</li>-->
		<li class="toc-item">
			<a class="js-toc toc" href="#CustomizeOrder">
				<span class="toc-text">
					モデルを選択する
				</span>
			</a>
		</li>
		<li class="toc-item">
			<a class="js-toc toc" href="#Compare">
				<span class="toc-text">
					製品比較
				</span>
			</a>
		</li>
	</ul>
	<div class="js-toc-aside floating-nav-aside">
		<a href="#CustomizeOrder" role="button" class="btn btn-primary">モデルを選択する</a>
	</div>
	<span class="js-indicator indicator"></span>
</div>
