<div class="product__adaptableCampaignWrapper">
	<div class="product__adaptableCampaign">
		<div class="clm1">
			<p class="bold f20 lhMid">適用可能なキャンペーン</p>
		</div>
		<div class="clm2">
			<a href="/directplus_ent/promotion/amazongift/">
				<img src="/directplus_ent/images/banners/bnr_400x90_amazongift_campaign.jpg" width="200" class="m0auto" alt="お見積でもらえる、ギフト券がもらえる">
			</a>
		</div>
		<div class="clm3">
			<a href="/directplus_ent/campaign/">
				<img src="/directplus_ent/images/banners/bnr_400_txt01.png" width="200" class="m0auto" alt="キャンペーン価格で即時お見積">
				<img src="/directplus_ent/images/banners/bnr_400x90_dx_campaign.jpg" width="200" class="m0auto" alt="HPE サーバー&amp;ストレージ DX応援キャンペーン">
			</a>
		</div>
	</div>
</div>