<div class="mb20" id="Compare">

	<h3 class="f24 bold mb5">
		1Uサーバーで多様なワークロードに対応する性能を追及したい場合は・・・
	</h3>
	<div class="mb10">
		<p class="mb10">
			1U筐体で2プロセッサー/最大128コアを実現する<a href="/directplus_ent/server/dl365gen10plus/" class="tertiary-link">HPE ProLiant DL365 Gen10 Plus</a>をおすすめいたします。高性能と高集約性を併せ持ち、CAE、HPC、VDIといったワークロードに最適です。<br>
			<!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" -->へお電話いただければ、専任スタッフがご希望の用途や環境に合わせた構成で比較のお見積をさせていただきます。</p>
		<div class="alignRgt"> <a href="#ContactUs"><span class="cta-link"><em class="icon-arrow-circle-right"></em><!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" --></span></a> </div>
	</div>
	<div class="optokuTable">
		<table>
			<tr>
				<th width="20%"></th>
				<th width="40%">DL325 Gen10</th>
				<th width="40%">DL365 Gen10 Plus</th>
			</tr>
			<tr class="whiteCell">
				<th>モデル</th>
				<td class="alignCtr">
					<a href="#CustomizeOrder">
						<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl325_gen10.gif" class="m0auto" alt="">
						<!--<img src="/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl325_gen10_campaign.gif" class="m0auto" alt="">-->
					</a>
					<a href="#CustomizeOrder" role="button" class="btn btn-secondary">カスタマイズ・お見積</a>
				</td>
				<td class="alignCtr">
					<a href="/directplus_ent/server/dl365gen10plus/">
						<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl365_gen10_plus.gif" class="m0auto" alt="">
					</a>
					<a href="/directplus_ent/server/dl365gen10plus/" role="button" class="btn btn-secondary">カスタマイズ・お見積</a>
				</td>
			</tr>
			<tr class="gryCell">
				<th>最小構成価格(税抜)</th>
				<td class="alignCtr">
					通常モデル　467,000円～
					<!--通常モデル　<span class="lineThrough">443,000円～</span><br>
					<span class="bold f18">期間限定　298,000円～</span>-->
				</td>
				<td class="alignCtr">
					通常モデル　695,000円～
				</td>
			</tr>
			<tr class="whiteCell">
				<th>おすすめ用途</th>
				<td class="alignCtr">
					・中規模業務アプリケーションサーバー<br>
					・Webサーバー<br>
					・メールサーバー<br>
					・仮想化<br>
					・中規模DB<br>
					・ファイルサーバー
				</td>
				<td class="alignCtr">
					・大中規模業務アプリケーションサーバー<br>
					・性能を重視する用途<br>
					・科学技術演算用サーバー<br>
					・メールサーバー<br>
					・仮想化&amp;VDI<br>
					・中規模DB<br>
					・ファイルサーバー
				</td>
			</tr>
			<tr class="gryCell">
				<th>プロセッサー</th>
				<td class="alignCtr">
					最大1基/32コア<br>
					AMD EPYC&trade; プロセッサー
				</td>
				<td class="alignCtr">
					最大2基/128コア<br>
					AMD EPYC&trade; プロセッサー
				</td>
			</tr>
			<tr class="whiteCell">
				<th>メモリ</th>
				<td class="alignCtr">16DIMMスロット DDR4 RDIMM</td>
				<td class="alignCtr">30DIMMスロット DDR4 RDIMM</td>
			</tr>
			<tr class="gryCell">
				<th>ドライブ</th>
				<td class="alignCtr">
					4(3.5型ホットプラグSAS/SATA)<br>
					標準8、最大10(2.5型ホットプラグSAS/SATA/SSD)
				</td>
				<td class="alignCtr">
					標準8、最大10(SFF ホットプラグSAS/SATA/SSD)
				</td>
			</tr>
			<tr class="whiteCell">
				<th>拡張スロット</th>
				<td class="alignCtr">
					2(フルハイト/フルレングス PCI Express Gen3 x16×1、<br>
					ロープロファイルPCI Express Gen3 x8×1)
				</td>
				<td class="alignCtr">
					3 (OCP 3.0 スロット×1、フルハイト/ハーフレングスPCI Express Gen4 x16(x16 コネクター) ×1、ロープロファイル/フルレングスPCI Express Gen4 x16(x16 コネクター)×1)<br>
					<span class="f12">※オプションにより最大4</span>
				</td>
			</tr>
		</table>
	</div>

</div><!-- /#Compare -->
