<div>
	<h4 class="f18 bold">
		1Pで2Pの性能を凌駕するコストパフォーマンス
	</h4>
	<p>
		HPE ProLiant DL325 Gen10は最大32コアのAMD EPYC&trade;プロセッサーを搭載し、従来のデュアルプロセッサーを凌駕する性能を実現しています。<br>
		メモリやストレージも高い拡張性を持ち、仮想化統合におすすめのコストパフォーマンスに優れた薄型1U ラックマウント型サーバーです。</p>
	<h4 class="f18 bold mt10">
		お客様の業務を守る“世界標準の安心サーバー”
	</h4>
	<p>
		“シリコンレベルの信頼性”を備え、HPE独自の電子認証によるファームウェアの更新や不正書き換えの早期認識と回復機能を備えています。
	</p>
	<p class="mt10">
		なお本製品の上位機種として、<a href="/directplus_ent/server/dl325gen10plus/" class="tertiary-link">HPE ProLiant DL325 Gen10 Plus</a>や、最新機種<a href="/directplus_ent/server/dl325gen10plusv2/" class="tertiary-link">HPE ProLiant DL325 Gen10 Plus v2</a>もラインアップしております。
	</p>
	<p class="mt15">
		<a href="/directplus_ent/server/infosight_for_servers.html" class="linkWithArrow" target="_blank">HPE InfoSight for Servers 対応サーバー　詳しくはこちら<span class="arrow">→</span></a>
	</p>
</div>
