<div class="specTable2Area fixedTable">
	<div class="specTable2">
		<div class="specTableTitle">
			<table width="1000">
				<tr>
					<th width="100"></th>
					<th width="450" class="f14">
						信頼性とコストパフォーマンス<br>
						<span class="f20">4LFF</span></th>
					<th width="450" class="f14">
						性能・信頼性重視<br>
						<span class="f20">8SFF</span>
					</th>
				</tr>
			</table>
		</div>
		<table width="1000">
			<tr>
				<th width="100"></th>
				<th width="450" class="f14">
					信頼性とコストパフォーマンス<br>
					<span class="f20">4LFF</span>
				</th>
				<th width="450" class="f14">
					性能・信頼性重視<br>
					<span class="f20">8SFF</span>
				</th>
			</tr>
			<tr>
				<th>ドライブ</th>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 3.5型</span> 最大4<br>
					SATA HDD、SAS HDD選択可
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 2.5型</span> 最大10<br>
					SATA HDD、SATA SSD、SAS HDD、SAS SSD選択可
				</td>
			</tr>
			<tr>
				<th>プロセッサー</th>
				<td colspan="2">
					<span class="cutomizable2">カスタマイズ可能</span>最大1基　AMD EPYC<sup>&trade;</sup> プロセッサー
				</td>
			</tr>
			<tr>
				<th>メモリ</th>
				<td colspan="2">
					<span class="cutomizable2">カスタマイズ可能</span>16DIMMスロット DDR4 RDIMM
				</td>
			</tr>
			<tr>
				<th>パワーサプライ</th>
				<td colspan="2">
					<span class="cutomizable2">カスタマイズ可能</span>標準1、最大2　オプションで冗長化対応、ホットプラグ対応
				</td>
			</tr>
			<tr>
				<th rowspan="2">
					<!--<span class="f11">EPYC xxx2搭載</span><br>-->最小構成価格<br>（税抜）
				</th>
				<td colspan="2" class="pt25" style="border-bottom: none;">
					<div class="bold f16">EPYC xxx2 (第2世代プロセッサー) 搭載</div>
				</td>
			</tr>
			<tr>
				<td class="pt10 pb10 valign-b bgW">
					<div>
						<span class="bold f14">通常モデル（NC<sup>※</sup>）</span><br>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4319&ProductSKU=BASE:15788" role="button" class="btn btn-secondary mt0 mb5">467,000円～</a>
					</div>
				</td>
				<td class="pt10 pb10 valign-b bgW">
					<div>
						<span class="bold f14">通常モデル（NC<sup>※</sup>）</span><br>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4319&ProductSKU=BASE:15787" role="button" class="btn btn-secondary mt0 mb5">485,000円～</a>
					</div>
				</td>
			</tr>
			<tr>
				<th></th>
				<td colspan="2" class="pt10 pb15 bgG"><a href="pdfs/spec.pdf" target="_blank" class="tertiary-link">スペックの詳細はこちら</a></td>
			</tr>
		</table>
	</div><!-- /.specTable2 -->

</div><!-- /.specTable2Area -->
<p class="f12 indent-1 mt10">
	※NCモデルは、従来マザーボードに標準搭載していたオンボードのネットワークアダプターを非搭載にして、お客様の環境やユースケースに合ったプライマリーのアダプターを柔軟に選択可能にしたモデルです。NIC専用ポートであるFlexibleLOMにNICカードを必ず搭載いただく必要があります。
</p>
