<div class="js-section has-js-toc mb20" id="Compare">
	<h3 class="f24 bold mb5">251人超の規模のDBサーバーや仮想化プラットフォームに利用したい場合は・・・</h3>
	<div class="mb10">
		<p class="mb10">
			高性能の追求とストレージ容量の大幅な強化、タワー型サーバーで最高クラスとなるHPE ProLiant ML350 Gen10をおすすめいたします。最大7年の長期保守にも対応。<br>
			<!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" -->へお電話いただければ、ご希望の用途や環境に合わせた構成で比較のお見積をさせていただきます。
		</p>
		<div class="alignRgt lhMid"> <a href="#ContactUs" class="linkWithArrow"><!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" --><span class="arrow">→</span></a> </div>
	</div>
	<div class="optokuTable">
		<table>
			<tr>
				<th width="20%"></th>
				<th width="40%">ML110 Gen10</th>
				<th width="40%">ML350 Gen10</th>
			</tr>
			<tr class="whiteCell">
				<th>モデル</th>
				<td class="alignCtr">
					<a href="#CustomizeOrder">
						<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml110_gen10_optoku.gif" alt="" class="m0auto">
					</a>
					<a href="#CustomizeOrder" role="button" class="btn btn-secondary">モデルを選択する</a>
				</td>
				<td class="alignCtr">
					<a href="/directplus_ent/server/ml350gen10/">
						<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml350_gen10.gif" alt="" class="m0auto">
					</a>
					<a href="/directplus_ent/server/ml350gen10/" role="button" class="btn btn-secondary">モデルを選択する</a>
				</td>
			</tr>
			<tr class="gryCell">
				<th>最小構成価格(税抜)</th>
				<td class="alignCtr">
					オプ得モデル　192,000円～
					<!--通常モデル　<span class="lineThrough">252,000円～</span><br>
					<span class="bold f18">期間限定　176,000円～</span>-->
				</td>
				<td class="alignCtr">
					通常モデル　403,000円～
				</td>
			</tr>
			<tr class="whiteCell">
				<th>おすすめ用途</th>
				<td class="alignCtr">・中規模向け(～250人)<br>・Web・APサーバー<br>・中規模ファイルサーバー</td>
				<td class="alignCtr">・大規模向け(251人～)<br>・高負荷のAPサーバー<br>・仮想化プラットフォーム<br>・大規模ファイルサーバー</td>
			</tr>
			<tr class="gryCell">
				<th>プロセッサー</th>
				<td class="alignCtr">最大1基/14コア<br>インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー</td>
				<td class="alignCtr">最大2基/28コア<br>インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー</td>
			</tr>
			<tr class="whiteCell">
				<th>メモリ</th>
				<td class="alignCtr">6DIMMスロット DDR4 RDIMM</td>
				<td class="alignCtr">24DIMMスロット DDR4 RDIMM</td>
			</tr>
			<tr class="gryCell">
				<th>ドライブ</th>
				<td class="alignCtr">標準8、最大16 (2.5型 ホットプラグSAS/SATA/SSD)<br>標準4、最大8 (3.5型 ホットプラグSAS/SATA/SSD)<br>標準4、最大8 (3.5型 ノンホットプラグSATA)</td>
				<td class="alignCtr">標準8、最大24 (2.5型 ホットプラグSAS/SATA/SSD)<br>標準4、最大12 (3.5型 ホットプラグSAS/SATA/SSD)</td>
			</tr>
			<tr class="whiteCell">
				<th>拡張スロット</th>
				<td class="alignCtr">5(FH/ 3/4 L PCI Express Gen3 x16、FH/HL PCI Express Gen3 x8、FH/HL PCI Express Gen3 x16、FH/HL PCI Express Gen3 x4 x2)</td>
				<td class="alignCtr">4(FH/FL PCI Express Gen3 x16 x2、FH/FL PCI Express Gen3 x8、FH/FL PCI Express Gen3 x4) <br><span class="f12">※オプションにより最大8</span></td>
			</tr>
			<tr class="gryCell">
				<th>音響ノイズ</th>
				<td class="alignCtr">24～25dBA</td>
				<td class="alignCtr">28～32dBA</td>
			</tr>
		</table>
	</div>
</div><!-- /#Compare -->
