<h4 class="f18 bold mb5">
	お客様の業務を守る”世界標準の安心サーバー”を1ソケット機でも
</h4>
<p>
	HPE ProLiant ML110 Gen10は、“Silicon root of trust (シリコンレベルの信頼性)”を基盤に、HPE独自の電子認証によるファームウェアの更新や不正書き換えの早期認識と回復機能を備えた1ソケットのタワー型サーバーです。<br>
	ビジネスワークロードに期待される拡張性を備えるほか、静音性(24 -25dBA)にも優れており、病院、図書館、オフィス環境に最適です。
</p>
<p class="mt15">
	<a href="/directplus_ent/server/infosight_for_servers.html" class="linkWithArrow" target="_blank">HPE InfoSight for Servers 対応サーバー　詳しくはこちら<span class="arrow">→</span></a>
</p>
