<div class="specTable2Area fixedTable">
	
	<div class="specTable2 title2lines">
		<!--<div class="specTableTitle">
			<table width="1000">
			<tr>
				<th width="100"></th>
				<th width="180" class="f14">コストパフォーマンス重視</th>
				<th width="360" class="f14" colspan="2">信頼性とコストパフォーマンス</th>
				<th width="360" class="f14" colspan="2">性能・信頼性重視</th>
			</tr>
			<tr>
				<th width="100"></th>
				<th width="180" class="f20">NHP 4LFF SATA</th>
				<th width="180" class="f20">4LFF SATA</th>
				<th width="180" class="f20">4LFF SAS</th>
				<th width="180" class="f20">8SFF SATA</th>
				<th width="180" class="f20">8SFF SAS</th>
			</tr>
			</table>
		</div>-->
		<table width="1000">
			<tr>
				<th width="100"></th>
				<th width="180" class="f14">コストパフォーマンス重視</th>
				<th width="360" class="f14" colspan="2">信頼性とコストパフォーマンス</th>
				<th width="360" class="f14" colspan="2">性能・信頼性重視</th>
			</tr>
			<tr>
				<th width="100"></th>
				<th width="180" class="f20">NHP 4LFF SATA</th>
				<th width="180" class="f20">4LFF SATA</th>
				<th width="180" class="f20">4LFF SAS</th>
				<th width="180" class="f20">8SFF SATA</th>
				<th width="180" class="f20">8SFF SAS</th>
			</tr>
			<tr>
				<th></th>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml110_gen10_optoku.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml110_gen10_optoku.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml110_gen10_optoku.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml110_gen10_optoku.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml110_gen10_optoku.gif" alt="" class="m0auto">
				</td>
			</tr>
			<tr>
				<th>ドライブ</th>
				<td><span class="cutomizable">カスタマイズ可能</span><span class="bold">ノンホットプラグ 3.5型</span> 最大8<br>SATA HDD選択可</td>
				<td><span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 3.5型</span> 最大8<br>SATA HDD/SSD選択可</td>
				<td><span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 3.5型</span> 最大8<br>SAS HDD選択可</td>
				<td><span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 2.5型</span> 最大16<br>SATA HDD/SSD選択可</td>
				<td><span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 2.5型</span> 最大16<br>SAS HDD選択可</td>
			</tr>
			<tr>
				<th>プロセッサー</th>
				<td colspan="5"><span class="cutomizable2">カスタマイズ可能</span>最大1基　インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー</td>
			</tr>
			<tr>
				<th>メモリ</th>
				<td colspan="5"><span class="cutomizable2">カスタマイズ可能</span>6DIMMスロット DDR4 RDIMM</td>
			</tr>
			<tr>
				<th>パワーサプライ</th>
				<td><span class="cutomizable2" style="margin:0 0 5px;">カスタマイズ可能</span><br>標準1、最大1</td>
				<td colspan="4"><span class="cutomizable2">カスタマイズ可能</span>標準1、最大2　オプションで冗長化対応、ホットプラグ対応</td>
			</tr>
			<tr>
				<th rowspan="2"><span class="f11">Xeon x2xx搭載</span><br>最小構成価格<br>（税抜）</th>
				<td colspan="5" class="pt25" style="border-bottom: none;"><div class="bold f16">Xeon x2xx (第2世代プロセッサー) 搭載</div></td>
			</tr>
			<tr>
				<!--<th>最小構成価格<br>（税抜）</th>-->
				<td class="pt10 pb10 bgG">
					<div class="mb25">
						<span class="bold f16">オプ得モデル</span><br>
						<span class="bold f18">192,000円～</span><br>
						<span class="f12">45,000円引き～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4289&ProductSKU=BASE:15776" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14"><span class="disp_ib">カスタマイズして</span><span class="disp_ib">見積・購入</span></span></a>
					</div>
					<div>
						<span class="bold f15">通常モデル</span>
						<span class="f15">237,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4274&ProductSKU=BASE:15771" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14"><span class="disp_ib">カスタマイズして</span><span class="disp_ib">見積・購入</span></span></a>
					</div>
				</td>
				<td class="pt10 pb10 bgG">
					<div class="mb25">
						<span class="bold f16">オプ得モデル</span><br>
						<span class="bold f18">207,000円～</span><br>
						<span class="f12">45,000円引き～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4289&ProductSKU=BASE:15779" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14"><span class="disp_ib">カスタマイズして</span><span class="disp_ib">見積・購入</span></span></a>
					</div>
					<div>
						<span class="bold f15">通常モデル</span>
						<span class="f15">252,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4274&ProductSKU=BASE:15774" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14"><span class="disp_ib">カスタマイズして</span><span class="disp_ib">見積・購入</span></span></a>
					</div>
				</td>
				<td class="pt10 pb10 bgG">
					<div class="mb25">
						<span class="bold f16">オプ得モデル</span><br>
						<span class="bold f18">240,000円～</span><br>
						<span class="f12">59,000円引き～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4289&ProductSKU=BASE:15780" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14"><span class="disp_ib">カスタマイズして</span><span class="disp_ib">見積・購入</span></span></a>
					</div>
					<div>
						<span class="bold f15">通常モデル</span>
						<span class="f15">299,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4274&ProductSKU=BASE:15775" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14"><span class="disp_ib">カスタマイズして</span><span class="disp_ib">見積・購入</span></span></a>
					</div>
				</td>
				<td class="pt10 pb10 bgG">
					<div class="mb25">
						<span class="bold f16">オプ得モデル</span><br>
						<span class="bold f18">231,000円～</span><br>
						<span class="f12">45,000円引き～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4289&ProductSKU=BASE:15777" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14"><span class="disp_ib">カスタマイズして</span><span class="disp_ib">見積・購入</span></span></a>
					</div>
					<div>
						<span class="bold f15">通常モデル</span>
						<span class="f15">276,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4274&ProductSKU=BASE:15772" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14"><span class="disp_ib">カスタマイズして</span><span class="disp_ib">見積・購入</span></span></a>
					</div>
				</td>
				<td class="pt10 pb10 bgG">
					<div class="mb25">
						<span class="bold f16">オプ得モデル</span><br>
						<span class="bold f18">264,000円～</span><br>
						<span class="f12">59,000円引き～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4289&ProductSKU=BASE:15778" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14"><span class="disp_ib">カスタマイズして</span><span class="disp_ib">見積・購入</span></span></a>
					</div>
					<div>
						<span class="bold f15">通常モデル</span>
						<span class="f15">323,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4274&ProductSKU=BASE:15773" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14"><span class="disp_ib">カスタマイズして</span><span class="disp_ib">見積・購入</span></span></a>
					</div>
				</td>
			</tr>
			<tr>
				<th></th>
				<td colspan="5" class="pt10 pb15 bgW">
					<a href="pdfs/spec.pdf" target="_blank" class="linkWithArrow">
						仕様一覧はこちら（PDF）
						<span class="arrow">→</span>
					</a>
				</td>
			</tr>
		</table>
	</div><!-- /.specTable2 -->
	
</div><!-- /.specTable2Area -->