<h4 class="f18 bold mb5">
	タワー型で最高クラスのパフォーマンス。“世界標準の安心サーバー”
</h4>
<p>
	HPE ProLiant ML350 Gen10は、HPE ProLiant タワー型サーバーの中で最も高いパフォーマンスを発揮するサーバーです。<br>
	“Silicon root of trust (シリコンレベルの信頼性)”を基盤に、HPE独自の電子認証によるファームウェアの更新や不正書き換えの早期認識と回復機能を備えたほか、業界最高レベルのセキュリティ基準に対応します。<br>
	大規模システムにおける拠点向けのビジネスサーバーの中でも最上位に位置する2ソケットタワーサーバーです。
</p>
<p class="mt15">
	<a href="/directplus_ent/server/infosight_for_servers.html" class="linkWithArrow" target="_blank">HPE InfoSight for Servers 対応サーバー　詳しくはこちら<span class="arrow">→</span></a>
</p>
