<div>
	<p>
		HPE ProLiant DL360 Gen10 Plusは、最新の第3世代インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサーを最大2基搭載可能な1Uラックマウント型サーバーです。第2世代インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサーを採用したHPE ProLiant DL160 Gen10やDL360 Gen10の上位機種に位置付けられます。<br>
		高い性能を要求されるCAE、HPC、VDIワークロードに提案するサーバーとして最適な性能と機能を備えています。<br>
		またGen10と同様に管理機能iLO5を標準搭載。その特長であるSilicon root of trust (シリコンレベルの信頼性)によるセキュリティ機能をサポートし、HPE独自の電子認証によるファームウェアの更新や不正書き換えの検知と回復機能を備えています。お客様の業務を守る”世界標準の安心サーバー”の進化版です。
	</p>
	<p class="mt10">
		性能とコストのバランスを重視されるお客様には、<a href="/directplus_ent/server/dl360gen10/" class="tertiary-link">HPE ProLiant DL360 Gen10</a>をおすすめいたします。<br>
		DL360 Gen10も引き続き販売をして参ります。
	</p>
	<p class="mt15">
		<a href="/directplus_ent/server/infosight_for_servers.html" class="linkWithArrow" target="_blank">HPE InfoSight for Servers 対応サーバー　詳しくはこちら<span class="arrow">→</span></a>
	</p>
</div>
