<div class="specTable2Area fixedTable">
	<div class="specTable2 title2lines">
		<div class="specTableTitle">
			<table width="1000">
				<tr>
					<th width="100"></th>
					<th width="450" class="f14" colspan="2">信頼性とコストパフォーマンス</th>
					<th width="450" class="f14" colspan="2">性能・信頼性重視</th>
				</tr>
				<tr>
					<th width="100"></th>
					<th width="225" class="f20">4LFF SATA</th>
					<th width="225" class="f20">4LFF SAS</th>
					<th width="225" class="f20">8SFF SATA</th>
					<th width="225" class="f20">8SFF SAS</th>
				</tr>
			</table>
		</div>
		<table width="1000">
			<tr>
				<th width="100"></th>
				<th width="450" class="f14" colspan="2">信頼性とコストパフォーマンス</th>
				<th width="450" class="f14" colspan="2">性能・信頼性重視</th>
			</tr>
			<tr>
				<th width="100"></th>
				<th width="225" class="f20">4LFF SATA</th>
				<th width="225" class="f20">4LFF SAS</th>
				<th width="225" class="f20">8SFF SATA</th>
				<th width="225" class="f20">8SFF SAS</th>
			</tr>
			<tr>
				<th></th>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl360_gen10_plus.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl360_gen10_plus.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl360_gen10_plus.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl360_gen10_plus.gif" alt="" class="m0auto">
				</td>
			</tr>
			<tr>
				<th>ドライブ</th>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ LFF</span> 最大4<br>
					SATA HDD、SATA SSD選択可
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ LFF</span> 最大4<br>
					SAS HDD、SAS SSD選択可
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ SFF</span> 最大10<br>
					SATA HDD、SATA SSD選択可
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ SFF</span> 最大10<br>
					SAS HDD、SAS SSD選択可
				</td>
			</tr>
			<tr>
				<th>プロセッサー</th>
				<td colspan="4">
					<span class="cutomizable2">カスタマイズ可能</span>最大2基　インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー
				</td>
			</tr>
			<tr>
				<th>メモリ</th>
				<td colspan="4">
					<span class="cutomizable2">カスタマイズ可能</span>24DIMMスロット DDR4 RDIMM
				</td>
			</tr>
			<tr>
				<th>パワーサプライ</th>
				<td colspan="4">
					<span class="cutomizable2">カスタマイズ可能</span>標準1、最大2　オプションで冗長化対応、ホットプラグ対応
				</td>
			</tr>
			<tr>
				<th rowspan="2">最小構成価格<br>（税抜）</th>
				<td class="pt10 pb10 vTop f12" style="border-bottom: none;">
					<div>
						<span class="bold f16">通常モデル</span>
						<span class="f16">700,000円～</span><br>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4390&ProductSKU=BASE:15986" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
				<td class="pt10 pb10 vTop f12" style="border-bottom: none;">
					<div>
						<!--<span class="bold f14"><a href="#ContactUs" class="tertiary-link">お問い合わせください</a></span>-->
						<span class="bold f16">通常モデル</span>
						<span class="f16">912,000円～</span><br>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4390&ProductSKU=BASE:15987" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
				<td class="pt10 pb10 vTop f12" style="border-bottom: none;">
					<div>
						<span class="bold f16">通常モデル</span>
						<span class="f16">731,000円～</span><br>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4390&ProductSKU=BASE:15984" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
				<td class="pt10 pb10 vTop f12" style="border-bottom: none;">
					<div>
						<!--<span class="bold f14"><a href="#ContactUs" class="tertiary-link">お問い合わせください</a></span>-->
						<span class="bold f16">通常モデル</span>
						<span class="f16">1,012,000円～</span><br>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4390&ProductSKU=BASE:15985" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
			</tr>
			<tr>
				<td colspan="4" class="bgG">
					<div class="f12">本製品は受注生産のため、納品目安は受注後3か月前後となります。</div>
				</td>
			</tr>
			<tr>
				<th></th>
				<td colspan="4" class="pt10 pb15 bgW">
					<a href="pdfs/spec.pdf" target="_blank" class="linkWithArrow">
						仕様一覧はこちら（PDF）
						<span class="arrow">→</span>
				</td>
			</tr>
		</table>
	</div><!-- /.specTable2 -->

</div><!-- /.specTable2Area -->
