<div class="casestudy">
	<div class="column50-50WithBdr">
		<div class="clm1">
			<div class="column60-40Flex fixUpperTablet mb10">
				<div class="clm1 flexGutter10 f15 bold lhMid">
					<span class="disp_ib">KDDIウェブコミュニケーションズが</span><span class="disp_ib">より高性能で</span><span class="disp_ib">顧客価値の高いサービスへ</span><br>
					<span class="disp_ib">CPIレンタルサーバーの</span><span class="disp_ib">新たな進化</span>
				</div>
				<div class="clm2">
					<img src="/directplus_ent/images/thumb_casestudy_kwc.jpg" alt="株式会社KDDIウェブコミュニケーションズ 様" width="1000" height="375" class="w100per">
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					都道府県
				</div>
				<div class="clm2">
					東京都
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					業種
				</div>
				<div class="clm2">
					サーバーホスティング、Webサービス
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					ソリューション
				</div>
				<div class="clm2">
					セキュリティ
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					製品
				</div>
				<div class="clm2">
					<a href="/directplus_ent/server/dl325gen10/" class="tertiary-link">HPE ProLiant DL325 Gen10サーバー</a><br class="spHide"><br class="spHide">
				</div>
			</div>
			<div class="mt15 bgGry paddBlock10">
				<p class="f15 bold">
					製品選定のポイント
				</p>
				<p>
					「検討を進めていた当時、CPUのセキュリティ脆弱性の報告が相次いでいたことが判断に影響したのは間違いありません。セキュリティは、CPIの専用サーバーを使うお客様が最も重視するポイントのひとつだからです」
				</p>
			</div>
			<div class="alignCtr">
				<a href="https://www.hpe.com/jp/ja/customer-case-studies/servers-proliant-kwc.html" role="button" class="btn btn-secondary">詳しくはこちら</a>
			</div>
		</div>
		<div class="clm2">
			<div class="column60-40Flex fixUpperTablet mb10">
				<div class="clm1 flexGutter10 f15 bold lhMid">
					<span class="disp_ib">北海道大学 人獣共通感染症</span><span class="disp_ib">リサーチ</span><span class="disp_ib">センターが、</span><span class="disp_ib">ゲノム解析による</span><span class="disp_ib">革新的な</span><span class="disp_ib">「感染症検査法」の</span><span class="disp_ib">開発を推進</span>
				</div>
				<div class="clm2">
					<img src="/directplus_ent/images/thumb_casestudy_hokaido-uni.jpg" alt="北海道大学 人獣共通感染症リサーチセンター 様" width="1000" height="375" class="w100per">
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					都道府県
				</div>
				<div class="clm2">
					北海道
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					業種
				</div>
				<div class="clm2">
					大学・研究機関
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					ソリューション
				</div>
				<div class="clm2">
					HPC
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					製品
				</div>
				<div class="clm2">
					<a href="/directplus_ent/server/dl385gen10plus/" class="tertiary-link">2CPU/128コアのAMD EPYC<sup>&trade;</sup> プロセッサー搭載 HPE ProLiant DL385 Gen10 Plus</a>
				</div>
			</div>
			<div class="mt15 bgGry paddBlock10">
				<p class="f15 bold">
					製品選定のポイント
				</p>
				<p>
					「先行して導入した64コア機の性能に驚かされて、直後に128コア機の導入を進めた経緯があります。進化した最新のハードウェアを利用するメリットを日々実感しています」
				</p>
			</div>
			<div class="alignCtr">
				<a href="https://www.hpe.com/jp/ja/customer-case-studies/servers-proLiant-hokaido-uni.html" role="button" class="btn btn-secondary">詳しくはこちら</a>
			</div>
		</div>
	</div>
	
	<div class="column50-50WithBdr">
		<div class="clm1">
			<div class="column60-40Flex fixUpperTablet mb10">
				<div class="clm1 flexGutter10 f15 bold lhMid">
					<span class="disp_ib">業務支援サービスの</span><span class="disp_ib">ジェットが、</span><span class="disp_ib">ソフトウェアコストを</span><span class="disp_ib">削減</span><span class="disp_ib">しながら</span><span class="disp_ib">サーバー</span><span class="disp_ib">環境を</span><span class="disp_ib">高密度に</span><span class="disp_ib">集約</span>
				</div>
				<div class="clm2">
					<img src="/directplus_ent/images/thumb_casestudy_jeet.jpg" alt="ジェット 様" width="1000" height="375" class="w100per">
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					都道府県
				</div>
				<div class="clm2">
					東京都
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					業種
				</div>
				<div class="clm2">
					情報サービス
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					ソリューション
				</div>
				<div class="clm2">
					仮想化
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					製品
				</div>
				<div class="clm2">
					<a href="/directplus_ent/server/dl385gen10/" class="tertiary-link">オールSSD構成のHPE ProLiant DL385 Gen10サーバー</a><div class="spHide" style="height: 68px;"></div>
				</div>
			</div>
			<div class="mt15 bgGry paddBlock10">
				<p class="f15 bold">
					製品選定のポイント
				</p>
				<p>
					「SSDによるI/O性能の向上も加わって、アプリケーションとファイルサーバーのレスポンスを大きく改善することができました。仮想化統合で省コスト化しながら、同時に高性能化を実現できたことは大きいですね」
				</p>
			</div>
			<div class="alignCtr">
				<a href="https://www.hpe.com/jp/ja/customer-case-studies/servers-proliant-jeet.html" role="button" class="btn btn-secondary">詳しくはこちら</a>
			</div>
		</div>
		<div class="clm2">
			<div class="column60-40Flex fixUpperTablet mb10">
				<div class="clm1 flexGutter10 f15 bold lhMid">
					<span class="disp_ib">スイーツの製造</span><span class="disp_ib">・販売を行う</span><span class="disp_ib">モンテールが、</span><span class="disp_ib">BIサーバーと</span><span class="disp_ib">ファイルサーバーの</span><span class="disp_ib">システムを</span><span class="disp_ib">Gen10サーバーへ</span><span class="disp_ib">移行</span>
				</div>
				<div class="clm2">
					<img src="/directplus_ent/images/thumb_casestudy_monteur-dl325.jpg" alt="モンテール 様" width="1000" height="375" class="w100per">
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					都道府県
				</div>
				<div class="clm2">
					埼玉県
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					業種
				</div>
				<div class="clm2">
					製造
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					ソリューション
				</div>
				<div class="clm2">
					デジタルトランスフォーメーション、セキュリティ
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					製品
				</div>
				<div class="clm2">
					<a href="/directplus_ent/server/dl325gen10/" class="tertiary-link">AMD EPYC<sup>&trade;</sup> プロセッサー搭載 HPE ProLiant DL325 Gen10 サーバー</a>
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					OS、ソフトウェア
				</div>
				<div class="clm2">
					Microsoft Windows Server
				</div>
			</div>
			<div class="mt15 bgGry paddBlock10">
				<p class="f15 bold">
					製品選定のポイント
				</p>
				<p>
					「シングルプロセッサー専用サーバーならではの優れた経済性と、エンタープライズクラスのシステム要求にも十分に応えられるパフォーマンスを得ることができました」
				</p>
			</div>
			<div class="alignCtr">
				<a href="https://www.hpe.com/jp/ja/customer-case-studies/servers-proliant-monteur-dl325.html" role="button" class="btn btn-secondary">詳しくはこちら</a>
			</div>
		</div>
	</div>
	
	<div class="column50-50WithBdr">
		<div class="clm1">
			<div class="column60-40Flex fixUpperTablet mb10">
				<div class="clm1 flexGutter10 f15 bold lhMid">
					</span><span class="disp_ib">山﨑建設が、</span><span class="disp_ib">OSの</span><span class="disp_ib">サポート終了を</span><span class="disp_ib">見越し</span><span class="disp_ib">Windows&nbsp;</span><span class="disp_ib">Server&nbsp;</span><span class="disp_ib">2016への</span><span class="disp_ib">移行を</span><span class="disp_ib">BIシステムから</span><span class="disp_ib">先行して</span><span class="disp_ib">スタート</span>
				</div>
				<div class="clm2">
					<img src="/directplus_ent/images/thumb_casestudy_yamazaki.jpg" alt="山﨑建設株式会社 様" width="1000" height="375" class="w100per">
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					都道府県
				</div>
				<div class="clm2">
					東京都
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					業種
				</div>
				<div class="clm2">
					建築・建設
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					ソリューション
				</div>
				<div class="clm2">
					仮想化
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					製品
				</div>
				<div class="clm2">
					<a href="/directplus_ent/server/dl325gen10/" class="tertiary-link">HPE ProLiant DL325 Gen10 サーバー</a>
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					OS、ソフトウェア
				</div>
				<div class="clm2">
					Microsoft Windows Server 2016、Hyper-V
				</div>
			</div>
			<div class="mt15 bgGry paddBlock10">
				<p class="f15 bold">
					<!--#include virtual="/comm/include/directplus_name.inc" -->を利用して良かった点
				</p>
				<p>
					「HPE ProLiant DL325 Gen10サーバーを採用することで、サーバーの調達コストを想定の6割ほどに抑えることができました」<br class="spHide"><br class="spHide">
				</p>
			</div>
			<div class="alignCtr">
				<a href="/directplus_ent/casestudy/yamazaki.html" role="button" class="btn btn-secondary">詳しくはこちら</a>
			</div>
		</div>
		<div class="clm2">
			<div class="column60-40Flex fixUpperTablet mb10">
				<div class="clm1 flexGutter10 f15 bold lhMid">
					</span><span class="disp_ib">奈良先端科学技術大学院大学が、</span><span class="disp_ib">機械学習と</span><span class="disp_ib">クラウドソーシングの</span><span class="disp_ib">融合により</span><span class="disp_ib">多元ビッグデータ解析の</span><span class="disp_ib">応用を推進</span>
				</div>
				<div class="clm2">
					<img src="/directplus_ent/casestudy/images/naist_main.png" alt="奈良先端科学技術大学院大学 様" width="1000" height="375" class="w100per">
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					都道府県
				</div>
				<div class="clm2">
					奈良県
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					業種
				</div>
				<div class="clm2">
					教育
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					ソリューション
				</div>
				<div class="clm2">
					HPC （ハイ・パフォーマンス・コンピューティング）
				</div>
			</div>
			<div class="caseColumn mb5 cfx">
				<div class="clm1">
					製品
				</div>
				<div class="clm2">
					<a href="/directplus_ent/server/dl385gen10/" class="tertiary-link">HPE ProLiant DL385 Gen10 サーバー</a><div class="spHide" style="height: 19px;"></div>
				</div>
			</div>
			<div class="mt15 bgGry paddBlock10">
				<p class="f15 bold">
					<!--#include virtual="/comm/include/directplus_name.inc" -->を利用して良かった点
				</p>
				<p>
					「最初の問合せから2週間かからずに仕様通りのHPE ProLiant DL385Gen10サーバーが届きました。<!--#include virtual="/comm/include/directplus_name.inc" -->では手間なく発注でき納品も早いので、忙しい年度末の調達時にはとても助かります」
				</p>
			</div>
			<div class="alignCtr">
				<a href="/directplus_ent/casestudy/naist.html" role="button" class="btn btn-secondary">詳しくはこちら</a>
			</div>
		</div>
	</div>
</div>
