<div class="faq">
	<div class="questions">
		<div class="question">
			<div class="clm1 icon">
				<img src="/directplus_ent/server/amd/images/icon-people1.png" width="162" height="195" alt="" class="w100per">
			</div>
			<div class="clm2 text">
				<div class="f22 bold">
					アプリの稼働は？
				</div>
				<p>
					HPCやCAEに始まり、仮想化やDBなどビジネス系のアプリケーションの実績や技術情報なども充実してきています。
				</p>
				<p>
					<a href="https://www.amd.com/en/processors/server-tech-docs/search" target="_blank" class="linkWithArrow">AMD EPYC<sup>&trade;</sup> プロセッサー テクニカルドキュメント<span class="arrow">→</span></a>
				</p>
			</div>
		</div>
		<div class="question">
			<div class="clm1 icon">
				<img src="/directplus_ent/server/amd/images/icon-people2.png" width="84" height="251" alt="" class="w100per">
			</div>
			<div class="clm2 text">
				<div class="f22 bold">
					パフォーマンスは？
				</div>
				<p>
					第3世代のAMD EPYC<sup>&trade;</sup>を搭載するHPE ProLiantサーバーが、記録を塗り替えるパフォーマンスを実現しています。業界標準ベンチマーク値が開示されていますので、ご参照ください。
				</p>
				<p>
					<a href="https://www.hpe.com/jp/ja/solutions/amd.html" target="_blank" class="linkWithArrow">HPEとAMD EPYC<sup>&trade;</sup>– EPYCならではのパフォーマンスを提供<span class="arrow">→</span></a>
				</p>
				<p>
					<a href="https://www.amd.com/ja/products/epyc-benchmarks" target="_blank" class="linkWithArrow">AMD EPYC<sup>&trade;</sup> Processor World Records<span class="arrow">→</span></a>
				</p>
				<div class="spHide" style="height: 25px;"></div>
			</div>
		</div>
		<div class="question">
			<div class="clm1 icon">
				<img src="/directplus_ent/server/amd/images/icon-people3.png" width="111" height="251" alt="" class="w100per">
			</div>
			<div class="clm2 text">
				<div class="f22 bold">
					もっと知りたい、検証してみたい
				</div>
				<p>
					AMDプロセッサー搭載 HPE ProLiantサーバーを安心して選んでいただくために。AMDサーバーについて高いご提案スキルを持つ“HPE x AMD パートナー倶楽部”販売パートナー様でご相談を承っております。<br>
					また検証機の無償貸出を行っております。ご希望の方は以下までご連絡ください。
				</p>
				<p>
					<a href="https://www.hpe.com/jp/ja/solutions/amd-partner.html" target="_blank" class="linkWithArrow">“HPE x AMD パートナー倶楽部” 参加パートナー ご紹介<span class="arrow">→</span></a>
					<!--<a href="https://h50146.www5.hpe.com/events/seminars/info/leaving_hpe.html?id=0&url=https%3A%2F%2Fevent.on24.com%2Fwcc%2Fr%2F2172585%2F1A8056FA0E1F10FF58E33D77195F9920" target="_blank" class="linkWithArrow">オンラインセミナー「50%削減も夢じゃない！限られた予算で高性能サーバーを調達する最新テクニック」<span class="arrow">→</span></a>-->
				</p>
			</div>
		</div>
		<!--<div class="question">
			<div class="clm1 icon">
				<img src="/directplus_ent/server/amd/images/icon-people4.png" width="232" height="239" alt="" class="w100per">
			</div>
			<div class="clm2 text">
				<div class="f22 bold">
					検証してみたい
				</div>
				<p>
					検証機の無償貸出を行っております。ご希望の方は、HPE×AMDパートナー倶楽部の参加パートナー様までご連絡ください。
				</p>
				<p>
					<a href="https://www.hpe.com/jp/ja/solutions/amd-partner.html" target="_blank" class="linkWithArrow">“HPE x AMD パートナー倶楽部” 参加パートナー ご紹介<span class="arrow">→</span></a>
				</p>
			</div>
		</div>-->
	</div>
</div>
