<style>
/*grid box-card css setting begin*/
	.box {
		display: grid;
	  grid-template-columns: repeat(auto-fill,minmax(32%, 1fr));
	  border-top: 1px solid #CCC;
		justify-items: center;
	}
	.box-card {
		border-bottom: 1px solid #CCC;
    border-right: 1px dotted #CCC;
    padding: 10px;
		padding-bottom: 70px;
		position: relative;
		
	}
	.box-card .btn-position{
		position: absolute;
		width: 90%;
		margin: 0 10px 10px 10px;
  	bottom: 0px;
	}	
	.box-card .btmBtn{
		margin: 0 auto;
	}
	.box img {
    margin: 0 auto;
}
	@media only screen and (max-width: 999px){
		.box {
			grid-template-columns: repeat(auto-fill,minmax(100%, 1fr));
		}
		.box-card {
			border-right: none;
			width: 90%;
			padding-bottom: 0;
		}
		.box-card .btn-position{
			position: static;
			width: auto;
		}	
	}
	/*grid box-card css setting end*/
</style>

<div class="gen10">
	<div class="box">
		<div class="box-card">
			<div class="alignCtr">
				<h6 class="f18 bold mb10">HPE ProLiant<br>DL325 Gen10 Plus</h6>
				<p class="f12">設計を一新し、常識を変えるストレージ拡張性を実現したGen10サーバーの進化版<br class="spHide"><br class="spHide"></p>
			</div>
			<img src="/directplus_ent/server/images/gen10_lineup_dl325_gen10_plus.jpg" alt="HPE ProLiant DL325 Gen10 Plus" width="500" height="300">
			<div>
				<p class="indent-1 f12 spAlignCtr">●AMD EPYC<sup>&trade;</sup> 7002 プロセッサー・ファミリー搭載</p>
			</div>
			<div class="btn-position">
				<div class="alignCtr btmBtn mt10">
					<a href="/directplus_ent/server/dl325gen10plus/" role="button" class="btn btn-secondary">カスタマイズ・お見積</a>
				</div>
			</div>
		</div>
		<div class="box-card">
			<div class="alignCtr">
				<h6 class="f18 bold mb10">HPE ProLiant<br>DL325 Gen10 Plus v2</h6>
				<p class="f12">2プロセッサーに匹敵する性能で高コストパフォーマンスを発揮する1ソケットサーバー<br class="spHide"><br class="spHide"></p>
			</div>
			<img src="/directplus_ent/server/images/gen10_lineup_dl325_gen10_plus_v2.png" alt="HPE ProLiant DL325 Gen10 Plus v2" width="500" height="300">
			<div>
				<p class="indent-1 f12 spAlignCtr">●AMD EPYC<sup>&trade;</sup> 7003 プロセッサー・ファミリー搭載</p>
			</div>
			<div class="btn-position">
				<div class="alignCtr btmBtn mt10">
					<a href="/directplus_ent/server/dl325gen10plusv2/" role="button" class="btn btn-secondary">カスタマイズ・お見積</a>
					<!--<span class="f16 bold"><a href="#ContactUs" class="tertiary-link">お問い合わせください</a></span>-->
				</div>
			</div>
		</div>
		<div class="box-card">
			<div class="alignCtr">
				<h6 class="f18 bold mb10">HPE ProLiant<br>DL345 Gen10 Plus</h6>
				<p class="f12">データを多用するワークロードに対応可能な<br>2Uラックのストレージ容量を備えた<br>1ソケットサーバー</p>
			</div>
			<img src="/directplus_ent/server/images/gen10_lineup_dl345_gen10_plus.png" alt="HPE ProLiant DL345 Gen10 Plus" width="500" height="300">
			<div>
				<p class="indent-1 f12 spAlignCtr">●AMD EPYC<sup>&trade;</sup> 7003 プロセッサー・ファミリーまたはAMD EPYC<sup>&trade;</sup> 7002 プロセッサー・ファミリー搭載</p>
			</div>
			<div class="btn-position">
			<div class="alignCtr btmBtn mt10">
				<a href="/directplus_ent/server/dl345gen10plus/" role="button" class="btn btn-secondary">カスタマイズ・お見積</a>
				<!--<span class="f16 bold"><a href="#ContactUs" class="tertiary-link">お問い合わせください</a></span>-->
			</div>
			</div>
		</div>
	
		<div class="box-card">
			<div class="alignCtr">
				<h6 class="f18 bold mb10">HPE ProLiant<br>DL365 Gen10 Plus</h6>
				<p class="f12">高性能と高集約性を併せ持つ<br>1U2ソケットサーバーの新たなラインアップ</p>
			</div>
			<img src="/directplus_ent/server/images/gen10_lineup_dl365_gen10_plus.png" alt="HPE ProLiant DL365 Gen10 Plus" width="500" height="300">
			<div>
				<p class="indent-1 f12 spAlignCtr">●AMD EPYC<sup>&trade;</sup> 7003 プロセッサー・ファミリーまたはAMD EPYC<sup>&trade;</sup> 7002 プロセッサー・ファミリー搭載</p>
			</div>
			<div class="btn-position">
			<div class="alignCtr btmBtn mt10">
				<a href="/directplus_ent/server/dl365gen10plus/" role="button" class="btn btn-secondary">カスタマイズ・お見積</a>
				<!--<span class="f16 bold"><a href="#ContactUs" class="tertiary-link">お問い合わせください</a></span>-->
			</div>
			</div>
		</div>
		<div class="box-card">
			<div class="alignCtr">
				<h6 class="f18 bold mb10">HPE ProLiant<br>DL385 Gen10 Plus</h6>
				<p class="f12">コストパフォーマンスの常識を変える世界標準の2Uサーバーが設計を一新し、適用用途をさらに拡大</p>
			</div>
			<img src="/directplus_ent/server/images/gen10_lineup_dl385_gen10_plus.jpg" alt="HPE ProLiant DL385 Gen10 Plus" width="500" height="300">
			<div>
				<p class="indent-1 f12 spAlignCtr">●AMD EPYC<sup>&trade;</sup> 7002 プロセッサー・ファミリー搭載</p>
			</div>
			<div class="btn-position">
			<div class="alignCtr btmBtn mt10">
				<a href="/directplus_ent/server/dl385gen10plus/" role="button" class="btn btn-secondary">カスタマイズ・お見積</a>
			</div>
			</div>
		</div>
		<div class="box-card">
			<div class="alignCtr">
				<h6 class="f18 bold mb10">HPE ProLiant<br>DL385 Gen10 Plus v2</h6>
				<p class="f12">すべての領域で高い性能を発揮する<br>新世代のフラッグシップ・サーバー</p>
			</div>
			<img src="/directplus_ent/server/images/gen10_lineup_dl385_gen10_plus_v2.png" alt="HPE ProLiant DL385 Gen10 Plus v2" width="500" height="300">
			<div>
				<p class="indent-1 f12 spAlignCtr">●AMD EPYC<sup>&trade;</sup> 7003 プロセッサー・ファミリー搭載</p>
			</div>
			<div class="btn-position">
			<div class="alignCtr btmBtn mt10">
				<a href="/directplus_ent/server/dl385gen10plusv2/" role="button" class="btn btn-secondary">カスタマイズ・お見積</a>
				<!--<span class="f16 bold"><a href="#ContactUs" class="tertiary-link">お問い合わせください</a></span>-->
			</div>
			</div>
		</div>
	</div>
</div>
