<div class="logo amd">
	<div class="column40-60Flex fixUpperTablet alignItemsCtr">
		<div class="clm1">
			<img src="/directplus_ent/server/amd/images/logo.svg" alt="" class="m0auto">
		</div>
		<div class="clm2">
			<div>
				<div class="f16 bold">
					AMD EPYC<sup>&trade;</sup> プロセッサー搭載
				</div>
				<div>
					AMD、AMD Arrow のロゴ、AMD EPYC、その組み合わせは、米国および/または他の地域での Advanced Micro Devices, Inc. の商標です。
				</div>
			</div>
		</div>
	</div>
</div>
