<style>
.AmdPartner .btn-secondary{
	max-width: 460px !important;
}
</style>
<div class="amd_page_title">
	<h3 class="f24 bold"><span class="disp_ib">わかっているからこそ</span><span class="disp_ib">AMDを選ぶ、</span><span class="disp_ib">AMDだから選ぶ</span></h3>
	<div class="features-img mb10">
		<img src="/directplus_ent/server/amd/images/features.jpg" width="1000" height="238" alt="" class="w100per">
	</div>
	<div class="column50-50Flex">
		<div class="clm1 flexGutter20 gutter20">
			<div class="feature">
				<div class="flexIconColumn alignItemsCtr">
					<div class="clm1 icon icon-feature mr20">
						<img src="/directplus_ent/server/amd/images/icon-speed.png" width="132" height="87" alt="">
					</div>
					<div class="clm2">
						はやい
					</div>
				</div>
				<div class="f15 bold lhMid">
					第3世代AMD EPYC<sup>&trade;</sup> プロセッサーを搭載するHPE ProLiantサーバー、その高いパフォーマンスは業界標準ベンチマークの結果でもしっかり証明されています
				</div>
			</div>
			<div class="feature">
				<div class="flexIconColumn alignItemsCtr">
					<div class="clm1 icon icon-feature mr20">
						<img src="/directplus_ent/server/amd/images/icon-assure.png" width="122" height="118" alt="">
					</div>
					<div class="clm2">
						あんしん
					</div>
				</div>
				<div class="f15 bold lhMid mb10">
					HPEとAMDはAMD EPYC<sup>&trade;</sup> プロセッサー開発について緊密に協力しており、長期戦略に基づいて共同で進めています
				</div>
				<p class="lhMid">
					現在の第3世代まで予定通りに発表・発売されており、次の世代の開発も順調に進んでいます。今後の製品展開にぜひご期待ください。
				</p>
			</div>
		</div>
		<div class="clm2 gutter20">
			<div class="feature">
				<div class="flexIconColumn alignItemsCtr">
					<div class="clm1 icon icon-feature mr20">
						<img src="/directplus_ent/server/amd/images/icon-price.png" width="120" height="121" alt="">
					</div>
					<div class="clm2">
						お求めやすい
					</div>
				</div>
				<div class="f15 bold lhMid mb20">
					ご予算が限られる場合でも、AMD EPYC<sup>&trade;</sup> プロセッサー搭載HPE ProLiantサーバーならお求めのスペックが満たせます
				</div>
				<div class="f13 lhMid mb20 column50-50Flex fixUpperTablet">
					<div class="clm1 flexGutter20">
						<div class="flexIconColumn">
							<div class="clm1 icon mr10">
								<img src="/directplus_ent/server/amd/images/icon-cpu.png" width="128" height="128" alt="">
							</div>
							<div class="clm2">
								サーバー全体で、他社CPU搭載サーバーと比較して約30%の価格削減可能<sup>※</sup>
							</div>
						</div>
					</div>
					<div class="clm2">
						<div class="flexIconColumn">
							<div class="clm1 icon mr10">
								<img src="/directplus_ent/server/amd/images/icon-license.png" width="122" height="114" alt="">
							</div>
							<div class="clm2">
								CPU数を減らすことができ、ソフトウェアライセンス費用も圧縮可能
							</div>
						</div>
					</div>
				</div>
				<div class="f12 indent-1 lhMid">
					※売れ筋の16コア、HPE定価ベースで比較
				</div>
				<div class="f12 indent-1 lhMid">
					※2021年6月に販売している機種での比較
				</div>
			</div>
			<div class="AmdPartner alignCtr mb40">
				<div class="alignCtr mb40">
					<a href="https://www.hpe.com/jp/ja/solutions/amd-partner.html" target="_blank" role="button" class="btn btn-secondary mt0"><span class="disp_ib">AMD製品のご相談はこちらでも</span><span class="disp_ib">“HPE x AMD パートナー倶楽部“参加パートナー 一覧</span></a>
				</div>
			</div>
		</div>
	</div>
</div>
