<!-- Begin Footer Area -->
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr class="decoration">
		<td class="color666666bg"><img src="/comm/legacy/img/s.gif" width="1" height="4" alt="" border="0"></td>
	</tr>
	<tr>
		<td align="left" valign="top">
			<table border="0" cellpadding="0" cellspacing="0" width="740">
				<tr class="decoration">
					<td colspan="3"><img src="/comm/legacy/img/s.gif" width="1" height="4" alt="" border="0"></td>
				</tr>
				<tr>
					<td width="33%" align="center"><a href="https://www.hpe.com/jp/privacy" target="_blank" class="udrlinesmall">プライバシー</a></td>
					<td width="34%" align="center"><a href="https://www.hpe.com/jp/termsofuse" target="_blank" class="udrlinesmall">本サイト利用時の合意事項</a></td>
					<td width="33%" align="center"><a href="/directplus_ent/jeprime/nttrd/riyou.html" class="udrlinesmall">HP Direct for NTT R＆D 販売条件</a></td>
				</tr>
				<tr class="decoration">
					<td colspan="3"><img src="/comm/legacy/img/s.gif" width="1" height="4" alt="" border="0"></td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<!-- End Footer Area -->