<div class="mb40WithBorder">
	<a href="https://www.hpe.com/h41268/live/index_e.aspx?qid=8812" target="_blank">
	<img src="images/bnr_contact_670x184.gif" alt="" width="670" class="m0auto recipeImg">
	</a>
</div>
<div class="mb40WithBorder">
	<h3 class="f24 mb20 bold">その他のレシピはこちら！</h3>
	<div class="column50-50 cfx mb40">
		<div class="clm1">
			<div>
				<h4 class="f20 mb10 bold">ファイルサーバー</h4>
				<ul class="recipeRelatedLink pl10">
					<li><a href="/directplus_ent/recipe/001_fileserver.html"><span class="cta-link f16"><em class="icon-arrow-circle-right"></em>200人規模の大容量ファイルサーバーを上手に更新するレシピ</span></a></li>
				</ul>
			</div>
		</div>
		<div class="clm2">
			<div>
				<h4 class="f20 mb10 bold">仮想化・統合システム</h4>
				<ul class="recipeRelatedLink pl10">
					<li><a href="/directplus_ent/recipe/004_hyperv.html"><span class="cta-link f16"><em class="icon-arrow-circle-right"></em>タワー型サーバーを活かす「いまどきのHyper-V仮想化」</span></a></li>
					<li><a href="/directplus_ent/recipe/005_hyperconverged.html"><span class="cta-link f16"><em class="icon-arrow-circle-right"></em>ハイパーコンバージドインフラの使い勝手はSSDで決まる！</span></a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="column50-50 cfx">
		<div class="clm1">
			<div>
				<h4 class="f20 mb10 bold">データベースサーバー</h4>
				<ul class="recipeRelatedLink pl10">
					<li><a href="/directplus_ent/recipe/002_sqlserver.html"><span class="cta-link f16"><em class="icon-arrow-circle-right"></em>前編：SQL Server 2017 へ上手に移行するための注意点</span></a></li>
					<li><a href="/directplus_ent/recipe/003_sqlserver.html"><span class="cta-link f16"><em class="icon-arrow-circle-right"></em>後編：サーバー選びでSQL Server 2017 移行の成否が決まる</span></a></li>
					<li><a href="/directplus_ent/recipe/006_sqlserver.html"><span class="cta-link f16"><em class="icon-arrow-circle-right"></em>データベース性能向上のための即効レシピ！</span></a></li>
				</ul>
			</div>
		</div>
		<div class="clm2">
			<!--<div>
				<h4 class="f20 mb10 bold">業務アプリケーション</h4>
			</div>-->
		</div>
	</div>
	<div class="alignRgt mt20"><a href="/directplus_ent/recipe/" class="cta-link"><em class="icon-arrow-circle-right"></em>HPE サーバーレシピ TOPへ</a></div>
</div>
	