<div class="spBnrArea mb40">
						<a href="https://www.hpe.com/h41268/live/index_e.aspx?qid=8812" target="_blank">
							<img src="images/bnr_contact_670x184.gif" alt="" width="670" class="m0auto recipeImg">
						</a>
					</div>
					<div class="bgGry paddBlock20 mb40">
						<h4 class="f18 mb5">HPE サーバーレシピとは？</h4>
						<p>
							サーバーを導入/更新するにあたって、必要な情報は多々あります。ハードウェアの仕様、最新技術、ソフトウェアのサポート情報、ソフトウェアのライセンスや実際に求める環境に合わせたサイジング、等々。“HPE サーバーレシピ”は、日本ヒューレット・パッカードのスペシャリストが“キュレーター”としてオススメする構成を用意し、情報をまとめたものです。ぜひご参考ください。
						</p>
					</div>