<div class="recipeRightNavBnr">
						<ul class="cfx">
							<li><a href="http://www.hpe.com/jp/partners/"><img src="images/cta_banner_02.jpg" alt="サーバーのご相談はHPE販売店へ！頼りになるHPE販売パートナー" width="170"></a></li>
							<li><a href="/products/servers/proliant/os/win_bundleplus.html"><img src="images/rok_banner.png" alt="Windows Server ROK サーバー買うならOEM版Windows" width="170"></a></li>
						</ul>
					</div>
					<div class="mb40">
						<div class="mb10">
							<a href="https://twitter.com/HPEJapan" target="_blank"><span class="cta-link f16"><em class="icon-arrow-circle-right"></em>Twitter</span></a>
						</div>
						<div>
							<a href="https://www.facebook.com/HPEJapan" target="_blank"><span class="cta-link f16"><em class="icon-arrow-circle-right"></em>Facebook</span></a>
						</div>
					</div>