<!--ダウンリスト用CSS-->
<style>
<!--
/* 見た目調整の為追記 */
.pageLayoutWide #mainBody, .pageLayoutWide #enhancedPageBody, .pageLayoutWide #copyright, .pageLayoutWide #footer, .pageLayoutWide #topBar { width: 100%; }
#headerTopBar { margin:0 auto; }
.pageLayoutWide #tabSearchArea { margin:0 auto; }
.pageLayoutWide #stretchLogoWithPageTitleBlack { margin: 0 auto 5px; }
.header .sub_menu_wrapper { z-index:4;}
.header .searchSubmit{ padding-right:0 !important; }
.header .wm_no_widgets .searchBox, .header .wm_no_widgets .search_container_active .searchBox { width: 223px !important; }
#searchBox { padding-bottom2px!important; padding-left:10px!important; margin-left:3px!important; }

#mainBody { margin: 0 auto; width:100% !important; }
#topBar { overflow: visible; margin: 0 auto;}
#breadcrumbsReserved #breadcrumbs { margin: 7px auto 10px !important; z-index:0; width: 974px !important; }
.pageLayoutWide #titleArea { margin:0 auto; }
#wo_nav1 { height:31px  !important; }
#wo_nav1 .wo_nav1-main { height:11px !important; }

.pageLayoutWide #featured .ui-tabs-panel { z-index:2 !important;}
.pageLayoutWide .mega_menu { z-index:1 !important;}
#enhancedPageBody { margin:0 auto; width:974px !important; }
#main_slide_box { z-index:0;}
.pageLayoutWide #footer{ width:100% !important;}


/* 見た目調整の為追記 */

#body #mega_nav {
	background: #000000;
	width: 100%;
}
#mega_nav .mega_nav_content {
	border-left: 1px solid #FFFFFF;
	width: 973px;
	margin: 0 auto;
	height: 31px;
}
#wo_nav1 {
    background: #000000;
    height: 2.6em;
    margin: 0;
    padding: 0;
    position: relative;
    width: 974px;
}
#wo_nav1 .wo_nav1-main {
	display: block;
	float: left;
	height: 14px;
	padding: 10px 16px;
	color: #FFFFFF;
	text-decoration: none;
	font-weight: bold;
    border-right: 1px solid #FFFFFF;
}
#wo_nav1 .wo_nav1-main:last-child {
    border-right: 1px solid #FFFFFF;
}
.wo_nav1-main:hover, .wo_nav1-main.active {
	color: #F2F2F2;
	background: #35383c;
}
#wo_nav1 .phone_shop {
	font-weight: bold;
	color: #ccc;
	border-right: 2px solid #000;
	padding-right: 10px;
	margin: 8px 10px 0 24px;
	float: left;
	letter-spacing: .1em;
}
#wo_nav1 .phone_shop img {
	vertical-align: middle;
}


.mega_menu {
	border-top: 1px solid #666666;
 	background: url(/directplus_ent//system/common_img/bg_mega-menu_b.png) left bottom repeat-x;
	padding-bottom:5px;
	width: 100%;
	position: absolute;
	z-index: 2000;
	display: none;
	left:0;
}
.mega_menu li {
	background: url(/directplus_ent/system/common_img/workstations_nav_bullet.png) no-repeat scroll 2px 7px transparent;
	width: 100%;
	padding: 2px 0 2px 13px;
	float: left;
	list-style-type:none;
}
.mega_menu .nav_section {
	float: left;
	margin-top: 10px;
	font-weight: bold;
}
.mega_menu a {
	color: #a4a5a7;
	width: 100%;
	float: left;
}
.mega_menu a:hover {
	color: #fff;
}
.mega_menu ul.alpha {
	margin-left: 0px;
}
.navigation_center {
	margin: 0 auto;
	width: 945px;
}
.mega_menu .nav_section {
	color: #fff;
}
.mega_menu .nav_section .spacer {
	height: 0px;
	border-top: 1px solid #232428;
	border-bottom: 1px solid #434448;
	margin: 5px 0;
}
.mega_menu .nav_section.alpha {
	width: 310px;
}
.mega_menu .nav_section.alpha .spacer {
	width: 290px;
}
.mega_menu .nav_section.beta {
	width: 230px;
}
.mega_menu .nav_section.beta .spacer {
	width: 210px;
}
.mega_menu .nav_section.gamma {
	width: 934px;
}
.mega_menu .nav_section.gamma .spacer {
	width:914px;
}
.mega_menu .nav_section.gamma ul.alpha {
	width: 510px;
	float: left;
	padding-left: 0;
	margin-right: 20px;
	padding-bottom:20px;
}

.mega_menu .nav_section.gamma ul.alpha2{
width:364px;
}
 
.mega_menu .nav_section.gamma ul.alpha .top_border{
	border-top: 1px solid #434448;
	margin-top:7px;
	padding-top:9px;
	background-position:2px 12px;
}




/* スペック表 タブあり新テンプレートの1つ前用 */
#spec_table {border-collapse: separate; border-spacing: 3px 2px; background-color:#FFFFFF;}
#spec_table td{border:solid 1px #CCC; border-style: none none solid dotted; padding: 15px 5px;}
#spec_table tr.spec_ttlarea td{padding: 0px 2px; border:none; color:#0066FF; border-bottom:#99CCFF 2px solid; border-right:#FFFFFF 2px solid; border-left:#FFFFFF 2px solid;}
#spec_table tr td.no_border{border:none;}
#spec_table tr.spec_ttlarea td h2{color:#0066FF;}
#spec_table col.spec_firstarea{padding: 0px 2px; border:none;}
#spec_table td.spec_space{padding:0; border:none;}
#spec_table tr{background:#FFFFFF;}
#spec_table td{background:#FFFFFF;}


-->
</style>
<!--/ダウンリスト用CSS-->