			<table border="0" cellspacing="0" cellpadding="0" summary="intel">
				<tr valign="top">
					<td><span class="small">※</span></td>
					<td><span class="small">Intel、インテル、Intel ロゴ、Intel Inside、Intel Inside ロゴ、Intel Atom、Intel Atom Inside、Intel Core、Core Inside、Intel vPro、vPro Inside、Celeron、Celeron Inside、Itanium、Itanium Inside、Pentium、Pentium Inside、Xeon、Xeon Phi、Xeon Inside、Ultrabook は、アメリカ合衆国および/またはその他の国における Intel Corporation の商標です。</span></td>
				</tr>
			</table>
