			<table border="0" cellspacing="0" cellpadding="0">
				<tr valign="top">
					<td><span class="small">※</span></td>
					<td><span class="small">本ページに掲載される<!--#include virtual="/comm/include/directplus_name.inc" -->価格には配送料は含まれておりません。ご購入の際には別途配送料がかかりますので、あらかじめご了承ください。</span></td>
				</tr>
			</table>
<br><table border="0" cellpadding="15" cellspacing="0" width="100%">
<tr>
<td><div class="prodText textLevelB">
<span class="small">Windows 8 と Windows 8.1 の機能を最大限に利用するために、システムには、アップグレードされたハードウェアか個別に購入したハードウェア、ドライバ、および/またはソフトウェアのいずれか、またはその両方が必要になる場合があります。<br>
また、Windows 8 と Windows 8.1 の全バージョンで全ての機能を利用できるわけではありません。詳しくは、<a href="http://windows.microsoft.com/ja-JP/" target="_blank" class="udrline">http://windows.microsoft.com/ja-JP/</a> を参照してください。</span></div></td>
</tr>
</table>