<!-- Begin Search Area -->
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td align="left" valign="top" bgcolor="#E7E7E7">
			<table border="0" cellpadding="0" cellspacing="0" width="740">
				<tr>
					<td width="20" valign="top"><img src="/comm/legacy/img/s.gif" width="20" height="48" alt="" class="decoration"></td>
					<td width="150" align="left" valign="middle"><span class="linkarrowbold">≫&nbsp;</span><!-- Activate Contact Link Here --><a href="/directplus_ent/contact/" class="smallbld">お問い合わせ</a><!-- End Activate Contact Link Here --></td>
					<td width="570" align="right"><form method="GET">
						<!--以下のタグに適切な値を挿入する-->
						<input type="hidden" name="cc" value="jp">
						<input type="hidden" name="lang" value="ja">
						<input type="hidden" name="hps" value="<!--#include virtual="/comm/include/directplus_name.inc" -->内">
						<input type="hidden" name="hpn" value="<!--#include virtual="/comm/include/directplus_name.inc" -->に戻る">
						<input type="hidden" name="qp" value="url:directplus -url:directpartner -url:directreseller -url:resellerplus -url:advantageplus -url:advantageplus_fp -url:jeprime -url:sony -url:epp">
						<input type="hidden" name="hpr" value="/directplus_ent/">
						<input type="hidden" name="hpa" value="/directplus_ent/contact/">
						<table border="0" cellpadding="0" cellspacing="0" align="right">
							<tr class="decoration">
								<td colspan="4"><img src="/comm/legacy/img/s.gif" width="1" height="2" alt="" border="0"></td>
							</tr>
							<tr>
								<td align="left" class="bold"><label for="textbox1">検索:</label></td>
								<td valign="top"><img src="/comm/legacy/img/s.gif" width="4" height="1" alt="" class="decoration"></td>
								<td align="left" valign="top"><input type="text" name="qt" size="26" maxlength="1991" id="textbox1" alt="検索キーワードをここに入力してください"><img src="/comm/legacy/img/s.gif" width="4" height="1" alt=""><a id="country" onmouseover="status='指定した条件で検索';return true;" onmouseout="status='';return true;" onFocus="status='指定した条件で検索';return true;" onBlur="status='';return true;"><input type="Image" name="submit" src="/comm/legacy/img/hpweb_1-2_arrw_sbmt.gif" border="0" alt="検索開始"></a><!-- <img src="/comm/legacy/img/s.gif" width="13" height="1" alt="" border="0"><a href="ENTER HERE" class="udrlinesmall">検索のヒントと例</a> --></td>
								<td align="left"><img src="/comm/legacy/img/s.gif" width="20" height="1" alt="" class="decoration"></td>
							</tr>
							<tr>
								<td></td>
								<td align="left" colspan="3" class="small"><div><!--BEGIN SEARCH HPL TAG --><input type="radio" value="1" name="hpl" checked class="srchradbtn" id="sectionRadio">
								<label for="sectionRadio"><span class="bold"><!--#include virtual="/comm/include/directplus_name.inc" -->内</span></label>
								<input type="radio" value="0" name="hpl" id="countryRadio" class="srchradbtn"><label for="countryRadio"><!--#include virtual="/comm/include/company_name_body.inc" -->サイト内</label><!-- END SEARCH HPL TAG --></div></td>
							</tr>
						</table></form>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<!-- End Search Area -->