<!-- Begin Top Navigation Area -->
<table border="0" cellpadding="0" cellspacing="0" width="740">
	<tr class="decoration">
		<td width="10"><a href="#jumptocontent"><img src="/comm/legacy/img/s.gif" width="10" height="1" alt="Jump to content" border="0"></a><noscript><a href="/comm/pages/noscript.html">サイト全体に関わるJavaScriptの機能の概要</a></noscript></td>
		<td align="left" width="260" class="smallbold"><!-- Welcome, 123456789012345678901234567890... --></td>
		<td><img src="/comm/legacy/img/s.gif" width="10" height="24" alt="" border="0"></td>
		<td align="left" width="155" class="color003366"><!-- &raquo;&nbsp;<a href="Insert_Link_Here" class="small">Sign-out</a>&nbsp;<span class="color666666">|</span>&nbsp;&raquo;&nbsp;<a href="Insert_Link_Here" class="small">Edit your profile</a> --></td>
		<td align="right" width="285" class="countryInd">日本-日本語</td>
		<td><img src="/comm/legacy/img/s.gif" width="20" height="1" alt=""></td>
	</tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td align="left" valign="top" bgcolor="#666666">
			<table border="0" cellpadding="0" cellspacing="0" width="720">
				<!--#include virtual="/comm/include/globalnav.inc" -->
			</table>
		</td>
	</tr>
</table>
<!-- End Top Navigation Area -->
