<div id="Campaign">
	<h4 class="bold f24 alignCtr mb20">現在実施中のキャンペーン</h4>
	<!--<div class="column33-66 cfx mb20">
		<div class="clm1">
			<a href="/directplus_ent/promotion/amazongift/"><img src="/directplus_ent/images/banners/bnr_400x90_amazongift_campaign.jpg" width="290" class="m0auto" alt="お見積でもらえる、ギフト券がもらえる"></a>
		</div>
		<div class="clm2">
			<div class="mb15">
				<div class="lhMid mb5">
					HPE DirectPlusでお見積、抽選で100名様に1,000円分のAmazonギフト券プレゼント
				</div>
				
				<div class="bold f16 mb5">
					2021年10月29日（金）17：00お申込み分まで
				</div>
			</div>
			
			<p class="alignRgt"><a href="/directplus_ent/promotion/amazongift/" class="cta-link"><em class="icon-arrow-circle-right"></em>「お見積でもらえる、ギフト券がもらえるキャンペーン」の詳細はこちら</a></p>
		</div>
	</div>-->
	<div class="column33-66 cfx">
		<div class="clm1">
			<img src="/directplus_ent/images/banners/bnr_400x90_it_asap_campaign.jpg" width="290" class="m0auto" alt="HPEサーバー&amp;ストレージ “ITの準備はお早めに”キャンペーン">
		</div>
		<div class="clm2">
			<div class="lhMid mb5">
				キャンペーンモデルのHPE ProLiant Gen10サーバー本体および内蔵オプション、UPS、StoreEasy、MSAストレージが<span class="bold f20">30%OFF</span><!--<br>
				メモリ、HDD/SSDが<span class="bold f20">50%OFF</span><br>
				さらにHPEプロアクティブケアも<span class="bold f20">15%OFF</span>-->
			</div>
			
			<div class="bold f16 mb5">
				2022年3月31日（木）お申し込み分まで
			</div>
			
			<div class="f14 lh24 mb5">
				対象製品：
				<a href="/directplus_ent/optoku/ml110gen10/" class="tertiary-link">ML110 Gen10</a>、<a href="/directplus_ent/server/dl325gen10plus/" class="tertiary-link">DL325 Gen10 Plus</a>、<a href="/directplus_ent/server/dl360gen10/" class="tertiary-link">DL360 Gen10</a>、<a href="/directplus_ent/storage/?hash=StoreEasy" class="tertiary-link">StoreEasy 1460</a>、<a href="/directplus_ent/storage/?hash=StoreEasy" class="tertiary-link">StoreEasy 1560</a>、<a href="/directplus_ent/storage/?hash=MSA" class="tertiary-link">MSAストレージ</a>
			</div>
			
			<p class="f16 lhMid bold indent-1 mt15">
				※本サイトでは「キャンペーンモデル」にて、キャンペーン価格で即時お見積・ご注文いただけます。
			</p>
		</div>
	</div>
</div>
