<div class="lineupSelector mb30">
	<div class="clm1 alignCtr">
		<div class="imgWrapper">
			<img src="images/lineup_selector_storeeasy1460.jpg" width="630" height="230" class="lineupImg" alt="">
		</div>
		<div class="lineupSelectorText bgGry">
			<div class="label">
				StoreEasy 1460
			</div>
			<div class="text">
				<span class="disp_ib">小規模環境向け</span><span class="disp_ib">ファイルサーバー</span>
			</div>
		</div>
	</div>
	<div class="clm2 alignCtr">
		<div class="imgWrapper">
			<img src="images/lineup_selector_storeeasy1560.jpg" width="630" height="230" class="lineupImg" alt="">
		</div>
		<div class="lineupSelectorText bgGry">
			<div class="label">
				StoreEasy 1560
			</div>
			<div class="text">
				<span class="disp_ib">オフィス環境向け</span><span class="disp_ib">エントリー</span><span class="disp_ib">ファイルサーバー</span>
			</div>
		</div>
	</div>
	<div class="clm3 alignCtr">
		<div class="imgWrapper">
			<img src="images/lineup_selector_storeeasy1660.jpg" width="630" height="230" class="lineupImg" alt="">
		</div>
		<div class="lineupSelectorText bgGry">
			<div class="label">
				StoreEasy 1660
			</div>
			<div class="text">
				<span class="disp_ib">中～大規模向け</span><span class="disp_ib">ファイルサーバー</span>
			</div>
		</div>
	</div>
</div>
