<h3 class="f20 bold dashed-text" id="RDX">HPE RDXラインアップ</h3>
<div class="lineuplist rdx mb20">
	<div class="lineuplist__bodyWrapper">
		<div class="lineuplist__body">
			<div class="lineuplist__body__y">
				<span>H</span><span>D</span><span>D</span>容量
			</div>
			<!--<div class="lineuplist__body__x">
				
			</div>-->
			<div class="lineuplist__main">
				<div class="lineuplist__item__groups">
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<a class="lineuplist__item" href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=nZoQ8gQ0zgcAAAEoKhko2Te3&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/storage/images/lineup_rdx_500gb.jpg" alt="" width="111" height="78.5">
									</div>
									<div class="lineuplist__item__name">
										<span class="bold">500GB</span><br>
										カートリッジのみ - Q2042A
									</div>
								</a>
							</div>
						</div>
					</div>
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<a class="lineuplist__item" href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=nZoQ8gQ0zgcAAAEoKhko2Te3&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/storage/images/lineup_rdx_1tb.jpg" alt="" width="111" height="78.5">
									</div>
									<div class="lineuplist__item__name">
										<span class="bold">1TB</span><br>
										カートリッジのみ - Q2044A
									</div>
								</a>
							</div>
						</div>
					</div>
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<a class="lineuplist__item" href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=nZoQ8gQ0zgcAAAEoKhko2Te3&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/storage/images/lineup_rdx_2tb.jpg" alt="" width="111" height="78.5">
									</div>
									<div class="lineuplist__item__name">
										<span class="bold">2TB</span><br>
										カートリッジのみ - Q2046A
									</div>
								</a>
							</div>
						</div>
					</div>
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<a class="lineuplist__item" href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=nZoQ8gQ0zgcAAAEoKhko2Te3&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/storage/images/lineup_rdx_4tb.jpg" alt="" width="111" height="78.5">
									</div>
									<div class="lineuplist__item__name">
										<span class="bold">4TB</span><br>
										カートリッジのみ - Q2048A
									</div>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="lineuplist__body-common gryBdr4px">
			<div class="mr50">
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=nZoQ8gQ0zgcAAAEoKhko2Te3&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">
					<span class="bold">外部ドック</span> - C8S07B
				</a>
			</div>
			<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=nZoQ8gQ0zgcAAAEoKhko2Te3&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">
				<img src="/directplus_ent/storage/images/lineup_rdx_dock.jpg" alt="" width="88" height="68.5">
			</a>
		</div>
	</div>
</div>

<div class="alignCtr">
	<div class="f16 bold lhMid alignCtr mb10">
		<span class="disp_ib">RDXドライブ/メディアの</span><span class="disp_ib">お見積・ご購入はこちら</span>
	</div>
	<div class="alignCtr">
		<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=nZoQ8gQ0zgcAAAEoKhko2Te3&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3" role="button" class="btn btn-secondary mt0">お見積・ご購入はこちら</a>
	</div>
</div>