<div class="lineupSelector mb30">
	<div class="clm1 alignCtr">
		<div class="imgWrapper">
			<img src="images/lineup_selector_lto.jpg" width="630" height="230" class="lineupImg" alt="">
		</div>
		<div class="lineupSelectorText bgGry">
			<div class="label">
				LTO テープドライブ
			</div>
			<div class="text">
				<div>サーバー単体のバックアップに</div>
				<div class="bold mb5">最大30TB<sup class="f12">※</sup></div>
				<div>セキュリティ―ハードウェア暗号化ソリューション（LTO8、LTO7、LTO6、LTO5）</div>
				<div>管理性―テープドライブとメディアをプロアクティブに監視するTapeAssureツール</div>
				<div>利便性―テープの使い勝手をディスクと同様に簡単にするLTFSを実装したHPE StoreOpen</div>
			</div>
		</div>
		<div class="f12 alignRgt pt0 pb0">
			※ LTO8使用の場合(圧縮率 2.5:1)
		</div>
	</div>
</div>
