<div class="column33-33-33WithBdr lineup cfx mb20WithBorder">
	<div class="clm1 alignCtr">
		<div class="paddBlock15">
			<p class="f18 lhMid">ファイルサーバー<br>HPE StoreEasy</p>
			<a href="#StoreEasy"><img src="images/icon_storage-storeeasy.jpg" width="150" class="m0auto" alt=""></a>
			<a href="#StoreEasy" role="button" class="btn btn-secondary">ラインアップを見る</a>
		</div>
	</div>
	<div class="clm2 alignCtr">
		<div class="paddBlock15">
			<p class="f18 lhMid">共有ストレージ<br>HPE MSA</p>
			<a href="#MSA"><img src="images/icon_storage-msa.jpg" width="150" class="m0auto" alt=""></a>
			<a href="#MSA" role="button" class="btn btn-secondary">ラインアップを見る</a>
		</div>
	</div>
	<div class="clm3 alignCtr">
		<div class="paddBlock15">
			<p class="f18 lhMid">バックアップ<br>HPE StoreEver / HPE RDX</p>
			<a href="#LTO"><img src="images/icon_storage-storeever.jpg" width="150" class="m0auto" alt=""></a>
			<a href="#LTO" role="button" class="btn btn-secondary">ラインアップを見る</a>
		</div>
	</div>
</div>
