<h3 class="bold dashed-text f20"><span class="disp_ib">HPE StoreEver&nbsp;</span><span class="disp_ib">LTO&nbsp;</span><span class="disp_ib">Ultrium</span><span class="disp_ib">テープドライブ</span><span class="disp_ib">ラインアップ</span></h3>
<div class="lineuplist lto">
	<div class="lineuplist__bodyWrapper">
		<div class="lineuplist__body">
			<div class="lineuplist__body__y">
				容量
			</div>
			<div class="lineuplist__body__x">
				性能
			</div>
			<div class="lineuplist__abs_item">
				<div class="inner">
					<div class="lineuplist__items">
						<a class="lineuplist__item" href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=oUIQpABQEz8AAAD_kuXGXGLG&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">
							<div class="lineuplist__item__img">
								<img src="/directplus_ent/storage/images/lineup_lto-8_ultrium_rw_data_cartridge.jpg" alt="" width="155.5" height="86">
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="lineuplist__main">
				<div class="lineuplist__item__groups">
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<a class="lineuplist__item" href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=L9QQ8gQ0z9UAAAEoK.Qo2Te3&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/storage/images/lineup_lto-5_ultrium_3000.jpg" alt="" width="144.5" height="59.5">
									</div>
									<div class="lineuplist__item__name">
										<span class="bold">LTO-5 Ultrium 3000</span>, HH<br>
										容量 3TB <sup>*</sup><br>
										転送レート 280MB/s<sup>*</sup>
									</div>
								</a>
							</div>
						</div>
					</div>
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<a class="lineuplist__item" href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=L9QQ8gQ0z9UAAAEoK.Qo2Te3&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/storage/images/lineup_lto-6_ultrium_6250.jpg" alt="" width="145.5" height="60">
									</div>
									<div class="lineuplist__item__name">
										<span class="bold">LTO-6 Ultrium 6250</span>, HH<br>
										容量 6.25TB <sup>*</sup><br>
										転送レート 400MB/s<sup>*</sup>
									</div>
								</a>
							</div>
						</div>
					</div>
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<a class="lineuplist__item" href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=L9QQ8gQ0z9UAAAEoK.Qo2Te3&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/storage/images/lineup_lto-7_ultrium_15000.jpg" alt="" width="145.5" height="60">
									</div>
									<div class="lineuplist__item__name">
										<span class="bold">LTO-7 Ultrium 15000</span>, HH<br>
										容量 15TB <sup>*</sup><br>
										転送レート 750MB/s<sup>*</sup>
									</div>
								</a>
							</div>
						</div>
					</div>
					<div class="lineuplist__item__group">
						<div class="inner">
							<div class="lineuplist__items">
								<a class="lineuplist__item" href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=L9QQ8gQ0z9UAAAEoK.Qo2Te3&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">
									<div class="lineuplist__item__img">
										<img src="/directplus_ent/storage/images/lineup_lto-8_ultrium_30750.jpg" alt="" width="145.5" height="60">
									</div>
									<div class="lineuplist__item__name">
										<span class="bold">LTO-8 Ultrium 30750</span>, HH<br>
										容量 30TB <sup>*</sup><br>
										転送レート 750MB/s<sup>*</sup>
									</div>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="lto lineuplist__body__x_outer">性能<div class="mb10 pcHide"></div></div>

<div class="f12 indent-2 mb20">
	* 圧縮時の容量および最大転送レート<br>
	圧縮比は、LTO-6/7/8が 2.5:1、LTO3/4/5 が 2:1
</div>

<div class="column50-50WithBdr choices mb40">
	<div class="clm1">
		<div class="inner">
			<div class="f16 bold lhMid alignCtr mb10">
				<span>HPE StoreEver&nbsp;</span><span>LTO&nbsp;</span><span>Ultrium</span><span>テープドライブ</span><br class="spHide"><span>の</span><br class="br320"><span>お見積・ご購入は</span><span>こちら</span>
			</div>
			<div class="alignCtr">
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=L9QQ8gQ0z9UAAAEoK.Qo2Te3&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3" role="button" class="btn btn-secondary mt0">お見積・ご購入はこちら</a>
			</div>
		</div>
	</div>
	<div class="clm2">
		<div class="inner">
			<div class="f16 bold lhMid alignCtr mb10">
				<span>HPE StoreEver&nbsp;</span><span>LTO&nbsp;</span><span>LTOメディア</span><br class="spHide"><span>の</span><br class="br320"><span>お見積・ご購入は</span><span>こちら</span>
			</div>
			<div class="alignCtr">
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=oUIQpABQEz8AAAD_kuXGXGLG&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3" role="button" class="btn btn-secondary mt0">お見積・ご購入はこちら</a>
			</div>
		</div>
	</div>
</div>
