<div class="lineupSelector mb30">
	<div class="clm1 alignCtr">
		<div class="lineupSelectorTitle">
			コスト重視
		</div>
		<div class="imgWrapper">
			<img src="images/lineup_selector_msa1060.jpg" width="630" height="230" class="lineupImg" alt="フラッシュ対応">
		</div>
		<div class="lineupSelectorText bgGry">
			<div class="label">
				MSA 1060<br class="br767">ストレージ
			</div>
			<div class="text">
				HPEで最も手頃な<br>
				エントリーSANアレイ
			</div>
		</div>
	</div>
	<div class="clm2 alignCtr">
		<div class="lineupSelectorTitle">
			オールラウンド
		</div>
		<div class="imgWrapper">
			<img src="images/lineup_selector_msa2060.jpg" width="630" height="230" class="lineupImg" alt="フラッシュ対応">
		</div>
		<div class="lineupSelectorText bgGry">
			<div class="label">
				MSA 2060<br class="br767">ストレージ
			</div>
			<div class="text">
				前世代と同等価格で<br>
				より高いパフォーマンス
			</div>
		</div>
	</div>
	<div class="clm3 alignCtr">
		<div class="lineupSelectorTitle">
			性能重視
		</div>
		<div class="imgWrapper">
			<img src="images/lineup_selector_msa2062.jpg" width="630" height="230" class="lineupImg" alt="ハイブリッドフラッシュ">
		</div>
		<div class="lineupSelectorText bgGry">
			<div class="label">
				MSA 2062<br class="br767">ストレージ
			</div>
			<div class="text">
				すべてのライセンス導入済<br>
				ハイパフォーマンスモデル
			</div>
		</div>
	</div>
</div>
