<!-- Start MSA 1060 -->
<div class="mb40">
	<div class="productLineupItemWithThumb" id="MSA1060">
		<p class="f24 lhMid">コスト重視　エントリー共有ストレージ</p>
		<h4 class="f18 mb10">HPE MSA 1060</h4>
		<div class="column66-33 cfx">
			<div class="clm1">
				<div class="productLineupThumb mt20">
					<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15981"><img src="/directplus_ent/storage/images/lineup_thumb_msa1060.jpg" alt=""></a>
				</div>
				<div class="productLineupTxt mb20">
					<ul class="listC">
						<li>コスト意識の非常に高いお客様のニーズにも対応する、手頃な価格の共有ストレージ</li>
						<li>SASホストインターフェイスを使用することで、高価なスイッチを使わずにサーバーに直接接続</li>
						<li>HPE ProLiantサーバー向けの標準外付けエントリーストレージ</li>
					</ul>
				</div>
				<p class="f12 indent-1 mb20">
					※画像は構成によって実際の製品と異なる場合があります
				</p>
			</div>
			<div class="clm2 alignCtr">
				<p class="rbpType">12Gb SAS SFF Storage</p>
				<p class="bold alignCtr f16">通常モデル</p>
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15981" role="button" class="btn btn-secondary mt0"><span class="bold f15">950,000円</span>(税抜)～</a>
			</div>
		</div>
	</div>
</div>
<!-- End MSA 1060 -->

<!-- Start MSA 2060 -->
<div class="mb40">
	<div class="productLineupItemWithThumb" id="MSA2060">
		<p class="f24 lhMid">オールラウンド　エントリー共有ストレージ</p>
		<h4 class="f18 mb10">HPE MSA 2060</h4>
		<div class="column66-33 cfx">
			<div class="clm1">
				<div class="productLineupThumb mt20">
					<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15982"><img src="/directplus_ent/storage/images/lineup_thumb_msa2060.jpg" alt=""></a>
				</div>
				<div class="productLineupTxt mb20">
					<ul class="listC">
						<li>小規模環境とリモートオフィス環境のアプリケーションを低コストで高速化</li>
						<li>SSDとHDDを任意に組み合わせることで必要に応じて拡張</li>
						<li>MSA-DP+により、可用性を向上させ、RAIDのリビルド時間を劇的に削減<sup>*</sup></li>
					</ul>
				</div>
				<p class="f12 indent-1 mb20">
					※画像は構成によって実際の製品と異なる場合があります
				</p>
			</div>
			<div class="clm2 alignCtr">
				<p class="rbpType">10GbE iSCSI SFF Storage</p>
				<p class="bold alignCtr f16">通常モデル</p>
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15982" role="button" class="btn btn-secondary mt0"><span class="bold f15">1,400,000円</span>(税抜)～</a>
			</div>
		</div>
	</div>
</div>
<!-- End MSA 2060 -->

<!-- Start MSA 2062 -->
<div class="mb30">
	<div class="productLineupItemWithThumb" id="MSA2062">
		<p class="f24 lhMid">性能重視　エントリー共有ストレージ</p>
		<h4 class="f18 mb10">HPE MSA 2062</h4>
		<div class="column66-33 cfx">
			<div class="clm1">
				<div class="productLineupThumb mt20">
					<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15983"><img src="/directplus_ent/storage/images/lineup_thumb_msa2060.jpg" alt=""></a>
				</div>
				<div class="productLineupTxt mb20">
					<ul class="listC">
						<li>SSDを2台標準搭載。SSDによるリードキャッシュ拡張や自動階層化により、ワークロードの変化に動的に対応</li>
						<li>FC接続により、拡張性と信頼性を向上</li>
						<li>MSA-DP+により、可用性を向上させ、RAIDのリビルド時間を劇的に削減<sup>*</sup></li>
					</ul>
				</div>
				<p class="f12 indent-1 mb20">
					※画像は構成によって実際の製品と異なる場合があります
				</p>
			</div>
			<div class="clm2 alignCtr">
				<p class="rbpType">16Gb Fibre Channel SFF Storage</p>
				<p class="bold alignCtr f16">通常モデル</p>
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15983" role="button" class="btn btn-secondary mt0"><span class="bold f15">1,800,000円</span>(税抜)～</a>
			</div>
		</div>
	</div>
</div>
<!-- End MSA 2062 -->