<div class="specTableArea specTableAreaSp">
	<div class="specTableAreaBg pt20">
		<div class="specTableAreaBgInr">
			<h4 class="f22 bold mb15 dashed-text">HPE MSA</h4>
			<div class="hpe-accordion">

				<div class="accordion-panel">
					<!--<div class="accordion-panel-header">
						<a href="javascript:void(0);" class="accordion-toggle icon-toggle-circle-open open"></a>
					</div>-->
					<div class="accordion-panel-body" style="display: block;">
						<div class="specTableItemsArea">
							<div class="specTableItems">

								<!-- HPE MSA 1060 -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:16051">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_msa1060_campaign.gif" alt="" class="productImg">
											HPE MSA 1060
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)<br>
										<span class="f14 bold">キャンペーンモデル</span>
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:16051" class="btn btn-secondary" role="button">
											<span>665,000円～</span>
										</a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">11,890円<sup>※</sup>〜</span>
									</div>
									<div class="specTableItemPrice">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15981" class="linkWithArrow f14 bold">
											通常モデル
											<span class="arrow">→</span>
										</a><br>
										950,000円～
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">16,990円<sup>※</sup>〜</span>
									</div>
								</div>

								<!-- HPE MSA 2060 -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:16052">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_msa2060_campaign.gif" alt="" class="productImg">
											HPE MSA 2060
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)<br>
										<span class="f14 bold">キャンペーンモデル</span>
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:16052" class="btn btn-secondary" role="button">
											<span>980,000円～</span>
										</a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">17,520円<sup>※</sup>〜</span>
									</div>
									<div class="specTableItemPrice">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15982" class="linkWithArrow f14 bold">
											通常モデル
											<span class="arrow">→</span>
										</a><br>
										1,400,000円～
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">25,030円<sup>※</sup>〜</span>
									</div>
								</div>

								<!-- HPE MSA 2062 -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:16053">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_msa2062_campaign.gif" alt="" class="productImg">
											HPE MSA 2062
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)<br>
										<span class="f14 bold">キャンペーンモデル</span>
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:16053" class="btn btn-secondary" role="button">
											<span>1,260,000円～</span>
										</a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">22,520円<sup>※</sup>〜</span>
									</div>
									<div class="specTableItemPrice">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15983" class="linkWithArrow f14 bold">
											通常モデル
											<span class="arrow">→</span>
										</a><br>
										1,800,000円～
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">32,180円<sup>※</sup>〜</span>
									</div>
								</div>

							</div>
							<div class="f12 mt5">※サブスク月額料は残価設定型の場合</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
</div><!-- ./specTableAreaSp -->
