<div class="specTableArea specTableAreaPc">
	<h4 class="f22 bold mb15 dashed-text">HPE MSA スペック一覧</h4>
	<table width="100%" cellpadding="0" cellspacing="0" class="specTable">
		
		<colgroup span="1" class="key"></colgroup>
		<colgroup span="1" class="value"></colgroup>
		<colgroup span="1" class="value"></colgroup>
		<colgroup span="1" class="value"></colgroup>
		
		<tr>
			<th width="16%">&nbsp;</th>
			<th width="28%">
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15981">
					HPE MSA 1060<br>
					12Gb SAS SFF Storage
				</a>
			</th>
			<th width="28%">
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15982">
					HPE MSA 2060<br>
					10GbE iSCSI SFF Storage
				</a>
			</th>
			<th width="28%">
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15983">
					HPE MSA 2062<br>
					16Gb Fibre Channel SFF Storage
				</a>
			</th>
		</tr>
		<tr class="specs">
			<th>
				商品<br>
				<span class="f11">※画像は構成によって実際の製品と異なる場合があります</span>
			</th>
			<!-- HPE MSA 1060 -->
			<td class="vMiddle">
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15981">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_msa1060.gif" alt="" class="productImg">
				</a>
			</td>
			<!-- HPE MSA 2060 -->
			<td class="vMiddle">
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15982">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_msa2060.gif" alt="" class="productImg">
				</a>
			</td>
			<!-- HPE MSA 2062 -->
			<td class="vMiddle">
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15983">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_msa2062.gif" alt="" class="productImg">
				</a>
			</td>
		</tr>
		<tr class="specs">
			<th>最小構成価格(税抜)<br>※サブスク月額料は残価設定型の場合</th>
			<!-- HPE MSA 1060 -->
			<td>
				<div class="alignCtr">
					<span class="price">
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15981" class="cta-link f12 lhMin">
							<em class="icon-arrow-circle-right"></em>通常モデル
						</a><br>
						<span class="bold f15 lhMin">
							950,000円～
						</span>
					</span>
					<div class="mb20">
						<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
						月額（5年）<span class="disp_ib bold f14">16,990円<sup>※</sup>〜</span><br>
					</div>
				</div>
			</td>
			<!-- HPE MSA 2060 -->
			<td>
				<div class="alignCtr">
					<span class="price">
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15982" class="cta-link f12 lhMin">
							<em class="icon-arrow-circle-right"></em>通常モデル
						</a><br>
						<span class="bold f15 lhMin">
							1,400,000円～
						</span>
					</span>
					<div class="mb20">
						<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
						月額（5年）<span class="disp_ib bold f14">25,030円<sup>※</sup>〜</span><br>
					</div>
				</div>
			</td>
			<!-- HPE MSA 2062 -->
			<td>
				<div class="alignCtr">
					<span class="price">
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15983" class="cta-link f12 lhMin">
							<em class="icon-arrow-circle-right"></em>通常モデル
						</a><br>
						<span class="bold f15 lhMin">
							1,800,000円～
						</span>
					</span>
					<div class="mb20">
						<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
						月額（5年）<span class="disp_ib bold f14">32,180円<sup>※</sup>〜</span><br>
					</div>
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th><!--おすすめ用途--></th>
			<!-- HPE MSA 1060 -->
			<td>
				<div class="indent-1">
					・コスト意識の非常に高いお客様のニーズにも対応する、手頃な価格の共有ストレージ
				</div>
				<div class="indent-1">
					・SASホストインターフェイスを使用することで、高価なスイッチを使わずにサーバーに直接接続
				</div>
				<div class="indent-1">
					・HPE ProLiantサーバー向けの標準外付けエントリーストレージ
				</div>
			</td>
			<!-- HPE MSA 2060 -->
			<td>
				<div class="indent-1">
					・小規模環境とリモートオフィス環境のアプリケーションを低コストで高速化
				</div>
				<div class="indent-1">
					・SSDとHDDを任意に組み合わせることで必要に応じて拡張
				</div>
				<div class="indent-1">
					・MSA-DP+により、可用性を向上させ、RAIDのリビルド時間を劇的に削減<sup>*</sup>
				</div>
				<div class="f11 indent-1">
					* MSA-DP+の仮想ディスクグループに必要なハードドライブ数は12台～となります
				</div>
			</td>
			<!-- HPE MSA 2062 -->
			<td>
				<div class="indent-1">
					・SSDを2台標準搭載。SSDによるリードキャッシュ拡張や自動階層化により、ワークロードの変化に動的に対応
				</div>
				<div class="indent-1">
					・FC接続により、拡張性と信頼性を向上
				</div>
				<div class="indent-1">
					・MSA-DP+により、可用性を向上させ、RAIDのリビルド時間を劇的に削減<sup>*</sup>
				</div>
				<div class="f11 indent-1">
					* MSA-DP+の仮想ディスクグループに必要なハードドライブ数は12台～となります
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th>シャーシ</th>
			<!-- HPE MSA 1060 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					2U<br>
					2.5インチドライブ x 24本
				</div>
			</td>
			<!-- HPE MSA 2060 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					2U<br>
					2.5インチドライブ x 24本
				</div>
			</td>
			<!-- HPE MSA 2062 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					2U<br>
					2.5インチドライブ x 24本
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th>最大物理容量<br>(1エンクロージャー)</th>
			<!-- HPE MSA 1060 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					92.16TB (3.84TB SAS SSD×24台)
				</div>
			</td>
			<!-- HPE MSA 2060 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					92.16TB (3.84TB SAS SSD×24台)
				</div>
			</td>
			<!-- HPE MSA 2062 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					92.16TB (3.84TB SAS SSD×24台)
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th>システムあたりの<br>最大キャッシュ + メモリ</th>
			<!-- HPE MSA 1060 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					24GB
				</div>
			</td>
			<!-- HPE MSA 2060 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					24GB
				</div>
			</td>
			<!-- HPE MSA 2062 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					24GB
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th>インターフェース</th>
			<!-- HPE MSA 1060 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					12Gb SAS
				</div>
			</td>
			<!-- HPE MSA 2060 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					10Gb iSCSI
				</div>
			</td>
			<!-- HPE MSA 2062 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					16Gb FC
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th>標準搭載SSD + 機能</th>
			<!-- HPE MSA 1060 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					―
				</div>
			</td>
			<!-- HPE MSA 2060 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					―
				</div>
			</td>
			<!-- HPE MSA 2062 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					2つの1.92TB RI SSDおよび<br>
					Advanced Data Services Suite
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th>管理</th>
			<!-- HPE MSA 1060 / HPE MSA 2060 / HPE MSA 2062 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					WebベースのUI(SMU V4)、OneView vCenter、Redfish用準のRESTfulインターフェイス
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th>データサービス</th>
			<!-- HPE MSA 1060 / HPE MSA 2060 -->
			<td colspan="2" class="vMiddle">
				<div class="alignCtr lhMid">
					<span class="disp_ib">ストレージ仮想化</span><span class="disp_ib">(RAID1, 5, 6, 10, MSA-DP+)、</span><span class="disp_ib">SSD読み取りキャッシュ、</span><span class="disp_ib">シンプロビジョニング、</span><span class="disp_ib">スナップショット最大64個、</span><span class="disp_ib">ボリュームコピー</span>
				</div>
			</td>
			<!-- HPE MSA 2062 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					<span class="disp_ib">ストレージ仮想化</span><span class="disp_ib">(RAID1, 5, 6, 10, MSA-DP+)、</span><span class="disp_ib">SSD読み取りキャッシュ、</span><span class="disp_ib">シンプロビジョニング、</span><span class="disp_ib">スナップショット最大512個、</span><span class="disp_ib">ボリュームコピー、</span><span class="disp_ib">SSD階層化、</span><span class="disp_ib">非同期リモートレプリケーション</span>
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th>省エネ法に基づく<br>エネルギー消費効率<sup>※1</sup></th>
			<!-- HPE MSA 1060 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					N区分 0.0051 (SFF)
				</div>
			</td>
			<!-- HPE MSA 2060 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					N区分 0.0051 (SFF)<br>
					　　　0.0008 (LFF)
				</div>
			</td>
			<!-- HPE MSA 2062 -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					N区分 0.0051 (SFF)<br>
					　　　0.0008 (LFF)
				</div>
			</td>
		</tr>
		<tr>
			<th>&nbsp;</th>
			<th>
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15981">
					HPE MSA 1060<br>
					12Gb SAS SFF Storage
				</a>
			</th>
			<th>
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15982">
					HPE MSA 2060<br>
					10GbE iSCSI SFF Storage
				</a>
			</th>
			<th>
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4387&ProductSKU=BASE:15983">
					HPE MSA 2062<br>
					16Gb Fibre Channel SFF Storage
				</a>
			</th>
		</tr>
	</table>
	<div class="indent-2 f12">
		※1 エネルギー消費効率とは、省エネルギー法で定める測定方法によって測定された消費電力を省エネルギー法で定める複合論理性能で除したものです。
	</div>
</div><!-- ./specTableAreaPc -->
