<div class="specTableArea specTableAreaPc">
	<h4 class="f22 bold mb15 dashed-text">HPE StoreEasy スペック一覧</h4>
	<table width="100%" cellpadding="0" cellspacing="0" class="specTable">
		
		<colgroup span="1" class="key"></colgroup>
		<colgroup span="3" class="value"></colgroup>
		<colgroup span="2" class="value"></colgroup>
		<colgroup span="3" class="value"></colgroup>
		
		<tr>
			<th rowspan="2" width="10%">&nbsp;</th>
			<th colspan="3">
				HPE StoreEasy 1460
			</th>
			<th colspan="2">
				HPE StoreEasy 1560
			</th>
			<th colspan="3">
				HPE StoreEasy 1660
			</th>
		</tr>
		<tr>
			<th width="11.25%">
				<!-- HPE StoreEasy 1460 -->
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:15991">
					8TB
				</a>
			</th>
			<th width="11.25%">
				<!-- HPE StoreEasy 1460 -->
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:15992">
					16TB
				</a>
			</th>
			<th width="11.25%">
				<!-- HPE StoreEasy 1460 -->
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:15993">
					32TB
				</a>
			</th>
			<th width="11.25%">
				<!-- HPE StoreEasy 1560 -->
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4315&ProductSKU=BASE:15994">
					8TB
				</a>
			</th>
			<th width="11.25%">
				<!-- HPE StoreEasy 1560 -->
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4315&ProductSKU=BASE:15995">
					16TB
				</a>
			</th>
			<th width="11.25%">
				<!-- HPE StoreEasy 1660 -->
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15996">
					16TB
				</a>
			</th>
			<th width="11.25%">
				<!-- HPE StoreEasy 1660 -->
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15997">
					32TB
				</a>
			</th>
			<th width="11.25%">
				<!-- HPE StoreEasy 1660 -->
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15998">
					64TB
				</a>
			</th>
		</tr>
		<tr class="specs">
			<th>
				商品<br>
				<span class="f11">※画像は構成によって実際の製品と異なる場合があります</span>
			</th>
			<!-- HPE StoreEasy 1460 8TB -->
			<td class="vMiddle">
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:15991">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_storeeasy1460.gif" alt="" class="productImg">
				</a>
			</td>
			<!-- HPE StoreEasy 1460 16TB -->
			<td class="vMiddle">
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:15992">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_storeeasy1460.gif" alt="" class="productImg">
				</a>
			</td>
			<!-- HPE StoreEasy 1460 32TB -->
			<td class="vMiddle">
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:15993">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_storeeasy1460.gif" alt="" class="productImg">
				</a>
			</td>
			<!-- HPE StoreEasy 1560 8TB -->
			<td class="vMiddle">
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4315&ProductSKU=BASE:15994">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_storeeasy1560.gif" alt="" class="productImg">
				</a>
			</td>
			<!-- HPE StoreEasy 1560 16TB -->
			<td class="vMiddle">
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4315&ProductSKU=BASE:15995">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_storeeasy1560.gif" alt="" class="productImg">
				</a>
			</td>
			<!-- HPE StoreEasy 1660 16TB -->
			<td class="vMiddle">
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15996">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_storeeasy1660.gif" alt="" class="productImg">
				</a>
			</td>
			<!-- HPE StoreEasy 1660 32TB -->
			<td class="vMiddle">
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15997">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_storeeasy1660.gif" alt="" class="productImg">
				</a>
			</td>
			<!-- HPE StoreEasy 1660 64TB -->
			<td class="vMiddle">
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15998">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_storeeasy1660.gif" alt="" class="productImg">
				</a>
			</td>
		</tr>
		<tr class="alignCtr bold lhMin specs">
			<th>適用可能な<br>キャンペーン</th>
			<!-- HPE StoreEasy 1460 8TB -->
			<td>
				<div class="specTableCpmBnr">
					<a href="/directplus_ent/campaign/">
						<!--<img src="/directplus_ent/images/banners/bnr_400_txt01.png" alt="キャンペーン価格で即時お見積">-->
						<p>12/下旬（予定）より<br>キャンペーンモデル開始</p>
						<img src="/directplus_ent/images/banners/bnr_400x90_it_asap_campaign.jpg" alt="HPE サーバー&amp;ストレージ “ITの準備はお早めに”キャンペーン">
					</a>
				</div>
			</td>
			<!-- HPE StoreEasy 1460 16TB -->
			<td>
				<div class="specTableCpmBnr">
					<a href="/directplus_ent/campaign/">
						<!--<img src="/directplus_ent/images/banners/bnr_400_txt01.png" alt="キャンペーン価格で即時お見積">-->
						<p>12/下旬（予定）より<br>キャンペーンモデル開始</p>
						<img src="/directplus_ent/images/banners/bnr_400x90_it_asap_campaign.jpg" alt="HPE サーバー&amp;ストレージ “ITの準備はお早めに”キャンペーン">
					</a>
				</div>
			</td>
			<!-- HPE StoreEasy 1460 32TB -->
			<td>
				<div class="specTableCpmBnr">
					<a href="/directplus_ent/campaign/">
						<!--<img src="/directplus_ent/images/banners/bnr_400_txt01.png" alt="キャンペーン価格で即時お見積">-->
						<p>12/下旬（予定）より<br>キャンペーンモデル開始</p>
						<img src="/directplus_ent/images/banners/bnr_400x90_it_asap_campaign.jpg" alt="HPE サーバー&amp;ストレージ “ITの準備はお早めに”キャンペーン">
					</a>
				</div>
			</td>
			<!-- HPE StoreEasy 1560 8TB -->
			<td>
				<div class="specTableCpmBnr">
					<a href="/directplus_ent/campaign/">
						<!--<img src="/directplus_ent/images/banners/bnr_400_txt01.png" alt="キャンペーン価格で即時お見積">-->
						<p>12/下旬（予定）より<br>キャンペーンモデル開始</p>
						<img src="/directplus_ent/images/banners/bnr_400x90_it_asap_campaign.jpg" alt="HPE サーバー&amp;ストレージ “ITの準備はお早めに”キャンペーン">
					</a>
				</div>
			</td>
			<!-- HPE StoreEasy 1560 16TB -->
			<td>
				<div class="specTableCpmBnr">
					<a href="/directplus_ent/campaign/">
						<!--<img src="/directplus_ent/images/banners/bnr_400_txt01.png" alt="キャンペーン価格で即時お見積">-->
						<p>12/下旬（予定）より<br>キャンペーンモデル開始</p>
						<img src="/directplus_ent/images/banners/bnr_400x90_it_asap_campaign.jpg" alt="HPE サーバー&amp;ストレージ “ITの準備はお早めに”キャンペーン">
					</a>
				</div>
			</td>
			<!-- HPE StoreEasy 1660 16TB -->
			<td>
				&nbsp;
			</td>
			<!-- HPE StoreEasy 1660 32TB -->
			<td>
				&nbsp;
			</td>
			<!-- HPE StoreEasy 1660 64TB -->
			<td>
				&nbsp;
			</td>
		</tr>
		<tr class="specs">
			<th>最小構成価格(税抜)</th>
			<!-- HPE StoreEasy 1460 8TB -->
			<td>
				<div class="alignCtr">
					<span class="price">
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:15991" class="cta-link f12 lhMin">
							<em class="icon-arrow-circle-right"></em>通常モデル
						</a><br>
						<span class="bold f15 lhMin">
							670,000円～
						</span>
					</span>
				</div>
			</td>
			<!-- HPE StoreEasy 1460 16TB -->
			<td>
				<div class="alignCtr">
					<span class="price">
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:15992" class="cta-link f12 lhMin">
							<em class="icon-arrow-circle-right"></em>通常モデル
						</a><br>
						<span class="bold f15 lhMin">
							780,000円～
						</span>
					</span>
				</div>
			</td>
			<!-- HPE StoreEasy 1460 32TB -->
			<td>
				<div class="alignCtr">
					<span class="price">
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:15993" class="cta-link f12 lhMin">
							<em class="icon-arrow-circle-right"></em>通常モデル
						</a><br>
						<span class="bold f15 lhMin">
							1,090,000円～
						</span>
					</span>
				</div>
			</td>
			<!-- HPE StoreEasy 1560 8TB -->
			<td>
				<div class="alignCtr">
					<span class="price">
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4315&ProductSKU=BASE:15994" class="cta-link f12 lhMin">
							<em class="icon-arrow-circle-right"></em>通常モデル
						</a><br>
						<span class="bold f15 lhMin">
							630,000円～
						</span>
					</span>
				</div>
			</td>
			<!-- HPE StoreEasy 1560 16TB -->
			<td>
				<div class="alignCtr">
					<span class="price">
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4315&ProductSKU=BASE:15995" class="cta-link f12 lhMin">
							<em class="icon-arrow-circle-right"></em>通常モデル
						</a><br>
						<span class="bold f15 lhMin">
							750,000円～
						</span>
					</span>
				</div>
			</td>
			<!-- HPE StoreEasy 1660 16TB -->
			<td>
				<div class="alignCtr">
					<span class="price">
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15996" class="cta-link f12 lhMin">
							<em class="icon-arrow-circle-right"></em>通常モデル
						</a><br>
						<span class="bold f15 lhMin">
							1,280,000円～
						</span>
					</span>
				</div>
			</td>
			<!-- HPE StoreEasy 1660 32TB -->
			<td>
				<div class="alignCtr">
					<span class="price">
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15997" class="cta-link f12 lhMin">
							<em class="icon-arrow-circle-right"></em>通常モデル
						</a><br>
						<span class="bold f15 lhMin">
							1,480,000円～
						</span>
					</span>
				</div>
			</td>
			<!-- HPE StoreEasy 1660 64TB -->
			<td>
				<div class="alignCtr">
					<span class="price">
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15998" class="cta-link f12 lhMin">
							<em class="icon-arrow-circle-right"></em>通常モデル
						</a><br>
						<span class="bold f15 lhMin">
							2,000,000円～
						</span>
					</span>
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th>おすすめ用途</th>
			<!-- HPE StoreEasy 1460 -->
			<td colspan="3">
				<div class="alignCtr bold f16 lhMid mb10">
					小規模環境向け<br>
					ファイルサーバー
				</div>
				<div class="indent-1">
					・小規模環境や拠点のファイル共有を1Uの省スペースで提供
				</div>
				<div class="indent-1">
					・CAL無制限でユーザーが増えてもコストがかからず安心
				</div>
				<div class="indent-1">
					・ファイルサーバー専用OSのためすぐに使えて管理も容易
				</div>
			</td>
			<!-- HPE StoreEasy 1560 -->
			<td colspan="2">
				<div class="alignCtr bold f16 lhMid mb10">
					オフィス環境向け<br>
					エントリーファイルサーバー
				</div>
				<div class="indent-1">
					・各部署や拠点内でのファイル共有を簡単に実現
				</div>
				<div class="indent-1">
					・CAL無制限でユーザーが増えてもコストがかからず安心
				</div>
				<div class="indent-1">
					・ファイルサーバー専用OSのためすぐに使えて管理も容易
				</div>
			</td>
			<!-- HPE StoreEasy 1660 -->
			<td colspan="3">
				<div class="alignCtr bold f16 lhMid mb10">
					中～大規模向け<br>
					ファイルサーバー
				</div>
				<div class="indent-1">
					・高い性能と拡張性を備え、中～大規模拠点や企業ワイドのファイル共有に最適
				</div>
				<div class="indent-1">
					・CAL無制限でユーザーが増えてもコストがかからず安心
				</div>
				<div class="indent-1">
					・ファイルサーバー専用OSのためすぐに使えて管理も容易
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th>標準搭載OS</th>
			<!-- HPE StoreEasy 1460 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					Windows Server IoT 2019 for Storage Standard Edition
				</div>
			</td>
			<!-- HPE StoreEasy 1560 -->
			<td colspan="2" class="vMiddle">
				<div class="alignCtr lhMid">
					Windows Server IoT 2019 for Storage Standard Edition
				</div>
			</td>
			<!-- HPE StoreEasy 1660 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					Windows Server IoT 2019 for Storage Standard Edition
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th>フォーム ファクター</th>
			<!-- HPE StoreEasy 1460 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					1U ラックマウント型
				</div>
			</td>
			<!-- HPE StoreEasy 1560 -->
			<td colspan="2" class="vMiddle">
				<div class="alignCtr lhMid">
					タワー型
				</div>
			</td>
			<!-- HPE StoreEasy 1660 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					2U ラックマウント型
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconProsessor">プロセッサー</th>
			<!-- HPE StoreEasy 1460 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					インテルXeon Bronze 3204 プロセッサー 1.9 GHz
				</div>
			</td>
			<!-- HPE StoreEasy 1560 -->
			<td colspan="2" class="vMiddle">
				<div class="alignCtr lhMid">
					インテルXeon Bronze<br>
					3204 プロセッサー 1.9 GHz
				</div>
			</td>
			<!-- HPE StoreEasy 1660 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					インテルXeon Bronze 3204 プロセッサー 1.9 GHz
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconMemory">メモリ</th>
			<!-- HPE StoreEasy 1460 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					16GB
				</div>
			</td>
			<!-- HPE StoreEasy 1560 -->
			<td colspan="2" class="vMiddle">
				<div class="alignCtr lhMid">
					16GB
				</div>
			</td>
			<!-- HPE StoreEasy 1660 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					16GB
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconDiscController">ディスク<br>コントローラー</th>
			<!-- HPE StoreEasy 1460 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					Smart アレイP408i-a SR Gen10 コントローラー (専用スロット)
				</div>
			</td>
			<!-- HPE StoreEasy 1560 -->
			<td colspan="2" class="vMiddle">
				<div class="alignCtr lhMid">
					Smart アレイP408i-p SR Gen10 コントローラー
				</div>
			</td>
			<!-- HPE StoreEasy 1660 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					OS領域：Smart アレイS100i Gen10 コントローラー (オンボード)<br>
					データ領域：Smart アレイP816i-a SR Gen10 コントローラー (専用スロット)
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconDrive">ドライブ</th>
			<!-- HPE StoreEasy 1460 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					4<br>
					(3.5 型 ホットプラグ対応SAS / SATA)
				</div>
			</td>
			<!-- HPE StoreEasy 1560 -->
			<td colspan="2" class="vMiddle">
				<div class="alignCtr lhMid">
					標準4<br>
					(3.5 型 ホットプラグ対応SAS / SATA)
				</div>
			</td>
			<!-- HPE StoreEasy 1660 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					標準12<br>
					(データ領域用：3.5 型 ホットプラグ対応SAS / SATA)
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th>ドライブ容量</th>
			<!-- HPE StoreEasy 1460 8TB -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					8TB<br>
					(2TB SATA×4)
				</div>
			</td>
			<!-- HPE StoreEasy 1460 16TB -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					16TB<br>
					(4TB SATA×4)
				</div>
			</td>
			<!-- HPE StoreEasy 1460 32TB -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					32TB<br>
					(8TB SATA×4)
				</div>
			</td>
			<!-- HPE StoreEasy 1560 8TB -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					8TB<br>
					(2TB SATA×4)
				</div>
			</td>
			<!-- HPE StoreEasy 1560 16TB -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					16TB<br>
					(4TB SATA×4)
				</div>
			</td>
			<!-- HPE StoreEasy 1660 16TB -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					16TB<br>
					(2TB SAS×8)
				</div>
			</td>
			<!-- HPE StoreEasy 1660 32TB -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					32TB<br>
					(4TB SAS×8)
				</div>
			</td>
			<!-- HPE StoreEasy 1660 64TB -->
			<td class="vMiddle">
				<div class="alignCtr lhMid">
					64TB<br>
					(8TB SAS×8)
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconNetwork">ネットワーク</th>
			<!-- HPE StoreEasy 1460 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					HPE Ethernet 1Gb 4ポート FLR-T I350-T4V2 Adapter（FlexibleLOMアダプター）
				</div>
			</td>
			<!-- HPE StoreEasy 1560 -->
			<td colspan="2" class="vMiddle">
				<div class="alignCtr lhMid">
					Ethernet 1Gb 2 ポート332i ネットワーク アダプター(オンボード）
				</div>
			</td>
			<!-- HPE StoreEasy 1660 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					HPE Ethernet 1Gb 4ポート FLR-T I350-T4V2 Adapter（FlexibleLOMアダプター）
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconRemote">リモート管理</th>
			<!-- HPE StoreEasy 1460 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					Integrated Lights-Out 5 (iLO 5)
				</div>
			</td>
			<!-- HPE StoreEasy 1560 -->
			<td colspan="2" class="vMiddle">
				<div class="alignCtr lhMid">
					Integrated Lights-Out 5 (iLO 5)
				</div>
			</td>
			<!-- HPE StoreEasy 1660 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					Integrated Lights-Out 5 (iLO 5)
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconPower">パワーサプライ</th>
			<!-- HPE StoreEasy 1460 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					500W パワーサプライ×1、<br>
					ホットプラグ対応
				</div>
			</td>
			<!-- HPE StoreEasy 1560 -->
			<td colspan="2" class="vMiddle">
				<div class="alignCtr lhMid">
					500W パワーサプライ×1、<br>
					ホットプラグ対応
				</div>
			</td>
			<!-- HPE StoreEasy 1660 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					800W パワーサプライ×2、<br>
					ホットプラグ対応　リダンダント構成
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th>付属コード</th>
			<!-- HPE StoreEasy 1460 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					200V 用C13-14 電源コード(2m)×1<br>
					(100V 用はオプション)
				</div>
			</td>
			<!-- HPE StoreEasy 1560 -->
			<td colspan="2" class="vMiddle">
				<div class="alignCtr lhMid">
					なし
				</div>
			</td>
			<!-- HPE StoreEasy 1660 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					200V 用C13-14 電源コード(2m)×2<br>
					(100V 用はオプション)
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th>サイズ(W×D×H)</th>
			<!-- HPE StoreEasy 1460 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					435×750×43 mm
				</div>
			</td>
			<!-- HPE StoreEasy 1560 -->
			<td colspan="2" class="vMiddle">
				<div class="alignCtr lhMid">
					195×494×440 mm<br>
					(ゴム脚、突起含む)
				</div>
			</td>
			<!-- HPE StoreEasy 1660 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					446×731×88 mm
				</div>
			</td>
		</tr>
		<tr class="specs">
			<th class="secsIcon iconSupport">標準保証</th>
			<!-- HPE StoreEasy 1460 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					3年間翌営業日オンサイトサービス、3年間パーツ保証
				</div>
			</td>
			<!-- HPE StoreEasy 1560 -->
			<td colspan="2" class="vMiddle">
				<div class="alignCtr lhMid">
					3年間翌営業日オンサイトサービス、<br>
					3年間パーツ保証
				</div>
			</td>
			<!-- HPE StoreEasy 1660 -->
			<td colspan="3" class="vMiddle">
				<div class="alignCtr lhMid">
					3年間翌営業日オンサイトサービス、3年間パーツ保証
				</div>
			</td>
		</tr>
		<tr>
			<th rowspan="2">&nbsp;</th>
			<th>
				<!-- HPE StoreEasy 1460 -->
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:15991">
					8TB
				</a>
			</th>
			<th>
				<!-- HPE StoreEasy 1460 -->
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:15992">
					16TB
				</a>
			</th>
			<th>
				<!-- HPE StoreEasy 1460 -->
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:15993">
					32TB
				</a>
			</th>
			<th>
				<!-- HPE StoreEasy 1560 -->
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4315&ProductSKU=BASE:15994">
					8TB
				</a>
			</th>
			<th>
				<!-- HPE StoreEasy 1560 -->
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4315&ProductSKU=BASE:15995">
					16TB
				</a>
			</th>
			<th>
				<!-- HPE StoreEasy 1660 -->
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15996">
					16TB
				</a>
			</th>
			<th>
				<!-- HPE StoreEasy 1660 -->
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15997">
					32TB
				</a>
			</th>
			<th>
				<!-- HPE StoreEasy 1660 -->
				<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15998">
					64TB
				</a>
			</th>
		</tr>
		<tr>
			<th colspan="3">
				HPE StoreEasy 1460
			</th>
			<th colspan="2">
				HPE StoreEasy 1560
			</th>
			<th colspan="3">
				HPE StoreEasy 1660
			</th>
		</tr>
	</table>
	<p class="alignRgt">
		その他のStoreEasyシリーズをご希望の方はコールセンターへお問い合わせください<br>
		<a href="#ContactUs" class="linkWithArrow">
			<!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" -->
			<span class="arrow">→</span>
		</a>
	</p>
</div><!-- ./specTableAreaPc -->