
<div class="specTableArea specTableAreaSp">
	<div class="specTableAreaBg pt20">
		<div class="specTableAreaBgInr">
			<h4 class="f22 bold mb15 dashed-text">HPE StoreEasy</h4>
			<div class="hpe-accordion">

				<!-- HPE StoreEasy 1460 -->
				<div class="accordion-panel" id="StoreEasy1460">
					<div class="accordion-panel-header">
						<a href="javascript:void(0);" class="accordion-toggle icon-toggle-circle-open open">小規模環境向けファイルサーバー</a>
					</div>
					<div class="accordion-panel-body" style="display: block;">
						<div class="specTableItemsArea">
							<div class="specTableItems">

								<!-- HPE StoreEasy 1460 8TB -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:16046">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_storeeasy1460_campaign.gif" alt="" class="productImg">
											HPE StoreEasy<br>1460 8TB
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)<br>
										<span class="f14 bold">キャンペーンモデル</span>
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:16046" class="btn btn-secondary" role="button">
											<span>469,000円～</span>
										</a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">8,270円<sup>※</sup>〜</span>
									</div>
									<div class="specTableItemPrice">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:15991" class="linkWithArrow f14 bold">
											通常モデル
											<span class="arrow">→</span>
										</a><br>
										670,000円～
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">11,820円<sup>※</sup>〜</span>
									</div>
								</div>

								<!-- HPE StoreEasy 1460 16TB -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:16047">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_storeeasy1460_campaign.gif" alt="" class="productImg">
											HPE StoreEasy<br>1460 16TB
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)<br>
										<span class="f14 bold">キャンペーンモデル</span>
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:16047" class="btn btn-secondary" role="button">
											<span>546,000円～</span>
										</a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">9,630円<sup>※</sup>〜</span>
									</div>
									<div class="specTableItemPrice">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:15992" class="linkWithArrow f14 bold">
											通常モデル
											<span class="arrow">→</span>
										</a><br>
										780,000円～
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">13,760円<sup>※</sup>〜</span>
									</div>
								</div>

								<!-- HPE StoreEasy 1460 32TB -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:16048">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_storeeasy1460_campaign.gif" alt="" class="productImg">
											HPE StoreEasy<br>1460 32TB
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)<br>
										<span class="f14 bold">キャンペーンモデル</span>
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:16048" class="btn btn-secondary" role="button">
											<span>763,000円～</span>
										</a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">13,460円<sup>※</sup>〜</span>
									</div>
									<div class="specTableItemPrice">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4313&ProductSKU=BASE:15993" class="linkWithArrow f14 bold">
											通常モデル
											<span class="arrow">→</span>
										</a><br>
										1,090,000円～
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">19,230円<sup>※</sup>〜</span>
									</div>
								</div>
							</div>
						</div>
						<div class="f12 mt5">※サブスク月額料は残価設定型の場合</div>
					</div>
				</div>
				<!-- HPE StoreEasy 1560 -->
				<div class="accordion-panel" id="StoreEasy1560">
					<div class="accordion-panel-header">
						<a href="javascript:void(0);" class="accordion-toggle icon-toggle-circle-open open">オフィス環境向けエントリーファイルサーバー</a>
					</div>
					<div class="accordion-panel-body" style="display: block;">
						<div class="specTableItemsArea">
							<div class="specTableItems">

								<!-- HPE StoreEasy 1560 8TB -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4315&ProductSKU=BASE:16049">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_storeeasy1560_campaign.gif" alt="" class="productImg">
											HPE StoreEasy<br>1560 8TB
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)<br>
										<span class="f14 bold">キャンペーンモデル</span>
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4315&ProductSKU=BASE:16049" class="btn btn-secondary" role="button">
											<span>441,000円～</span>
										</a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">7,780円<sup>※</sup>〜</span>
									</div>
									<div class="specTableItemPrice">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4315&ProductSKU=BASE:15994" class="linkWithArrow f14 bold">
											通常モデル
											<span class="arrow">→</span>
										</a><br>
										630,000円～
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">11,110円<sup>※</sup>〜</span>
									</div>
								</div>

								<!-- HPE StoreEasy 1560 16TB -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4315&ProductSKU=BASE:16050">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_storeeasy1560_campaign.gif" alt="" class="productImg">
											HPE StoreEasy<br>1560 16TB
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)<br>
										<span class="f14 bold">キャンペーンモデル</span>
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4315&ProductSKU=BASE:16050" class="btn btn-secondary" role="button">
											<span>525,000円～</span>
										</a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">9,260円<sup>※</sup>〜</span>
									</div>
									<div class="specTableItemPrice">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4315&ProductSKU=BASE:15995" class="linkWithArrow f14 bold">
											通常モデル
											<span class="arrow">→</span>
										</a><br>
										750,000円～
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">13,230円<sup>※</sup>〜</span>
									</div>
								</div>

							</div>
						</div>
						<div class="f12 mt5">※サブスク月額料は残価設定型の場合</div>
					</div>
				</div>

				<!-- HPE StoreEasy 1660 -->
				<div class="accordion-panel" id="StoreEasy1660">
					<div class="accordion-panel-header">
						<a href="javascript:void(0);" class="accordion-toggle icon-toggle-circle-open open">中～大規模環境向け大容量ファイルサーバー</a>
					</div>
					<div class="accordion-panel-body" style="display: block;">
						<div class="specTableItemsArea">
							<div class="specTableItems">

								<!-- HPE StoreEasy 1660 16TB -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15996">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_storeeasy1660.gif" alt="" class="productImg">
											HPE StoreEasy<br>1660 16TB
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)<br>
										<span class="f14 bold">通常モデル</span>
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15996" class="btn btn-secondary" role="button">
											<span>1,280,000円～</span>
										</a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">22,580円<sup>※</sup>〜</span>
									</div>
								</div>

								<!-- HPE StoreEasy 1660 32TB -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15997">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_storeeasy1660.gif" alt="" class="productImg">
											HPE StoreEasy<br>1660 32TB
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)<br>
										<span class="f14 bold">通常モデル</span>
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15997" class="btn btn-secondary" role="button">
											<span>1,480,000円～</span>
										</a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">26,110円<sup>※</sup>〜</span>
									</div>
								</div>

								<!-- HPE StoreEasy 1660 64TB -->
								<div class="specTableItem">
									<div class="specTableItemImg">
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15998">
											<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_storeeasy1660.gif" alt="" class="productImg">
											HPE StoreEasy<br>1660 64TB
										</a>
									</div>
									<div class="specTableItemPrice">
										最小構成価格(税抜)<br>
										<span class="f14 bold">通常モデル</span>
										<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4340&ProductSKU=BASE:15998" class="btn btn-secondary" role="button">
											<span>2,000,000円～</span>
										</a>
									</div>
									<div class="mb20">
										<a href="/directplus_ent/subscription/" target="_blank" class="tertiary-link">サブスクご利用で</a><br>
										月額（5年）<span class="disp_ib bold f14">35,280円<sup>※</sup>〜</span>
									</div>
								</div>

							</div>
						</div>
						<div class="f12 mt5">※サブスク月額料は残価設定型の場合</div>
					</div>
				</div>

			</div>
			<p class="indent-1 f12 mt15 mb15">
				※画像は構成によって実際の製品と異なる場合があります
			</p>
		</div>
	</div>
</div><!-- ./specTableAreaSp -->
