<div>
	<p>
		HPE ProLiant DL380 Gen10 Plusは、最新の第3世代インテル&reg; Xeon&reg; スケーラブル・プロセッサーを最大2基登載可能なサーバーです。第2世代インテル&reg; Xeon&reg; スケーラブル・プロセッサーを採用したHPE ProLiant DL180 Gen10やDL380 Gen10の上位機種に位置付けられます。<br>
		CPU、GPU、ストレージとすべての領域で高い性能と拡張性を発揮し、CAE、HPC、HCI、AIワークロードに高性能を提供するサーバーとして最適です。<br>
		またGen10と同様に管理機能iLO5を標準搭載。その特長であるSilicon root of trust (シリコンレベルの信頼性)によるセキュリティ機能をサポートし、HPE独自の電子認証によるファームウェアの更新や不正書き換えの検知と回復機能を備えています。お客様の業務を守る”世界標準の安心サーバー”の進化版です。
	</p>
	<p class="mt10">
		性能とコストのバランスを重視されるお客様には、<a href="/directplus_ent/server/dl380gen10/" class="tertiary-link">HPE ProLiant DL380 Gen10</a>をおすすめいたします。<br>
		DL380 Gen10も引き続き販売をして参ります。
	</p>
	<p class="mt15">
		<a href="/directplus_ent/server/infosight_for_servers.html" class="linkWithArrow" target="_blank">HPE InfoSight for Servers 対応サーバー　詳しくはこちら<span class="arrow">→</span></a>
	</p>
</div>
