<div class="any_questions">
	<h3 class="f24 bold alignCtr mb40">
		<span class="disp_ib">こんな疑問・お困りごとは</span><span class="disp_ib">ありませんか？</span>
	</h3>

	<div class="gutter20 mb40">
		<div class="column50-50Flex fixUpperTablet">
			<div class="clm1 flexGutter30">
				<div class="column25-75Flex fixAll">
					<div class="clm1 flexGutter10">
						<div class="icon-wrapper">
							<div class="icon-user flexGutter20">
								<img src="/directplus_ent/callcenter/images/icon-user.png" width="79" height="93" alt="">
							</div>
							<div class="icon-baloon">
								<img src="/directplus_ent/callcenter/images/icon-baloon.png" width="38" height="43" alt="">
							</div>
						</div>
					</div>
					<div class="clm2">
						ITの専門用語があまりわからないけど<br>
						電話しても大丈夫？
					</div>
				</div>
			</div>
			<div class="clm2">
				<div class="column25-75Flex fixAll">
					<div class="clm1 flexGutter10">
						<div class="icon-wrapper">
							<div class="icon-user flexGutter20">
								<img src="/directplus_ent/callcenter/images/icon-user.png" width="79" height="93" alt="">
							</div>
							<div class="icon-baloon">
								<img src="/directplus_ent/callcenter/images/icon-baloon.png" width="38" height="43" alt="">
							</div>
						</div>
					</div>
					<div class="clm2">
						情シス専任者がいないのに<br>
						サーバーをリプレイスしなくてはならない・・・
					</div>
				</div>
			</div>
		</div>
		<div class="column50-50Flex fixUpperTablet">
			<div class="clm1 flexGutter30">
				<div class="column25-75Flex fixAll">
					<div class="clm1 flexGutter10">
						<div class="icon-wrapper">
							<div class="icon-user flexGutter20">
								<img src="/directplus_ent/callcenter/images/icon-user.png" width="79" height="93" alt="">
							</div>
							<div class="icon-baloon">
								<img src="/directplus_ent/callcenter/images/icon-baloon.png" width="38" height="43" alt="">
							</div>
						</div>
					</div>
					<div class="clm2">
						サーバーの構成違いで何パターンも<br>
						自分で見積を作るのは手間がかかる・・・
					</div>
				</div>
			</div>
			<div class="clm2">
				<div class="column25-75Flex fixAll">
					<div class="clm1 flexGutter10">
						<div class="icon-wrapper">
							<div class="icon-user flexGutter20">
								<img src="/directplus_ent/callcenter/images/icon-user.png" width="79" height="93" alt="">
							</div>
							<div class="icon-baloon">
								<img src="/directplus_ent/callcenter/images/icon-baloon.png" width="38" height="43" alt="">
							</div>
						</div>
					</div>
					<div class="clm2">
						これくらいの予算しかないけど、性能も必要・・・<br>
						収まりますか？
					</div>
				</div>
			</div>
		</div>
		<div class="column50-50Flex fixUpperTablet">
			<div class="clm1 flexGutter30">
				<div class="column25-75Flex fixAll">
					<div class="clm1 flexGutter10">
						<div class="icon-wrapper">
							<div class="icon-user flexGutter20">
								<img src="/directplus_ent/callcenter/images/icon-user.png" width="79" height="93" alt="">
							</div>
							<div class="icon-baloon">
								<img src="/directplus_ent/callcenter/images/icon-baloon.png" width="38" height="43" alt="">
							</div>
						</div>
					</div>
					<div class="clm2">
						とにかく納期重視、<br>
						ささっと決めてすばやく納入したい
					</div>
				</div>
			</div>
			<div class="clm2">
				<div class="column25-75Flex fixAll">
					<div class="clm1 flexGutter10">
						<div class="icon-wrapper">
							<div class="icon-user flexGutter20">
								<img src="/directplus_ent/callcenter/images/icon-user.png" width="79" height="93" alt="">
							</div>
							<div class="icon-baloon">
								<img src="/directplus_ent/callcenter/images/icon-baloon.png" width="38" height="43" alt="">
							</div>
						</div>
					</div>
					<div class="clm2">
						ファイルサーバー、うちの会社に最適な<br>
						容量や性能はどのくらい？
					</div>
				</div>
			</div>
		</div>
		<div class="column50-50Flex fixUpperTablet">
			<div class="clm1 flexGutter30">
				<div class="column25-75Flex fixAll">
					<div class="clm1 flexGutter10">
						<div class="icon-wrapper">
							<div class="icon-user flexGutter20">
								<img src="/directplus_ent/callcenter/images/icon-user.png" width="79" height="93" alt="">
							</div>
							<div class="icon-baloon">
								<img src="/directplus_ent/callcenter/images/icon-baloon.png" width="38" height="43" alt="">
							</div>
						</div>
					</div>
					<div class="clm2">
						会社内でこういうことがやりたいのだけど<br>
						サーバーが必要ですか？
					</div>
				</div>
			</div>
			<div class="clm2">
				<div class="column25-75Flex fixAll">
					<div class="clm1 flexGutter10">
						<div class="icon-wrapper">
							<div class="icon-user flexGutter20">
								<img src="/directplus_ent/callcenter/images/icon-user.png" width="79" height="93" alt="">
							</div>
							<div class="icon-baloon">
								<img src="/directplus_ent/callcenter/images/icon-baloon.png" width="38" height="43" alt="">
							</div>
						</div>
					</div>
					<div class="clm2">
						オプションの追加購入、自社サーバーに適合するか不安。オプション１つだけの問い合わせでも大丈夫？
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="mb40">
		<img src="/directplus_ent/callcenter/images/icon-drop_caret.png" width="76" height="54" alt="" class="m0auto">
	</div>

	<div class="gutter40">
		<div class="column25-75Flex fixUpperTablet">
			<div class="clm1 flexGutter20">
				<img src="/directplus_ent/callcenter/images/image1.jpg" width="" height="" alt="">
			</div>
			<div class="clm2">
				<div class="like">
					お客様の”お見積コンシェルジュ” へお気軽にお声がけください
				</div>
				<div class="f15 gutter5">
					<p>
						日本ヒューレット・パッカードの公式ストアHPE DirectPlusでは「急にサーバーなどのシステムを構成するのは難しくて不安」という方や「自分で見積作成する手間を省きたい」という方のためにコールセンターをご用意しており、お客様に代わって構成作成やパターン見積の作成などを承ります。
					</p>
					<p>
						また豊富なサーバーラインアップの中から「どの製品を選んでよいか分からない」という場合にも、コールセンターがお客様にご要件をお伺いし、最適な製品を提案させていただきます。
					</p>
				</div>
			</div>
		</div>
		<div class="column25-75Flex fixUpperTablet">
			<div class="clm1 flexGutter20">
				<img src="/directplus_ent/callcenter/images/image2.jpg" width="" height="" alt="">
			</div>
			<div class="clm2">
				<div class="like">
					お客様のビジネスにフィットする、最適なご提案を実施
				</div>
				<div class="f15 gutter5">
					<p>
						用途やご利用人数、設置場所、ご予算、導入時期など、導入の条件は会社の数だけ異なります。
HPE DirectPlusコールセンターでは、経験豊かな専任スタッフがお客様のご利用環境、ご希望、お悩みをお伺いし、それぞれのお客様のビジネスに適したご提案をいたします。
					</p>
				</div>
			</div>
		</div>
		<div class="column25-75Flex fixUpperTablet">
			<div class="clm1 flexGutter20">
				<img src="/directplus_ent/callcenter/images/image3.jpg" width="" height="" alt="">
			</div>
			<div class="clm2">
				<div class="like">
					「人によるサポート」を大切に
				</div>
				<div class="f15 gutter5">
					<p>
						人と人が実際に顔を合わせてのIT機器購入は難しい、そのような時代だからこそ、Webでのオンライン販売だけでなくコールセンターの「人によるサポート」を大切にしています。
具体的な導入時期が決まっていない段階からすぐに納入が必要な段階まで、HPE DirectPlusコールセンターがお客様に寄り添い強力にバックアップ。電話して良かったと感じていただける対応を目指します。
					</p>
					<p>
						<a href="https://www.itmedia.co.jp/enterprise/articles/2107/29/news006.html" target="_blank" class="linkWithArrow">こちらもご覧ください「経験不足のIT担当者でも望み通りのサーバが手に入るオンラインストア、その秘密を探る」<span class="arrow">→</span></a>
					</p>
				</div>
			</div>
		</div>
	</div>
	
</div>
