<div class="casestudy">
	<h3 class="f24 bold mb20">
		お客様の声
	</h3>

	<div class="case_list gutter20">
		<div class="column40-60Flex fixUpperTablet">
			<div class="clm1 flexGutter20">
				<img src="/directplus_ent/images/thumb_casestudy_glory.jpg" width="1000" height="375" alt="" class="w100per">
			</div>
			<div class="clm2">
				<p>
					「HPE DirectPlusは担当者が手厚く対応してくれ、レスポンスも常にテンポ良く、オンラインと対面の良いところを組み合わせて効率とコミュニケーションを両立させたサービスでした。今回初めて利用しましたが、社内で相談があればHPE DirectPlusを推薦します」（グローリー株式会社様）
				</p>
				<div class="alignRgt">
					<a href="https://www.hpe.com/jp/ja/customer-case-studies/servers-proliant-glory.html" class="linkWithArrow">お客様事例はこちら<span class="arrow">→</span></a>
				</div>
			</div>
		</div>
		
		<div class="column40-60Flex fixUpperTablet">
			<div class="clm1 flexGutter20">
				<img src="/directplus_ent/images/thumb_casestudy_eri.jpg" width="1000" height="375" alt="" class="w100per">
			</div>
			<div class="clm2">
				<p>
					「HPE DirectPlusでは、サーバーを構成するパーツについても、詳しく解説・提案してくれるので大変助かりますね。たとえばSSDの採用についても、保守条件が緩和されたことをいち早く教えてもらったことがきっかけとなりました」（ERIホールディングス株式会社様）
				</p>
				<div class="alignRgt">
					<a href="https://www.hpe.com/jp/ja/customer-case-studies/servers-proliant-eri.html" class="linkWithArrow">お客様事例はこちら<span class="arrow">→</span></a>
				</div>
			</div>
		</div>

		<div class="column40-60Flex fixUpperTablet">
			<div class="clm1 flexGutter20">
				<img src="/directplus_ent/images/thumb_casestudy_nakamura.jpg" width="1000" height="375" alt="" class="w100per">
			</div>
			<div class="clm2">
				<p>
					「検討段階でHPE DirectPlusのコールセンターに連絡したところ、懇切丁寧に相談に乗っていただき、機種選定や内蔵ストレージのサイジングなど、使用目的や規模に応じた適切な提案をしていただけました。」（医療法人HSR名嘉村クリニック様）
				</p>
				<div class="alignRgt">
					<a href="/directplus_ent/casestudy/nakamura.html" class="linkWithArrow">お客様事例はこちら<span class="arrow">→</span></a>
				</div>
			</div>
		</div>

		<div class="column40-60Flex fixUpperTablet">
			<div class="clm1 flexGutter20">
				<img src="/directplus_ent/casestudy/images/naist_main.png" width="1000" height="375" alt="" class="w100per">
			</div>
			<div class="clm2">
				<p>
					「電話で仕様を相談しながら翌日には見積を提示してもらえるなど、今回もスムーズかつ短期間で導入することができました。最初の問合せから2週間かからずに仕様通りのHPE ProLiant DL385 Gen10サーバーが届きました。HPE DirectPlusでは手間なく発注でき納品も早いので、忙しい年度末の調達時にはとても助かります。」（奈良先端科学技術大学院大学様）
				</p>
				<div class="alignRgt">
					<a href="/directplus_ent/casestudy/naist.html" class="linkWithArrow">お客様事例はこちら<span class="arrow">→</span></a>
				</div>
			</div>
		</div>

		<div class="column40-60Flex fixUpperTablet">
			<div class="clm1 flexGutter20">
				<img src="/directplus_ent/images/thumb_casestudy_gaba.jpg" width="1000" height="375" alt="" class="w100per">
			</div>
			<div class="clm2">
				<p>
					「コンフィグレーターに表示されないオプションも選べることがわかり安心しました。他のサーバーメーカーよりも価格優位性があり、コールセンターの担当者にスピーディに対応してもらえたことが大きかったですね。」（株式会社GABA様）
				</p>
				<div class="alignRgt">
					<a href="/directplus_ent/casestudy/gaba.html" class="linkWithArrow">お客様事例はこちら<span class="arrow">→</span></a>
				</div>
			</div>
		</div>
	</div>
	
</div>
