<div class="contact gryBdr2px paddBlock10-15">
	<div class="f20 bold mb20">
		ご連絡はこちらまで。お客様だけでなく販売パートナー様のお見積ご支援も行っています。
	</div>
	<div class="column33-67Flex mb20 fixUpperTablet contact-tel">
		<div class="clm1 flexGutter40">
			<div class="column20-80Flex fixAll">
				<div class="clm1 flexGutter20">
					<span class="label">電話</span><br>
					<img src="/directplus_ent/callcenter/images/icon-tel.png" width="100" height="98" alt="" class="m0auto">
				</div>
				<div class="clm2">
					<p class="f26 bold lhMin mb5 mt20">
						<span data-action="call" data-tel="0120-215-542">
							0120-215-542
						</span>
					</p>
					<p class="f12 lhMin">
						フリーダイヤルをご利用できない場合<br>
						<span class="f20 bold">
							<span data-action="call" data-tel="03-6743-6355">
								03-6743-6355
							</span>
						</span>
					</p>
				</div>
			</div>
		</div>
		<div class="clm2">
			<p class="mt20">
				受付時間：月曜日～金曜日 9:00～19:00（土曜日、日曜日、祝日、年末年始、および5月1日 お休み）<br>
				応答メッセージが流れましたら1→2を押してください。 販売店のお客様で再販をご検討の方は、1→1を押してください。
			</p>
		</div>
	</div>
	<div class="column50-50Flex fixUpperTablet">
		<div class="clm1 contact-way contact-mail flexGutter40">
			<div class="column20-80Flex flexGutter20 fixAll">
				<div class="clm1 flexGutter20">
					<span class="label">メール</span><br>
					<img src="/directplus_ent/callcenter/images/icon-mail.png" width="100" height="76" alt="" class="m0auto">
				</div>
				<div class="clm2">
					<a href="https://www.hpe.com/h41268/live/index_e.aspx?qid=8812" target="_blank" role="button" class="btn btn-secondary"><span class="disp_ib">メールでの</span><span class="disp_ib">お問い合わせは</span><span class="disp_ib">こちら</span></a>
				</div>
			</div>
		</div>
		<div class="clm2 contact-way contact-chat">
			<div class="column20-80Flex flexGutter20 fixAll">
				<div class="clm1 flexGutter20">
					<span class="label">チャット</span><br>
					<img src="/directplus_ent/callcenter/images/icon-chat.png" width="100" height="100" alt="" class="m0auto">
				</div>
				<div class="clm2">
					<a href="javascript:void" onclick="DCEData.chatFunctions.DCECallToAction();" role="button" class="btn btn-secondary"><span class="disp_ib">チャットでの</span><span class="disp_ib">お問い合わせは</span><span class="disp_ib">こちら</span></a>
				</div>
			</div>
		</div>
	</div>
</div>
