<div class="member">
	<h3 class="f24 bold dashed-text">
		私たちが対応いたします
	</h3>
	
	<p class="mb20">
		コールセンターのメンバーを一部ご紹介します。下記をはじめとする全てのスタッフが皆さまのお問い合わせをお待ちしております。
	</p>
	
	<div class="member_list gutter20">
		<div class="column50-50Flex fixUpperTablet">
			<div class="clm1 flexGutter20">
				<div class="column25-75Flex fixAll">
					<div class="clm1 flexGutter20">
						<img src="/directplus_ent/callcenter/images/member1.jpg" width="300" height="300" alt="" class="gryBdr1px">
					</div>
					<div class="clm2 gutter5">
						<div class="f18 bold">
							熊谷 <span class="f14">Kumagae　<span class="normal">コンシェルジュ</span></span>
						</div>
						<p>
							お問い合わせに対し回答した結果「おかげで良く分かりました」とお礼をいただいた時が一番うれしいです。
						</p>
						<p>
							趣味：資格を取得すること
						</p>
					</div>
				</div>
			</div>
			<div class="clm2">
				<div class="column25-75Flex fixAll">
					<div class="clm1 flexGutter20">
						<img src="/directplus_ent/callcenter/images/member4.jpg" width="300" height="300" alt="" class="gryBdr1px">
					</div>
					<div class="clm2 gutter5">
						<div class="f18 bold">
							植山 <span class="f14">Ueyama　<span class="normal">スーパーバイザー</span></span>
						</div>
						<p>
							「ありがとう」と仰っていただけるととても嬉しく、いつも励みにしています。
						</p>
						<p>
							趣味：お散歩
						</p>
					</div>
				</div>
			</div>
		</div>
		
		<div class="column50-50Flex fixUpperTablet">
			<div class="clm1 flexGutter20">
				<div class="column25-75Flex fixAll">
					<div class="clm1 flexGutter20">
						<img src="/directplus_ent/callcenter/images/member3.jpg" width="300" height="300" alt="" class="gryBdr1px">
					</div>
					<div class="clm2 gutter5">
						<div class="f18 bold">
							山下 <span class="f14">Yamashita　<span class="normal">リーダー</span></span>
						</div>
						<p>
							お客様のお問い合わせに分かりやすく回答するよう心がけています。
						</p>
						<p>
							趣味：映画鑑賞
						</p>
					</div>
				</div>
			</div>
			<div class="clm2">
			</div>
		</div>
	</div>
	
</div>
