<table width="80%" class="data">
						<tr>
							<th width="25%" align="center" bgcolor="#666" style="color:#FFF;">正式受注日</th>
							<th width="25%" align="center" bgcolor="#666" style="color:#FFF;">納品日</th>
							<th width="30%" align="center" bgcolor="#666" style="color:#FFF;">コメント</th>
						</tr>
						<tr>
							<td align="center">8月4日(木)</td>
							<td align="center">8月10日(水)</td>
							<td align="center">標準5営業日</td>
						</tr>
						<tr bgcolor="#F0F0F0">
							<td align="center">8月5日(金)</td>
							<td align="center">8月12日(金)</td>
							<td align="center">標準5営業日</td>
						</tr>
						<tr>
							<td align="center">8月8日(月)</td>
							<td align="center">8月17日(水)</td>
							<td align="center" style="color: #ff0000;">変則7営業日</td>
						</tr>
						<tr bgcolor="#F0F0F0">
							<td align="center">8月9日(火)</td>
							<td align="center">8月18日(木)</td>
							<td align="center" style="color: #ff0000;">変則7営業日</td>
						</tr>
						<tr>
							<td align="center">8月10日(水)</td>
							<td align="center">8月19日(金)</td>
							<td align="center" style="color: #ff0000;">変則7営業日</td>
						</tr>
						<tr bgcolor="#F0F0F0">
							<td align="center">8月12日(金)</td>
							<td align="center">8月22日(月)</td>
							<td align="center" style="color: #ff0000;">変則7営業日</td>
						</tr>
						<tr>
							<td align="center">8月15日(月)</td>
							<td align="center">8月22日(月)</td>
							<td align="center" style="color: #ff0000;">変則6営業日</td>
						</tr>
						<tr bgcolor="#F0F0F0">
							<td align="center">8月16日(火)</td>
							<td align="center">8月22日(月)</td>
							<td align="center">標準5営業日</td>
						</tr>
					</table>