<div class="p10">
		<div class="floatLeft mr10">
			<img src="/directplus_ent/system/common_img/intel_xeon_inside_100x100.png" alt="intel Xeon inside">
		</div>
		<p>
			<span class="fs18 bold">インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> プロセッサー E2-2600 v4 製品ファミリー</span><br>
			Intel、インテル、Intel ロゴ、Intel Inside、Intel Inside ロゴ、Intel Atom、Intel Atom Inside、Intel Core、Core Inside、Intel vPro、vPro Inside、Celeron、Celeron Inside、Itanium、Itanium Inside、Pentium、Pentium Inside、Xeon、Xeon Phi、Xeon Inside、Ultrabook は、アメリカ合衆国および/またはその他の国における Intel Corporation の商標です。
		</p>
		<div class="clear"></div>
	</div>