<!--<div class="campaignBnr mb30">
							<img class="campaignBnrImg" src="/directplus_ent/images/banners/bnr_800x350_dx_campaign.jpg" alt="">
							<div class="campaignBnrInr">
								<p class="campaignBnrTtl">HPE サーバー&amp;ストレージ DX応援キャンペーン</p>
								<div class="campaignBnrTxtPc mb0" style="min-height: 5em;">
									キャンペーンモデルのHPE ProLiant Gen10サーバー本体、内蔵オプション、UPS、StoreEasy、MSAストレージが<span>30％OFF</span>!--<sup>※1</sup>--<br>
									メモリ、HDD/SSDが<span>50％OFF</span>!--　さらに、HPEプロアクティブケアも<span>15％OFF</span><sup>※2</sup>--
									!--<p class="f12 indent-2 mt20">
										※1 MicroServer Gen10 Plusは10%OFF
									</p>
									<p class="f12 indent-2">
										※2 キャンペーン価格についてはHPE DirectPlusコールセンターへお問い合わせください。
									</p>--
								</div>
								<p class="campaignBnrTxtSp">
									サーバー/内蔵オプション30%OFF、メモリ/ディスクは50％OFF
								</p>
								<div class="campaignBnrBtn">
									<a href="/directplus_ent/campaign/" role="button" class="btn btn-secondary alpha">キャンペーン詳細はこちら</a>
								</div>
							</div>
						</div>-->
