<style>
.bnrWithTxt.os_software {
	background-image: url(/directplus_ent/os_software/images/banner.jpg);
	background-position: 0 -180px;
}
.bnrWithTxt.os_software .row {
	min-height: auto;
}
.bnrWithTxt.os_software .row > * {
	flex: 1 1 auto;
}
.bnrWithTxt.os_software .bnrBtn {
	flex: 1 0 auto;
}
.bnrWithTxt.os_software .bnrBtn .btn {
	padding: 15px;
	align-self: center;
}
.bnrWithTxt.os_software span {
	display: inline-block;
}
@media (min-width: 1000px) {
	.bnrWithTxt.os_software .inner::after {
		background: linear-gradient(180deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.4) 100%);
	}
}
@media only screen and (max-width: 999px) {
	.bnrWithTxt .bnrBtn {
		text-align: right;
	}
}
@media only screen and (max-width: 767px) {
	.bnrWithTxt .bnrBtn {
		align-self: center;
	}
}
</style>
<div class="bnrArea mb20">
	<a href="/directplus_ent/os_software/" class="bnrWithTxt gradient os_software">
		<div class="inner">
			<div class="bnrContent">
				<div class="row">
					<div>
						<div class="bnrTtl white"><span>ハードウェアも</span><span>ソフトウェアも、</span><span>HPEが</span><span>一括サポート</span></div>
						<div class="bnrTxt white">
							<span>一緒に購入いただくことで</span><span>大きなメリットをご提供します</span>
						</div>
					</div>
					<div class="bnrBtn">
						<span class="btn btn-secondary alpha mt0">OS/ソフトウェアはこちら</span>
					</div>
				</div>
			</div>
		</div>
	</a>
</div>