<div class="boxArea storage mb40">
	<h2 class="mb20 bold">ストレージ</h2>
	
	<div class="boxItemsWrapper mb10">
		
		<div class="boxItems col2 mb10">
			
			<a class="boxItem noImg noBg" href="/directplus_ent/storage/?ref=dplustopstorage1">
				<span class="cta-link">
					<em class="icon-arrow-circle-right"></em>ラインアップで選ぶ
				</span>
			</a>
			
			<div class="boxItem">
				<div class="boxItemChildren storage">
					<a class="boxItemChild withImg storeEasy" href="/directplus_ent/storage/?ref=dplustopstorage2&hash=StoreEasy">
						<span class="cta-link">
							<em class="icon-arrow-circle-right"></em>NAS製品<br class="br414">（HPE StoreEasy）
						</span>
					</a>
					
					<a class="boxItemChild withImg msa" href="/directplus_ent/storage/?ref=dplustopstorage5&hash=MSA">
						<span class="cta-link">
							<em class="icon-arrow-circle-right"></em>共有ストレージ：HPE MSA
						</span>
					</a>
					
					<a class="boxItemChild withImg rdx" href="/directplus_ent/storage/?ref=dplustopstorage3&hash=RDX">
						<span class="cta-link">
							<em class="icon-arrow-circle-right"></em>バックアップ：RDX
						</span>
					</a>
					
					<a class="boxItemChild withImg lto" href="/directplus_ent/storage/?ref=dplustopstorage4&hash=LTO">
						<span class="cta-link">
							<em class="icon-arrow-circle-right"></em>バックアップ：LTO
						</span>
					</a>
				</div>
			</div>
			
		</div>
		
	</div>
	
</div>