<!-- PC Sub header -->
<div class="subHeader">
			<div class="titleArea cfx">
				<div class="h1Title">
					<span>日本ヒューレット・パッカード合同会社が運営する<br class="spbr">公式オンラインストア</span><br>
					<h1><a href="/directplus_ent/">HPE DirectPlus オンラインストア</a></h1>
				</div>
				<div class="contact cfx mb10">
					<div class="tel">
						<p>
							<span>電話</span><span class="number"><span data-action="call" data-tel="0120-215-542">0120-215-542</span></span> または<span class="number2"><span data-action="call" data-tel="03-6743-6355">03-6743-6355</span></span>
						</p>
						<p><span class="spHide">受付時間：</span>月曜日～金曜日 9:00～19:00 (土日祝、年末年始、5月1日お休み)</p>
					</div>
					<div class="mail">
						<a href="https://www.hpe.com/h41268/live/index_e.aspx?qid=8812" target="_blank">Eメールはこちら</a>
					</div>
				</div>
				<div class="subHeadMenu">
					<ul>
						<li class="spHide"><a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/ViewOrderHistoryForBusiness-Start">保存した見積</a></li>
						<li class="spHide"><a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/ViewPlacedOrderHistoryForBusiness-Start">お届け予定日</a></li>
						<li><a href="/directplus_ent/faq/?refdplus=0082">よくあるご質問</a></li>
						<li><a href="/directplus_ent/guide/?refdplus=0083">ご利用ガイド</a></li>
						<li class="pcHide popupBlnMovSp">
							<a href="/directplus_ent/beginner/" class="pr20" style="position:relative;"><span class="icon-video_icon f20"></span>はじめての方へ</a>
						</li>
						<li class="pcHide"><a href="/directplus_ent/salessupport/">販売パートナー様へ</a></li>
						<li class="pcHide"><a href="/directplus_ent/callcenter/">コールセンターのご紹介</a></li>
					</ul>
				</div>
			</div>
		</div><!--End Sub header -->
<!--End PC Sub header -->


<!--SP Sub header -->
<div class="spSubHeader">
	
	<h1 class="spSubHeader__title">
		<a href="/directplus_ent/">HPE DirectPlus <br class="br320">オンラインストア</a>
	</h1>
	
	<ul class="spSubHeader__tabTriggers">
		<li class="spSubHeader__tabTrigger"><span>製品カテゴリ</span></li>
		<li class="spSubHeader__tabTrigger"><span>メニュー</span></li>
		<li class="spSubHeader__tabTrigger"><span>お問い合わせ</span></li>
	</ul>
	
	<div class="spSubHeader__tabs">
		
		<div class="spSubHeader__tab">
			<!--製品カテゴリ-->
			<ul class="spSubHeader__tab__prductsNavi">
				<li class="spSubHeader__tab__prductNavi">
					<a href="/directplus_ent/server/?refdplus=0075">
						<img src="/directplus_ent/system/images/cgnv_dpb_serverx120.png" height="60" alt="">
						<span>サーバー</span>
					</a>
				</li>
				<li class="spSubHeader__tab__prductNavi">
					<a href="/directplus_ent/storage/?refdplus=0076">
						<img src="/directplus_ent/system/images/cgnv_dpb_storagex120.png" height="60" alt="">
						<span>ストレージ</span>
					</a>
				</li>
				<li class="spSubHeader__tab__prductNavi">
					<a href="/directplus_ent/network/?refdplus=0077">
						<img src="/directplus_ent/system/images/cgnv_dpb_arubax120.png" height="60" alt="">
						<span>ネットワーク</span>
					</a>
				</li>
				<li class="spSubHeader__tab__prductNavi">
					<a href="/directplus_ent/supportservice/?refdplus=0078">
						<img src="/directplus_ent/system/images/cgnv_dpb_supportx120.png" height="60" alt="">
						<span>サポートサービス</span>
					</a>
				</li>
				<li class="spSubHeader__tab__prductNavi">
					<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e">
						<img src="/directplus_ent/system/images/cgnv_dpb_optionx120.png" height="60" alt="">
						<span>オプション</span>
					</a>
				</li>
			</ul>
			
			<div class="spSubHeader__tab__close">
				閉じる
			</div>
		</div>
		
		<div class="spSubHeader__tab">
			<!--ユーザーメニュー-->
			<ul class="spSubHeader__tab__links">
				<li class="spSubHeader__tab__link">
					<a href="/directplus_ent/faq/?refdplus=0082">よくある<br class="br767">ご質問</a>
				</li>
				<li class="spSubHeader__tab__link">
					<a href="/directplus_ent/guide/?refdplus=0083">ご利用<br class="br767">ガイド</a>
				</li>
				<li class="spSubHeader__tab__link">
					<a href="/directplus_ent/beginner/" class="pr20" style="position:relative;"><span class="icon-video_icon f20"></span>はじめての<br class="br767">方へ</a>
				</li>
				<li class="spSubHeader__tab__link">
					<a href="/directplus_ent/salessupport/">販売<br class="br767">パートナー<br class="br414">様へ</a>
				</li>
				<li class="spSubHeader__tab__link">
					<a href="/directplus_ent/callcenter/">コール<br class="br414">センター<br class="br767">のご紹介</a>
				</li>
			</ul>
			
			<ul class="spSubHeader__tab__links">
				<li class="spSubHeader__tab__link">
					<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/ViewBasketForBusiness-View">カート</a>
				</li>
				<li class="spSubHeader__tab__link">
					<a href="<!--#include virtual="/directplus_ent/include/intershop_domain_ssl.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/ViewOrderHistoryForBusiness-Start">保存した<br class="br414">見積</a>
				</li>
				<li class="spSubHeader__tab__link">
					<a href="<!--#include virtual="/directplus_ent/include/intershop_domain_ssl.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/ViewPlacedOrderHistoryForBusiness-Start">お届け予定<br class="br414">確認</a>
				</li>
				<li class="spSubHeader__tab__link">
					<a href="/directplus_ent/members/">会員メニュー</a>
				</li>
			</ul>
			
			<div class="spSubHeader__tab__close">
				閉じる
			</div>
		</div>
		
		<div class="spSubHeader__tab">
			<!--お問い合わせ-->
			<div class="spSubHeader__tab__contacts">
				<div class="spSubHeader__tab__tel">
					<p>
						<span>電話</span><span class="number"><span data-action="call" data-tel="0120-215-542" class="f20">0120-215-542</span></span><br>
						または<span class="number"><span data-action="call" data-tel="03-6743-6355" class="f17">03-6743-6355</span></span>
					</p>
					<p>
						月曜日～金曜日 9:00～19:00 <br>
						(土日祝、年末年始、5月1日お休み)
					</p>
				</div>
				<div class="spSubHeader__tab__mail">
					<a href="https://www.hpe.com/h41268/live/index_e.aspx?qid=8812" target="_blank">Eメールはこちら</a>
				</div>
			</div>
			
			<div class="spSubHeader__tab__close">
				閉じる
			</div>
		</div>
		
	</div>

</div>
<!--End SP Sub header -->

<style>

/* PC Sub Header&subNaviと、spSubHeaderの表示切替 */
.spSubHeader {
	display: none;
}
@media only screen and (max-width: 767px) {
	/* 768px(tablet)はPCメニューを表示、それ未満はSPメニューを表示 */
	.subHeader,
	.subNavi {
		display: none;
	}
	.spSubHeader {
		display: block;
	}
}

/* Common Style (Add) */
.br320,
.br414 {
	display: none;
}
@media only screen and (max-width: 414px) {
	.br414 {
		display: block;
	}
}
@media only screen and (max-width: 320px) {
	.br320 {
		display: block;
	}
}




/* 以下、spSubHeader用CSS */
.spSubHeader,
.spSubHeader * {
	box-sizing: border-box;
}

/* 表題 */
.spSubHeader__title {
	font-size: 20px;
	font-weight: bold;
	margin: 10px 17px;
}
.spSubHeader__tabTriggers {
	display: flex;
	width: 100%;
}
.spSubHeader__tabTrigger {
	cursor: pointer;
	flex: 1;
	line-height: 1;
	padding: 13.5px 8px;
	font-size: 11px;
	display: flex;
	align-items: center;
	justify-content: space-between;
	border-top: 1px solid #ccc;
	border-bottom: 1px solid #ccc;
}
.spSubHeader__tabTrigger.active {
	cursor: unset;
	border-bottom-color: transparent;
}
.spSubHeader__tabTrigger:after {
	content: '';
	width: 5px;
	height: 5px;
	display: block;
	border-top: 2px solid #000;
	border-right: 2px solid #000;
	transform: rotate(135deg);
	margin: -7px 0 0 5px;
}
.spSubHeader__tabTrigger:nth-of-type(n + 2) {
	border-left: 1px solid #ccc;
}

/* タブエリア */
.spSubHeader__tabs {
	margin-bottom: 10px;
}
.spSubHeader__tabs a {
	font-size: 12px;
	color: #707070;
}
.spSubHeader__tabs a:hover {
	color: #000;
}
.spSubHeader__tab {
	display: none;
}
.spSubHeader__tab.show {
	border-bottom: 1px solid #ccc;
}
.spSubHeader__tab > *:not(:last-child) {
	margin: 10px 0;
}
.spSubHeader__tab__close {
	cursor: pointer;
	background: #eaeaea;
	display: flex;
	align-items: center;
	justify-content: center;
	position: relative;
	font-size: 11px;
	padding: 10.5px;
}
.spSubHeader__tab__close:after {
	content: '';
	width: 5px;
	height: 5px;
	display: block;
	border-top: 2px solid #000;
	border-right: 2px solid #000;
	transform: rotate(-45deg);
	margin: 4px 0 0 10px;
}

/* 製品カテゴリ */
.spSubHeader__tab__prductsNavi {
	display: flex;
	flex-wrap: wrap;
	justify-content: space-between;
}
.spSubHeader__tab__prductsNavi > * {
	flex: 1;
	flex-basis: 33.333%;
	margin-bottom: 10px;
	text-align: center;
}
.spSubHeader__tab__prductsNavi > *:nth-child(n + 4) {
	margin-bottom: 0;
}
.spSubHeader__tab__prductNavi img {
	margin: auto;
}
.spSubHeader__tab__prductNavi a {
	display: block;
	padding: 0 4px 2px;
}
@media only screen and (max-width: 767px) {
	.spSubHeader__tab__prductNavi img {
		height: 96px;
	}
}
@media only screen and (max-width: 414px) {
	.spSubHeader__tab__prductNavi img {
		height: 60px;
	}
}

/* ユーザーメニュー */
.spSubHeader__tab__linksWrapper {
	display: flex;
}
.spSubHeader__tab__links {
	display: flex;
	text-align: center;
	align-items: center;
	line-height: 1.41;
}
.spSubHeader__tab__links + .spSubHeader__tab__links {
	border-top: 1px solid #ccc;
	padding: 10px 0 0;
}
.spSubHeader__tab__link {
	padding: 10.5px 2px;
	flex: 1;
	white-space: nowrap;
}
.spSubHeader__tab__link:nth-child(n + 2) {
	border-left: 1px solid #ccc;
}

/* お問い合わせ */
.spSubHeader__tab__contacts {
	padding: 0 10px;
}
.spSubHeader__tab__tel:before,
.spSubHeader__tab__mail:before {
	content: "";
	display: block;
	width: 30px;
	position: absolute;
	left: 0;
	background-image: url(/directplus_ent/system/images/contact_icon.png);
	background-repeat: no-repeat;
	background-size: 30px auto;
}
.spSubHeader__tab__tel,
.spSubHeader__tab__mail {
	position:relative;
	padding-left:40px;
}
.spSubHeader__tab__tel:before {
	height: 30px;
	background-position: 0 0;
	top: 4px;
}
.spSubHeader__tab__mail:before {
	height: 22px;
	background-position: 0 -37px;
	top: 3px;
}
.spSubHeader__tab .number {
	display: inline-block;
	font-weight: bold;
	margin-left: 5px;
}
.spSubHeader__tab__tel .number a {
	color: #000;
}
</style>

<script>
$(function() {
	$('.spSubHeader__tabTrigger').click(function() {
		if(!$(this).hasClass('active')) {
			var index = $('.spSubHeader__tabTrigger').index(this);
			$(this).addClass('active');
			$.when(
				$('.spSubHeader__tab')
					.slideUp()
					.removeClass('show')
			).done(function() {
				$('.spSubHeader__tab')
					.eq(index).addClass('show')
					.slideDown(),
				$('.spSubHeader__tabTrigger')
					.removeClass('active')
					.eq(index).addClass('active')
			});
		}
	});
	
	$('.spSubHeader__tab__close').click(function() {
		$.when(
			$(this).parent('.show').removeClass('.show').slideUp()
		).done(function() {
			$('.spSubHeader__tabTrigger').removeClass('active')
		});
	});
	
	$(window).on('load', function () {
		var DPLUSTOP = (location.pathname == '/directplus_ent/');
		var notTriggered = $('.spSubHeader__tabTriggers').find('.active').length == 0;
		
		if(DPLUSTOP && notTriggered) {
			var activeTab = 0;
			$('.spSubHeader__tabTrigger').eq(activeTab).addClass('active');
			$('.spSubHeader__tab').hide().eq(activeTab).addClass('show').slideDown();
		}
		
	});
});
</script>
