<div class="column33-66 cfx mb20WithBorder">
							<div class="clm1">
                            <p class="alignCtr bold">ご好評につき第2弾！</p>
								<a href="/directplus_ent/campaign/mitsumori/"><img src="/directplus_ent/images/banners/bnr_400x90_mitsumori.gif" width="280" class="m0auto" alt="見積したらLINEポイント　まず参加登録！"></a>
							</div>
							<div class="clm2">
								<p class="lhMid mb15">
									ご好評につき、今回は見積すべてが対象です。<br>
                                    キャンペーン期間中、当サイトでお見積いただいた方に<span class="f20 bold">LINEポイント</span>コードをご送付いたします。<br>
									<span class="bold f16">キャンペーン特典のLINEポイントコードがなくなり次第終了</span>
								</p>
								<p class="alignRgt"><a href="/directplus_ent/campaign/mitsumori/" class="cta-link"><em class="icon-arrow-circle-right"></em>参加登録はこちら</a></p>
							</div>
						</div>