<style>
@media only screen and (min-width: 767px) {
	.cardTitle {
		height: 66px;
		/*height: 44px;*/
	}
}
/*@media only screen and (min-width: 768px) and (max-width: 799px) {
	.cardTitle {
		height: 66px;
	}
}
@media only screen and (min-width: 800px) {
	.cardTitle {
		height: 44px;
	}
}*/
@media only screen and (min-width: 1000px) {
	.cardTitle {
		/*height: 80px;*/
		/*height: 66px;*/
	}
	.techCare .cardImage > img {
		margin-left: 20%;
	}
}

</style>

<!--<div class="contentBox mb20">
	<div class="megaCard">
		<div class="clm1">
			<div class="brightCove gryBdr1px">
				<video
					id="bc_video_campaign"
					data-account="4119874060001"
					data-player="321f0ea8-4a70-4101-8de4-b22992f451f5"
					data-embed="default"
					data-video-id="ref:df6be7f1-3fc8-413a-8be2-41db3b13d485"
					class="video-js"
					controls
				></video>
			</div>
		</div>
		<div class="clm2">
			<div class="title bold lhMid">
				テレワークで行こう：<br>
				Go To テレワーク<br class="brTabletOnly">キャンペーン
			</div>
			<p class="bold lhMid">
				2021年3月31日（水）までの期間限定
			</p>
			<p class="bold lhMid">
				最新サーバーが特別価格、<br>
				メモリ&amp;ディスクは通常価格の半額
			</p>
			<p>
				<a class="f14 cardLink" href="/directplus_ent/campaign/?ref=dplustopmv0001">
					キャンペーン詳細と価格例は<br class="brTabletOnly">こちら
					<span class="cardLinkArrow">→</span>
				</a>
			</p>
		</div>
	</div>
</div>-->

<div class="bgGry">
			<div class="contentBox">
				<div class="cardsWrapper">
					<div class="cards">
						<a class="card bgSlate" href="/directplus_ent/server/delivery.html?ref=dplustopbnr0035">
							<div class="cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_dl20gen10plus.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									最短5営業日で納品可能な<br>構成例はこちら
								</div>
								<div class="cardLink">
									詳細はこちら
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>
						<a class="card bgSteel" href="/directplus_ent/server/infosight_for_servers.html?ref=dplustopbnr0031">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_infosight.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									“するための”ではなく“してくれる” 次世代IT監視ツール
								</div>
								<div class="cardLink">
									HPE InfoSight for Servers
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>
						<a class="card bgPurple" href="/directplus_ent/subscription/?ref=dplustopbnr0030">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_subscription_v2.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									サーバーのサブスク、はじめました。
								</div>
								<div class="cardLink">
									「所有する」だけじゃない、「利用する」という選択肢
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>
						<a class="card bgBronze" href="/directplus_ent/server/ml30gen10plus/?ref=dplustopbnr0034">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_ml30gen10plus_optoku.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									管理、静音、冗長性。さらに進化した中小規模システム向けタワー型サーバー
								</div>
								<div class="cardLink">
									HPE ProLiant ML30 Gen10 Plus
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>

						<!--<a class="card bgBronze" href="/directplus_ent/optoku/ml110gen10/?ref=dplustopbnr0026">
							<div class="cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_ml110gen10.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									中小規模システムに最適な高性能、<br>
									優れた拡張性を備えた1ソケットタワー型サーバー
								</div>
								<div class="cardLink">
									HPE ProLiant ML110 Gen10
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgSlate" href="/directplus_ent/os_software/?ref=dplustopbnr0028">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_microsoft.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									Windows Server 2022
								</div>
								<div class="cardLink">
									高度なセキュリティ、Azure によるハイブリッド機能を備えた最新OS
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgSlate" href="/directplus_ent/callcenter/?ref=dplustopbnr0027">
							<div class="cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_callcenter.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									お客様の”お見積コンシェルジュ” へお気軽にお声がけください
								</div>
								<div class="cardLink">
									HPE DirectPlusコールセンターが皆さまをご支援します
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgSlate" href="/directplus_ent/os_software/ws2012eos/?ref=dplustopbnr0023">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_ws2012eos.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									Windows Server 2012のサポートがまもなく終了します
								</div>
								<div class="cardLink">
									詳細はこちら
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgBronze" href="/directplus_ent/os_software/?ref=dplustopbnr0028">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_os_software_ws2022.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									Windows Server 2022
								</div>
								<div class="cardLink">
									高度なセキュリティ、Azure によるハイブリッド機能を備えた最新OS
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgBronze" href="/directplus_ent/os_software/?ref=dplustopbnr0024">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_os_software.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									ハードウェアもソフトウェアも、HPEが一括サポート<br>
									一緒に購入いただくことでメリットをご提供します
								</div>
								<div class="cardLink">
									OS/ソフトウェアはこちら
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgBronze" href="/directplus_ent/guide/video/?ref=dplustopbnr0022">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_video_guide.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									動画で解説 HPE DirectPlus ご利用ガイド
								</div>
								<div class="cardLink">
									動画版ご利用ガイドはこちら
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgSteel" href="/directplus_ent/server/dl20gen10/?ref=dplustopbnr0025">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_dl20.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									手頃な価格、でも幅広い要件に対応するコンパクトラックサーバー
								</div>
								<div class="cardLink">
									HPE ProLiant DL20 Gen10
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgSteel" href="/directplus_ent/server/delivery.html?ref=dplustopbnr0002">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_stock.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									毎週情報更新中！<br>いま5営業日で納品可能なサーバー本体はこちら
								</div>
								<div class="cardLink">
									詳細はこちら
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgPurple" href="/directplus_ent/server/dl160gen10/?ref=dplustopbnr0006">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_dl160.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									低コストで導入可能、でも柔軟な拡張性
								</div>
								<div class="cardLink">
									中小規模のワークロードに最適なサーバー
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgBronze techCare" href="/directplus_ent/supportservice/?ref=dplustopbnr0018">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_supportservice.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									新サポートサービス<br class="spHide"><br class="br320">「HPE Tech Care」<br>
									AIを含むデジタルなサポートで<br class="spHide"><br class="br375">お客様の負担を軽減
								</div>
								<div class="cardLink">
									詳細はこちら
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgPurple" href="/directplus_ent/salessupport/?ref=dplustopbnr0021">
							<div class="cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_salessupport.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									販売パートナー様を強力にご支援します
								</div>
								<div class="cardLink">
									”お見積コンシェルジュ” へお気軽にお声がけください
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgSlate" href="/directplus_ent/server/microservergen10.html?ref=dplustopbnr0004">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_microservergen10plus_small.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									わずか12㎝の極小安心サーバー
								</div>
								<div class="cardLink">
									コンパクト性、性能、管理性を大幅に強化
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<div class="card bordered shareNo1" href="/directplus_ent/supportservice/?ref=dplustopbnr0018">
							<div class="cardImageWithTxt">
								<img src="/directplus_ent/images/bnr_share_no1.png" alt="">
								<div class="txt lhMin">
									<div>皆様のご愛顧に感謝申し上げます</div>
									<div>国内x86サーバー市場 <br class="br320">出荷台数 <br><span>2四半期連続 <br class="br375"><br class="brTabletOnly"><br class="spHide">シェアNo.1</span></div>
									<div>国内NAS市場 出荷台数 <br><span>7四半期連続 <br class="br375"><br class="brTabletOnly"><br class="spHide">シェアNo.1</span></div>
								</div>
							</div>
							<div class="cardText">
								出典：IDC Quarterly Server Tracker 2021Q1(Share by Company, Product Category: x86 OS: Windows,Linux,Unix)<br>
								IDC Worldwide Quarterly Enterprise Storage Systems Tracker - 2021Q1(Share by Company, Installation NAS)
							</div>
						</div>-->

						<!--<a class="card bgSteel" href="/directplus_ent/server/dl360gen10plus/?ref=dplustopbnr0016">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_dl360gen10plus.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									高い性能を要求されるワークロードに最適なGen10サーバーの進化版
								</div>
								<div class="cardLink">
									1Uラック型サーバー<br>
									HPE ProLiant DL360 Gen10 Plus
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgSteel techCare" href="/directplus_ent/supportservice/?ref=dplustopbnr0018">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_supportservice.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									新サポートサービス<br class="spHide"><br class="br320">「HPE Tech Care」<br>
									AIを含むデジタルなサポートで<br class="spHide"><br class="br375">お客様の負担を軽減
								</div>
								<div class="cardLink">
									詳細はこちら
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgBronze" href="/directplus_ent/promotion/amazongift/?ref=dplustopbnr0019">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_img_800x350_amazongift.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									お見積すると、抽選で100名様に1,000円分のAmazonギフト券プレゼント
								</div>
								<div class="cardLink">
									期間限定 6月30日まで
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgSlate" href="/directplus_ent/campaign/?ref=dplustopbnr0020">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_dx_campaign.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									お客様のデジタルトランスフォーメーションを応援する、期間限定特別価格<br>
									DX応援 キャンペーン
								</div>
								<div class="cardLink">
									2021年10月29日まで
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgBronze" href="/directplus_ent/storage/?hash=MSA&ref=dplustopbnr0015">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_msa2060.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									ついにオンラインストアで共有ストレージが購入可能に！
								</div>
								<div class="cardLink">
									HPE MSAはこちら
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgSteel" href="/directplus_ent/server/microservergen10.html?ref=dplustopbnr0013">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_microservergen10plus_small.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									GIGAスクール構想を成功に導く<br>サーバー活用例
								</div>
								<div class="cardLink">
									校内にも設置しやすい<br>12cmの安心サーバー
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgBronze" href="/directplus_ent/promotion/cal/?ref=dplustopbnr0012">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_microsoft.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									Windows Server&reg; 2019 CAL<br>3つのチェックポイント

								</div>
								<div class="cardLink">
									リスク削減と有効活用の近道に
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgPurple" href="/directplus_ent/server/delivery.html?ref=dplustopbnr0002">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_stock.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									年度末の”駆け込み導入”にも対応します！<br>
									売れ筋製品を中心に在庫大増量中
								</div>
								<div class="cardLink">
									5営業日で納品可能なサーバーはこちら
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgBronze" href="/directplus_ent/campaign/?ref=dplustopbnr0010">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_goto_telework_campaign.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									いよいよ3月31日まで！<br>
									最新サーバーが特別価格、<br class="br375">メモリ&amp;ディスクは半額<br>
									GoTo テレワークキャンペーン
								</div>
								<div class="cardLink">
									キャンペーン価格例はこちら
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgBronze" href="/directplus_ent/server/advice.html?ref=dplustopbnr0011">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_advice.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									導入検討と選定に関わる<br class="br768">全てのITプロフェッショナルの皆様に
								</div>
								<div class="cardLink">
									サーバー「導入前のアドバイス」
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->

						<!--<a class="card bgSlate" href="/directplus_ent/promotion/convenient/?ref=dplustopbnr0005">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_quote_step.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									ご存じですか？サーバー構成を<br>“8週間”保存できます
								</div>
								<div class="cardLink">
									Web見積機能をご活用ください
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->
						<!--<a class="card bgBronze" href="/directplus_ent/optoku/?ref=dplustopbnr0007">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_optoku.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									お得にシステムをパワーアップ
								</div>
								<div class="cardLink">
									オプション30%OFF「オプ得」
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->
						<!--<a class="card bgBronze" href="/events/seminars/info/leaving_hpe.html?id=1&url=https%3A%2F%2Fhpe.zoom.us%2Fwebinar%2Fregister%2F6115982814773%2FWN_uFRNWxHHRH-UJMs_KVzn3Q" target="_blank">
							<div class="spTrimHeight cardImage">
								<img src="/directplus_ent/images/banners/bnr_800x350_onlineseminar_20200902.jpg" alt="">
							</div>
							<div class="cardText">
								<div class="cardTitle">
									30分でわかる！上司に「うちのIT、セキュリティ大丈夫？」と言われた時の返し方
								</div>
								<div class="cardLink">
									10月7日開催 お申込みはこちら
									<span class="cardLinkArrow">→</span>
								</div>
							</div>
						</a>-->


					</div>
				</div><!--End Pannel banners -->

			</div>
		</div>
