<h4>製品カテゴリ</h4>
					<ul class="leftNavLink">
						<li><a href="/directplus_ent/server/">サーバー</a></li>
						<li><a href="/directplus_ent/storage/">ストレージ</a></li>
						<li><a href="/directplus_ent/network/">ネットワーク</a></li>
						<li><a href="/directplus_ent/supportservice/">サポートサービス</a></li>
						<li><a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e">オプション</a></li>
						<li><a href="/directplus_ent/os_software/">OS/ソフトウェア</a></li>
					</ul>