<style>
.pause {
	color: #000;
	display: block;
	padding: 10px 8px 10px 10px;
	font-size: 12px;
	border-bottom: 1px #CCC dotted;
}
</style>

<ul class="leftNavMemu" id="serverLeftMenu">
						<li class="level1">
							<a href="javascript:viod(0);">スペックで選ぶ</a>
							<ul class="level3">
								<li><a href="/directplus_ent/server/microservergen10.html">小型サーバー</a></li>
								<li><a href="/directplus_ent/server/?spec=tower">タワー型サーバー</a></li>
								<li><a href="/directplus_ent/server/?spec=rack">ラックマウント型サーバー</a></li>
							</ul>
						</li>
						<li class="level1 serverLeftMenuTrg">
							<a href="javascript:viod(0);">用途で選ぶ</a>
							<ul class="level3" style="display:none;">
								<li><a href="/directplus_ent/server/purpose/file.html">ファイルサーバー</a></li>
								<li><a href="/directplus_ent/server/purpose/virtualhost.html">仮想化ホストサーバー</a></li>
								<li><a href="/directplus_ent/server/purpose/webapp.html">Web・アプリサーバー</a></li>
								<li><a href="/directplus_ent/server/purpose/database.html">データベースサーバー</a></li>
								<li><a href="/directplus_ent/server/purpose/utm.html">統合脅威管理サーバー</a></li>
								<li><a href="/directplus_ent/server/purpose/sds.html">ソフトウェア・デファインド・ストレージ</a></li>
							</ul>
						</li>
						<li class="level1"><a href="/directplus_ent/server/gen10.html">Gen10サーバーで選ぶ</a></li>
                        <li class="level1"><a href="/directplus_ent/server/search/index.asp">HPE プロダクトセレクションから選ぶ</a></li>
					</ul>

					<h4 class="f14">
						お求めのサーバーが決まっている方はこちらからお見積へお進みください<!--<br>
						<span class="f11">※キャンペーンモデルは「オプ得モデル」からお選びください</span>-->
					</h4>
					<ul class="leftNavMemu">
						<li class="level1">
							<a href="javascript:viod(0);">タワー型</a>
							<ul class="level3">
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=1z4Qz0Nz5jUAAAFwP5kKboSD&sc=2">MicroServer Gen10 Plus <br class="spHide">オプ得モデル</a></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=cbgQz0Nzzk4AAAFwGN4KboUM&sc=2">MicroServer Gen10 Plus <br class="spHide">通常モデル</a></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=SERI:4421">ML30 Gen10 Plus オプ得モデル</a></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=SERI:4415">ML30 Gen10 Plus 通常モデル</a></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=yoQQz0NzqdcAAAFi3_ImFXCq&sc=2">ML110 Gen10 <br class="spHide">オプ得モデル</a></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=sSgQz0NzzrkAAAFemB9.Tep5&sc=2">ML110 Gen10 通常モデル</a></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=_KkQz0NzWq0AAAFeQVt.Teqy&sc=2">ML350 Gen10 通常モデル</a></li>
							</ul>
						</li>
						<li class="level1">
							<a href="javascript:viod(0);">ラックマウント型</a>
							<ul class="level3">
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=SERI:4418">DL20 Gen10 Plus オプ得モデル</a></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=SERI:4412">DL20 Gen10 Plus 通常モデル</a></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=SERI:4378">DL160 Gen10 通常モデル</a></li>
								<!--<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start;sid=N01lF6X1BTVlF_tTnfpzEl7lKiQNtBINCC7S75qW?CatalogCategoryID=_EAQz0Nz4XUAAAFx5xcKbi.Y&sc=2">DL160 Gen10 通常モデル</a></li>-->
								<!--<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start;sid=N01lF6X1BTVlF_tTnfpzEl7lKiQNtBINCC7S75qW?CatalogCategoryID=uoMQz0NzNbEAAAFxVPMKbj6T&sc=2">DL180 Gen10 通常モデル</a></li>-->
								<!--<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=Zs8Qz0NzKZYAAAFkJ9cQLm6x&sc=2">DL325 Gen10 通常モデル</a></li>-->
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start;sid=N01lF6X1BTVlF_tTnfpzEl7lKiQNtBINCC7S75qW?CatalogCategoryID=fC4Qz0NzTYEAAAFwe3YKbp4t&sc=2">DL325 Gen10 Plus <br class="spHide">通常モデル</a></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=H.4Qz0NzPnUAAAF5KcwL6Kuq&sc=2">DL325 Gen10 Plus v2 <br class="spHide">通常モデル</a></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=kdAQz0Nz95YAAAFdQ.V0fHRT&sc=2">DL360 Gen10 通常モデル</a></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=Cu8Qz0NzJmgAAAF4PfgLMfyl&sc=2">DL360 Gen10 Plus <br class="spHide">通常モデル</a></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=aiYQz0Nzc1AAAAF6d4Q8zg6l&sc=2">DL365 Gen10 Plus <br class="spHide">通常モデル</a></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=SERI:4381">DL180 Gen10 通常モデル</a></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=5LwQz0Nzcg0AAAF6v4c8zgky&sc=2">DL345 Gen10 Plus <br class="spHide">通常モデル</a><!--<span class="pause">DL345 Gen10 Plus <br class="spHide">通常モデル</span>--></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=Tf8Qz0Nz3JkAAAFdJqB0fIHF&sc=2">DL380 Gen10 通常モデル</a></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=J_QQz0NzpbYAAAF4cPwLMf0k&sc=2">DL380 Gen10 Plus <br class="spHide">通常モデル</a></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=0EAQz0Nz5M0AAAFwZTRX62D0&sc=2">DL385 Gen10 Plus <br class="spHide">通常モデル</a></li>
								<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=oVQQz0NzDawAAAF5loc8zvNT&sc=2">DL385 Gen10 Plus v2 <br class="spHide">通常モデル</a></li>
							</ul>
						</li>
					</ul>

					<h4>お得なキャンペーン</h4>
					<ul class="leftNavLink">
						<li><a href="/directplus_ent/campaign/">現在実施中のキャンペーン</a></li>
					</ul>

					<h4>サーバー導入をご検討中のお客様へ</h4>
					<ul class="leftNavLink">
						<li><a href="/directplus_ent/server/advice.html">サーバー導入前のアドバイス</a></li>
						<li><a href="/doc/catalog/proliant/pdfs/jpc13797.pdf">HPEのサーバーを選ぶ理由</a></li>
						<li><a href="/directplus_ent/promotion/25years_of_proliant/">HPE ProLiantの設計思想</a></li>
						<li><a href="/directplus_ent/promotion/merit/">HPE DirectPlusを使うメリット</a></li>
						<li><a href="/directplus_ent/pdfs/estimate_online.pdf" target="_blank">HPE DirectPlus 店長のオススメポイント[PDF]</a></li>
						<li><a href="/directplus_ent/casestudy/">導入事例 ～お客様のサーバー活用法をご紹介</a></li>
						<li><a href="/directplus_ent/server/features.html">最新テクノロジーを解説、サーバー記事特集</a></li>
					</ul>

					<h4>製品ガイド</h4>
					<ul class="leftNavLink">
						<li><a href="https://www.hpe.com/jp/ja/doc/general-catalog.html" target="_blank">プロダクトセレクション(総合カタログ)</a></li>
						<li><a href="https://www.hpe.com/jp/ja/doc/server-system.html" target="_blank">サーバーシステム構成図</a></li>
						<li><a href="/doc/catalog/proliant/" target="_blank">サーバー製品カタログ</a></li>
						<li><a href="https://h50146.www5.hpe.com/doc/manual/proliant/soft.html" target="_blank">サーバー製品マニュアル</a></li>
					</ul>

<script>
<!--
$(window).on('load',function(){
	var pUrl = location.pathname ;
	var cuurentMenu
	if(pUrl.match("/directplus_ent/server/")){ cuurentMenu=0 }
	if(pUrl.match("/directplus_ent/server/microservergen10.html")){ cuurentMenu=0 }
	if(pUrl.match("/directplus_ent/server/purpose/")){ cuurentMenu=1 }
	if(pUrl.match("/directplus_ent/server/gen10.html")){ cuurentMenu=2 }
	if(pUrl.match("/directplus_ent/server/search/index.asp")){ cuurentMenu=3 }
	//console.log("cuurentMenu is " + cuurentMenu);
	var cuurentMenuItem = $('#serverLeftMenu').children('li').eq(cuurentMenu);
	$(cuurentMenuItem).removeClass('level1');
	$(cuurentMenuItem).addClass('level2');
});
$('.serverLeftMenuTrg').on("mouseenter", function() {
	$(this).children('.level3').stop().slideDown(200);
});
$('.serverLeftMenuTrg').on("mouseleave", function() {
	$(this).children('.level3').stop().slideUp(300);
});
-->
</script>
