<div class="recommendLinksArea">
	<div class="contentBox">
		<h2 class="bold f24 mb15">こちらもおすすめ</h2>
		<div class="recommendLinks">
			<a href="/directplus_ent/server/gen10.html?ref=dplustoprecommend1" class="recommendLink">
				<div class="cover">
					<img src="/directplus_ent/images/top_recommend_link_cover_gen10.jpg" alt="" width="400" height="568" class="gryBdr1px m0auto">
				</div>
				<div class="text">
					<span class="disp_ib">Gen10サーバーで</span><span class="disp_ib">選ぶ</span>
				</div>
			</a>
			<a href="/doc/catalog/proliant/pdfs/jpc13797.pdf?ref=dplustoprecommend2" target="_blank" class="recommendLink">
				<div class="cover">
					<img src="/directplus_ent/images/top_recommend_link_cover_catalog_jpc13797.jpg" alt="" width="400" height="568" class="gryBdr1px m0auto">
				</div>
				<div class="text">
					<span class="disp_ib">サーバーセキュリティに</span><br class="brUpper415"><span class="disp_ib">世界標準の安心を</span><br>
					<span class="description"><span class="disp_ib">HPE Gen10 サーバー</span><span class="disp_ib">プラットフォーム</span><span class="disp_ib">ハンドブック</span></span>
				</div>
			</a>
			<a href="/directplus_ent/promotion/25years_of_proliant/?ref=dplustoprecommend3" class="recommendLink">
				<div class="cover">
					<img src="/directplus_ent/images/top_recommend_link_cover_25years_of_proliant.jpg" alt="" width="400" height="568" class="gryBdr1px m0auto">
				</div>
				<div class="text">
					ProLiant 登場から<br>
					<span class="disp_ib">今日までの</span><span class="disp_ib">イノベーション</span>
				</div>
			</a>
			<a href="https://www.hpe.com/jp/ja/doc/general-catalog.html?ref=dplustoprecommend5" target="_blank" class="recommendLink">
				<div class="cover">
					<img src="/directplus_ent/images/top_recommend_link_cover_product_selection.jpg" alt="" width="400" height="568" class="m0auto">
				</div>
				<div class="text">
					<span class="disp_ib">HPE</span><span class="disp_ib">プロダクト</span><span class="disp_ib">セレクション</span><br>
					<span class="description">(総合製品カタログ)</span>
				</div>
			</a>
		</div>
	</div>
</div>