	
	<a name="ToTop" id="ToTop"></a>
	<style>
	@media only screen and (max-width:999px){
		.spFixedBnr {
			display:none;
		}
	}
	.floatingBnr {
		width:470px;
		height:268px;
	}
	</style>
	<!-- Start Floating banner -->
	<div class="floatingBnr">
		<div class="floatingTrg">
			<a href="javascript:void(0);" class="floatingBnrCls glyphicon glyphicon-remove"></a>
			<a class="floatingBnrUp f16 bold">お見積・ご注文のお問い合わせはこちら</a>
		</div>
		<div class="floatingBnrCnt">
			<p class="f14 bold mb10">お見積、ご注文でお困りの場合は専門スタッフがお応え致します<br>まずは、お気軽にお電話ください</p>
			<p class="bold lhMin fbTel mb5">
				<span class="f18"><!--#include virtual="/comm/include/directplus_name.inc" -->コールセンター</span><br>
				<span class="f40">0120-215-542</span>
			</p>
			<p class="lhMin">
				<span class="f14">または 03-6743-6355</span><br>
				<span class="f12">
					受付時間：月曜日～金曜日 9:00～19:00<br>
					（土曜日、日曜日、祝日、年末年始、および5月1日 お休み）
				</span>
			</p>
		</div>
	</div>
	<div class="spFixedBnr">
		<a href="javascript:void(0);" class="spFixedCls glyphicon glyphicon-remove"></a>
		<ul>
			<li><a href="tel:03-6743-6355" class="tell"><span>電話でお問い合わせ</span></a></li>
		</ul>
	</div>
	<!-- End Floating banner -->
	