<div class="contentBox mb40">
			<h2 class="f24 mb25 alignCtr bold">お問い合わせ</h2>
			<div class="mb40WithBorder">
				<h3 class="f24 bold mb5">ご購入前のお見積・ご注文のご相談（<!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" -->）</h3>
				<div class="mb20 cfx">
					<div class="floatLft mr15"><img src="/directplus_ent/images/common/contact_us.jpg" width="120"></div>
					<div><p>
						経験・知識豊富な専門スタッフが、製品選定、構成、お見積をサポート<br>
						お客様のお悩みにお応えします。まずは、お気軽にご相談ください。<br class="spHide">
						販売パートナー様もお気軽にご相談ください。
					</p></div>
				</div>
				<div class="column33-66 cfx mb20">
					<div class="clm1">
						<div class="contactUsIconTel">
							<p class="f30 bold lhMin mb5"><span data-action="call" data-tel="0120-215-542">0120-215-542</span></p>
							<p class="f16 lhMin">フリーダイヤルをご利用できない場合<br><span class="f20 bold"><span data-action="call" data-tel="03-6743-6355">03-6743-6355</span></span></p>
						</div>
					</div>
					<div class="clm2">
						<p>
							受付時間：月曜日～金曜日 9:00～19:00（土曜日、日曜日、祝日、年末年始、および5月1日 お休み）<br>
							応答メッセージが流れましたら1→2を押してください。 販売店のお客様で再販をご検討の方は、1→1を押してください。<br>
							複数台導入のご相談もこちらにお電話ください。担当のスタッフが対応致します。
						</p>
					</div>
				</div>
				<div class="contactUsIconMail">
					<p>お見積・ご購入のご相談・製品に関するご質問などにEメールでご返答いたします。</p>
					<a href="https://www.hpe.com/h41268/live/index_e.aspx?qid=8812" target="_blank" role="button" class="btn btn-secondary">WEBフォームはこちら</a>
				</div>
			</div>
			<div class="mb40WithBorder">
				<h3 class="f24 bold mb5">ご購入前の製品仕様についてのお問い合わせ（カスタマーインフォメーションセンター）</h3>
				<div class="column33-66 cfx">
					<div class="clm1">
						<p class="f16 lhMin mb5">電話 <span class="f26 bold"><span data-action="call" data-tel="0120-268-186">0120-268-186</span></span></p>
						<p class="f16 lhMin">フリーダイヤルをご利用できない場合<br><span class="f20 bold"><span data-action="call" data-tel="03-6743-6370">03-6743-6370</span></span></p>
					</div>
					<div class="clm2">
						<p>受付時間：月曜日～金曜日 9:00～19:00（土曜日、日曜日、祝日、年末年始、および5月1日 お休み）</p>
					</div>
				</div>
			</div>
			<div class="mb40WithBorder">
				<h3 class="f24 bold mb5">ご購入後の操作や技術的なお問い合わせ（カスタマーケアセンター）</h3>
				<div class="column33-66 cfx">
					<div class="clm1">
						<p class="f16 lhMin mb5">固定電話（IP電話を除く） <span class="f24 bold"><span data-action="call" data-tel="0120-101-589">0120-101-589</span></span></p>
						<p class="f16 lhMin">IP電話・携帯電話 <span class="f20 bold"><span data-action="call" data-tel="0570-064-235">0570-064-235</span></span></p>
					</div>
					<div class="clm2">
						<p>受付時間：月曜日～金曜日 9:00～21:00、土曜日 9:00～17:00</p>
					</div>
				</div>
			</div>
			<div class="mb40WithBorder">
				<h3 class="f24 bold mb5">ご購入後の修理受付や修理状況のお問い合わせ（レスポンスセンター）</h3>
				<div class="column33-66 cfx">
					<div class="clm1">
						<p class="f16 lhMin">電話 <span class="f24 bold"><span data-action="call" data-tel="0120-220-119">0120-220-119</span></span></p>
					</div>
					<div class="clm2">
						<p>受付時間：月曜日～金曜日 8:45～17:30</p>
					</div>
				</div>
			</div>
			<div>
				<h3 class="f24 bold mb5">その他の製品の製品・技術的なご質問や修理に関するお問い合わせ</h3>
				<a href="http://h20564.www2.hpe.com/hpsc/doc/public/display?lang=ja&cc=JP&docId=emr_na-c04770344" target="_blank"><span class="cta-link"><em class="icon-arrow-circle-right"></em>HPE サポートセンター</span></a>
			</div>
		</div><!-- End Contact us -->