<div class="ranking2Area mb40WithBorder">
	<h2 class="bold dashed-text" id="Ranking">売れ筋商品ランキング</h2>
	<div class="rankItems">
		
		<div class="rankItem rank1">
			<a href="/directplus_ent/optoku/ml110gen10/?ref=dplustopranking7">
				<div class="rankItemHeader">
					<div class="rankItemNum"><span>1</span>位</div>
					<div class="rankItemName"><span>HPE ProLiant </span><span>ML110 Gen10</span></div>
				</div>
				<div class="rankItemImg">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp3_ml110_gen10_campaign.jpg" alt="" class="pcImg">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml110_gen10_campaign.gif" alt="" class="spImg">
				</div>
			</a>
			<div class="rankItemTxt">
				<div class="pcTxt">
					<p class="minPrice">
						通常モデル最小構成価格 252,000円(税抜)～
					</p>
					<p class="optokuPrice">
						オプ得モデル<span class="strikethrough">207,000円(税抜)～</span>
					</p>
				</div>
				<div class="spTxt">
					最小構成価格
				</div>
				<a href="/directplus_ent/optoku/ml110gen10/?ref=dplustopranking8" role="button" class="btn btn-secondary"><span class="pcTxt">期間限定 </span>176,000円(税抜)～</a>
				<!--<div class="pcTxt">
					<p class="minPrice">
						通常モデル最小構成価格 237,000円(税抜)～
					</p>
				</div>
				<a href="/directplus_ent/optoku/ml110gen10/?ref=dplustopranking8" role="button" class="btn btn-secondary"><span class="pcTxt">オプ得モデル </span>192,000円(税抜)～</a>-->
			</div>
		</div>
		
		<div class="rankItem rank2">
			<a href="/directplus_ent/server/microservergen10plus/?ref=dplustopranking5">
				<div class="rankItemHeader">
					<div class="rankItemNum"><span>2</span>位</div>
					<div class="rankItemName"><span>HPE ProLiant </span><br class="brUpper768"><span>MicroServer </span><span>Gen10 Plus</span></div>
				</div>
				<div class="rankItemImg">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp3_microserver_gen10_plus_optoku.jpg" alt="" class="pcImg">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_microserver_gen10_plus_optoku.gif" alt="" class="spImg">
				</div>
			</a>
			<div class="rankItemTxt">
				<!--<div class="pcTxt">
					<p class="minPrice">
						通常モデル最小構成価格 110,000円(税抜)～
					</p>
					<p class="optokuPrice">
						オプ得モデル<span class="strikethrough">110,000円(税抜)～</span>
					</p>
				</div>
				<div class="spTxt">
					最小構成価格
				</div>
				<a href="/directplus_ent/server/microservergen10plus/?ref=dplustopranking6" role="button" class="btn btn-secondary"><span class="pcTxt">期間限定 </span>77,000円(税抜)～</a>-->
				<div class="pcTxt">
					<p class="minPrice">
						通常モデル最小構成価格 110,000円(税抜)～
					</p>
				</div>
				<a href="/directplus_ent/server/microservergen10plus/?ref=dplustopranking6" role="button" class="btn btn-secondary"><span class="pcTxt">オプ得モデル </span>110,000円(税抜)～</a>
			</div>
		</div>
		
		<div class="rankItem rank3">
			<a href="/directplus_ent/server/dl360gen10/?ref=dplustopranking9">
				<div class="rankItemHeader">
					<div class="rankItemNum"><span>3</span>位</div>
					<div class="rankItemName"><span>HPE ProLiant </span><span>DL360 Gen10</span></div>
				</div>
				<div class="rankItemImg">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp3_dl360_gen10_campaign.jpg" alt="" class="pcImg">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl360_gen10_campaign.gif" alt="" class="spImg">
				</div>
			</a>
			<div class="rankItemTxt">
				<div class="pcTxt">
					<p class="minPrice">
						通常モデル最小構成価格 548,000円(税抜)～
					</p>
				</div>
				<div class="spTxt">
					最小構成価格
				</div>
				<a href="/directplus_ent/server/dl360gen10/?ref=dplustopranking10" role="button" class="btn btn-secondary"><span class="pcTxt">期間限定 </span>385,000円(税抜)～</a>
				<!--<div class="pcTxt">
					<p class="minPrice">
						通常モデル最小構成価格 494,000円(税抜)～
					</p>
				</div>-->
				<!--<a href="/directplus_ent/server/dl360gen10/?ref=dplustopranking10" role="button" class="btn btn-secondary"><span class="pcTxt">通常モデル </span>494,000円(税抜)～</a>-->
			</div>
		</div>
		
		<!--<div class="rankItem rank3">
			<a href="/directplus_ent/optoku/ml110gen10/?ref=dplustopranking5">
				<div class="rankItemHeader">
					<div class="rankItemNum"><span>3</span>位</div>
					<div class="rankItemName"><span>HPE ProLiant </span><span>ML110 Gen10</span></div>
				</div>
				<div class="rankItemImg">
					<img src="/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp3_ml110_gen10_optoku.jpg" alt="" class="pcImg">
					<img src="/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml110_gen10_optoku.gif" alt="" class="spImg">
				</div>
			</a>
			<div class="rankItemTxt">
				<div class="pcTxt">
					<p class="minPrice">
						通常モデル最小構成価格 237,000円(税抜)～
					</p>
				</div>
				<a href="/directplus_ent/optoku/ml110gen10/?ref=dplustopranking6" role="button" class="btn btn-secondary"><span class="pcTxt">オプ得モデル </span>192,000円(税抜)～</a>
			</div>
		</div>-->
		
	</div>
</div><!-- End Ranking -->