<!--<div class="footnoteIntel2 mb65 cfx">
				<div class="intelLogo">
					<img src="/directplus_ent/images/common/intel_xeon_platinum_inside_200x200.png" width="100" alt="intel® XEON® PLATINUM inside™">
				</div>
				<div class="intelTxt">
					<p>
						Intel、Intelロゴ、Intel Insideロゴ、およびXeonは、Intel Corporationまたはその子会社の商標です。
					</p>
				</div>
			</div>-->
<div class="mb65">
				<p>
					Intel、Intelロゴ、Intel Insideロゴ、およびXeonは、Intel Corporationまたはその子会社の商標です。
				</p>
			</div>