<div class="mb65">
				<ul class="footnote indent-1">
					<li>※本ページに掲載される<!--#include virtual="/comm/include/directplus_name.inc" -->価格には配送料・消費税は含まれておりません。ご購入の際には別途配送料・消費税がかかりますので、あらかじめご了承ください。</li>
					<li>※本ページに掲載される<!--#include virtual="/comm/include/directplus_name.inc" -->価格は、カスタマイズ内容によって価格が異なりますので、あらかじめご了承ください。</li>
					<li>※本ページに掲載される製品の色、デザイン、仕様、価格、その他の情報は、予告なしに変更されることがあります。</li>
					<li>※本ページに掲載される製品画像は構成によって実際の製品と異なる場合があります。</li>
				</ul>
			</div>