<div class="contentBox directplusMerit">
	<h2 class="f24 white mb20 bold">まずは<!--#include virtual="/comm/include/directplus_name.inc" -->でお見積を</h2>
	<p class="white mb20">
		<!--#include virtual="/comm/include/company_name_body_utf8.inc" -->（HPE）が運営する「<!--#include virtual="/comm/include/directplus_name.inc" -->」は、公式オンラインストアならではのメリットが満載です。<br>
		お見積からご購入までWebサイトで完結！もちろんコールセンターでも対応いたします。<br>
		また、日頃お取引のあるHPE販売パートナー様へのご発注時には、作成したお見積の構成IDをお使いいただけるので便利です。
	</p>
	<ul class="horizontalList">
		<li><a href="/directplus_ent/beginner/" role="button" class="btn btn-tertiary alpha">はじめての方へ</a></li>
		<li><a href="/directplus_ent/salessupport/" role="button" class="btn btn-tertiary alpha">販売パートナー様へ</a></li>
		<li><a href="/directplus_ent/guide/" role="button" class="btn btn-tertiary alpha">ご利用ガイド</a></li>
	</ul>
</div>
