<style>
.js-moxie-online:focus {
	outline:none;
}
.whatsNew > ul > li:nth-child(n+6) {
	display: none;
}
.whatsNewArea {
	position: relative;
}
.whatsNewArea .whatsNewBtn .btn {
	margin: 0 0 20px;
}
@media only screen and (min-width: 375px) {
	.whatsNewArea > h2 {
		margin-bottom: 20px;
	}
	.whatsNewArea .whatsNewBtn {
		position: absolute;
		top: 0;
		right: 0;
	}
	.whatsNewArea .whatsNewBtn .btn {
		margin: 0;
	}
}
</style>
<div class="whatsNewArea mb40WithBorder" id="whatsnew">
						<h2 class="f24 bold dashed-text">新着情報</h2>
							<div class="whatsNewBtn">
								<a href="/directplus_ent/whatsnew/?ref=dplustopwhatsnew1" role="button" class="btn btn-secondary">過去の新着情報を見る</a>
							</div>
						<p class="mb20">
							最新5件までを掲載しております。過去の新着情報は<a href="/directplus_ent/whatsnew/" class="tertiary-link">こちら</a>をご覧ください。
						</p>
						<div class="whatsNew">
							<ul>
								<li class="newsIcon_newpro">
									<span class="newsDate">2022.06.24</span>
									<span class="newsTxt">
										<a href="/directplus_ent/server/dl380gen10plus/">DL380 Gen10 Plus</a>で以下のオプション製品を販売開始<br>
										・DL38x Gen10 Plus SAS/SATA to Tri-Mode ケーブルキット<br>
										・DL38x Gen10 Plus 8SFF SAS/SATA Tri-Mode ドライブケージキット<br>
									</span>
								</li>
								<li class="newsIcon_old">
									<span class="newsDate">2022.06.09</span>
									<span class="newsTxt">
										<a href="/directplus_ent/server/dl160gen10/">DL160 Gen10</a>、<a href="/directplus_ent/server/dl180gen10/">DL180 Gen10</a>、<a href="/directplus_ent/server/dl360gen10plus/">DL360 Gen10 Plus</a>、<a href="/directplus_ent/server/dl325gen10plus/">DL325 Gen10 Plus</a>、<a href="/directplus_ent/server/dl385gen10plus/">DL385 Gen10 Plus</a>、<a href="/directplus_ent/optoku/ml110gen10/">ML110 Gen10</a>、<a href="/directplus_ent/server/ml350gen10/">ML350 Gen10</a>、<a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e">オプション</a>で以下のオプション製品を販売終了
										<br>・480GB RI LP 3.5型 6G SATA 5300P SSD（代替推奨製品：960GB SATA 6G RI LFF LPC MV SSD）
										<br>・960GB MU LP 3.5型 6G SATA 5300M SSD（代替製品はございません）
										<br>
										<br><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e">オプション</a> ＞ <a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=2LMQ9SZErj0AAAFR4E9gZJ.L&amp;CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">DL20</a> ＞
										<br>・ドライブケージ ＞ DL20 Gen10 2SFF(2.5型) ベイ追加キット（代替製品はございません）
										<br>・アクセサリ ＞ M.2 SATAケーブル/LFFアレイ接続ケーブルキット（代替製品はございません）
										<br>
										<br><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e">オプション</a> ＞ <a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=mEEQz0NzTtUAAAFkBGUQLnzv&amp;CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">DL325</a>、<a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=2iYQpABQadsAAAED1SjVqXit&amp;CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">DL385</a> ＞
										<br>・メモリ＞ 8GB 1Rx8 PC4-2933Y-R Smartメモリキット（代替製品はございません）
										<br>・メモリ＞ 16GB 2Rx8 PC4-2933Y-R Smartメモリキット（代替製品はございません）
										<br>・メモリ＞ 32GB 2Rx4 PC4-2933Y-R Smartメモリキット（代替製品はございません）
										<br>
										<br><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e">オプション</a> ＞ <a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=ctgQ9SZEpi8AAAFS0JAEWRWL&amp;CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">ML30</a> ＞
										<br>・電源その他 ＞ ML30 Gen10 リダンダント パワーサプライ バックプレーン（代替製品はございません）
									</span>
								</li>
								<li class="newsIcon_feat">
									<span class="newsDate">2022.06.07</span>
									<span class="newsTxt">
										<a href="/directplus_ent/server/purpose/file.html">「用途で選ぶ - サーバー選定ガイド」 ページをアップデート</a>
									</span>
								</li>
								<li class="newsIcon_feat">
									<span class="newsDate">2022.05.19</span>
									<span class="newsTxt">
										<a href="/directplus_ent/server/features.html">「最新テクノロジーをご紹介、HPE ProLiant サーバー 解説記事」ページに以下の記事を追加</a>
										<br>・建設業界のデジタルトランスフォーメーションを支援「電子申請とBIMデータ」の活用推進に取り組む日本ERI
									</span>
								</li>
								<li class="newsIcon_feat">
									<span class="newsDate">2022.05.18</span>
									<span class="newsTxt">
										<a href="/directplus_ent/subscription/">「サブスクでの導入も是非、ご相談ください」ページをアップデート</a>
									</span>
								</li>
								<li class="newsIcon_newpro">
									<span class="newsDate">2022.05.13</span>
									<span class="newsTxt">
										<a href="/directplus_ent/server/ml30gen10plus/">カスタマイズオプションを通常価格の30％OFFでご購入できる「オプ得」に、ML30 Gen10 Plus を追加</a>
									</span>
								</li>
								<li class="newsIcon_old">
									<span class="newsDate">2022.05.12</span>
									<span class="newsTxt">
										<a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e">オプション</a> ＞ <a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=mEEQz0NzTtUAAAFkBGUQLnzv&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">DL325</a> ＞<br>
										・電源その他 ＞ DL325 Gen10 リダンダントパワーサプライ バックプレーン（代替製品はございません）<br>
										・アクセサリ ＞ DL325 Gen10 10SFF SASケーブルキット（代替製品はございません）<br>
										・アクセサリ ＞ DL325 Gen10 4LFF オプティカルケーブルキット（代替製品はございません）<br>
									</span>
								</li>
								<li class="newsIcon_feat">
									<span class="newsDate">2022.05.09</span>
									<span class="newsTxt">
										<a href="/directplus_ent/casestudy/">お客様導入事例を追加</a>
										<br>・グローリーがHPE ProLiant ML350 Gen10をHPE DirectPlusで導入、新規事業展開の要となるOCR製品の開発環境を強化
									</span>
								</li>
							</ul>
						</div>
					</div><!-- End Whatsnew -->
