<div class="bnr_to_hp_dp gryBdr2px paddBlock10 lhMid">
	<a href="https://jp.ext.hp.com/directplus/business/smb/?jumpid=nm_vgrxuinf2h" target="_blank" class="bnr_to_hp_dp_link hasLinkWithArrow">
		<img src="/directplus_ent/images/bnr_hp_dp.jpg" alt="">
		<div class="bnrTxt">
			<div class="bnrTitle">
				<span class="disp_ib">パソコン</span><span class="disp_ib">・プリンターの</span><span class="disp_ib">お見積</span><span class="disp_ib">・ご注文は</span><span class="disp_ib">「HP Directplus」</span>
			</div>
			<span class="bnrLink">
				<span class="disp_ib">株式会社 日本HPが運営する</span><span class="disp_ib">オンラインストアは</span><span class="disp_ib">こちら</span>
				<span class="arrow">→</span>
			</span>
		</div>
	</a>
</div>