<div class="mb40WithBorder">
						<h2 class="f24 bold dashed-text">スペシャリストに聞く！HPEサーバーレシピ</h2>
						<div class="column50-50 cfx">
							<div class="clm1">
							<div class="mb10">
								<ul class="recipeThumb cfx">
									<li><a href="/directplus_ent/recipe/006_sqlserver.html?ref=dplustoprecipe2"><img src="/directplus_ent/recipe/images/komori.jpg" alt=""></a></li>
									<li><a href="/directplus_ent/recipe/004_hyperv.html?ref=dplustoprecipe3"><img src="/directplus_ent/recipe/images/ogawa.jpg" alt=""></a></li>
									<li><a href="/directplus_ent/recipe/001_fileserver.html?ref=dplustoprecipe4"><img src="/directplus_ent/recipe/images/oikawa.jpg" alt=""></a></li>
								</ul>
							</div>
							</div>
							<div class="clm2">
							<p>
							サーバーを導入/更新するにあたって、必要な情報は多々あります。ハードウェアの仕様、最新技術、ソフトウェアのサポート情報、ソフトウェアのライセンスや実際に求める環境に合わせたサイジング、等々。“HPE サーバーレシピ”は、<!--#include virtual="/comm/include/company_name_body_utf8.inc" -->のスペシャリストが“キュレーター”としてオススメする構成を用意し、情報をまとめたものです。<br>ぜひご参考ください。
							</p>
							</div>
						</div>
						<div class="alignCtr">
							<a href="/directplus_ent/recipe/?ref=dplustoprecipe1" role="button" class="btn btn-secondary">HPE サーバーレシピ一覧はこちら</a>
						</div>
					</div><!-- End Recipe -->