<h3 class="f24 bold mb10">ダイレクトパートナー一覧</h3>
<p class="f12 indent-1 mb20">※ダイレクトパートナーとは、<!--#include virtual="/comm/include/directplus_name.inc" -->製品をご販売いただくHPE販売パートナー様です。お見積後に発行される見積番号・構成IDを共有ください。</p>				
<table class="table f14 bgGryEven" width="100%">
	<tr>
		<td><a href="http://www.ftime.co.jp/" class="tertiary-link" target="_blank">（株）エフタイム</a></td>
	</tr>
	<tr>
		<td>オリックス・レンテック（株）</td>
	</tr>
	<tr>
		<td><a href="https://www.syc.co.jp/" class="tertiary-link" target="_blank">（株）エス・ワイ・シー</a></td>
	</tr>
	<tr>
		<td><a href="https://www.yrl.com/" class="tertiary-link" target="_blank">横河レンタ・リース（株）</a></td>
	</tr>
	<tr>
		<td><a href="http://www.ryoyo.co.jp/" class="tertiary-link" target="_blank">菱洋エレクトロ（株）</a></td>
	</tr>
	<tr>
		<td><a href="http://www.nissho-ele.co.jp/index.html" class="tertiary-link" target="_blank">日商エレクトロニクス（株）</a></td>
	</tr>
	<tr>
		<td><a href="https://www.kel.co.jp/" class="tertiary-link" target="_blank">兼松エレクトロニクス（株）</a></td>
	</tr>
	<tr>
		<td><a href="http://www.nttdata.com/jp/" class="tertiary-link" target="_blank">（株）エヌ・ティ・ティ・データ</a></td>
	</tr>
	<tr>
		<td><a href="http://www.nri.co.jp/" class="tertiary-link" target="_blank">（株）野村総合研究所</a></td>
	</tr>
	<tr>
		<td>ＳＣＳＫ（株）</td>
	</tr>
	<tr>
		<td><a href="http://www.ctc-g.co.jp/" class="tertiary-link" target="_blank">伊藤忠テクノソリューションズ（株）</a></td>
	</tr>
	<tr>
		<td>東芝デジタルソリューションズ（株）</td>
	</tr>
	<tr>
		<td>（株）理経</td>
	</tr>
	<tr>
		<td><a href="http://www.iukinc.co.jp/" class="tertiary-link" target="_blank">（株）アイ・ユー・ケイ</a></td>
	</tr>
	<tr>
		<td>（株）日立システムズ</td>
	</tr>
	<!--<tr>
		<td>（株）イグアス</td>
	</tr>-->
	<tr>
		<td>（株）大塚商会</td>
	</tr>
	<tr>
		<td>SB C&amp;S（株）</td>
	</tr>
	<tr>
		<td>ダイワボウ情報システム（株）</td>
	</tr>
	<tr>
		<td>TD SYNNEX（株）</td>
	</tr>
	<tr>
		<td>リコージャパン（株）</td>
	</tr>
	<tr>
		<td>富士フイルムビジネスイノベーション（株）</td>
	</tr>
	<tr>
		<td><a href="http://www.systena.co.jp/" class="tertiary-link" target="_blank">（株）システナ</a></td>
	</tr>
	<tr>
		<td>三谷商事（株）</td>
	</tr>
	<tr>
		<td>キヤノンマーケティングジャパン（株）</td>
	</tr>
	<tr>
		<td><a href="http://www.alphatec-sol.co.jp/" class="tertiary-link" target="_blank">アルファテック・ソリューションズ（株）</a></td>
	</tr>
	<tr>
		<td>パナソニックソリューションテクノロジー（株）</td>
	</tr>
	<tr>
		<td>シャープマーケティングジャパン（株）</td>
	</tr>
	<tr>
		<td>OKIクロステック（株）</td>
	</tr>
	<tr>
		<td><a href="https://www.jbs.co.jp/solution" class="tertiary-link" target="_blank">日本ビジネスシステムズ（株）</a></td>
	</tr>
</table>

<div class="alignCtr mt25 mb40">
	<a href="/directplus_ent/server/" class="btn btn-secondary" role="button">今すぐお見積を始める</a>
</div>
