<h4>お得なコンテンツ</h4>
					<ul class="rightNavLink">
						<li><a href="https://www.hpe.com/jp/ja/servers/tokutoku-campaign.html"><span class="bold">[サーバー&amp;ストレージとくとくキャンペーン]</span><br>Gen10サーバー本体および内蔵オプション、StoreEasyが30%OFF(MicroServer Gen10は10%OFF)</a></li>
						<li><a href="/directplus_ent/campaign/mitsumori/?refdplus=0071"><span class="bold">[見積したらLINEポイント 第2弾]</span><br>ご好評につき、今回は見積すべてが対象です。参加登録&amp;会員登録&amp;お見積保存で、もれなくLINEポイント！なくなり次第終了！</a></li>
						<li><a href="/directplus_ent/optoku/?refdplus=0072"><span class="bold">[オプ得]</span><br>オプション製品30%オフでお得にシステムをパワーアップ</a></li>
					</ul>