<style>
.js-moxie-online:focus {
	outline:none;
}
.whatsNew > ul > li:nth-child(n+6) {
	display: none;
}
.whatsNewArea {
	position: relative;
}
.whatsNewArea .whatsNewBtn .btn {
	margin: 0 0 20px;
}
@media only screen and (min-width: 375px) {
	.whatsNewArea > h2 {
		margin-bottom: 20px;
	}
	.whatsNewArea .whatsNewBtn {
		position: absolute;
		top: 0;
		right: 0;
	}
	.whatsNewArea .whatsNewBtn .btn {
		margin: 0;
	}
}
</style>
<div class="whatsNewArea mb40WithBorder" id="whatsnew">
						<h2 class="f24 bold dashed-text">新着情報</h2>
							<div class="whatsNewBtn">
								<a href="/directplus_ent/whatsnew/?ref=dplustopwhatsnew1" role="button" class="btn btn-secondary">過去の新着情報を見る</a>
							</div>
						<p class="mb20">
							最新5件までを掲載しております。過去の新着情報は<a href="/directplus_ent/whatsnew/" class="tertiary-link">こちら</a>をご覧ください。
						</p>
						<div class="whatsNew">
							<ul>
								<!--<li class="newsIcon_info">
									<span class="newsDate">2022.07.22</span>
									<span class="newsTxt">
										【重要】<a href="/directplus_ent/informations/delivery_schedule/fusion_stop.html">システムメンテナンスに伴う納品スケジュールのお知らせ（8月8日(月)～8月18日(木)の正式受注分に関して）</a>
									</span>
								</li>-->
								<li class="newsIcon_feat">
									<span class="newsDate">2022.07.20</span>
									<span class="newsTxt">
										<a href="/directplus_ent/server/features.html">「最新テクノロジーをご紹介、HPE ProLiant サーバー 解説記事」ページに以下の記事を追加</a>
										<br>・日本のホワイトハッカー第一人者に聞く、ハードウェアのセキュリティ対策が重要な理由
										<br>・HPEの考えるWX - 新しい働き方を実現するビジョンと意識改革
										<br>・「米国人だけで行くとナメられるから来てくれ」～冷却ファン開発秘話 - 前編
									</span>
								</li>
								<li class="newsIcon_old">
									<span class="newsDate">2022.07.14</span>
									<div class="newsTxt">
										<p>
											<a href="/directplus_ent/server/dl325gen10plus/">DL325 Gen10 Plus</a>で以下のオプション製品を販売終了
											<br>・Ethernet 10Gb 2ポート SFP+ X710-DA2 NIC
											<br>
											<br><a href="/directplus_ent/server/dl345gen10plus/">DL345 Gen10 Plus</a>で以下のオプション製品を販売終了
											<br>・Ethernet 10/25Gb 2ポート SFP28 E810-XXVDA2 NIC
											<br>
											<br><a href="/directplus_ent/server/dl360gen10/">DL360 Gen10</a>で以下のオプション製品を販売終了
											<br>・Ethernet 1Gb 2ポート BASE-T I350-T2V2 NIC
											<br>
											<br><a href="/directplus_ent/server/dl365gen10plus/">DL365 Gen10 Plus</a>で以下のオプション製品を販売終了
											<br>・Ethernet 1Gb 4ポート BASE-T I350-T4 NIC
											<br>
											<br><a href="/directplus_ent/optoku/ml110gen10/">ML110 Gen10</a>で以下のオプション製品を販売終了
											<br>・Ethernet 10Gb 2ポート BASE-T X550-AT2 NIC
											<br>・Ethernet 10Gb 2ポート SFP+ X710-DA2 NIC
										</p>
									</div>
								</li>
								<li class="newsIcon_old">
									<span class="newsDate">2022.07.07</span>
									<div class="newsTxt">
										<p>
											<a href="/directplus_ent/server/dl360gen10/">DL360 Gen10</a>、<a href="/directplus_ent/server/dl380gen10/">DL380 Gen10</a>、<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e">オプション</a>で以下のオプション製品を販売終了
											<br>・300GB 15krpm SC 3.5型 12G SAS DS HDD（代替推奨製品：2TB 7.2krpm SC 3.5型 12G SAS DS HDD、15krpm/10krpm SFF HDD 、またはSATA RI LFF SSDをご検討ください。）
											<br>・600GB 15krpm SC 3.5型 12G SAS DS HDD（代替推奨製品：2TB 7.2krpm SC 3.5型 12G SAS DS HDD、15krpm/10krpm SFF HDD 、またはSATA RI LFF SSDをご検討ください。）
											<br>
											<br><a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e">オプション</a> ＞ <a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=mEEQz0NzTtUAAAFkBGUQLnzv&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">DL325</a>、<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=2iYQpABQadsAAAED1SjVqXit&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">DL385</a> ＞
											<br>・メモリ＞ 16GB 1Rx4 PC4-2933Y-R Smartメモリキット（代替製品はございません）
											<br>
											<br><a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e">オプション</a> ＞ <a href="/directplus_ent/server/dl325gen10plusv2/">DL325 Gen10 Plus v2</a>、<a href="/directplus_ent/server/dl345gen10plus/">DL345 Gen10 Plus</a>、<a href="/directplus_ent/server/dl360gen10plus/">DL360 Gen10 Plus</a>、<a href="/directplus_ent/server/dl380gen10plus/">DL380 Gen10 Plus</a>、<a href="/directplus_ent/server/dl385gen10plusv2/">DL385 Gen10 Plus v2</a> ＞
											<br>・ハードディスク（ベーシックキャリア）/3.5型SAS ＞ 600GB SAS 12G 15Krpm LFF LPC HDD（代替推奨製品：15krpm/10krpm SFF HDD 、またはSATA RI LFF SSDをご検討ください。）
										</p>
									</div>
								</li>
								<li class="newsIcon_newpro">
									<span class="newsDate">2022.07.07</span>
									<div class="newsTxt">
										<p><a href="/directplus_ent/server/dl325gen10plusv2/">DL325 Gen10 Plus v2</a>（4LFF モデル）で以下のオプション製品を販売開始</p>
										<p>・MegaRAID MR216i-a コントローラー</p>
										<p>・MegaRAID MR416i-a コントローラー</p>
										<p>・DL325 Gen10 Plus v2 SAS/SATA to Tri-Mode ケーブルキット</p>
										<p class="f12 ml15 indent-1">※8SFFモデルDL325 Gen10 Plus v2 8SFF SAS/SATA FIO Kitとのセット販売となります。カスタマイズ画面では「SFF SAS/SATA バックプレーンキット w/ケーブル」と表示されます。</p>
										<p class="f12 ml15 indent-1">※4LFFモデルDL325 Gen10 Plus v2 4LFF SAS/SATA FIO Kitとのセット販売となります。カスタマイズ画面では「4LFF SAS/SATA バックプレーンキット w/ケーブル」と表示されます。</p>
									</div>
								</li>
								<li class="newsIcon_newpro">
									<span class="newsDate">2022.07.5</span>
									<div class="newsTxt">
										<p><a href="/directplus_ent/server/dl365gen10plus/">DL365 Gen10 Plus</a>で以下のオプション製品を販売開始</p>
										<p>・DL36x Gen10 Plus 8SFF SAS/SATA to Tri-Mode ケーブルキット</p>
										<p class="f12 ml15 indent-1">※DL365 Gen10 Plus 8SFF SAS/SATAバックプレーンキットとのセット販売となります。カスタマイズ画面では「DL365 Gen10 Plus 8SFF SAS/SATAバックプレーンキット w/ケーブル」と表示されます。</p>
										<p>・DL36x Gen10 Plus 2SFF SAS/SATA to Tri-Mode ケーブルキット</p>
										<p class="f12 ml15 indent-1">※DL365 Gen10 Plus 2SFF SAS/SATAバックプレーンキットとのセット販売となります。カスタマイズ画面では「DL365 Gen10 Plus 2SFF SAS/SATAバックプレーンキット w/ケーブル」と表示されます。</p>
									</div>
								</li>
								<li class="newsIcon_newpro">
									<span class="newsDate">2022.06.29</span>
									<div class="newsTxt">
										<a href="/directplus_ent/server/dl360gen10plus/">DL360 Gen10 Plus</a>（4LFF SAS モデル）で以下のオプション製品を販売開始<br>
										・MegaRAID MR216i-a コントローラー<br>
										・MegaRAID MR416i-a コントローラー<br>
										・DL36x Gen10 Plus 4LFF SAS/SATA to Tri-Mode ケーブルキット<br>
										・DL36x Gen10 Plus 8SFF SAS/SATA to Tri-Mode ケーブルキット<br>
										<p class="f12 ml15 indent-1" >※DL360 Gen10 Plus 8SFF SAS/SATA バックプレーンキットとのセット販売となります。カスタマイズ画面では「DL360 Gen10 Plus 8SFF SAS/SATA バックプレーンキット w/ケーブル」と表示されます。</p>
										・DL36x Gen10 Plus 2SFF SAS/SATA to Tri-Mode ケーブルキット<br>
										<p class="f12 ml15 indent-1">※DL360 Gen10 Plus 2SFF SAS/SATA バックプレーンキットとのセット販売となります。カスタマイズ画面では「DL360 Gen10 Plus 2SFF SAS/SATA バックプレーンキット w/ケーブル」と表示されます。</p>
									</div>
								</li>
								<li class="newsIcon_old">
									<span class="newsDate">2022.06.28</span>
									<div class="newsTxt">
										<a href="/directplus_ent/server/dl380gen10plus/">DL380 Gen10 Plus</a>で以下のオプション製品を販売終了
										<br>・SN1600Q 32Gb 1ポート FC ホストバスアダプター
										<br>・SN1600Q 32Gb 2ポート FC ホストバスアダプター
										<br>・SN1600E 32Gb 1ポート FC ホストバスアダプター
										<br>・SN1600E 32Gb 2ポート FC ホストバスアダプター
									</div>
								</li>
								<li class="newsIcon_newpro">
									<span class="newsDate">2022.06.24</span>
									<div class="newsTxt">
										<a href="/directplus_ent/server/dl385gen10plusv2/">DL385 Gen10 Plus v2</a>（8SFF モデル）で以下のオプション製品を販売開始<br>
										・MegaRAID MR216i-a コントローラー<br>
										・MegaRAID MR416i-a コントローラー<br>
										・DL38x Gen10 Plus SAS/SATA to Tri-Mode ケーブルキット<br>
										・DL300 Gen10 Plus 2U 8SFF x1 Tri-Mode U.3 ドライブケージ<br>
										・8SFF フロントケージ取り外し指示 FIO<br>
										<p class="f12 ml15 indent-1">※DL300 Gen10 Plus 2U 8SFF x1 Tri-Mode U.3 ドライブケージ とのセット販売となります。カスタマイズ画面では「DL300 Gen10 Plus 2U 8SFF x1 Tri-Mode U.3 ドライブケージ w/ケージ取り外し」と表示されます。</p>
										・DL38x Gen10 Plus 8SFF SAS/SATA Tri-Mode ドライブケージキット<br>
										・DL300 Gen10 Plus 2U 8SFF x1 Tri-Mode U.3 ドライブケージ
									</div>
								</li>
								<li class="newsIcon_newpro">
									<span class="newsDate">2022.06.24</span>
									<span class="newsTxt">
										<a href="/directplus_ent/server/dl380gen10plus/">DL380 Gen10 Plus</a>で以下のオプション製品を販売開始<br>
										・DL38x Gen10 Plus SAS/SATA to Tri-Mode ケーブルキット<br>
										・DL38x Gen10 Plus 8SFF SAS/SATA Tri-Mode ドライブケージキット<br>
									</span>
								</li>
								<li class="newsIcon_newpro">
									<span class="newsDate">2022.06.21</span>
									<div class="newsTxt">
										<a href="/directplus_ent/server/dl345gen10plus/">DL345 Gen10 Plus</a>（8SFF モデル）で以下のオプション製品を販売開始<br>
										・MegaRAID MR216i-a コントローラー<br>
										・MegaRAID MR416i-a コントローラー<br>
										・DL300 Gen10 Plus 2U 8SFF x1 Tri-Mode U.3 ドライブケージ<br>
										・8SFF フロントケージ取り外し指示 FIO<br>
										<p class="f12 ml15 indent-1">※DL300 Gen10 Plus 2U 8SFF x1 Tri-Mode U.3 ドライブケージ とのセット販売となります。カスタマイズ画面では「DL300 Gen10 Plus 2U 8SFF x1 Tri-Mode U.3 ドライブケージ w/ケージ取り外し」と表示されます。</p>
									</div>
								</li>
								<li class="newsIcon_newpro">
									<span class="newsDate">2022.06.09</span>
									<div class="newsTxt">
										<a href="/directplus_ent/server/dl325gen10plusv2/">DL325 Gen10 Plus v2</a>（8SFF モデル）、<a href="/directplus_ent/server/dl365gen10plus/">DL365 Gen10 Plus</a>（8SFF モデル）で以下のオプション製品を販売開始<br>
										・MegaRAID MR216i-a コントローラー<br>
										・MegaRAID MR416i-a コントローラー<br>
										<br>
										<a href="/directplus_ent/server/dl325gen10plusv2/">DL325 Gen10 Plus v2</a>（8SFF モデル）で以下のオプション製品を販売開始<br>
										・DL325 Gen10 Plus v2 8SFF U.3 BC FIO バックプレーンキット<br>
										・DL325 Gen10 Plus v2 8SFF NVMe TM ケーブルキット<br>
										<p class="f12 ml15 indent-1">※セット販売となります。カスタマイズ画面では「8SFF U.3 BC FIO バックプレーンキット w/ケーブル」と表示されます。</p>
										・DL325 Gen10 Plus v2 2SFF NVMe TM ケーブルキット（追加ドライブケージ用）<br>
										<br>
										<a href="/directplus_ent/server/dl365gen10plus/">DL365 Gen10 Plus</a>（8SFF モデル）で以下のオプション製品を販売開始<br>
										・DL36X Gen10 Plus 8SFF x4 Tri-Mode U.3 バックプレーンキット<br>
										・DL36X Gen10 Plus 8SFF Tri-Mode ケーブルキット<br>
										<p class="f12 ml15 indent-1">※セット販売となります。カスタマイズ画面では「DL36X Gen10 Plus 8SFF x4 Tri-Mode U.3 バックプレーンキットw/ケーブル」と表示されます。</p>
										・DL365 Gen10 Plus 2SFF U.3バックプレーンキット<br>
										・DL36X Gen10 Plus 2SFF Tri-Mode ケーブルキット<br>
										<p class="f12 ml15 indent-1">※セット販売となります。カスタマイズ画面では「DL365 Gen10 Plus 2SFF U.3バックプレーンキットw/ケーブル」と表示されます。</p>
										・960GB SAS 24G RI SFF BC MV SSD<br>
										・800GB SAS 24G MU SFF BC MV SSD
									</div>
								</li>
								<li class="newsIcon_old">
									<span class="newsDate">2022.06.09</span>
									<span class="newsTxt">
										<a href="/directplus_ent/server/dl160gen10/">DL160 Gen10</a>、<a href="/directplus_ent/server/dl180gen10/">DL180 Gen10</a>、<a href="/directplus_ent/server/dl360gen10plus/">DL360 Gen10 Plus</a>、<a href="/directplus_ent/server/dl325gen10plus/">DL325 Gen10 Plus</a>、<a href="/directplus_ent/server/dl385gen10plus/">DL385 Gen10 Plus</a>、<a href="/directplus_ent/optoku/ml110gen10/">ML110 Gen10</a>、<a href="/directplus_ent/server/ml350gen10/">ML350 Gen10</a>、<a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e">オプション</a>で以下のオプション製品を販売終了
										<br>・480GB RI LP 3.5型 6G SATA 5300P SSD（代替推奨製品：960GB SATA 6G RI LFF LPC MV SSD）
										<br>・960GB MU LP 3.5型 6G SATA 5300M SSD（代替製品はございません）
										<br>
										<br><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e">オプション</a> ＞ <a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=2LMQ9SZErj0AAAFR4E9gZJ.L&amp;CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">DL20</a> ＞
										<br>・ドライブケージ ＞ DL20 Gen10 2SFF(2.5型) ベイ追加キット（代替製品はございません）
										<br>・アクセサリ ＞ M.2 SATAケーブル/LFFアレイ接続ケーブルキット（代替製品はございません）
										<br>
										<br><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e">オプション</a> ＞ <a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=mEEQz0NzTtUAAAFkBGUQLnzv&amp;CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">DL325</a>、<a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=2iYQpABQadsAAAED1SjVqXit&amp;CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">DL385</a> ＞
										<br>・メモリ＞ 8GB 1Rx8 PC4-2933Y-R Smartメモリキット（代替製品はございません）
										<br>・メモリ＞ 16GB 2Rx8 PC4-2933Y-R Smartメモリキット（代替製品はございません）
										<br>・メモリ＞ 32GB 2Rx4 PC4-2933Y-R Smartメモリキット（代替製品はございません）
										<br>
										<br><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e">オプション</a> ＞ <a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=ctgQ9SZEpi8AAAFS0JAEWRWL&amp;CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">ML30</a> ＞
										<br>・電源その他 ＞ ML30 Gen10 リダンダント パワーサプライ バックプレーン（代替製品はございません）
									</span>
								</li>
								<li class="newsIcon_feat">
									<span class="newsDate">2022.06.07</span>
									<span class="newsTxt">
										<a href="/directplus_ent/server/purpose/file.html">「用途で選ぶ - サーバー選定ガイド」 ページをアップデート</a>
									</span>
								</li>
								<li class="newsIcon_feat">
									<span class="newsDate">2022.05.19</span>
									<span class="newsTxt">
										<a href="/directplus_ent/server/features.html">「最新テクノロジーをご紹介、HPE ProLiant サーバー 解説記事」ページに以下の記事を追加</a>
										<br>・建設業界のデジタルトランスフォーメーションを支援「電子申請とBIMデータ」の活用推進に取り組む日本ERI
									</span>
								</li>
								<li class="newsIcon_feat">
									<span class="newsDate">2022.05.18</span>
									<span class="newsTxt">
										<a href="/directplus_ent/subscription/">「サブスクでの導入も是非、ご相談ください」ページをアップデート</a>
									</span>
								</li>
								<li class="newsIcon_newpro">
									<span class="newsDate">2022.05.13</span>
									<span class="newsTxt">
										<a href="/directplus_ent/server/ml30gen10plus/">カスタマイズオプションを通常価格の30％OFFでご購入できる「オプ得」に、ML30 Gen10 Plus を追加</a>
									</span>
								</li>
								<li class="newsIcon_old">
									<span class="newsDate">2022.05.12</span>
									<span class="newsTxt">
										<a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e">オプション</a> ＞ <a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CatalogCategoryID=mEEQz0NzTtUAAAFkBGUQLnzv&CategoryName_value=%E7%B4%94%E6%AD%A3%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3">DL325</a> ＞<br>
										・電源その他 ＞ DL325 Gen10 リダンダントパワーサプライ バックプレーン（代替製品はございません）<br>
										・アクセサリ ＞ DL325 Gen10 10SFF SASケーブルキット（代替製品はございません）<br>
										・アクセサリ ＞ DL325 Gen10 4LFF オプティカルケーブルキット（代替製品はございません）<br>
									</span>
								</li>
								<li class="newsIcon_feat">
									<span class="newsDate">2022.05.09</span>
									<span class="newsTxt">
										<a href="/directplus_ent/casestudy/">お客様導入事例を追加</a>
										<br>・グローリーがHPE ProLiant ML350 Gen10をHPE DirectPlusで導入、新規事業展開の要となるOCR製品の開発環境を強化
									</span>
								</li>
							</ul>
						</div>
					</div><!-- End Whatsnew -->
