<div class="boxArea server mb40">
	<h2 class="mb20 bold">サーバー</h2>
	
	<div class="boxItemsWrapper mb10">
		
		<div class="boxItems col2 mb10">
			
			<a class="boxItem noImg noBg" href="/directplus_ent/server/?ref=dplustopserver1">
				<span class="cta-link">
					<em class="icon-arrow-circle-right"></em>スペックで選ぶ
				</span>
			</a>
			
			<div class="boxItem">
				<div class="boxItemChildren spec">
					<a class="boxItemChild withImg tower" href="/directplus_ent/server/?ref=dplustopserver2&spec=tower">
						<span class="cta-link">
							<em class="icon-arrow-circle-right"></em>HPE ProLiant タワー型サーバー
						</span>
					</a>
					
					<a class="boxItemChild withImg rack" href="/directplus_ent/server/?ref=dplustopserver3&spec=rack">
						<span class="cta-link">
							<em class="icon-arrow-circle-right"></em>HPE ProLiant ラックマウント型サーバー
						</span>
					</a>
					
					<a class="boxItemChild withImg storeEasy" href="/directplus_ent/storage/?ref=dplustopserver4&hash=StoreEasy">
						<span class="cta-link">
							<em class="icon-arrow-circle-right"></em>NAS製品<br class="br414">（HPE StoreEasy）
						</span>
						
						<div class="boxItemChild storeEasyTxt">
							ファイルサーバーに特化したNAS (Network Attached Storage) を利用することで、容易かつトータルコストを抑えた導入が可能です。無制限のWindows CALがつき、ユーザー数が増えても追加コストがかからず安心です。<br>
							・CAL無制限でユーザーが増えてもコストがかからず安心<br>
							・ファイルサーバー専用OSのためすぐに使えて管理も容易
						</div>
						
					</a>
				</div>
			</div>
			
		</div>
		
	</div>
	
	<div class="boxItemsWrapper">
		
		<div class="boxItems">
			
			<a class="boxItem noImg noBg" href="/directplus_ent/server/purpose/file.html?ref=dplustopserver5">
				<span class="cta-link">
					<em class="icon-arrow-circle-right"></em>用途で選ぶ
				</span>
			</a>
			
			<div class="boxItem">
				<div class="boxItemChildren purpose">
					<a class="boxItemChild noImg bgWht" href="/directplus_ent/server/purpose/file.html?ref=dplustopserver6">
						<span class="cta-link">
							<em class="icon-arrow-circle-right"></em>ファイルサーバー
						</span>
					</a>
					
					<a class="boxItemChild noImg bgWht" href="/directplus_ent/server/purpose/virtualhost.html?ref=dplustopserver7">
						<span class="cta-link">
							<em class="icon-arrow-circle-right"></em>仮想化ホストサーバー
						</span>
					</a>
					
					<a class="boxItemChild noImg bgWht" href="/directplus_ent/server/purpose/webapp.html?ref=dplustopserver8">
						<span class="cta-link">
							<em class="icon-arrow-circle-right"></em>Web・アプリケーションサーバー
						</span>
					</a>
					
					<a class="boxItemChild noImg bgWht" href="/directplus_ent/server/purpose/database.html?ref=dplustopserver9">
						<span class="cta-link">
							<em class="icon-arrow-circle-right"></em>データベースサーバー
						</span>
					</a>
					
					<a class="boxItemChild noImg bgWht" href="/directplus_ent/server/purpose/utm.html?ref=dplustopserver10">
						<span class="cta-link">
							<em class="icon-arrow-circle-right"></em>統合脅威管理（UTM）サーバー
						</span>
					</a>
					
					<a class="boxItemChild noImg bgWht" href="/directplus_ent/server/purpose/sds.html?ref=dplustopserver11">
						<span class="cta-link">
							<em class="icon-arrow-circle-right"></em>ソフトウェア・デファインド・ストレージ（SDS）
						</span>
					</a>
				</div>
			</div>
			
			<a class="boxItem noImg noBg" href="/directplus_ent/recipe/?ref=dplustopserver12">
				<span class="cta-link">
					<em class="icon-arrow-circle-right"></em>HPEスペシャリストのおすすめ <br class="br414">「HPEサーバーレシピ」
				</span>
			</a>
			
		</div>
		
	</div>
	
</div>