<div class="meritsArea">
	<h2 class="bold dashed-text"><!--#include virtual="/comm/include/directplus_name.inc" -->で購入する<br class="br414">5つのメリット</h2>
	<div class="inner">
	<div class="merits_and_video">
		<div class="merit_video">
			<div class="brightCove">
				<video
					id="bc_video"
					data-account="4119874060001"
					data-player="321f0ea8-4a70-4101-8de4-b22992f451f5"
					data-embed="default"
					data-video-id="6213334852001"
					class="video-js"
					controls
					></video>
				<script src="//players.brightcove.net/4119874060001/321f0ea8-4a70-4101-8de4-b22992f451f5_default/index.min.js"></script>
			</div>
		</div>
		<div class="merits">
			<ul class="meritsList">
				<li>
					<a href="/directplus_ent/promotion/merit/?hash=merit01&ref=dplustopmerit1" class="utility-link">
						<img src="/directplus_ent/promotion/merit/images/icon_01.png" alt="" class="meritIcon">
						<div class="meritTitle">5営業日の短納期</div>
					</a>
				</li>
				<li>
					<a href="/directplus_ent/promotion/merit/?hash=merit02&ref=dplustopmerit2" class="utility-link">
						<img src="/directplus_ent/promotion/merit/images/icon_02.png" alt="" class="meritIcon">
						<div>
							<div class="meritTitle">フルカスタマイズ</div>
							<div class="f11">組み込み、OSインストールも無償</div>
							<div class="f11 indent-1">※フルカスタマイズCTO対応のみ</div>
						</div>
					</a>
				</li>
				<li>
					<a href="/directplus_ent/promotion/merit/?hash=merit03&ref=dplustopmerit3" class="utility-link">
						<img src="/directplus_ent/promotion/merit/images/icon_03.png" alt="" class="meritIcon">
						<div>
							<div class="meritTitle">信頼の日本生産</div>
							<div class="f11 indent-1">※フルカスタマイズCTO対応のみ</div>
						</div>
					</a>
				</li>
				<li class="merit_campaign">
					<a href="/directplus_ent/promotion/merit/?hash=merit04&ref=dplustopmerit4" class="utility-link">
						<img src="/directplus_ent/promotion/merit/images/icon_04.png" alt="" class="meritIcon">
						<div class="meritTitle">いつもお得な<br class="brUpper415">キャンペーン</div>
					</a>
				</li>
				<li>
					<a href="/directplus_ent/promotion/merit/?hash=merit05&ref=dplustopmerit5" class="utility-link">
						<img src="/directplus_ent/promotion/merit/images/icon_05.png" alt="" class="meritIcon">
						<div class="meritTitle">豊富な購入経路</div>
					</a>
				</li>
				<li class="btnWrapper">
					<a href="/directplus_ent/promotion/merit/?ref=dplustopmerit" class="btn btn-secondary" role="button"><span class="disp_ib">動画で解説！</span><span class="disp_ib">詳しくはこちら</span></a>
				</li>
			</ul>
		</div>
	</div>
	</div><!-- .inner -->
</div>
