<!--<style>
	.bnrShareNo1 {
		width: 100%;
	}
	.bnrShareNo1Img {
		float: left;
		width: 65px;
		margin-left: 10px;
		margin-right: 20px;
	}
	.bnrShareNo1Img img {
		width: 100%;
		height: auto;
	}
	.bnrShareNo1Ttl,
	.bnrShareNo1Txt {
		float: left;
		width: calc(100% - 95px);
	}
	@media only screen and (max-width: 767px) {
		.bnrShareNo1Txt {
			float: none;
			width: 100%;
		}
	}
	.bnrShareNo1Ttl {
		margin-bottom: 10px;
	}
	.bnrShareNo1Ttl p {
		font-size: 20px;
		line-height: 1.2;
	}
	@media only screen and (max-width: 768px) {
		.bnrShareNo1Ttl p {
			font-size: 16px;
		}
	}
	.bnrShareNo1Ttl .txtL {
		font-size: 36px;
	}
	@media only screen and (max-width: 768px) {
		.bnrShareNo1Ttl .txtL {
			font-size: 30px;
		}
	}
	.bnrShareNo1Ttl .txtS {
		font-size: 12px;
		display: inline-block;
		margin-left: 20px;
	}
	@media only screen and (max-width: 999px) {
		.bnrShareNo1Ttl .txtS {
			display: block;
			margin-left: 0;
		}
	}
	.bnrShareNo1Txt{
		line-height: 1.6;
	}
	@media only screen and (max-width: 767px) {
		.bnrShareNo1Txt{
			font-size: 12px;;
		}
	}
	.page.dplustop .cardImage > img {
		margin-top: -1px;
	}
</style>
		<div class="contentBox">
			<div class="gryBdr4px paddBlock10 mb15">
				<div class="bnrShareNo1 cfx">
					<div class="bnrShareNo1Img"><img src="/directplus_ent/images/bnr_share_no1.png"></div>
					<div class="bnrShareNo1Ttl">
						<p><span class="bold">皆様のご愛顧に感謝申し上げます：x86サーバー 国内市場 シェア<span class="txtL">No.1</span></span><span class="txtS">2020年度第4四半期 国内x86サーバー市場 工場出荷台数</span></p>
					</div>
					<div class="bnrShareNo1Txt">
						<p>日本ヒューレット・パッカードは、IT専門調査会社「IDC Japan」が実施した「IDC Quarterly Server Tracker 2020Q4 (Share by Company)」において、x86サーバー市場 出荷台数で国内シェアNo.1を獲得しました。</p>
					</div>
				</div>
			</div>
		</div>-->
