<div class="mb40WithBorder">
						<h2 class="f24 bold dashed-text" id="CaseStudy">導入事例 ～お客様のサーバー活用法をご紹介</h2>
						<p class="mb20"><!--#include virtual="/comm/include/directplus_name.inc" --> オンラインストアでご購入いただいたお客様の導入事例です。<br>
						お客様がHPE ProLiant サーバーを始めとするHPEのITテクノロジーを、どのように活用されているかをご紹介します。</p>
						<div class="column33-33-33 cfx">
							<div class="clm1 casestudyWithThumb">
								<div class="caseThumb">
									<a href="/directplus_ent/casestudy/yamazaki.html?ref=dplustopcasestudy2"><img src="/directplus_ent/images/thumb_casestudy_yamazaki.jpg" alt=""></a>
								</div>
								<div class="caseTxt">
									<h4 class="f16 bold mb10">
										建築・建設
									</h4>
									<p class="mb10">
										山﨑建設株式会社様<br>
										OSのサポート終了を見越しWindows Server 2016への移行をBIシステムから先行してスタート
									</p>
									<p>
										採用製品：<a href="/directplus_ent/server/dl325gen10/?ref=dplustopcasestudy3">HPE ProLiant DL325 Gen10</a>
									</p>
								</div>
								<div class="mt10">
									<a href="/directplus_ent/casestudy/yamazaki.html?ref=dplustopcasestudy4"><span class="cta-link"><em class="icon-arrow-circle-right"></em>詳しくはこちら</a>
								</div>
							</div>
							<div class="clm2 casestudyWithThumb">
								<div class="caseThumb">
									<a href="https://www.hpe.com/jp/ja/customer-case-studies/servers-proliant-gotlilabs.html?ref=dplustopcasestudy5"><img src="/directplus_ent/images/thumb_casestudy_gotlilabs.jpg" alt=""></a>
								</div>
								<div class="caseTxt">
									<h4 class="f16 bold mb10">
										ソフトウェア開発
									</h4>
									<p class="mb10">
										ゴトリラボス 様<br>
										クリーニング／リネンサプライ業界のスマート工場化を推進
									</p>
									<p>
										採用製品：<a href="/directplus_ent/optoku/ml110gen10/?ref=dplustopcasestudy6">HPE ProLiant ML110 Gen10</a>
									</p>
								</div>
								<div class="mt10">
									<a href="https://www.hpe.com/jp/ja/customer-case-studies/servers-proliant-gotlilabs.html?ref=dplustopcasestudy7"><span class="cta-link"><em class="icon-arrow-circle-right"></em>詳しくはこちら</a>
								</div>
							</div>
							<div class="clm3 casestudyWithThumb">
								<div class="caseThumb">
									<a href="/directplus_ent/casestudy/nakamura.html?ref=dplustopcasestudy8"><img src="/directplus_ent/images/thumb_casestudy_nakamura.jpg" alt=""></a>
								</div>
								<div class="caseTxt">
									<h4 class="f16 bold mb10">
										医療
									</h4>
									<p class="mb10">
										医療法人HSR名嘉村クリニック 様<br>
										電子カルテシステム用ファイルサーバーとして、<!--#include virtual="/comm/include/directplus_name.inc" -->で要件に最適な構成のサーバーを調達
									</p>
									<p>
										採用製品：<a href="/directplus_ent/server/dl360gen10/?ref=dplustopcasestudy9">HPE ProLiant DL360 Gen10</a>
									</p>
								</div>
								<div class="mt10">
									<a href="/directplus_ent/casestudy/nakamura.html?ref=dplustopcasestudy10"><span class="cta-link"><em class="icon-arrow-circle-right"></em>詳しくはこちら</a>
								</div>
							</div>
						</div>
						<div class="alignCtr mt10">
							<a href="/directplus_ent/casestudy/?ref=dplustopcasestudy1" role="button" class="btn btn-secondary">お客様事例一覧はこちら</a>
						</div>
					</div><!-- End Case study -->

					
					<div class="mb40WithBorder column50-50 cfx">
						<div class="clm1">
							<img src="/directplus_ent/images/common/intel_xeon_gold_inside_200x200.png" height="100" alt="intel&reg; XEON&reg; inside&trade;" class="m0auto">
							<div style="height: 20px;"></div>
							<p class="f16 bold">インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> プロセッサー・スケーラブル・ファミリー搭載</p>
							<p class="f14">インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> プロセッサー・スケーラブル・ファミリー搭載モデルをラインアップ。オフィスに最適な性能とセキュリティ、信頼性、拡張性を備えています。</p>
						</div>
						<div class="clm2">
							<img src="/directplus_ent/images/common/microsoft_600x200.png" height="100" alt="Microsoft" class="m0auto">
							<div class="spHide" style="height: 20px;"></div>
							<p class="f16">
								<span class="bold">Windows Server 2022:</span>
								Be cloud ready with hybrid.
							</p>
						</div>
					</div>