<div class="boxArea network mb40">
	<h2 class="mb20 bold">ネットワーク</h2>
	
	<div class="boxItemsWrapper mb10">
		
		<div class="boxItems col2 mb10">
			
			<a class="boxItem noImg noBg" href="/directplus_ent/network/?ref=dplustopnetwork1">
				<span class="cta-link">
					<em class="icon-arrow-circle-right"></em>ラインアップで選ぶ
				</span>
			</a>
			
			<div class="boxItem">
				<div class="boxItemChildren network">
					<a class="boxItemChild withImg accessPoint" href="/directplus_ent/network/?ref=dplustopnetwork2&hash=AccessPoint">
						<span class="cta-link">
							<em class="icon-arrow-circle-right"></em>HPE Aruba アクセスポイント
						</span>
					</a>
					
					<a class="boxItemChild withImg switch" href="/directplus_ent/network/?ref=dplustopnetwork3&hash=Switch">
						<span class="cta-link">
							<em class="icon-arrow-circle-right"></em>HPE Aruba スイッチ
						</span>
					</a>
				</div>
			</div>
			
		</div>
		
	</div>
	
</div>