<div class="bgSteel">
			<div class="contentBox directplusMerit">
				<h2 class="f24 white mb20 bold">まずは<!--#include virtual="/comm/include/directplus_name.inc" -->でお見積を</h2>
				<p class="white mb20">
					<!--#include virtual="/comm/include/company_name_body_utf8.inc" -->（HPE）が運営する「<!--#include virtual="/comm/include/directplus_name.inc" -->」は、公式オンラインストアならではのメリットが満載です。<br>
					お見積からご購入までWebサイトで完結！もちろんコールセンターでも対応いたします。<br>
					また、日頃お取引のあるHPE販売パートナー様へのご発注時には、作成したお見積の構成IDをお使いいただけるので便利です。
				</p>
				<ul class="horizontalList">
					<li><a href="/directplus_ent/beginner/" role="button" class="btn btn-tertiary alpha">はじめての方へ</a></li>
					<li><a href="/directplus_ent/salessupport/" role="button" class="btn btn-tertiary alpha">販売パートナー様へ</a></li>
					<li><a href="/directplus_ent/guide/" role="button" class="btn btn-tertiary alpha">ご利用ガイド</a></li>
				</ul>
			</div>
		</div>
		<div class="bgSlate mb40">
			<div class="contentBox directplusMerit">
				<div class="meritIconsArea hasDetailBtn">
					<h2 class="f24 white bold"><!--#include virtual="/comm/include/directplus_name.inc" -->で購入する5つのメリット</h2>
					<div class="detailBtnArea">
						<a href="/directplus_ent/promotion/merit/" class="btn btn-tertiary alpha" role="button">詳しくはこちら</a>
					</div>
					<ul class="meritIcons columnFixWidth gutter15Right">
						<li>
							<a href="/directplus_ent/promotion/merit/?hash=merit01" class="utility-link">
								<div class="meritIcon merit01Icon">
									<img src="/directplus_ent/promotion/merit/images/icon_01.png" alt="">
								</div>
								<div class="meritTitle merit01Title">5営業日の短納期</div>
							</a>
						</li>
						<li>
							<a href="/directplus_ent/promotion/merit/?hash=merit02" class="utility-link">
								<div class="meritIcon merit02Icon">
									<img src="/directplus_ent/promotion/merit/images/icon_02.png" alt="">
								</div>
								<div>
									<div class="meritTitle merit02Title">フルカスタマイズ</div>
									<span class="f12">組み込み、OSインストールも無償<sup>※</sup></span>
								</div>
							</a>
						</li>
						<li>
							<a href="/directplus_ent/promotion/merit/?hash=merit03" class="utility-link">
								<div class="meritIcon merit03Icon">
									<img src="/directplus_ent/promotion/merit/images/icon_03.png" alt="">
								</div>
								<div class="meritTitle merit03Title">信頼の日本生産<sup>※</sup></div>
							</a>
						</li>
						<li>
							<ul class="columnFixHeight gutter15">
								<li>
									<a href="/directplus_ent/promotion/merit/?hash=merit04" class="utility-link">
										<div class="meritIcon merit04Icon">
											<img src="/directplus_ent/promotion/merit/images/icon_04.png" alt="">
										</div>
										<div class="meritTitle merit04Title">いつもお得な<br>キャンペーン</div>
									</a>
								</li>
								<li>
									<a href="/directplus_ent/promotion/merit/?hash=merit05" class="utility-link">
										<div class="meritIcon merit05Icon">
											<img src="/directplus_ent/promotion/merit/images/icon_05.png" alt="">
										</div>
										<div class="meritTitle merit05Title">豊富な<br>購入経路</div>
									</a>
								</li>
							</ul>
						</li>
					</ul>
					<p class="alignRgt f12 white">※フルカスタマイズCTO対応のみ</p>
				</div>
			</div>
		</div><!-- End Directplus merit -->