<h4 class="mb40"><a href="/directplus_ent/campaign/">お得なキャンペーン</a></h4>

<h4>サーバー導入をご検討中のお客様へ</h4>
					<ul class="rightNavLink">
						<li><a href="/doc/catalog/proliant/pdfs/jpc13797.pdf">HPEのサーバーを選ぶ理由</a></li>
						<li><a href="/directplus_ent/promotion/25years_of_proliant/">HPE ProLiantの設計思想</a></li>
						<li><a href="/directplus_ent/pdfs/estimate_online.pdf">HPE DirectPlusを使うメリット</a></li>
						<li><a href="/directplus_ent/casestudy/">導入事例 ～お客様のサーバー活用法をご紹介</a></li>
						<li><a href="/directplus_ent/promotion/tokuhon/">知っているだけで&quot;得する&quot;サーバーの最新テクノロジー</a></li>
						<li><a href="/directplus_ent/server/features.html">最新テクノロジーを解説、サーバー記事特集</a></li>
					</ul>
