<h4>お客様サポート</h4>
					<ul class="rightNavLink">
						<li><a href="/directplus_ent/guide/payment/estimates_01.html?refdplus=0056">お見積り作成</a></li>
						<li><a href="/directplus_ent/guide/payment/?refdplus=0057">お支払い方法</a></li>
						<li><a href="/directplus_ent/guide/delivery/delivery02.html?refdplus=0058">納品スケジュール</a></li>
						<li><a href="/directplus_ent/guide/delivery/delivery03.html?refdplus=0059">配送料について</a></li>
						<li><a href="/directplus_ent/guide/delivery/delivery04.html?refdplus=0060">注文状況の確認</a></li>
						<li><a href="/directplus_ent/guide/?refdplus=0061">ご利用ガイド</a></li>
						<li><a href="/directplus_ent/faq/?refdplus=0062">よくあるご質問</a></li>
						<li><a href="/directplus_ent/contact/?refdplus=0063">お問い合わせ</a></li>
					</ul>