<div class="mb20WithBorder column50-50 cfx">
				<div class="clm1">
					<img src="/directplus_ent/images/common/intel_xeon_gold_inside_200x200.png" height="100" alt="intel&reg; XEON&reg; inside&trade;" class="m0auto">
					<div style="height: 20px;"></div>
					<p class="f16 bold">インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> プロセッサー・スケーラブル・ファミリー搭載</p>
					<p class="f14">インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> プロセッサー・スケーラブル・ファミリー搭載モデルをラインアップ。オフィスに最適な性能とセキュリティ、信頼性、拡張性を備えています。</p>
				</div>
				<div class="clm2">
					<img src="/directplus_ent/images/common/microsoft_600x200.png" height="100" alt="Microsoft" class="m0auto">
					<div class="spHide" style="height: 20px;"></div>
					<p class="f16">
						<span class="bold">Windows Server 2022:</span>
						Be cloud ready with hybrid.
					</p>
				</div>
			</div>
			<!--#include virtual="/directplus_ent/system/includes/dpb_totop_responsive.inc" -->
			
			<div class="mb65">
				<p>
					Intel、Intelロゴ、Intel Insideロゴ、およびXeonは、Intel Corporationまたはその子会社の商標です。
				</p>
			</div>