<meta http-equiv="content-language" content="ja-jp"/>
	<meta http-equiv="content-style-type" content="text/css"/>
	<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
	<meta name="format-detection" content="telephone=no"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">

	<link href="/hpe-favicon-16.ico" rel="shortcut icon" type="image/ico">
	<link href="/hpe-favicon-16.png" rel="apple-touch-icon" type="image/png">
	
	<link rel="stylesheet" type="text/css" href="/directplus_ent/system/styles/dp_responsive_main.css?update=20220214">
	
	<script type="text/javascript" language="javascript">
	var cann_url = location.href;
	var s_idx = cann_url.indexOf('#');
	var q_idx = cann_url.indexOf('?');
	var sep_idx = -1;

	if (s_idx < q_idx){
		sep_idx = q_idx;
	} else if  (q_idx < s_idx){
		sep_idx = s_idx;
	}

	if (sep_idx != -1){
		cann_url = cann_url.substr(0,sep_idx);
	}
	if (cann_url.indexOf('/index.html') != -1){
		cann_url = cann_url.substr(0,cann_url.indexOf('/index.html')+1);
	}

	var head   = document.getElementsByTagName("head")[0] || document.documentElement;
	var meta   = document.createElement('link');
	meta.setAttribute("rel", "canonical");
	meta.setAttribute("href",cann_url);
	head.appendChild(meta);
	</script>