<style>
.bnr_hp_dp {
	border: 1px solid #ccc;
	margin-bottom: 40px;
}
.bnr_hp_dp img {
	margin: auto;
}
.bnr_hp_dp_link {
	text-align: center;
}
.bnr_hp_dp_link .bnrTitle {
	font-size: 16px;
	font-weight: bold;
	margin: 10px 0 5px;
}
.bnr_hp_dp_link .cta-link {
	font-size: 13px;
}
@media only screen and (min-width: 768px) {
	.bnr_hp_dp_link {
		text-align: left;
		display: flex;
		align-items: center;
	}
	.bnr_hp_dp_link > * {
		flex: 1;
	}
	.bnr_hp_dp_link > *:first-child {
		flex-grow: 0;
		margin: 0 40px 0 30px;
	}
	.bnr_hp_dp_link .bnrTitle {
		font-size: 22px;
		margin: 0 0 5px;
	}
	.bnr_hp_dp_link .cta-link {
		font-size: 16px;
	}
}
@media only screen and (min-width: 900px) {
	.bnr_hp_dp_link > *:first-child {
		flex-grow: 0;
		margin: 0 20px 0 10px;
	}
}

</style>
<div class="bnr_hp_dp gryBdr2px paddBlock10 lhMid">
	<a href="https://jp.ext.hp.com/directplus/business/smb/?jumpid=nm_vgrxuinf2h" target="_blank" class="bnr_hp_dp_link">
		<img src="/directplus_ent/images/bnr_hp_dp.jpg" alt="">
		<div class="bnrTxt">
			<div class="bnrTitle">
				パソコン・プリンターの<br class="br768">お見積・ご注文は<br class="br414">「HP Directplus」
			</div>
			<span class="cta-link">
				<em class="icon-arrow-circle-right"></em>株式会社 日本HPが運営する<br class="br320">オンラインストアはこちら
			</span>
		</div>
	</a>
</div>