<h4>お得なキャンペーン</h4>
					<ul class="rightNavLink">
						<li><a href="/directplus_ent/campaign/?ref=dplustopsidenavi1">現在実施中のキャンペーン</a></li>
					</ul>
					
					<h4>サーバー導入をご検討中のお客様へ</h4>
					<ul class="rightNavLink">
						<li><a href="/directplus_ent/server/advice.html?ref=dplustopsidenavi27">サーバー導入前のアドバイス</a></li>
						<li><a href="/doc/catalog/proliant/pdfs/jpc13797.pdf">HPEのサーバーを選ぶ理由</a></li>
						<li><a href="/directplus_ent/promotion/25years_of_proliant/?ref=dplustopsidenavi3">HPE ProLiantの設計思想</a></li>
						<li><a href="/directplus_ent/promotion/merit/?ref=dplustopsidenavi4">HPE DirectPlusを使うメリット</a></li>
						<li><a href="/directplus_ent/pdfs/estimate_online.pdf" target="_blank">HPE DirectPlus 店長のオススメポイント[PDF]</a></li>
						<li><a href="/directplus_ent/casestudy/?ref=dplustopsidenavi6">導入事例 ～お客様のサーバー活用法をご紹介</a></li>
						<li><a href="/directplus_ent/server/features.html?ref=dplustopsidenavi8">最新テクノロジーを解説、サーバー記事特集</a></li>
					</ul>
					
					<h4>製品ガイド</h4>
					<ul class="rightNavLink">
						<li><a href="https://www.hpe.com/jp/ja/doc/general-catalog.html?ref=dplustopsidenavi9" target="_blank">プロダクトセレクション(総合カタログ)</a></li>
						<li><a href="https://www.hpe.com/jp/ja/doc/server-system.html?ref=dplustopsidenavi10" target="_blank">サーバーシステム構成図</a></li>
						<li><a href="/doc/catalog/proliant/?ref=dplustopsidenavi11" target="_blank">サーバー製品カタログ</a></li>
						<li><a href="https://h50146.www5.hpe.com/doc/manual/proliant/soft.html?ref=dplustopsidenavi12" target="_blank">サーバー製品マニュアル</a></li>
					</ul>
					
					<h4>製品カテゴリ</h4>
					<ul class="rightNavLink">
						<li><a href="/directplus_ent/server/?ref=dplustopsidenavi13">サーバー</a></li>
						<li><a href="/directplus_ent/storage/?ref=dplustopsidenavi14">ストレージ</a></li>
						<li><a href="/directplus_ent/network/?ref=dplustopsidenavi15">ネットワーク</a></li>
						<li><a href="/directplus_ent/supportservice/?ref=dplustopsidenavi16">サポートサービス</a></li>
						<li><a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e">オプション</a></li>
						<li><a href="/directplus_ent/os_software/?ref=dplustopsidenavi28">OS/ソフトウェア</a></li>
					</ul>
					
					<h4>お客様サポート</h4>
					<ul class="rightNavLink">
						<li><a href="/directplus_ent/guide/payment/estimates_01.html?ref=dplustopsidenavi19">お見積り作成</a></li>
						<li><a href="/directplus_ent/guide/payment/?ref=dplustopsidenavi20">お支払い方法</a></li>
						<li><a href="/directplus_ent/guide/delivery/delivery02.html?ref=dplustopsidenavi21">納品スケジュール</a></li>
						<li><a href="/directplus_ent/guide/delivery/delivery03.html?ref=dplustopsidenavi22">配送料について</a></li>
						<li><a href="/directplus_ent/guide/delivery/delivery04.html?ref=dplustopsidenavi23">注文状況の確認</a></li>
						<li><a href="/directplus_ent/guide/?ref=dplustopsidenavi24">ご利用ガイド</a></li>
						<li><a href="/directplus_ent/faq/?ref=dplustopsidenavi25">よくあるご質問</a></li>
						<li><a href="/directplus_ent/contact/?ref=dplustopsidenavi26">お問い合わせ</a></li>
					</ul>