<div class="ranking2Area mb20WithBorder recommendServer">
	<h2 class="bold dashed-text" id="Ranking">おすすめサーバー</h2>
	<div class="rankItems">
		
		<div class="rankItem rank1">
			<a href="/directplus_ent/server/dl20gen10plus/?ref=dplustopranking13">
				<div class="rankItemHeader">
					<div class="rankItemNum"><span>1</span>位</div>
					<div class="rankItemName"><span>HPE ProLiant </span><br class="brUpper768"><span>DL20 Gen10 Plus</span></div>
				</div>
				<div class="rankItemImg">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp3_dl20_gen10_plus_optoku.jpg" alt="" class="pcImg">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl20_gen10_plus_optoku.gif" alt="" class="spImg">
				</div>
			</a>
			<div class="rankItemTxt">
				<div class="spTxt">
					 オプ得モデル
				</div>
				<!--<a href="/directplus_ent/server/dl20gen10plus/?ref=dplustopranking13" role="button" class="btn btn-secondary"><span class="pcTxt">通常モデル </span>336,000円(税抜)～</a>-->
				<!--<div class="pcTxt">
					<p class="minPrice">
						通常モデル最小構成価格 252,000円(税抜)～
					</p>
					<p class="optokuPrice">
						オプ得モデル<span class="strikethrough">207,000円(税抜)～</span>
					</p>
				</div>
				<div class="spTxt">
					最小構成価格
				</div>
				<a href="/directplus_ent/optoku/ml110gen10/?ref=dplustopranking8" role="button" class="btn btn-secondary"><span class="pcTxt">期間限定 </span>176,000円(税抜)～</a>-->
				<div class="pcTxt">
					<p class="minPrice">
						通常モデル最小構成価格 336,000円(税抜)～
					</p>
				</div>
				<a href="/directplus_ent/server/dl20gen10plus/?ref=dplustopranking13" role="button" class="btn btn-secondary"><span class="pcTxt">オプ得モデル </span>296,000円(税抜)～</a>
			</div>
		</div>
		
		<div class="rankItem rank2">
			<a href="/directplus_ent/server/ml30gen10plus/?ref=dplustopranking14">
				<div class="rankItemHeader">
					<div class="rankItemNum"><span>2</span>位</div>
					<div class="rankItemName"><span>HPE ProLiant </span><br class="brUpper768"><span>ML30 </span><span>Gen10 Plus</span></div>
				</div>
				<div class="rankItemImg">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp3_ml30_gen10_plus_optoku.jpg" alt="" class="pcImg">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_ml30_gen10_plus_optoku.gif" alt="" class="spImg">
				</div>
			</a>
			<div class="rankItemTxt">
				<div class="spTxt">
					 オプ得モデル
				</div>
				<div class="pcTxt">
					<p class="minPrice">
						通常モデル最小構成価格 247,000円(税抜)～
					</p>
				</div>
				<a href="/directplus_ent/server/ml30gen10plus/?ref=dplustopranking14" role="button" class="btn btn-secondary"><span class="pcTxt">オプ得モデル </span>216,000円(税抜)～</a>
			</div>
		</div>
		
		<div class="rankItem rank3">
			<a href="/directplus_ent/server/dl360gen10/?ref=dplustopranking9">
				<div class="rankItemHeader">
					<div class="rankItemNum"><span>3</span>位</div>
					<div class="rankItemName"><span>HPE ProLiant </span><span>DL360 Gen10</span></div>
				</div>
				<div class="rankItemImg">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp3_dl360_gen10.jpg" alt="" class="pcImg">
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl360_gen10.gif" alt="" class="spImg">
				</div>
			</a>
			<div class="rankItemTxt">
				<!--<div class="pcTxt">
					<p class="minPrice">
						通常モデル最小構成価格 548,000円(税抜)～
					</p>
				</div>
				<div class="spTxt">
					最小構成価格
				</div>
				<a href="/directplus_ent/server/dl360gen10/?ref=dplustopranking10" role="button" class="btn btn-secondary"><span class="pcTxt">期間限定 </span>385,000円(税抜)～</a>-->
				<!--<div class="pcTxt">
					<p class="minPrice">
						通常モデル最小構成価格 494,000円(税抜)～
					</p>
				</div>-->
				<div class="spTxt">
					通常モデル
				</div>
				<a href="/directplus_ent/server/dl360gen10/?ref=dplustopranking10" role="button" class="btn btn-secondary"><span class="pcTxt">通常モデル </span>494,000円(税抜)～</a>
			</div>
		</div>
		
	</div>
</div><!-- End Ranking -->
