<div class="boxArea supportservice mb40">
	<h2 class="mb20 bold">サポートサービス</h2>
	
	<div class="boxItemsWrapper mb10">
		
		<div class="boxItems col2 mb10">
			
			<a class="boxItem noImg noBg" href="/directplus_ent/supportservice/?ref=dplustopsupportservice1">
				<span class="cta-link">
					<em class="icon-arrow-circle-right"></em>ラインアップで選ぶ
				</span>
			</a>
			
			<div class="boxItem hideSpOnly">
				<h3 class="f18 mb10 bold">サポートサービス購入をお勧めする3つのポイント</h3>
				<!--#include virtual="/directplus_ent/system/includes/dpb_top_support_responsive_techcare_inner.inc" -->
			</div>
			
		</div>
		
	</div>
	
</div>