<h4 class="guideLftNavHeader icon-cart"><!--#include virtual="/comm/include/directplus_name.inc" -->とは？</h4>
					<ul class="leftNavLink">
						<li><a href="/directplus_ent/beginner/"><!--#include virtual="/comm/include/directplus_name.inc" -->とは</a></li>
						<li><a href="/directplus_ent/promotion/merit/"><!--#include virtual="/comm/include/directplus_name.inc" -->で購入するメリット</a></li>
						<li><a href="/directplus_ent/guide/intro/?hash=intro01">ご利用の前に</a></li>
						<li><a href="/directplus_ent/guide/intro/?hash=intro02"><!--#include virtual="/comm/include/directplus_name.inc" -->の責任者および本社所在地</a></li>
					</ul>
					<h4 class="guideLftNavHeader icon-search">製品を探す</h4>
					<ul class="leftNavLink">
						<li><a href="/directplus_ent/guide/product_search/?hash=search01">製品カテゴリから選ぶ</a></li>
						<li><a href="/directplus_ent/guide/product_search/?hash=search02">お得なキャンペーンを選ぶ</a></li>
						<li><a href="/directplus_ent/server/">スペックで選ぶ</a></li>
						<li><a href="/directplus_ent/server/purpose/file.html">用途で選ぶ</a></li>
						<li><a href="/directplus_ent/server/search/index.asp">HPE プロダクトセレクションから選ぶ</a></li>
					</ul>
					<h4 class="guideLftNavHeader icon-customize">製品をカスタマイズ</h4>
					<ul class="leftNavLink">
						<li><a href="/directplus_ent/guide/customize/">カスタマイズ&nbsp;&amp;&nbsp;カートに入れる（サーバー製品）</a></li>
						<li><a href="/directplus_ent/guide/customize/custom_02.html">カートの中身を確認</a></li>
						<li><a href="/directplus_ent/guide/customize/custom_03.html">サーバー製品以外を単品で購入する場合のご注文方法<br>（ストレージ/ネットワーク/サポートサービス/オプション）</a></li>
					</ul>
					<h4 class="guideLftNavHeader icon-person">ログイン／お客様登録／ゲスト登録／登録内容の変更</h4>
					<ul class="leftNavLink">
						<li><a href="/directplus_ent/guide/login/">ログインする</a></li>
						<li><a href="/directplus_ent/guide/login/login_02.html">お客様登録をする</a></li>
						<li><a href="/directplus_ent/guide/login/login_03.html">ゲスト登録をする</a></li>
						<li><a href="/directplus_ent/guide/login/login_04.html">登録内容の変更</a></li>
						<li><a href="/directplus_ent/guide/login/login_05.html">納品先の変更</a></li>
					</ul>
					<h4 class="guideLftNavHeader icon-cost">お支払い、お見積</h4>
					<ul class="leftNavLink">
						<li><a href="/directplus_ent/guide/payment/">お見積作成・お支払方法の選択</a></li>
						<li><a href="/directplus_ent/guide/payment/pay_cash.html">現金前振込みでのお支払い</a></li>
						<li><a href="/directplus_ent/guide/payment/pay_card.html">クレジットカードでのお支払い</a></li>
						<li><a href="/directplus_ent/guide/payment/pay_credit.html?hash=Online">掛売り（オンライン）でのお申込み</a></li>
						<li><a href="/directplus_ent/guide/payment/pay_credit.html?hash=Call">掛売り（お電話）でのお申込み</a></li>
						<li><a href="/directplus_ent/guide/payment/estimates_01.html">見積書作成</a></li>
						<li><a href="/directplus_ent/guide/payment/estimates_02.html">見積り構成の確認</a></li>
					</ul>
					<h4 class="guideLftNavHeader icon-delivery">ご納品・配送について</h4>
					<ul class="leftNavLink">
						<li><a href="/directplus_ent/guide/delivery/">ご注文からご納品まで</a></li>
						<li><a href="/directplus_ent/guide/delivery/delivery02.html">納品スケジュール</a></li>
						<li><a href="/directplus_ent/guide/delivery/delivery03.html">配送料について</a></li>
						<li><a href="/directplus_ent/guide/delivery/delivery04.html">注文状況の確認</a></li>
					</ul>
					<h4 class="guideLftNavHeader icon-rack">製品到着後、その他サービス</h4>
					<ul class="leftNavLink">
						<li><a href="/directplus_ent/guide/henpin/">着荷時不良について</a></li>
						<li><a href="/directplus_ent/guide/henpin/henpin01.html">保証内容の確認</a></li>
						<li><a href="/directplus_ent/guide/henpin/receipt.html">領収書表示サービス</a></li>
						<li><a href="/directplus_ent/guide/cpreg/">サポートサービス製品お客様登録に関して</a></li>
					</ul>
					<h4 class="guideLftNavHeader icon-question">FAQ</h4>
					<ul class="leftNavLink">
						<li><a href="/directplus_ent/faq/">よくあるご質問</a></li>
					</ul>