<div class="productsCategory mb40WithBorder hideSpOnly">
				<h2 class="bold dashed-text"><!--#include virtual="/comm/include/directplus_name.inc" --> <br class="br414">お取り扱い商品カテゴリ</h2>
				<div class="categoryList">
					<a href="/directplus_ent/server/?ref=dplustopcategory1" class="categoryServer">
						<div class="categoryName">サーバー</div>
					</a>
					<a href="/directplus_ent/storage/?ref=dplustopcategory2" class="categoryStorage">
						<div class="categoryName">ストレージ</div>
					</a>
					<a href="/directplus_ent/network/?ref=dplustopcategory3" class="categoryNetwork">
						<div class="categoryName">ネットワーク</div>
					</a>
					<a href="/directplus_ent/supportservice/?ref=dplustopcategory4" class="categorySupportservice">
						<div class="categoryName">サポートサービス</div>
					</a>
					<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e" class="categoryOption">
						<div class="categoryName">オプション</div>
					</a>
				</div>
			</div><!-- End Products category -->