<div class="mb40WithBorder column50-50 cfx">
    <div class="clm1">
        <img src="/directplus_ent/images/common/intel_xeon_inside_200x200.png" height="100" alt="intel&reg; XEON&reg; inside&trade;" class="m0auto">
        <div style="height: 20px;"></div>
        <p class="f16 bold">インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー搭載</p>
        <p class="f14">HPE ProLiant MicroServer Gen10 Plusは、インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> プロセッサー搭載モデルをラインアップ。極小筐体ながら、エントリーレベルのサーバーに必要不可欠な性能を備えています。</p>
    </div>
    <div class="clm2">
        <img src="/directplus_ent/images/common/microsoft_600x200.png" height="100" alt="Microsoft" class="m0auto">
        <div class="spHide" style="height: 20px;"></div>
        <p class="f16">
            <span class="bold">Windows Server 2022:</span>
            Be cloud ready with hybrid.
        </p>
    </div>
</div>
