<div class="mb40">
				<div class="column33-66 cfx mb20">
					<div class="clm1">
						<div class="contactUsIconTel">
							<p class="f28 bold lhMin mb5"><span data-action="call" data-tel="0120-215-542">0120-215-542</span></p>
							<p class="f14 lhMin">フリーダイヤルをご利用できない場合<br><span class="f20 bold"><span data-action="call" data-tel="03-6743-6355">03-6743-6355</span></span></p>
						</div>
					</div>
					<div class="clm2">
						<p>
							受付時間：月曜日～金曜日 9:00～19:00（土曜日、日曜日、祝日、年末年始、および5月1日 お休み）<br>
							応答メッセージが流れましたら1→2を押してください。 販売店のお客様で再販をご検討の方は、1→1を押してください。<!--<br>
							複数台導入のご相談もこちらにお電話ください。担当のスタッフが対応致します。-->
						</p>
					</div>
				</div>
				<div class="contactUsIconMail">
					<p>お見積・ご購入のご相談・製品に関するご質問などにEメールでご返答いたします。</p>
					<a href="https://www.hpe.com/h41268/live/index_e.aspx?qid=8812" target="_blank" role="button" class="btn btn-secondary">WEBフォームはこちら</a>
				</div>
			</div>