<style>
.hpeBlogLink {
	height: 120px;
	overflow-y: scroll;
	-ms-overflow-style: scroll;
}
@supports (-ms-ime-align: auto){
	.hpeBlogLink > a.linkWithArrow .arrow,
	.hpeBlogLink > .hasLinkWithArrow .arrow {
		transition: all 0.2s ease-out;
		position: absolute;
		right: -12px;
	}
	.hpeBlogLink > a.linkWithArrow:hover .arrow,
	.hpeBlogLink > .hasLinkWithArrow:hover .arrow {
		right: -17px;
	}
}
@media all and (-ms-high-contrast: none){
	.hpeBlogLink > a.linkWithArrow .arrow,
	.hpeBlogLink > .hasLinkWithArrow .arrow {
		transition: all 0.2s ease-out;
		position: absolute;
		right: -12px;
	}
	.hpeBlogLink > a.linkWithArrow:hover .arrow,
	.hpeBlogLink > .hasLinkWithArrow:hover .arrow {
		right: -17px;
	}
}

</style>
<div class="hpeBlogs mb40" id="hpeBlog">
	<div class="hpeBlog gryBdr4px paddBlock15">
		<div class="f20 bold mb10">日本ヒューレット・パッカード公式ブログ</div>
		<div class="hpeBlogLink">
			<a href="https://community.hpe.com/t5/HPE-Blog-Japan/%E9%80%A3%E8%BC%89-%E7%94%A3%E6%A5%AD%E5%88%A5%E3%82%BD%E3%83%AA%E3%83%A5%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3-TELCO-vRAN%E7%B7%A8/ba-p/7165145#.YpB32ajP1hE" target="_blank" class="linkWithArrow">【連載 : 産業別ソリューション】TELCO – vRAN編<span class="arrow">→</span></a><br>
			<a href="https://community.hpe.com/t5/HPE-Blog-Japan/HPE-ProLiant%E3%81%A8Windows-Server-2022%E3%81%AE%E3%82%BB%E3%82%AD%E3%83%A5%E3%83%AA%E3%83%86%E3%82%A3%E3%83%88%E3%83%AC%E3%83%BC%E3%83%8B%E3%83%B3%E3%82%B0%E3%83%93%E3%83%87%E3%82%AA%E3%82%92%E5%85%AC%E9%96%8B%E3%81%97%E3%81%BE%E3%81%97%E3%81%9F/ba-p/7163914#.YldsfejP1EY" target="_blank" class="linkWithArrow">HPE ProLiantとWindows Server 2022のセキュリティトレーニングビデオを公開しました！<span class="arrow">→</span></a><br>
			<a href="https://community.hpe.com/t5/HPE-Blog-Japan/Windows-Server%E3%81%A8HPE-ProLiant%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%81%AB%E5%AF%BE%E3%81%99%E3%82%8B%E3%82%B5%E3%83%9D%E3%83%BC%E3%83%88%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AE%E6%A6%82%E8%A6%81/ba-p/7162851#.Yld_hujP1EY" target="_blank" class="linkWithArrow">Windows ServerとHPE ProLiantサーバーに対するサポートオプションの概要<span class="arrow">→</span></a><br>
			<a href="https://community.hpe.com/t5/HPE-Blog-Japan/%E9%80%A3%E8%BC%89-HPE-ProLiant%E3%81%8C%E3%83%8F%E3%82%A4%E3%83%96%E3%83%AA%E3%83%83%E3%83%89%E3%82%AF%E3%83%A9%E3%82%A6%E3%83%89%E3%81%AE%E3%82%A4%E3%83%B3%E3%83%86%E3%83%AA%E3%82%B8%E3%82%A7%E3%83%B3%E3%83%88%E3%81%AA%E3%82%B3%E3%83%B3%E3%83%94%E3%83%A5%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%E5%9F%BA%E7%9B%A4%E3%81%A8%E3%81%AA%E3%82%8B10%E3%81%AE%E7%90%86%E7%94%B1/ba-p/7163497#.YldsgejP1EY" target="_blank" class="linkWithArrow">【連載】HPE ProLiantがハイブリッドクラウドのインテリジェントなコンピューティング基盤となる10の理由③：インテリジェントな自動化<span class="arrow">→</span></a><br>
			<a href="https://community.hpe.com/t5/HPE-Blog-Japan/%E9%80%A3%E8%BC%89-HPE-ProLiant%E3%81%8C%E3%83%8F%E3%82%A4%E3%83%96%E3%83%AA%E3%83%83%E3%83%89%E3%82%AF%E3%83%A9%E3%82%A6%E3%83%89%E3%81%AE%E3%82%A4%E3%83%B3%E3%83%86%E3%83%AA%E3%82%B8%E3%82%A7%E3%83%B3%E3%83%88%E3%81%AA%E3%82%B3%E3%83%B3%E3%83%94%E3%83%A5%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%E5%9F%BA%E7%9B%A4%E3%81%A8%E3%81%AA%E3%82%8B10%E3%81%AE%E7%90%86%E7%94%B1/ba-p/7163287#.Yld-5ujP1EY" target="_blank" class="linkWithArrow">【連載】HPE ProLiantがハイブリッドクラウドのインテリジェントなコンピューティング基盤となる10の理由②：全方位的なセキュリティ<span class="arrow">→</span></a><br>
			<a href="https://community.hpe.com/t5/HPE-Blog-Japan/%E9%80%A3%E8%BC%89-HPE-ProLiant%E3%81%8C%E3%83%8F%E3%82%A4%E3%83%96%E3%83%AA%E3%83%83%E3%83%89%E3%82%AF%E3%83%A9%E3%82%A6%E3%83%89%E3%81%AE%E3%82%A4%E3%83%B3%E3%83%86%E3%83%AA%E3%82%B8%E3%82%A7%E3%83%B3%E3%83%88%E3%81%AA%E3%82%B3%E3%83%B3%E3%83%94%E3%83%A5%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%E5%9F%BA%E7%9B%A4%E3%81%A8%E3%81%AA%E3%82%8B10%E3%81%AE%E7%90%86%E7%94%B1/ba-p/7162010#.Yi7LdXrP1EY" target="_blank" class="linkWithArrow">
				【連載】HPE ProLiantがハイブリッドクラウドのインテリジェントなコンピューティング基盤となる10の理由①：ワークロードの最適化<span class="arrow">→</span>
			</a><br>
			<a href="https://community.hpe.com/t5/HPE-Blog-Japan/%E3%82%A2%E3%83%B3%E3%82%B1%E3%83%BC%E3%83%88%E7%B5%90%E6%9E%9C-HPE-ProLiant%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%81%8C%E9%81%B8%E3%81%B0%E3%82%8C%E3%82%8B%E7%90%86%E7%94%B1/ba-p/7158358#.Yi7P83rP1EY" target="_blank" class="linkWithArrow">
				アンケート結果: HPE ProLiantサーバーが選ばれる理由<span class="arrow">→</span>
			</a><br>
			<a href="https://community.hpe.com/t5/HPE-Blog-Japan/%E3%81%93%E3%82%93%E3%81%AA%E3%83%A1%E3%83%AA%E3%83%83%E3%83%88%E3%81%8C%E3%81%82%E3%82%8B%E3%81%AA%E3%82%93%E3%81%A6-5%E5%96%B6%E6%A5%AD%E6%97%A5%E3%81%AE%E7%9F%AD%E7%B4%8D%E6%9C%9F-HPE-DirectPlus-Online-Store/ba-p/7153312#.Yi7SxXrP1EZ" target="_blank" class="linkWithArrow">
				こんなメリットがあるなんて：5営業日の短納期 HPE DirectPlus Online Store<span class="arrow">→</span>
			</a><br>
			<a href="https://community.hpe.com/t5/HPE-Blog-Japan/HPE-DirectPlus%E3%81%A7-%E5%AE%87%E5%AE%99%E3%82%92%E4%BD%93%E9%A8%93-%E3%83%95%E3%83%AB%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BACTO%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC/ba-p/7156578#.Yi7TQnrP1EZ" target="_blank" class="linkWithArrow">
				HPE DirectPlusで 宇宙を体験！？フルカスタマイズCTOサーバー<span class="arrow">→</span>
			</a><br>
			<a href="https://community.hpe.com/t5/HPE-Blog-Japan/Windows-Admin-Center%E3%81%AE%E6%9C%80%E6%96%B0%E6%83%85%E5%A0%B1/ba-p/7160222#.Yi7MvHrP1EY" target="_blank" class="linkWithArrow">
				Windows Admin Centerの最新情報<span class="arrow">→</span>
			</a><br>
			<a href="https://community.hpe.com/t5/HPE-Blog-Japan/Windows-Server-2022%E3%81%8C%E3%81%84%E3%82%88%E3%81%84%E3%82%88%E7%99%BB%E5%A0%B4%E3%81%97%E3%81%BE%E3%81%97%E3%81%9F-%E9%87%8D%E8%A6%81%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88%E3%82%92%E3%81%94%E7%B4%B9%E4%BB%8B%E3%81%97%E3%81%BE%E3%81%99/ba-p/7160193#.Yi7NQnrP1EY" target="_blank" class="linkWithArrow">
				Windows Server 2022がいよいよ登場しました — 重要ポイントをご紹介します<span class="arrow">→</span>
			</a><br>
			<a href="https://community.hpe.com/t5/HPE-Blog-Japan/Red-Hat-Partner-Awards-%E3%82%923%E5%B9%B4%E9%80%A3%E7%B6%9A%E3%81%A7%E5%8F%97%E8%B3%9E%E3%81%97%E3%81%BE%E3%81%97%E3%81%9F/ba-p/7160072#.Yi7N93rP1EY" target="_blank" class="linkWithArrow">
				Red Hat Partner Awards を3年連続で受賞しました！<span class="arrow">→</span>
			</a><br>
			<a href="https://community.hpe.com/t5/HPE-Blog-Japan/%E9%80%A3%E8%BC%89-%E7%94%A3%E6%A5%AD%E5%88%A5%E3%82%BD%E3%83%AA%E3%83%A5%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3-%E3%81%BE%E3%81%A8%E3%82%81%E3%83%AA%E3%83%B3%E3%82%AF%E9%9B%86/ba-p/7159940#.Yi7OrXrP1EY" target="_blank" class="linkWithArrow">
				【連載 : 産業別ソリューション】まとめリンク集<span class="arrow">→</span>
			</a><br>
			<a href="https://community.hpe.com/t5/forums/recentpostspage/post-type/message/user-id/2037274" target="_blank" class="linkWithArrow">
				【まとめ】HPE検証センターの若手エンジニア.log<span class="arrow">→</span>
			</a><br>
			<a href="https://community.hpe.com/t5/HPE-Blog-Japan/%E3%82%AA%E3%83%B3%E3%83%97%E3%83%AC%E3%83%9F%E3%82%B9%E3%81%8B%E3%82%AF%E3%83%A9%E3%82%A6%E3%83%89%E3%81%8B-%E3%81%9D%E3%82%8C%E3%81%A8%E3%82%82-%E5%8D%81%E5%88%86%E3%81%AA%E6%83%85%E5%A0%B1%E3%81%AB%E5%9F%BA%E3%81%A5%E3%81%84%E3%81%A6%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AE%E5%AE%9F%E8%A1%8C%E5%A0%B4%E6%89%80%E3%82%92%E6%B1%BA%E5%AE%9A/ba-p/7157999#.Yi7QiXrP1EY" target="_blank" class="linkWithArrow">
				オンプレミスかクラウドか、それとも? 十分な情報に基づいてアプリケーションの実行場所を決定<span class="arrow">→</span>
			</a><br>
			<a href="https://community.hpe.com/t5/HPE-Blog-Japan/bg-p/JapanEnterpriseTopics#.Yi7JjHrP1EZ" target="_blank" class="linkWithArrow">
				その他の記事はこちら<span class="arrow">→</span>
			</a>
		</div>
	</div>
</div>
