<h4>お客様サポート</h4>
					<ul class="leftNavLink">
						<li><a href="/directplus_ent/guide/payment/estimates_01.html">お見積り作成</a></li>
						<li><a href="/directplus_ent/guide/payment/">お支払い方法</a></li>
						<li><a href="/directplus_ent/guide/delivery/delivery02.html">納品スケジュール</a></li>
						<li><a href="/directplus_ent/guide/delivery/delivery03.html">配送料について</a></li>
						<li><a href="/directplus_ent/guide/delivery/delivery04.html">注文状況の確認</a></li>
						<li><a href="/directplus_ent/guide/">ご利用ガイド</a></li>
						<li><a href="/directplus_ent/faq/">よくあるご質問</a></li>
						<li><a href="/directplus_ent/contact/">お問い合わせ</a></li>
					</ul>