<h4>製品ガイド</h4>
					<ul class="rightNavLink">
						<li><a href="/doc/catalog/general/?refdplus=0064" target="_blank">プロダクトセレクション(総合カタログ)</a></li>
						<li><a href="https://www.hpe.com/jp/ja/doc/server-system.html?refdplus=0065" target="_blank">サーバーシステム構成図</a></li>
						<li><a href="/doc/catalog/proliant/?refdplus=0066" target="_blank">サーバー製品カタログ</a></li>
						<li><a href="/doc/manual/proliant/soft.html?refdplus=0067" target="_blank">サーバー製品マニュアル</a></li>
					</ul>