          <ul class="leftNavMemu spHide">
            <li class="level2"> <a href="/directplus_ent/network/">ラインアップで選ぶ</a>
              <ul class="level3">
                <li><a href="/directplus_ent/network/?hash=AccessPoint">アクセスポイント</a></li>
                <li><a href="/directplus_ent/network/?hash=Switch">スイッチ</a></li>
              </ul>
            </li>
          </ul>
          <h4>お得なキャンペーン</h4>
          <ul class="leftNavLink">
            <li><a href="/directplus_ent/campaign/">現在実施中のキャンペーン</a></li>
          </ul>
          <h4>ネットワーク製品ガイド</h4>
          <ul class="leftNavLink">
            <li><a href="https://www.hpe.com/jp/ja/doc/networking-system.html" target="_blank">ネットワークシステム構成図</a></li>
            <li><a href="https://www.hpe.com/jp/ja/doc/networking-catalog.html" target="_blank">ネットワーク製品カタログ</a></li>
          </ul>
          <h4>HPE ネットワークの導入をご検討中のお客様へ</h4>
          <ul class="leftNavLink">
            <li><a href="https://www.hpe.com/jp/ja/networking/case-studies.html" target="_blank">お客様導入事例</a></li>
          </ul>
          <h4>ネットワーク関連リンク</h4>
          <ul class="leftNavLink">
            <li><a href="https://www.hpe.com/jp/ja/networking/news.html" target="_blank">ニュース&amp;トピックス</a></li>
          </ul>
