<div id="sub_footer">
	<div class="mb40 fs14">
		
		<h2 class="fs24 bold centerAligned mb25">お問い合わせ</h2>
		
		<div class="bottomDivider mb40">
			<h3 class="fs24 bold mb10">ご購入前のお見積・ご注文のご相談（<!--#include virtual="/comm/include/directplus_cc_name.inc" -->）</h3>
			<div class="column40-60 cfx mb20">
				<div class="clm1">
					<div class="contactUsIconTel">
						<p class="fs30 bold mb5">0120-215-542</p>
						<p class="fs16">フリーダイヤルをご利用できない場合 <span class="fs20 bold">03-6743-6355</span></p>
					</div>
				</div>
				<div class="clm2">
					<p>
						受付時間：月曜日～金曜日 9:00～19:00（土・日曜日、祝日、年末年始、および5月1日 お休み）<br>
						応答メッセージが流れましたら1→2を押してください。 販売店のお客様で再販をご検討の方は、1→1を押してください。<br>
						複数台導入のご相談もこちらにお電話ください。担当のスタッフが対応致します。
					</p>
				</div>
			</div>
			<div class="contactUsIconMail mb40">
				<p>お見積・ご購入のご相談・製品に関するご質問などにEメールでご返答いたします。</p>
				<a href="https://www.hpe.com/h41268/live/index_e.aspx?qid=8812" target="_blank" role="button" class="btn btn-secondary">WEBフォームはこちら</a>
			</div>
		</div>
		
		<div class="bottomDivider mb40">
			<h3 class="fs24 bold mb10">ご購入前の製品仕様についてのお問い合わせ（カスタマーインフォメーションセンター）</h3>
			<div class="column40-60 cfx mb40">
				<div class="clm1">
					<p class="fs16 mb5">電話 <span class="fs26 bold">0120-268-186</span></p>
					<p class="fs16">フリーダイヤルをご利用できない場合 <span class="fs20 bold">03-6743-637003-5749-8279</span></p>
				</div>
				<div class="clm2">
					<p>受付時間：月曜日～金曜日 9:00～19:00（土曜日、日曜日、祝日、年末年始、および5月1日 お休み）</p>
				</div>
			</div>
		</div>
		
		<div class="bottomDivider mb40">
			<h3 class="fs24 bold mb10">ご購入後の操作や技術的なお問い合わせ（カスタマーケアセンター）</h3>
			<div class="column40-60 cfx mb40">
				<div class="clm1">
					<p class="fs16 mb5">固定電話（IP電話を除く） <span class="fs24 bold">0120-101-589</span></p>
					<p class="fs16">IP電話・携帯電話 <span class="fs20 bold">0570-064-235</span></p>
				</div>
				<div class="clm2">
					<p>受付時間：月曜日～金曜日 9:00～21:00、土曜日 9:00～17:00</p>
				</div>
			</div>
		</div>
		
		<div class="bottomDivider mb40">
			<h3 class="fs24 bold mb10">ご購入後の修理受付や修理状況のお問い合わせ（レスポンスセンター）</h3>
			<div class="column40-60 cfx mb40">
				<div class="clm1">
					<p class="fs16 mb5">電話 <span class="fs24 bold">0120-220-119</span></p>
				</div>
				<div class="clm2">
					<p>受付時間：月曜日～金曜日 9:00～17:00</p>
				</div>
			</div>
		</div>
		
		<div>
			<h3 class="fs24 bold mb10">その他の製品の製品・技術的なご質問や修理に関するお問い合わせ</h3>
			<a href="http://h20564.www2.hpe.com/hpsc/doc/public/display?lang=ja&amp;cc=JP&amp;docId=emr_na-c04770344" target="_blank"><span class="cta-link"><em class="icon-arrow-circle-right"></em>HPE サポートセンター</span></a>
		</div>
		
	</div>
	
	<div class="arlk_area3 mb40">
		<p class="noMargin">
			<a href="/directplus_ent/whatsnew/" class="txt_007DBA">新着情報</a><span class="subfooter_separ">|</span><a href="/directplus_ent/law/" class="txt_007DBA">特定商取引に関する法律に基づく表示</a><span class="subfooter_separ">|</span><a href="/directplus_ent/howto/condition.html" class="txt_007DBA">販売条件</a><span class="subfooter_separ">|</span><a href="/products/servers/server_tax/" target="_blank" class="txt_007DBA">生産性向上設備投資促進税制</a><span class="subfooter_separ">|</span><a href="/directplus_ent/sitemap/" class="txt_007DBA">サイトマップ</a>
		</p>
	</div>
	
	<div class="mb40">
		<!--#include virtual="/directplus_ent/include/footnote_delivery_charge.inc" -->
		<!--#include virtual="/directplus_ent/include/footnote_consumption_tax.inc" -->
		<!--#include virtual="/directplus_ent/include/footnote_price_2.inc" -->
	</div>
</div>

