<div class="productsCategory productsCategoryLineup mt20 mb30">
				<h2 class="bold dashed-text"><!--#include virtual="/comm/include/directplus_name.inc" --> <br class="br414">お取り扱い製品ラインアップ</h2>
				<div class="categoryList">
					<div class="categoryItem">
						<div class="categoryItemParent">
							<a href="/directplus_ent/server/?ref=dplustopcategory1" class="categoryServer">
								<div class="categoryName">サーバー</div>
							</a>
						</div>
						<ul class="categoryItemChild">
							<li>
								<a href="/directplus_ent/server/?spec=tower&ref=dplustopsubcategory1" class="linkWithArrow">
									タワー型サーバー
									<span class="arrow">→</span>
								</a><br>
								<a href="/directplus_ent/server/?spec=rack&ref=dplustopsubcategory2" class="linkWithArrow">
									ラックマウント型サーバー
									<span class="arrow">→</span>
								</a><br>
								<a href="/directplus_ent/storage/?hash=StoreEasy&ref=dplustopsubcategory3" class="linkWithArrow">
									NASファイルサーバー
									<span class="arrow">→</span>
								</a><br>
								<a href="/directplus_ent/os_software/?ref=dplustopsubcategory4" class="linkWithArrow">
									サーバーOS
									<span class="arrow">→</span>
								</a><br>
							</li>
						</ul>
					</div>
					<div class="categoryItem">
						<div class="categoryItemParent">
							<a href="/directplus_ent/storage/?ref=dplustopcategory2" class="categoryStorage">
								<div class="categoryName">ストレージ</div>
							</a>
						</div>
						<ul class="categoryItemChild">
							<li>
								<a href="/directplus_ent/storage/?hash=StoreEasy&ref=dplustopsubcategory5" class="linkWithArrow">
									NASファイルサーバー
									<span class="arrow">→</span>
								</a>
							</li>
							<li>
								<a href="/directplus_ent/storage/?hash=MSA&ref=dplustopsubcategory6" class="linkWithArrow">
									共有ストレージ
									<span class="arrow">→</span>
								</a>
							</li>
							<li>
								<a href="/directplus_ent/storage/?hash=LTO&ref=dplustopsubcategory7" class="linkWithArrow">
									バックアップ
									<span class="arrow">→</span>
								</a>
							</li>
						</ul>
					</div>
					<div class="categoryItem">
						<div class="categoryItemParent">
							<a href="/directplus_ent/network/?ref=dplustopcategory3" class="categoryNetwork">
								<div class="categoryName">ネットワーク</div>
							</a>
						</div>
						<ul class="categoryItemChild">
							<li>
								<a href="/directplus_ent/network/?hash=AccessPoint&ref=dplustopsubcategory8" class="linkWithArrow">
									無線アクセスポイント
									<span class="arrow">→</span>
								</a>
							</li>
							<li>
								<a href="/directplus_ent/network/?hash=Switch&ref=dplustopsubcategory9" class="linkWithArrow">
									ネットワークスイッチ
									<span class="arrow">→</span>
								</a>
							</li>
						</ul>
					</div>
					<div class="categoryItem">
						<div class="categoryItemParent">
							<a href="/directplus_ent/supportservice/?ref=dplustopcategory4" class="categorySupportservice">
								<div class="categoryName">サポートサービス</div>
							</a>
						</div>
						<ul class="categoryItemChild">
							<li>
								<a href="/directplus_ent/supportservice/?ref=dplustopsubcategory10" class="linkWithArrow">
									保守サービス
									<span class="arrow">→</span>
								</a>
							</li>
							<li>
								<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBService_e&ref=dplustopsubcategory11" class="linkWithArrow">
									延長保守サービス
									<span class="arrow">→</span>
								</a>
							</li>
						</ul>
					</div>
					<div class="categoryItem">
						<div class="categoryItemParent">
							<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e&ref=dplustopcategory5" class="categoryOption">
								<div class="categoryName">オプション</div>
							</a>
						</div>
						<ul class="categoryItemChild">
							<li>
								<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e&ref=dplustopsubcategory12" class="linkWithArrow">
									サーバーオプション
									<span class="arrow">→</span>
								</a>
							</li>
							<li>
								<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e&ref=dplustopsubcategory13" class="linkWithArrow">
									ストレージオプション
									<span class="arrow">→</span>
								</a>
							</li>
							<li>
								<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e&ref=dplustopsubcategory14" class="linkWithArrow">
									ネットワークオプション
									<span class="arrow">→</span>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div><!-- End Products category -->
