<div class="footLink mb40">
				<ul class="cfx">
					<li><a href="/directplus_ent/whatsnew/">新着情報</a></li>
					<li><a href="/directplus_ent/law/">特定商取引に関する法律に基づく表示</a></li>
					<li><a href="/directplus_ent/howto/condition.html">販売条件</a></li>
					<li><a href="/products/servers/server_tax/" target="_blank">生産性向上設備投資促進税制</a></li>
					<li><a href="/directplus_ent/sitemap/">サイトマップ</a></li>
				</ul>
			</div>