<script src="/comm/js/jquery.js" charset="UTF-8"></script>
	<script src="/comm/js/can.jquery.js" charset="UTF-8"></script>
	<script src="//h50007.www5.hpe.com/hfws/jp/ja/hpe/latest.r/root?contentType=js&switchToCHF=true&hide_cart=true&hide_sign_in=true&hide_cube_menu=true&slim_footer=false&hide_footer_cookies=true&hide_footer_ccpa=true"></script>

	
	<!-- for Cookie set START -->
	<script type="text/javascript">
		document.cookie = "lang=ja; path=/; domain=.hpe.com; max-age=31536000";
		document.cookie = "cc=jp; path=/; domain=.hpe.com; max-age=31536000";
	</script>
	<!-- for Cookie set END -->

	<!-- for synaps START -->
	<script type="text/javascript">
	setTimeout(function() {
		var head   = document.getElementsByTagName("head")[0] ||
		document.documentElement;
		var script = document.createElement('script');
		script.type = 'text/javascript';
		script.src = 'https://sygrip.info/bf78dat4/js/synapcap.js' + '?' + new Date().getTime().toString();
		head.appendChild(script);
	}, 0);
	</script>
	<!-- for synaps END -->
	
