<div class="nocontent">
<!--footer-->
	<div id="footer" class="footer">
	
	</div>
<!--/footer-->

<!--Begin SCREENREADING_LABELS JavaScript -->
<script type="text/javascript">
//
window.SCREENREADING_LABELS = {
'open_menu_prefix': "開く ",
'open_menu_suffix': " メニュー",
'close_menu_prefix': "閉じる ",
'close_menu_suffix': " メニュー",

'opened_state_menu_prefix': "",
'opened_state_menu_suffix': "",
'closed_state_menu_prefix': "",
'closed_state_menu_suffix': "",

'open_popup_prefix': "開く ",
'open_popup_suffix': " ポップアップ",
'close_popup_prefix': "閉じる ",
'close_popup_suffix': " ポップアップ",

"expand_prefix": "展開 ",
"expand_suffix": "",
"collapse_prefix": "折りたたむ",
"collapse_suffix": "",
"search_box_suggestion_title": ""
};

	HP.hfInit({
		communityWidgetURL: "",
		countrySelectorURL: "",
autocompleteURL:"//iapproautocm.austin.hp.com/hp-iap-autocomplete/search" , 
autocompleteSSRequest: false,
			countryCode: "jp",
	   			languageCode: "ja"
	});
HP.Utils.ready( function() {
initHFMetrics('.link_metrics');
});
//</script>
</div>