<div class="subHeader">
		<div class="titleArea">
			<div class="h1Title">
				<p>日本ヒューレット・パッカード合同会社が運営する公式オンラインストア</p>
				<h1><a href="/directplus_ent/">HPE DirectPlus オンラインストア</a></h1>
			</div>
			<div class="contact cfx">
				<div class="tel">
					<p class="noMargin">
						電話<span class="number">0120-215-542</span><br>
						受付時間：月曜日～金曜日 9:00～19:00
					</p>
				</div>
				<div class="mail">
					<a href="https://www.hpe.com/h41268/live/index_e.aspx?qid=8812" target="_blank">Eメール<span class="spHide">はこちら</span></a>
				</div>
			</div>
			<div class="subHeadMenu">
				<ul>
					<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/ViewOrderHistoryForBusiness-Start">保存した見積</a></li>
					<li><a href="https://onlinestore-japan.hpe.com/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/ViewPlacedOrderHistoryForBusiness-Start">お届け予定日</a></li>
					<li><a href="/directplus_ent/faq/">よくあるご質問</a></li>
					<li><a href="/directplus_ent/guide/">ご利用ガイド</a></li>
				</ul>
			</div>
		</div>
	</div>

	<div style="width:1200px; margin-left:-88px;margin-top:104px;">
		<div style="float:left; width:820px;">
			<!--slider-->
			<div id="snav" class="snv_AreaBox1">
				<div class="snv_AreaBox2">
					<div class="snv_AreaBox3">
						<div class="jcarousel" data-jcarousel="true">
							<ul class="snav_list_cover" style="left: 0px; top: 0px;">
	
							<li class="snav_list">
								<a href="/directplus_ent/server/">
									<span class="snv_cell_h"><img src="/directplus_ent/system/images/cgnv_dpb_serverx120.png" height="60"></span><p>サーバー</p>
								</a>
							</li>
							<li class="snav_list">
								<a href="/directplus_ent/storage/">
									<span class="snv_cell_h"><img src="/directplus_ent/system/images/cgnv_dpb_storagex120.png" height="60"></span><p>ストレージ</p>
								</a>
							</li>
							<li class="snav_list">
								<a href="/directplus_ent/network/">
									<span class="snv_cell_h"><img src="/directplus_ent/system/images/cgnv_dpb_networkx120.png" height="60"></span><p>ネットワーク</p>
								</a>
							</li>
							<li class="snav_list">
								<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBService_e">
									<span class="snv_cell_h"><img src="/directplus_ent/system/images/cgnv_dpb_supportx120.png" height="60"></span><p><!--#include virtual="/directplus_ent/include/capa_single.inc" --></p>
								</a>
							</li>
							<li class="snav_list">
								<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/BrowseCatalogForBusiness-Start?CategoryName=DPBOption_e">
									<span class="snv_cell_h"><img src="/directplus_ent/system/images/cgnv_dpb_optionx120.png" height="60"></span><p>オプション</p></a>
							</li>
							</ul>
						</div>
						<!--<a data-jcarouselcontrol="true" href="#" class="jcarousel-control-prev2 inactive2"></a> <a data-jcarouselcontrol="true" href="#" class="jcarousel-control-next2"></a>-->
					</div>
				</div>
			</div>
			<!--slider-->
		</div>
		<!--icon-->
		<div style="float:right; width:180px;">
			<div id="header" class="header2" style="background-color:#FFF!important; width:180px!important;">
				<div class="primary_nav" style="float: right; position: relative;">
					<ul class="js_menu menu level2">
						<li class="selectable first_li">
							<a role="menuitem" class="header_link" tabindex="2" href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/ViewBasketForBusiness-View">
								<img width="44" height="51" border="0" alt="カート" src="/directplus_ent/system/images/cgnv_icon4451_cart_hpe.png">
							</a>
						</li>
						<li class="selectable first_li">
							<a role="menuitem" class="header_link" tabindex="2" href="javascript:void(0);">
								<img width="44" height="51" border="0" src="/directplus_ent/system/images/cgnv_icon4451_userid_hpe.png" alt="アカウント"><span class="screenReading js_screen_reading"></span>
							</a>
							<div class="expand_area2" id="menu_1099612641" style="margin-top: 13px; display: none;">
								<div class="top_corner2">&nbsp;</div>
								<div class="level3" style="background-color:#FFF!important;">
									<ul class="js_menu menu">
										<li style="text-align: left;"><a href="<!--#include virtual="/directplus_ent/include/intershop_domain_ssl.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/ViewOrderHistoryForBusiness-Start" tabindex="2" class="no_flyout link_metrics">保存した見積</a></li>
										<li style="text-align: left;"><a href="<!--#include virtual="/directplus_ent/include/intershop_domain_ssl.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/ViewPlacedOrderHistoryForBusiness-Start" tabindex="2" class="no_flyout link_metrics">お届け予定確認</a></li>
										<li style="text-align: left;"><a href="<!--#include virtual="/directplus_ent/include/intershop_domain_ssl.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/ViewAddressBookForBusiness-View" tabindex="2" class="no_flyout link_metrics">納品先の変更</a></li>
										<li style="text-align: left;"><a href="<!--#include virtual="/directplus_ent/include/intershop_domain_ssl.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/ViewBuyerAccountForBusiness-View2" tabindex="2" class="no_flyout link_metrics">登録内容の変更</a></li>
									</ul>
								</div>
								<div class="shadow_divider">&nbsp;</div>
								<!--<div class="level4"></div>-->
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<!--/ icon　-->
		<div class="clear"></div>
	</div>
	

<style>
.header2 p, .header2 h4, .header2 ul {
    margin: 0;
    padding: 0;
}
.header2 ul,.footer ul{
	list-style-type:none;
}
.header2 .top_corner2 {
    background: url('/directplus_ent/system/images/s-hf-v3.gif') no-repeat;
}
.header2 .top_corner2 {
    background-position: -188px -130px;
    width: 17px;
    height: 12px;
    position: absolute;
    top: -12px;
}
.header2 .primary_nav .expand_area2 .top_corner2{
	left:140px;
}

*+html .header2 .primary_nav .expand_area2 .top_corner2{
	top:-12px;
}
@media \0screen{
	.header2 .primary_nav .expand_area2 .top_corner2{
		top:-12px;
	}
}
.header2 .primary_nav .expand_area2{
	font-size:14px;
	line-height:18px;
	display:none;
	position:absolute;
	width:auto;
	z-index:11;
	background:#fff;
	border:2px solid #ccc;
	/*border-bottom:3px #0096d6 solid;*/
	border-bottom:3px #80746e solid;  /*add to 20151221*/
	margin-left:-130px;
	margin-top:18px;
}

.header2 .primary_nav .expand_area2 .menu li{
	display:block;
	position:static;
	width:100%;
	height:auto;
	padding:4px 0;
	margin:0 0 9px 0;
}

.header2 .primary_nav .expand_area2 .menu li a{
	margin:0 20px;
	display:inline-block;
}

.header2 .primary_nav .expand_area2 .menu li a:hover{
	color:#007DBA;
}

.header2 .primary_nav .expand_area2 .menu li a:focus{
	color:#000000;
}
.header2 .primary_nav .expand_area2 .level3,
.header2 .primary_nav .expand_area2 .level4{
	width:251px;
	height:auto;
	padding-top:11px;
	padding-bottom:8px;
}
.header2 .primary_nav .expand_area2 .level4{
	padding-top:12px;
}

.header2 .primary_nav .expand_area2 .level3{
	display:inline-block;
	float:left;width:200px;
}

.header2 .primary_nav .expand_area2 .level4 .menu li{
	padding:0;
	margin:3px 0;
}

.header2 .primary_nav .expand_area2 .level4 .menu li.lstchild{
	margin-bottom:10px;
}

.header2 .primary_nav .expand_area2 p{
	padding:10px 18px 8px 18px;
	font-weight:bold;
	cursor:text;
	color:#000;
}

.header2 .primary_nav .expand_area2 .shadow_divider{display:none;width:1px;background:transparent;position:absolute;left:250px;top:20px;bottom:24px}
.header2 .primary_nav .expand_area2 .level4 .menu,.header2 .primary_nav .expand_area .level4{display:none}
.header2 .primary_nav .expand_area2 .menu .separator{margin:4px 20px 2px;border-top:1px solid #ccc}
.header2 .primary_nav .expand_area2 .level4 .menu .separator{margin:15px 20px 13px}
.header2 .primary_nav{
	float:left;
	width:auto;
}

.header2 .primary_nav .level2{
	display:block;
	width:auto;
}

.header2 .primary_nav .level2 li{
	float:left;
	margin:35px 0 0 10px;
	z-index:15;
}

.header2 .primary_nav .level2 li a.header_link{
	font-weight:bold;
	font-size:16px;
	line-height:18px;
	padding: 1px 0;
}

.header2 .primary_nav .level2 li.empty a.header_link:hover{
	text-decoration:underline;
}

.header2 .primary_nav .level2 li a,
.header2 .primary_nav .level2 li a:visited{
	color:#707070;
	display:block;
}
.header2 .primary_nav .level2 li a:hover{
	color:#333333 !important;
	text-decoration:none;
}

.header2 .primary_nav .level2 li a.header_link,
.header2 .primary_nav .level2 li a.header_link:visited,
.header2 .primary_nav .level2 li a.header_link:hover,
.header2 .primary_nav .level2 li a.header_link:active,
.header2 .primary_nav .level2 li a.header_link:focus,
.header2 .primary_nav .level2 li.selected a.header_link{
	color:#FFFFFF;
}

.header2 .primary_nav .expand_area{
	font-size:14px;
	line-height:18px;
	display:none;
	position:absolute;
	width:auto;
	z-index:11;
	background:#fff;
	border:2px solid #ccc;
	border-bottom:3px #0096d6 solid;
	margin-left:-150px; /*20141023 2px より変更*/
	margin-top:18px;
}

.header2 .primary_nav .expand_area .menu li{
	display:block;
	position:static;
	width:100%;
	height:auto;
	padding:4px 0;
	margin:0 0 9px 0;
}

.header2 .primary_nav .expand_area .menu li a{
	margin:0 20px;
	display:inline-block;
}

.header2 .primary_nav .expand_area .menu li a:hover{
	color:#007DBA;
}

.header2 .primary_nav .expand_area .menu li a:focus{
	color:#000000;
}
.header2 .primary_nav .expand_area .level3,
.header2 .primary_nav .expand_area .level4{
	width:251px;
	height:auto;
	padding-top:11px;
	padding-bottom:8px;
}
.header2 .primary_nav .expand_area .level4{
	padding-top:12px;
}

.header2 .primary_nav .expand_area .level3{
	display:inline-block;
	float:left;width:250px;
}

.header2 .primary_nav .expand_area .level4 .menu li{
	padding:0;
	margin:3px 0;
}

.header2 .primary_nav .expand_area .level4 .menu li.lstchild{
	margin-bottom:10px;
}

.header2 .primary_nav .expand_area p{
	padding:10px 18px 8px 18px;
	font-weight:bold;
	cursor:text;
	color:#000;
}

.header2 .primary_nav .extend_expandable_area .level3 .menu li.selected{background:#007dba}
.header2 .primary_nav .extend_expandable_area .level3 .menu li.selected a{color:#fff;outline:none}
.header2 .primary_nav .expand_area .shadow_divider{display:none;width:1px;background:transparent;position:absolute;left:250px;top:20px;bottom:24px}
.header2 .primary_nav .expand_area .level4 .menu,.header2 .primary_nav .expand_area .level4{display:none}
.header2 .primary_nav .extend_expandable_area .level4,.header2 .primary_nav .extend_expandable_area .shadow_divider{display:block;float:left}
.header2 .primary_nav .extend_expandable_area .shadow_divider{background:#ccc}
.header2 .primary_nav .expand_area .menu .separator{margin:4px 20px 2px;border-top:1px solid #ccc}
.header2 .primary_nav .expand_area .level4 .menu .separator{margin:15px 20px 13px}
.header2 .primary_nav .extend_expandable_area{*width:501px}
</style>	
