
	
	<h3 class="f24 bold mb5">
		2Uサーバーであらゆるワークロードに対応する性能を追及したい場合は・・・
	</h3>
	<div class="mb10">
		<p class="mb10">
			AMD EPYC<sup>&trade;</sup> プロセッサーを2基搭載可能で、高い性能と拡張性により適用用途の拡大を実現する<a href="/directplus_ent/server/dl385gen10plus/" class="tertiary-link">HPE ProLiant DL385 Gen10 Plus</a>や、同<a href="/directplus_ent/server/dl385gen10plusv2/" class="tertiary-link">DL385 Gen10 Plus v2</a>をおすすめいたします。<br>
			<!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" -->へお電話いただければ、専任スタッフがご希望の用途や環境に合わせた構成で比較のお見積をさせていただきます。
		</p>
		<div class="alignRgt"><a href="#ContactUs" class="linkWithArrow"><!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" --><span class="arrow">→</span></a></div>
	</div>
	<div class="optokuTable">
		<table>
			<tr>
				<th width="20%"></th>
				<th width="40%">DL345 Gen10 Plus</th>
				<th width="40%">DL385 Gen10 Plus</th>
			</tr>
			<tr class="whiteCell">
				<th>モデル</th>
				<td class="alignCtr"><a href="#CustomizeOrder"><img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl345_gen10_plus.gif" class="m0auto"></a><a href="#CustomizeOrder" role="button" class="btn btn-secondary">モデルを選択する</a></td>
				<td class="alignCtr">
					<a href="/directplus_ent/server/dl385gen10plus/">
						<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl385_gen10_plus.gif" class="m0auto">
					</a>
					<a href="/directplus_ent/server/dl385gen10plus/" role="button" class="btn btn-secondary">モデルを選択する</a></td>
			</tr>
			<tr class="gryCell">
				<th>最小構成価格(税抜)</th>
				<td class="alignCtr">
					通常モデル　966,000円～
					<!--<a href="#ContactUs" class="tertiary-link">お問い合わせください</a>-->
				</td>
				<td class="alignCtr">
					通常モデル　651,000円～
				</td>
			</tr>
			<tr class="whiteCell">
				<th>おすすめ用途</th>
				<td class="alignCtr">
					・中規模業務アプリケーションサーバー<br>
					・ディスク容量を重視する用途<br>
					・メールサーバー<br>
					・仮想化&amp;VDI<br>
					・中規模DB<br>
					・中規模ファイルサーバー
				</td>
				<td class="alignCtr">
					・大中規模ファイル/メールサーバー<br>
					・仮想化&amp;VDI<br>
					・ディスク容量を重視する用途<br>
					・中規模DB<br>
					・画像配信用ストリーミング<br>
					・人工知能/HPCなどのニーズ
				</td>
			</tr>
			<tr class="gryCell">
				<th>プロセッサー</th>
				<td class="alignCtr">
					最大1基<br>
					AMD EPYC<sup>&trade;</sup> プロセッサー
				</td>
				<td class="alignCtr">
					最大2基<br>
					AMD EPYC<sup>&trade;</sup> プロセッサー
				</td>
			</tr>
			<tr class="whiteCell">
				<th>メモリ</th>
				<td class="alignCtr">16DIMMスロット DDR4 RDIMM</td>
				<td class="alignCtr">32DIMMスロット DDR4 RDIMM</td>
			</tr>
			<tr class="gryCell">
				<th>ドライブ</th>
				<td class="alignCtr">
					8(LFF ホットプラグ SAS/SATA/SSD)<br>
					標準8、最大16(SFF ホットプラグ SAS/SATA/SSD)
				</td>
				<td class="alignCtr">
					標準8、最大16(2.5型ホットプラグSAS/SATA/SSD)<br>
					標準12、最大16(3.5型ホットプラグSAS/SATA/SSD)
				</td>
			</tr>
			<tr class="whiteCell">
				<th>拡張スロット</th>
				<td class="alignCtr">
					3 (OCP 3.0 スロット×1、フルハイト/フルレングスPCI Express Gen4 x16(x16 コネクター) ×2)<br>
					<span class="f12">※オプションにより最大5</span>
				</td>
				<td class="alignCtr">
					4 (OCP 3.0 スロット×1、フルハイト/フルレングスPCI Express Gen4 x8 ×1、フルハイト/フルレングスPCI Express Gen4 x16 ×1、フルハイト/ハーフレングスPCI Express Gen4 x8 ×1)<br>
					<span class="f12">※オプションにより最大6</span>
				</td>
			</tr>
		</table>
	</div>
