<div>
	<p>
		HPE ProLiant DL345 Gen10 Plusは、コストパフォーマンスの高い1ソケット専用のAMD EPYC<sup>&trade;</sup> プロセッサーを搭載し、2Uのストレージ拡張性を備えた新しいサーバーです。<br>
		2Uの筐体に2.5型ドライブを最大26基、または3.5型ドライブを最大12基搭載可能であり、さらに1ソケットサーバーであるため、戦略的なAMDの1ソケット専用のコストパフォーマンスの高いプロセッサーを搭載可能です。このためファイルサーバー、データベースなどデータマネージメントワークロードに高いコストパフォーマンスを提供するサーバーとして最適です。<br>
		サーバー管理機能にはiLO5を搭載。Silicon root of trust (シリコンレベルの信頼性)によるセキュリティ機能をサポートし、HPE独自の電子認証によるファームウェアの更新や不正書き換えの検知と回復機能を備えています。お客様の業務を守る”世界標準の安心サーバー”の進化版です。
	</p>
	<p class="mt15">
		<a href="/directplus_ent/server/infosight_for_servers.html" class="linkWithArrow" target="_blank">HPE InfoSight for Servers 対応サーバー　詳しくはこちら<span class="arrow">→</span></a>
	</p>
</div>
