<div class="specTable2Area fixedTable">
	<div class="specTable2">
		<div class="specTableTitle">
			<table width="1000">
				<tr>
					<th width="100"></th>
					<th width="450" class="f14">信頼性とコストパフォーマンス<br>
					<span class="f20">8LFF</span></th>
					<th width="450" class="f14">性能・信頼性重視<br>
					<span class="f20">8SFF</span></th>
				</tr>
			</table>
		</div>
		<table width="1000">
			<tr>
				<th width="100"></th>
				<th width="450" class="f14">信頼性とコストパフォーマンス<br>
				<span class="f20">8LFF</span></th>
				<th width="450" class="f14">性能・信頼性重視<br>
				<span class="f20">8SFF</span></th>
			</tr>
			<tr>
				<th></th>
				<td>
					<img src="https://onlinestore-japan.hpe.com/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl345_gen10_plus.gif" alt="dl345_gen10_plus" class="m0auto">
				</td>
				<td>
					<img src="https://onlinestore-japan.hpe.com/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl345_gen10_plus.gif" alt="dl345_gen10_plus" class="m0auto">
				</td>
			</tr>
			<tr>
				<th>ドライブ</th>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ LFF</span> 最大8<br>
					SATA HDD、SATA SSD、SAS HDD、SAS SSD選択可
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ SFF</span> 最大16<br>
					SATA HDD、SATA SSD、SAS HDD、SAS SSD選択可
				</td>
			</tr>
			<tr>
				<th>プロセッサー</th>
				<td colspan="2">
					<span class="cutomizable2">カスタマイズ可能</span>最大1基　AMD EPYC<sup>&trade;</sup> プロセッサー
				</td>
			</tr>
			<tr>
				<th>メモリ</th>
				<td colspan="2">
					<span class="cutomizable2">カスタマイズ可能</span>16DIMMスロット DDR4 RDIMM
				</td>
			</tr>
			<tr>
				<th>パワーサプライ</th>
				<td colspan="2">
					<span class="cutomizable2">カスタマイズ可能</span>標準1、最大2　オプションで冗長化対応、ホットプラグ対応
				</td>
			</tr>
			<tr>
				<th rowspan="2">最小構成価格<br>（税抜）</th>
				<td class="pt10 pb10" style="border-bottom: none;">
					<div>
						<span class="bold f14"><a href="#ContactUs" class="tertiary-link">お問い合わせください</a></span>
						<!--<span class="bold f14">通常モデル</span><span class="f14">&ensp;966,000円～</span><br>
						<a href="/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4404&ProductSKU=BASE:16035" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>-->
					</div>
				</td>
				<td class="pt10 pb10" style="border-bottom: none;">
					<div>
						<!--<span class="bold f14"><a href="#ContactUs" class="tertiary-link">お問い合わせください</a></span>-->
						<span class="bold f14">通常モデル</span><span class="f14">&ensp;966,000円～</span><br>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4404&ProductSKU=BASE:16034" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
			</tr>
			<tr>
				<td colspan="2" class="bgG">
					<div class="f12">本製品は受注生産のため、納品目安は受注後3か月前後となります。</div>
				</td>
			</tr>
			<tr>
				<th></th>
				<td colspan="2" class="pt10 pb15 bgW">
					<a href="pdfs/spec.pdf" target="_blank" class="linkWithArrow">仕様一覧はこちら（PDF）<span class="arrow">→</span></a>
				</td>
			</tr>
		</table>
	</div><!-- /.specTable2 -->
	
</div><!-- /.specTable2Area -->
