<div>
	<p>
		HPE ProLiant DL325 Gen10 Plus v2は、第3世代AMD EPYC<sup>&trade;</sup> プロセッサーを採用した1Uラックマウント型サーバーです。<br>
		前世代のDL325 Gen10 Plusと比較して奥行きが約18cm短くなり、省スペース化を図りました。また1プロセッサーながら従来の2プロセッサーに匹敵する高性能を提供できるため、仮想化統合で高集約を提供でき、コスト削減に効果を発揮します。<br>
		サーバー管理機能にはGen10やGen10 Plusと同じくiLO5を搭載。Silicon root of trust (シリコンレベルの信頼性)によるセキュリティ機能をサポートし、HPE独自の電子認証によるファームウェアの更新や不正書き換えの検知と回復機能を備えています。お客様の業務を守る”世界標準の安心サーバー”の進化版です。
	</p>
	<p class="mt10">
		第2世代AMD EPYC<sup>&trade;</sup> プロセッサー搭載の<a href="/directplus_ent/server/dl325gen10plus/" class="tertiary-link">HPE ProLiant DL325 Gen10 Plus</a>もラインアップしています。<br>
		DL325 Gen10 Plusも引き続き販売をして参ります。
	</p>
</div>
<p class="mt15">
	<a href="/directplus_ent/server/infosight_for_servers.html" class="linkWithArrow" target="_blank">HPE InfoSight for Servers 対応サーバー　詳しくはこちら<span class="arrow">→</span></a>
</p>
