<div class="product__campaignWrapper">
	<div class="product__campaign">
		<div class="clm1">
			<a href="https://www.hpe.com/jp/ja/servers/servers-campaign.html">
				<img src="/directplus_ent/images/banners/bnr_400_txt01.png" width="200" class="m0auto" alt="キャンペーン価格で即時お見積">
				<img src="/directplus_ent/images/banners/bnr_400x90_goto_telework_campaign.jpg" width="200" class="m0auto" alt="サーバー & ストレージ “Go To テレワーク” キャンペーン">
			</a>
		</div>
		<div class="clm2">
			<p class="lhMid">
				キャンペーンモデルのHPE ProLiant Gen10サーバー本体および内蔵オプション、UPS、StoreEasyが<span class="bold f16">30％OFF</span><br>
				メモリ、HDD/SSDが<span class="bold f16">50%OFF</span><br>
				さらにHPEプロアクティブケアも<span class="bold f16">15%OFF</span><br>
				<span class="f14 bold">2021年3月31日（水）お申し込み分まで</span><br>
				<span class="f12">※本サイトでは「キャンペーンモデル」にて、キャンペーン価格で即時お見積・ご注文いただけます。</span>
			</p>
			<div class="product__campaign__detailLink">
				<a href="https://www.hpe.com/jp/ja/servers/servers-campaign.html">
					<span class="cta-link">
						<em class="icon-arrow-circle-right"></em>「サーバー & ストレージ “Go To テレワーク” キャンペーン」の詳細はこちら
					</span>
				</a>
			</div>
		</div>
	</div>
</div>