<div>
	<p>
		HPE ProLiant DL385 Gen10 Plus v2は、高性能な第3世代AMD EPYC<sup>&trade;</sup> プロセッサーを2基搭載可能な、GPU搭載能力を強化した新世代のフラッグシップ2Uサーバーです。CPU、GPU、ストレージとすべての領域で高い性能を発揮し、CAE、HPC、HCI、AIワークロードに高性能を提供するサーバーとして最適です。<br>
		サーバー管理機能にはGen10やGen10 Plusと同じくiLO5を搭載。Silicon root of trust (シリコンレベルの信頼性)によるセキュリティ機能をサポートし、HPE独自の電子認証によるファームウェアの更新や不正書き換えの検知と回復機能を備えています。お客様の業務を守る”世界標準の安心サーバー”の進化版です。
	</p>
	<p class="mt10">
		コストと性能のバランスを重視されるお客様には、<a href="/directplus_ent/server/dl385gen10plus/" class="tertiary-link">HPE ProLiant DL385 Gen10 Plus</a>をおすすめいたします。<br>
		DL385 Gen10 Plusも引き続き販売をして参ります。
	</p>
	<p class="mt15">
		<a href="/directplus_ent/server/infosight_for_servers.html" class="linkWithArrow" target="_blank">HPE InfoSight for Servers 対応サーバー　詳しくはこちら<span class="arrow">→</span></a>
	</p>
</div>
