<div class="mb40" id="Compare">
	
	<h3 class="f24 bold mb5">
		1Uサーバーであらゆるワークロードに対応する性能を追及したい場合は・・・
	</h3>
	<div class="mb10">
		<p class="mb10">
			2プロセッサー/最大56コアを1Uで実現するHPE ProLiant DL360 Gen10をおすすめいたします。最大7年の長期保守にも対応。<br>
			またAMD EPYC&trade; プロセッサーを2基搭載可能な2Uサーバー、<a href="/directplus_ent/server/dl385gen10/" class="tertiary-link">HPE ProLiant DL385 Gen10</a>もございます。<br>
			<!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" -->へお電話いただければ、ご希望の用途や環境に合わせた構成で比較のお見積をさせていただきます。</p>
		<div class="alignRgt"> <a href="#ContactUs"><span class="cta-link"><em class="icon-arrow-circle-right"></em><!--#include virtual="/comm/include/directplus_cc_name_utf8.inc" --></span></a> </div>
	</div>
	<div class="optokuTable">
		<table>
			<tr>
				<th width="20%"></th>
				<th width="40%">DL325 Gen10</th>
				<th width="40%">DL360 Gen10</th>
			</tr>
			<tr class="whiteCell">
				<th>モデル</th>
				<td class="alignCtr">
					<a href="#CustomizeOrder"><img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl325_gen10_campaign.gif" class="m0auto"></a> <a href="#CustomizeOrder" role="button" class="btn btn-secondary">カスタマイズ・お見積</a>
				</td>
				<td class="alignCtr">
					<a href="/directplus_ent/server/dl360gen10/"><img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl360_gen10.gif" class="m0auto"></a> <a href="/directplus_ent/server/dl360gen10/" role="button" class="btn btn-secondary">カスタマイズ・お見積</a>
				</td>
			</tr>
			<tr class="gryCell">
				<th>最小構成価格(税抜)</th>
				<td class="alignCtr">
					<!--通常モデル　443,000円～-->
					通常モデル　<span class="lineThrough">443,000円～</span><br>
					<span class="bold f18">期間限定　298,000円～</span>
				</td>
				<td class="alignCtr">
					通常モデル　495,000円～
					<!--<div class="lhMin">
						<span class="bold">キャンペーン価格適用モデル (8SFF SAS)</span><br>
						<span class="lineThrough">680,000円～</span><br>
						<span class="bold f18">期間限定　477,000円～</span>
					</div>-->
				</td>
			</tr>
			<tr class="whiteCell">
				<th>おすすめ用途</th>
				<td class="alignCtr">
					・Webサーバー<br>
					・メールサーバー<br>
					・仮想化<br>
					・一般的な業務アプリ<br>
					・中規模DB<br>
					・ファイルサーバー
				</td>
				<td class="alignCtr">
					・Webサーバー<br>
					・メールサーバー<br>
					・仮想化<br>
					・一般的な業務アプリ<br>
					・中規模DB<br>
					・ファイルサーバー
				</td>
			</tr>
			<tr class="gryCell">
				<th>プロセッサー</th>
				<td class="alignCtr">
					最大1基/32コア<br>
					AMD EPYC&trade; プロセッサー
				</td>
				<td class="alignCtr">
					最大2基/56コア<br>
					インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー
				</td>
			</tr>
			<tr class="whiteCell">
				<th>メモリ</th>
				<td class="alignCtr">16DIMMスロット DDR4 RDIMM</td>
				<td class="alignCtr">24DIMMスロット DDR4 RDIMM</td>
			</tr>
			<tr class="gryCell">
				<th>ドライブ</th>
				<td class="alignCtr">
					4(3.5型ホットプラグSAS/SATA)<br>
					標準8、最大10(2.5型ホットプラグSAS/SATA/SSD)
				</td>
				<td class="alignCtr">
					標準8、最大10(2.5型ホットプラグSAS/SATA/SSD)
				</td>
			</tr>
			<tr class="whiteCell">
				<th>拡張スロット</th>
				<td class="alignCtr">
					2(フルハイト/フルレングス PCI Express Gen3 x16×1、<br>
					ロープロファイルPCI Express Gen3 x8×1)
				</td>
				<td class="alignCtr">
					3(FlexibleLOMアダプター用スロット×1、FH/HL PCI Express Gen3 x16×1、LP/HL PCI Express Gen3 x8×1)<br>
					<span class="f12">※オプションにより最大4</span>
				</td>
			</tr>
		</table>
	</div>
	
</div><!-- /#Compare -->