<div>
	<h4 class="f18 bold">
		新次元のサーバーセキュリティ
	</h4>
	<p>
		HPE ProLiant DL380 Gen10の最大の特長はセキュリティー機能です。HPE独自の電子認証によるファームウエアの更新や不正書き換えの早期認識と回復機能を備えています。
	</p>
	<h4 class="f18 bold mt10">
		最高クラスの性能とストレージ拡張性の大幅向上
	</h4>
	<p>
		最新のインテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリーを2基(最大56コア)搭載可能。さらにワークロード自働設定機能のHPE Intelligent System Tuningが各ワークロードに最高の性能を実現します。<br>
		またストレージの拡張性を強化。3.5型ドライブは前モデルDL380 Gen9と比較して、同じ2U筐体でありながら33%の搭載数アップを実現しました。
	</p>
	<p class="mt10">
		より高い性能を追求するお客様には、<a href="/directplus_ent/server/dl380gen10plus/" class="tertiary-link">HPE ProLiant DL380 Gen10 Plus</a>をおすすめいたします。<br>
		なお本製品DL380 Gen10も引き続き販売をして参ります。
	</p>
	<p class="mt15">
		<a href="/directplus_ent/server/infosight_for_servers.html" class="linkWithArrow" target="_blank">HPE InfoSight for Servers 対応サーバー　詳しくはこちら<span class="arrow">→</span></a>
	</p>
</div>
