<div class="specTable2Area fixedTable">

	<div class="specTable2">
		<!--<div class="specTableTitle">
			<table width="1000">
				<tr>
					<th width="100"></th>
					<th width="450" class="f14">信頼性とコストパフォーマンス<br>
					<span class="f20">8SFF</span></th>
					<th width="450" class="f14">性能・信頼性重視<br>
					<span class="f20">12LFF</span></th>
				</tr>
			</table>
		</div>-->
		<table width="1000">
			<tr>
				<th width="100"></th>
				<th width="450" class="f14">
					信頼性とコストパフォーマンス<br>
					<span class="f20">8SFF</span>
				</th>
				<th width="450" class="f14">
					性能・信頼性重視<br>
					<span class="f20">12LFF</span>
				</th>
			</tr>
			<tr>
				<th></th>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl380_gen10.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl380_gen10.gif" alt="" class="m0auto">
				</td>
			</tr>
			<tr>
				<th>ドライブ</th>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 2.5型</span> 最大16<br>
					SATA HDD、SATA SSD、SAS HDD、SAS SSD選択可
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 3.5型</span> 最大16<br>
					SATA HDD、SATA SSD、SAS HDD選択可
				</td>
			</tr>
			<tr>
				<th>プロセッサー</th>
				<td colspan="2">
					<span class="cutomizable2">カスタマイズ可能</span>最大2基　インテル<sup>&reg;</sup> Xeon<sup>&reg;</sup> スケーラブル・プロセッサー・ファミリー
				</td>
			</tr>
			<tr>
				<th>メモリ</th>
				<td colspan="2">
					<span class="cutomizable2">カスタマイズ可能</span>24DIMMスロット DDR4 RDIMM
				</td>
			</tr>
			<tr>
				<th>パワーサプライ</th>
				<td colspan="2">
					<span class="cutomizable2">カスタマイズ可能</span>標準1、最大2　オプションで冗長化対応、ホットプラグ対応
				</td>
			</tr>
			<tr>
				<th rowspan="2"><span class="f11">Xeon x2xx搭載</span><br>最小構成価格<br>（税抜）</th>
				<td colspan="2" class="pt25" style="border-bottom: none;">
					<div class="bold f16">Xeon x2xx (第2世代プロセッサー) 搭載</div>
				</td>
			</tr>
			<tr>
				<td class="pt10 pb10 bgG">
					<div>
						<span class="bold f16">通常モデル（NC<sup>※</sup>）</span>
						<span class="f16">832,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4264&ProductSKU=BASE:16120" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
				<td class="pt10 pb10 bgG">
					<div>
						<span class="bold f16">通常モデル（NC<sup>※</sup>）</span>
						<span class="f16">732,000円～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4264&ProductSKU=BASE:15786" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
			</tr>
			<tr>
				<th></th>
				<td colspan="4" class="pt10 pb15 bgW">
					<a href="pdfs/spec.pdf" target="_blank" class="linkWithArrow">
						仕様一覧はこちら（PDF）
						<span class="arrow">→</span>
					</a>
				</td>
			</tr>
		</table>
	</div><!-- /.specTable2 -->
	
</div><!-- /.specTable2Area -->
<p class="f12 indent-1 mt10">
	※NCモデルは、従来マザーボードに標準搭載していたオンボードのネットワークアダプターを非搭載にして、お客様の環境やユースケースに合ったプライマリーのアダプターを柔軟に選択可能にしたモデルです。NIC専用ポートであるFlexibleLOMにNICカードを必ず搭載いただく必要があります。
</p>
