<style>
.column66-33 .clm2 img{
	max-width: 120px;
	height:auto;
	margin: 0px auto 20px;
}

</style>
	<div class="column66-33 cfx">
		<div class="clm1">
			<p>
				HPE ProLiant DL20 Gen10 Plusは、手ごろな価格帯でありながら冗長電源、HW RAIDなど十分な可用性を備える1Uラックマウント型サーバーです。コンパクトな筐体のため、省スペースにも貢献します。<br>
			またHPE独自の管理チップ iLO5の提供する“シリコンレベルの信頼性”を基盤に、HPE独自の電子認証によるファームウェアの更新や不正書き換えの早期認識と回復機能を備えています。さらにセキュリティ強化としてTPM2.0も標準搭載となります。<br>
			前世代DL20 Gen10からI/O性能、拡張性、セキュリティをいずれも強化した、パワフルな1Uエントリーサーバーです。
			</p>
			<p class="mt15">
				<a href="/directplus_ent/server/infosight_for_servers.html" class="linkWithArrow" target="_blank">HPE InfoSight for Servers 対応サーバー　詳しくはこちら<span class="arrow">→</span></a>
			</p>
		</div>
		<div class="clm2">
			<a href="../pdfs/dl20gen10plus_ml30gen10plus.pdf" target="_blank">
				<img src="../images/dl20gen10plus_ml30gen10plus_thumb.jpg">
			</a>
			<div class="alignCtr lhMid">
				<a href="../pdfs/dl20gen10plus_ml30gen10plus.pdf" class="linkWithArrow" target="_blank">
					HPE ProLiant<br>DL20 Gen10 Plus チラシ<span class="arrow">→</span>
				</a>
			</div>
		</div>
	</div>
