<div class="specTable2Area fixedTable">
	<div class="specTable2">
		<!--<div class="specTableTitle">
			<table width="1000">
				<tr>
					<th width="100"></th>
					<th width="450" class="f14">信頼性とコストパフォーマンス<br>
					<span class="f20">8SFF</span></th>
					<th width="450" class="f14">性能・信頼性重視<br>
					<span class="f20">12LFF</span></th>
				</tr>
			</table>
		</div>-->
		<table width="1000">
			<tr>
				<th width="100"></th>
				<th width="300" class="f14">コストパフォーマンス重視<br>
				<span class="f20">NHP 2LFF</span></th>
				<th width="300" class="f14">信頼性とコストパフォーマンス<br>
				<span class="f20">2LFF</span></th>
				<th width="300" class="f14">性能・信頼性重視<br>
				<span class="f20">4SFF</span></th>
			</tr>
			<tr>
				<th></th>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl20_gen10_plus_optoku.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl20_gen10_plus_optoku.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl20_gen10_plus_optoku.gif" alt="" class="m0auto">
				</td>
			</tr>
			<tr>
				<th>ドライブ</th>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ SFF</span> 最大2<br>
					SATA HDD選択可
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ LFF</span> 最大2<br>
					SATA HDD、SATA SSD、SAS HDD、SAS SSD選択可
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ SFF</span> 最大6<br>
					SATA HDD、SATA SSD、SAS HDD、SAS SSD選択可
				</td>
			</tr>
			<tr>
				<th>プロセッサー</th>
				<td colspan="3">
					<span class="cutomizable2">カスタマイズ可能</span>最大1基　インテル<sup>&reg;</sup> Pentium<sup>&reg;</sup> G6400 / Xeon<sup>&reg;</sup> E-2300 シリーズ
				</td>
			</tr>
			<tr>
				<th>メモリ</th>
				<td colspan="3">
					<span class="cutomizable2">カスタマイズ可能</span> 4DIMMスロット DDR4 UDIMM
				</td>
			</tr>
			<tr>
				<th>パワーサプライ</th>
				<td colspan="3">
					<span class="cutomizable2">カスタマイズ可能</span>標準1、最大2　オプションで冗長化対応、ホットプラグ対応
				</td>
			</tr>
			<tr>
				<th>最小構成価格<br>（税抜）</th>
				<td class="pt10 pb10 bgG" style="border-bottom: none;">
					<div class="mb25">
						<span class="bold f16">オプ得モデル</span><br>
						<span class="bold f18">296,000円～</span><br>
						<span class="f12">40,000円引き～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4418&ProductSKU=BASE:16105" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
					<div>
						<span class="bold f16">通常モデル</span>
						<span class="f16">336,000円～</span><br>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4412&ProductSKU=BASE:16099" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
				<td class="pt10 pb10 bgG" style="border-bottom: none;">
					<div class="mb25">
						<span class="bold f16">オプ得モデル</span><br>
						<span class="bold f18">318,000円～</span><br>
						<span class="f12">40,000円引き～</span>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4418&ProductSKU=BASE:16106" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
					<div>
						<span class="bold f16">通常モデル</span>
						<span class="f16">358,000円～</span><br>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4412&ProductSKU=BASE:16100" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
					<td class="pt10 pb10 bgG" style="border-bottom: none;">
						<div class="mb25">
							<span class="bold f16">オプ得モデル</span><br>
							<span class="bold f18">369,000円～</span><br>
							<span class="f12">40,000円引き～</span>
							<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4418&ProductSKU=BASE:16107" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
						</div>
						<div>
							<span class="bold f16">通常モデル</span>
							<span class="f16">409,000円～</span><br>
							<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4412&ProductSKU=BASE:16101" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
						</div>
				</td>
			</tr>
			<!--<tr>
				<td colspan="3" class="bgG">
					<div class="f12">本製品は受注生産のため、納品目安は受注後1か月前後となります。</div>
				</td>
			</tr>-->
			<tr>
				<th></th>
				<td colspan="3" class="pt10 pb15 bgW">
					<a href="pdfs/spec.pdf" target="_blank" class="linkWithArrow">
						仕様一覧はこちら（PDF）
						<span class="arrow">→</span>
					</a>
				</td>
			</tr>
		</table>
	</div><!-- /.specTable2 -->
	
</div><!-- /.specTable2Area -->
