<div class="callcenter">
	<div class="contact gryBdr4px paddBlock15">
		<div class="f20 bold lhMid mb10 alignCtr">
			HPE DirectPlus コールセンター
		</div>
		<div class="contact-column column33-67Flex fixUpperTablet">
			<div class="clm1 flexGutter20">
				<div class="column20-80Flex fixAll alignItemsCtr">
					<div class="clm1 flexGutter10">
						<img src="/directplus_ent/callcenter/images/icon-tel.png" width="100" height="98" alt="" class="w100per hauto m0auto">
					</div>
					<div class="clm2">
						<p class="f26 bold lhMin mb5">
							<span data-action="call" data-tel="0120-215-542" class="tel-number">
								0120-215-542
							</span>
						</p>
						<p class="f12 lhMin">
							フリーダイヤルをご利用できない場合<br>
							<span class="f20 bold">
								<span data-action="call" data-tel="03-6743-6355" class="tel-number">
									03-6743-6355
								</span>
							</span>
						</p>
					</div>
				</div>
			</div>
			<div class="clm2">
				<p class="f13">
					受付時間：月曜日～金曜日 9:00～19:00（土曜日、日曜日、祝日、年末年始、および5月1日 お休み）<br>
					応答メッセージが流れましたら1→2を押してください。<br>
					販売店のお客様で再販をご検討の方は、1→1を押してください。
				</p>
			</div>
		</div>
	</div>
</div>
