          <div class="gryBdr4px threeColumnLinkList mb30">
          	<h3 class="f20 bold mt10 ml10">用途で選ぶ</h3>
			<ul class="cfx">
            	<li><a href="/directplus_ent/server/purpose/file.html"><span class="cta-link"><em class="icon-arrow-circle-right"></em>ファイルサーバー</span></a></li>
                <li><a href="/directplus_ent/server/purpose/virtualhost.html"><span class="cta-link"><em class="icon-arrow-circle-right"></em>仮想化ホストサーバー</span></a></li>
                <li><a href="/directplus_ent/server/purpose/webapp.html"><span class="cta-link"><em class="icon-arrow-circle-right"></em>Web・アプリケーションサーバー</span></a></li>
                <li><a href="/directplus_ent/server/purpose/database.html"><span class="cta-link"><em class="icon-arrow-circle-right"></em>データベースサーバー</span></a></li>
                <li><a href="/directplus_ent/server/purpose/utm.html"><span class="cta-link"><em class="icon-arrow-circle-right"></em>統合脅威管理サーバー</span></a></li>
                <li><a href="/directplus_ent/server/purpose/sds.html"><span class="cta-link"><em class="icon-arrow-circle-right"></em>ソフトウェア・デファインド・ストレージ</span></a></li>
                <li style="width: 100%;"><a href="/directplus_ent/recipe/"><span class="cta-link"><em class="icon-arrow-circle-right"></em>HPEスペシャリストのおすすめ 「HPEサーバーレシピ」</span></a></li>
            </ul>
          </div>
