<div>
	<p>
		HPE ProLiant DL325 Gen10 Plusは、従来機DL325 Gen10の設計を一新し、機能をさらに進化させた1U/1ソケットサーバーです。最大の特長は常識を変えるストレージ拡張性。ストレージ搭載容量を従来モデルの最大2.4倍に強化し、同等サイズの製品の中で群を抜いたストレージ拡張性を提供します。<br>
		また第2世代AMD EPYC<sup>&trade;</sup> プロセッサーを搭載し、さらなる性能向上を実現します。<br>
		Gen10 PlusでもGen10と同じiLO5を搭載。Silicon root of trust (シリコンレベルの信頼性)によるセキュリティ機能をサポートし、HPE独自の電子認証によるファームウェアの更新や不正書き換えの検知と回復機能を備えています。お客様の業務を守る“世界標準の安心サーバー”です。
	</p>
	<p class="mt10">
		より高いプロセッサー性能を追求するお客様には、<a href="/directplus_ent/server/dl325gen10plusv2/" class="tertiary-link">HPE ProLiant DL325 Gen10 Plus v2</a>をおすすめいたします。<br>
		なお本製品も引き続き販売をして参ります。
	</p>
	<p class="mt15">
		<a href="/directplus_ent/server/infosight_for_servers.html" class="linkWithArrow" target="_blank">HPE InfoSight for Servers 対応サーバー　詳しくはこちら<span class="arrow">→</span></a>
	</p>
</div>
