<div class="specTable2Area fixedTable">
	<div class="specTable2">
		<div class="specTableTitle">
			<table width="1000">
				<tr>
					<th width="100"></th>
					<th width="450" class="f14">
						信頼性とコストパフォーマンス<br>
						<span class="f20">4LFF</span>
					</th>
					<th width="450" class="f14">
						性能・信頼性重視<br>
						<span class="f20">8SFF</span>
					</th>
				</tr>
			</table>
		</div>
		<table width="1000">
			<tr>
				<th width="100"></th>
				<th width="450" class="f14">
					信頼性とコストパフォーマンス<br>
					<span class="f20">4LFF</span>
				</th>
				<th width="450" class="f14">
					性能・信頼性重視<br>
					<span class="f20">8SFF</span>
				</th>
			</tr>
			<tr>
				<th></th>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl325_gen10_plus.gif" alt="" class="m0auto">
				</td>
				<td>
					<img src="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/intershop.static/WFS/Directplus-Customer-Site/-/ja_JP/Productsimages_hpe/pp1_dl325_gen10_plus.gif" alt="" class="m0auto">
				</td>
			</tr>
			<tr>
				<th>ドライブ</th>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 3.5型</span> 最大8<br>
					SATA HDD、SATA SSD、SAS HDD、SAS SSD選択可
				</td>
				<td>
					<span class="cutomizable">カスタマイズ可能</span><span class="bold">ホットプラグ 2.5型</span> 最大16<br>
					SATA HDD、SATA SSD、SAS HDD、SAS SSD選択可
				</td>
			</tr>
			<tr>
				<th>プロセッサー</th>
				<td colspan="2">
					<span class="cutomizable2">カスタマイズ可能</span>最大1基　AMD EPYC<sup>&trade;</sup> プロセッサー
				</td>
			</tr>
			<tr>
				<th>メモリ</th>
				<td colspan="2">
					<span class="cutomizable2">カスタマイズ可能</span>16DIMMスロット DDR4 RDIMM
				</td>
			</tr>
			<tr>
				<th>パワーサプライ</th>
				<td colspan="2">
					<span class="cutomizable2">カスタマイズ可能</span>標準1、最大2　オプションで冗長化対応、ホットプラグ対応
				</td>
			</tr>
			<tr>
				<th>最小構成価格<br>（税抜）</th>
				<td class="pt10 pb10">
					<div>
						<span class="bold f14">通常モデル</span>
						<span class="f16">530,000円～</span><br>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4360&ProductSKU=BASE:15839" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
				<td class="pt10 pb10">
					<div>
						<span class="bold f14">通常モデル</span>
						<span class="f16">545,000円～</span><br>
						<a href="<!--#include virtual="/directplus_ent/include/intershop_domain.inc" -->/is-bin/INTERSHOP.enfinity/WFS/Directplus-Customer-Site/ja_JP/-/JPY/DisplayProductInformationForBusiness-Frame?CategoryName=SERI:4360&ProductSKU=BASE:15838" role="button" class="btn btn-secondary mt0 mb5"><span class="bold f14">カスタマイズして見積・購入</span></a>
					</div>
				</td>
			</tr>
			<tr>
				<th></th>
				<td colspan="2" class="pt10 pb15"><a href="pdfs/spec.pdf" target="_blank" class="tertiary-link">スペックの詳細はこちら</a></td>
			</tr>
		</table>
	</div><!-- /.specTable2 -->
	
</div><!-- /.specTable2Area -->
