<div>
	<p>
		HPE ProLiant DL365 Gen10 Plusは、第3世代AMD EPYC<sup>&trade;</sup> プロセッサーを最大2基搭載可能な1Uラックマウント型サーバーの新しいラインアップです。1Uのラックプロファイルでコンピューティング性能を向上させており、高性能と高集約性を併せ持つためCAE、HPC、VDIといったワークロードに最適です。<br>
		サーバー管理機能にはiLO5を搭載。Silicon root of trust (シリコンレベルの信頼性)によるセキュリティ機能をサポートし、HPE独自の電子認証によるファームウェアの更新や不正書き換えの検知と回復機能を備えています。お客様の業務を守る”世界標準の安心サーバー”の進化版です。
	</p>
	<p class="mt15">
		<a href="/directplus_ent/server/infosight_for_servers.html" class="linkWithArrow" target="_blank">HPE InfoSight for Servers 対応サーバー　詳しくはこちら<span class="arrow">→</span></a>
	</p>
</div>
