<div class="product__price">
	
	<div class="clm1 layout__show1000px">
		<!-- 1000px以上でのみ表示 -->
		<div class="clmInr mb20 mt20">
			<div class="gsPriceArea">
				<p class="f18 mb10">通常モデル最小構成価格</p>
				<p><span>1,839,000</span><span class="f18">円(税抜)～</span></p>
			</div>
			<div class="alignCtr mb20">
				<a href="#CustomizeOrder" role="button" class="btn btn-secondary">カスタマイズ・お見積</a>
			</div>
		</div>
	</div>
	
	<div class="clm2">
		<div class="clmInr mb20 mt20">
			<div class="gsPriceArea">
				<p class="bold f18 mb10 spHide">キャンペーンモデル最小構成価格</p>
				
				<p class="f18 strikethrough spHide">1,839,000円(税抜)～</p>
				<p class="bold">期間限定 <span>X,XXX,XXX</span><span class="f18">円(税抜)～</span></p>
				<p class="f18 mt5 mb5 spHide">XXX,XXX円引き～</p>
			</div>
			<div class="alignCtr">
				<a href="#CustomizeOrder" role="button" class="btn btn-secondary">カスタマイズ・お見積</a>
			</div>
		</div>
	</div>
	
</div>