<div>
	<p>HPE ProLiant DL385 Gen10 Plusは、従来機DL385 Gen10の設計を一新し、機能をさらに進化させた2U/2ソケットサーバーです。最大の特長は常識を変えるパフォーマンス。第2世代AMD EPYC<sup>&trade;</sup> プロセッサーを2基搭載可能で、高い仮想化集約率とコスト効率を実現します。<br>
	Gen10 Plus でもGen10と同じiLO5を搭載。Silicon root of trust (シリコンレベルの信頼性)によるセキュリティ機能をサポートし、HPE独自の電子認証によるファームウェアの更新や不正書き換えの検知と回復機能を備えています。お客様の業務を守る“世界標準の安心サーバー”です。
	</p>
	<p class="mt10">
		より高い性能を追求するお客様には、<a href="/directplus_ent/server/dl385gen10plusv2/" class="tertiary-link">HPE ProLiant DL385 Gen10 Plus v2</a>をおすすめいたします。<br>
		なお本製品も引き続き販売をして参ります。
	</p>
	<p class="mt15">
		<a href="/directplus_ent/server/infosight_for_servers.html" class="linkWithArrow" target="_blank">HPE InfoSight for Servers 対応サーバー　詳しくはこちら<span class="arrow">→</span></a>
	</p>
</div>
